### ISSUE TITLE
[DataCap Application] Epeng Times Technology Ltd

### ISSUE THREAD

**Issue by Epengtimes** [filecoin-project/filecoin-plus-large-datasets#86]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Epeng Times Technology Ltd
- Website / Social Media: epengtimes@163.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Epeng Times Technology Ltd is a cryptocurrency market research company providing consolidated market insights and analyses drawn from on-chain data.
```

What is the primary source of funding for this project?
```
Investment from shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We're not associated with other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Consolidated cryptocurrency market data from various public information source, such as DefiLIama, Etherscan, Trading View, DexGuru, etc.
```

Where was the data in this dataset sourced from?
```
Market information from web crawler tools.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://www.dropbox.com/s/f29ignxvy9jjwnm/sample_epeng.json?dl=0
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it's public data can be retrieved and used by anyone on the Filecoin network.
```

What is the expected retrieval frequency for this data?
```
It depends on users' demands.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to store the data permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we will transfer data both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to run testing first with different storage providers. We prefer storage providers who have good track record in storing verified data.
```

How will you be distributing deals across storage providers?
```
We will distribute deals faily among miners in all regions.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources to start making deals. 
```

**Comment by darrellhendershot** [comment]
Hi Epengtimes, will you please provide us a Website / Social Media link regarding to your company instead of a email address( epengtimes@163.com) Thanks

**Comment by Epengtimes** [comment]
> Hi Epengtimes, will you please provide us a Website / Social Media link regarding to your company instead of a email address( [epengtimes@163.com](mailto:epengtimes@163.com)) Thanks

Hi there! The data is for our internal use, we don't have a social media now.

**Comment by darrellhendershot** [comment]
> > Hi Epengtimes, will you please provide us a Website / Social Media link regarding to your company instead of a email address( [epengtimes@163.com](mailto:epengtimes@163.com)) Thanks
> 
> Hi there! The data is for our internal use, we don't have a social media now.

Thanks for your reply. All data and company will be public when you join the LDN.

**Comment by IreneYoung** [comment]
Hi @Epengtimes, is there an offline data transfer process?

**Comment by Epengtimes** [comment]
> Hi @Epengtimes, is there an offline data transfer process?

From the very beginning, we prefer to transfer data online. When we make some tests afterwards and find several miners with good reputation and technical strength, we may store some large dataset on HDDs first and then send the HDDs to miners offline to make the storage deals.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by AnthnoySmith** [comment]
At this time, the large dataset process is intended for public client data. It sounds like you are hoping to upload private or encrypted data, which we are not able to validate and verify at this time. In addition, no one can get the download channel through your private email address or your dropbox.

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahpildxn4q4sds7ly55qubfafy2n2fugv3eq77cf35yo7yq26gcy 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 100TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahpildxn4q4sds7ly55qubfafy2n2fugv3eq77cf35yo7yq26gcy

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4bmyhmkwiderv57akuvklkhb6t6o5jlfbwc6eyrmsoxjjhi32ae 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 100TiB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4bmyhmkwiderv57akuvklkhb6t6o5jlfbwc6eyrmsoxjjhi32ae

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3kstbccjdoc2k7ufary5u5sotwsgidmqtqmvwjvoqozm5bxiyxm 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 200TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3kstbccjdoc2k7ufary5u5sotwsgidmqtqmvwjvoqozm5bxiyxm

**Comment by Epengtimes** [comment]
@ozhtdong @IreneYoung 
Hi, could you help to approve the subsequent datacap allocation pls? Thanks!

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawzpc2xiwro6ksmapu5ew7nk3giaeez2yvnmormepick2s2vwaf6 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 200TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawzpc2xiwro6ksmapu5ew7nk3giaeez2yvnmormepick2s2vwaf6

**Comment by IreneYoung** [comment]
> @ozhtdong @IreneYoung Hi, could you help to approve the subsequent datacap allocation pls? Thanks!

Done👌

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawl6tibkcffwk7akcntn322ubqdxbq557cy4qcdbmel3kcdhtjv4 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 400TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawl6tibkcffwk7akcntn322ubqdxbq557cy4qcdbmel3kcdhtjv4

**Comment by Epengtimes** [comment]
@rayshitou @flyworker @Fenbushi-Filecoin @ozhtdong @IreneYoung @cryptowhizzard @Reiers 
 Any notary can help with the allocation please? Thanks in advance!

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecggqfqsqeqqllyhm3z72grgb6ed2vutkmd4fj4kewxh536q7iqg6 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 400TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecggqfqsqeqqllyhm3z72grgb6ed2vutkmd4fj4kewxh536q7iqg6

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtehrzmrd6hydhhsf25ppnulcanbgvvsb575i6i7o5tpfyfeb6nc 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtehrzmrd6hydhhsf25ppnulcanbgvvsb575i6i7o5tpfyfeb6nc

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebh45jga3gnzhq5sxbwtfmdbewlgldiv5bx3iuewtwqbqjcigq5je 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebh45jga3gnzhq5sxbwtfmdbewlgldiv5bx3iuewtwqbqjcigq5je

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayvb4k6sug44u2xl32hav65ll7u4kb64b3krfqvscah5nz7gra2s 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayvb4k6sug44u2xl32hav65ll7u4kb64b3krfqvscah5nz7gra2s

**Comment by Epengtimes** [comment]
Hi, any notaries can help to approve the subsequent datacap allocation pls? Thanks!
@ozhtdong @IreneYoung

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxip3snbwfibgxykmwrumvoxikwatuzyxk6puzfpk6af7cgadtc6 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxip3snbwfibgxykmwrumvoxikwatuzyxk6puzfpk6af7cgadtc6

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecq63ag4qehzqslu4assm2tyd6gklcoz3an7n65chmpc2kmhtkwws 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecq63ag4qehzqslu4assm2tyd6gklcoz3an7n65chmpc2kmhtkwws

**Comment by Epengtimes** [comment]
Hello  everybody, could you help to approve next batch Datacap ? Thank you very much!
@IreneYoung @ozhtdong @rayshitou @MegTei @Reiers @cryptowhizzard

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrkjy2xz3v2hm4kfvlmalzmzvyloupz2cblj76kzyjqfrxoq6ila 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 425.12TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrkjy2xz3v2hm4kfvlmalzmzvyloupz2cblj76kzyjqfrxoq6ila

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecg2inb7ctxhevazarsqbhrmptsfnsthhqcz4tgmbfdijvfi6zzzs 
#### Address 
> f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea
#### Datacap Allocated
> 425.12TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecg2inb7ctxhevazarsqbhrmptsfnsthhqcz4tgmbfdijvfi6zzzs

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Epeng Times Technology Ltd`
 - Client: `f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 83.28% of total deal sealed by [f01641612](https://filfox.info/en/address/f01641612) are duplicate data.

⚠️ 79.90% of total deal sealed by [f01606849](https://filfox.info/en/address/f01606849) are duplicate data.

⚠️ 80.33% of total deal sealed by [f01602479](https://filfox.info/en/address/f01602479) are duplicate data.

⚠️ 77.93% of total deal sealed by [f01606675](https://filfox.info/en/address/f01606675) are duplicate data.

⚠️ 80.91% of total deal sealed by [f01716466](https://filfox.info/en/address/f01716466) are duplicate data.

⚠️ 86.75% of total deal sealed by [f01781851](https://filfox.info/en/address/f01781851) are duplicate data.

⚠️ 33.83% of total deal sealed by [f01666984](https://filfox.info/en/address/f01666984) are duplicate data.

⚠️ 26.09% of total deal sealed by [f01264125](https://filfox.info/en/address/f01264125) are duplicate data.

⚠️ 66.09% of total deal sealed by [f01662887](https://filfox.info/en/address/f01662887) are duplicate data.

⚠️ 83.33% of total deal sealed by [f01380788](https://filfox.info/en/address/f01380788) are duplicate data.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01641612](https://filfox.info/en/address/f01641612)       |             Montréal, Quebec, CA |           1.01 PiB |     20.27% |  173.56 TiB |          83.28% |
| [f01606849](https://filfox.info/en/address/f01606849)`new`  |             Montréal, Quebec, CA |         978.47 TiB |     19.11% |  196.69 TiB |          79.90% |
| [f01602479](https://filfox.info/en/address/f01602479)       |            Longueuil, Quebec, CA |         973.72 TiB |     19.02% |  191.53 TiB |          80.33% |
| [f01606675](https://filfox.info/en/address/f01606675)`new`  |             Montréal, Quebec, CA |         867.66 TiB |     16.95% |  191.52 TiB |          77.93% |
| [f01716466](https://filfox.info/en/address/f01716466)`new`  |         Singapore, Singapore, SG |         552.53 TiB |     10.79% |  105.50 TiB |          80.91% |
| [f01781851](https://filfox.info/en/address/f01781851)       |         Singapore, Singapore, SG |         500.19 TiB |      9.77% |   66.28 TiB |          86.75% |
| [f01666984](https://filfox.info/en/address/f01666984)       |               Dorval, Quebec, CA |         140.70 TiB |      2.75% |   93.11 TiB |          33.83% |
| [f01264125](https://filfox.info/en/address/f01264125)       |             Montréal, Quebec, CA |          36.41 TiB |      0.71% |   26.91 TiB |          26.09% |
| [f01662887](https://filfox.info/en/address/f01662887)`new`  |         Singapore, Singapore, SG |          32.34 TiB |      0.63% |   10.97 TiB |          66.09% |
| [f01380788](https://filfox.info/en/address/f01380788)       |           Shanghai, Shanghai, CN |         192.00 GiB |      0.00% |   32.00 GiB |          83.33% |
| [f01776738](https://filfox.info/en/address/f01776738)`new`  |             Montréal, Quebec, CA |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |
| [f01201327](https://filfox.info/en/address/f01201327)       | Heerhugowaard, North Holland, NL |           1.00 GiB |      0.00% |    1.00 GiB |           0.00% |
| [f01240](https://filfox.info/en/address/f01240)             | Heerhugowaard, North Holland, NL |           1.00 GiB |      0.00% |    1.00 GiB |           0.00% |
| [f01199442](https://filfox.info/en/address/f01199442)       | Heerhugowaard, North Holland, NL |         512.00 MiB |      0.00% |  512.00 MiB |           0.00% |
| [f01199430](https://filfox.info/en/address/f01199430)       | Heerhugowaard, North Holland, NL |         512.00 MiB |      0.00% |  512.00 MiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/86/1671092453600.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 28.50% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        41.28 TiB |        53.16 TiB |                   1 |           1.04% |
|        86.41 TiB |         1.05 PiB |                   2 |          20.91% |
|        34.55 TiB |       335.23 TiB |                   3 |           6.55% |
|        40.63 TiB |       801.44 TiB |                   4 |          15.65% |
|       108.05 TiB |         2.61 PiB |                   5 |          52.21% |
|         5.91 TiB |       185.28 TiB |                   6 |           3.62% |
|        32.00 GiB |         1.03 TiB |                   7 |           0.02% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/86/1671092455674.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                   | Total Deals Affected | Unique CIDs | Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------- | -------------------: | ----------: | -------: |
| [f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6<br/>yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56f<br/>qdsq](https://filfox.info/en/address/f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq) | [Ecology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/36) |             1.10 PiB |       1,934 | LDN # 36 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
