### ISSUE TITLE
[DataCap Application] Guangdong Win Sing Animation Co.

### ISSUE THREAD

**Issue by evansher** [filecoin-project/filecoin-plus-large-datasets#860]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangdong Win Sing Animation Co.
- Website / Social Media:https://www.winsing.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):201 TiB
- On-chain address for first allocation:f1uc7zqityz4i2xeb7sz4iinxhxsen4vmowhcqs4i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ltd. is a leading domestic digital animation film and television content creation and production enterprise, more than ten years deep into the animation industry, has formed a 3D animation production technology research and development-based business system covering the "animation content production - animation content distribution - animation derivative content, products and services" the whole industry chain. The company's main business is the production and distribution of content products such as animation TV and movies with animation IP as the core, as well as the operation of multiple derivative businesses such as animation toys and other products and brand image licensing based on animation IP.
```

What is the primary source of funding for this project?
```
Distribution revenue of animation film and television, licensing revenue of animation IP.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Animation film and television posters and videos, company development videos.
```

Where was the data in this dataset sourced from?
```
Produced by the Corporate Communications Department
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1mPHf4BG_SUbV90oYFuz_X3vIton4giRh?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES
```

What is the expected retrieval frequency for this data?
```
2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Stable service provider.
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
