### ISSUE TITLE
[DataCap Application] Hunan Kid's Dream Culture Co.

### ISSUE THREAD

**Issue by juliechen11** [filecoin-project/filecoin-plus-large-datasets#861]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hunan Kid's Dream Culture Co.
- Website / Social Media:https://www.tomnclass.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):203 TiB
- On-chain address for first allocation:f1nlh2rnksus5qlswkmeeb6xtro7tns7tqvbrorja

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
 Hunan Tongmeng Culture Joint Stock Company was established in Changsha in November 2009, has been committed to preschool education and special education research and digital education products (including online education platform development) planning, research and development, distribution. in October 2015, the company was listed on the New Third Board (securities abbreviation: Tongmeng Culture, securities code: 833725); in November 2015, the company was recognized as "At the same time, the company is also the executive director of Hunan Provincial Preschool Education Society, the vice chairman of Hunan Provincial Teachers Education Society Kindergarten Director Professional Committee, and the national distributor of "Renjiao Peizhi Cloud Classroom" products of Renjiao Digital Publishing Co. Ltd.
```

What is the primary source of funding for this project?
```
Income from learner courses, income from joining the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Classroom teaching videos, faculty team honor showcase, and course training showcase videos.
```

Where was the data in this dataset sourced from?
```
Corporate Division Production.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/15HreZF4yWlmMjrlV-3xG0A5xSAMU0tVR?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES
```

What is the expected retrieval frequency for this data?
```
3-5 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Strong service providers.
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
