### ISSUE TITLE
[DataCap Application] Taizhou Feifan International Trade Co., Ltd

### ISSUE THREAD

**Issue by Mathervofila** [filecoin-project/filecoin-plus-large-datasets#862]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Feifan
- Website / Social Media:  www.cnfeifan.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1kxndavffexxc5tswkhtke2wsya4a5tq5c3mss6i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Taizhou Feifan International Trade Co., Ltd. was established on May 30, 2019. The legal representative is Lin junxuan. The registered capital is 50 million yuan. The unified social credit code is 91331001ma2duxgr93. The enterprise address is located in Room 802, building 1, modern building, No. 99, Zhengxue Road, Songmen Town, Wenling City, Taizhou City, Zhejiang Province (only for public use). The industry belongs to the wholesale industry. The business scope includes aquatic products, primary agricultural products, food, first class medical devices Sales of building materials, mechanical equipment, hardware products and electronic products, textiles, clothing and household goods; Import and export of goods and technologies; Enterprise management consulting services; Mass cultural and sports activities; Conference and exhibition services. Wholesale of computer software, hardware and auxiliary equipment; Wholesale of class II medical devices; Wholesale of protective articles for medical personnel; Wholesale of medical masks; Category II retail of medical devices; Retail of protective articles for medical personnel; Retail of medical masks; Wholesale of office equipment; Technical service, technical development, technical consultation, technical exchange, technology transfer and technology promotion (for projects subject to approval according to law, business activities can only be carried out after approval by relevant departments). Taizhou Feifan International Trade Co., Ltd. is currently in existence.
```

What is the primary source of funding for this project?
```
From ourselves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Only related to ourselves.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Business data generated during the operation of the company, including but not limited to product introduction, product service and service plan data;  
The data we intend to store will be desensitized. 
```

Where was the data in this dataset sourced from?
```
The data is obtained from the data provided by users and the analysis data generated during service processes. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Please answer here.](https://drive.google.com/drive/folders/1B3nTI70Uyn18HQuCLmNFgFSC-dDvFXLQ?usp=sharing)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is a public dataset.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will contact SP, and also accept SP to contact us.
Data will be stored in multiple SPs, ensuring distributed storage and data security.  
We periodically retrieve data to ensure that it is safely stored. 
```

How will you be distributing deals across storage providers?
```
We will choose more stable and secure storage suppliers first, and then allocate according to the allocation rules on this basis.  We hope that more storage providers can contact us and provide us with storage services. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. 
```

**Comment by jessie8o8** [comment]
Hello @Mathervofila. Please explain the discrepancy of the ages listed in your 
- [Business License](https://www.gsxt.gov.cn/%7BC465113DAC44B0EF5F73D63E8E9832A38FB1B101E9D7C1E1957DECC0FE055874D1EFF9D9AD45451A54C59AD4D47171998E22318DFAAC4CD88E9D29BDEBB32CF92CE82CE82CF92CD410D42CE82CE82CD401C50A65B0C0FA50AB3041F1E74D58FD6CDCD921D90CC88989D69898A60CBCB9418541854185-1661469021921%7D)) : 3 years
- [Website](http://www.cnfeifan.com/page/70824.html): 36 Years
- [Website Registration Date](https://www.whois.com/whois/cnfeifan.com): 3 years
![image 3](https://user-images.githubusercontent.com/90115194/186804070-850c3173-25ea-48f7-85da-2f61fe527f1e.png)
![image 1](https://user-images.githubusercontent.com/90115194/186804072-84a6a7bf-e903-44bc-96b8-53d9e3d91f7b.png)
![image 2](https://user-images.githubusercontent.com/90115194/186804074-ae05ea05-ed08-4841-9393-4d45002fd2d7.png)

In addtion to that, please explain what is the composition of the sample dataset you have provided. None of the data seems to be relevant to your product (seafood)
![image](https://user-images.githubusercontent.com/90115194/186805267-c2d1238d-f47a-46f1-9186-5abce4df49cf.png)

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
