### ISSUE TITLE
[DataCap Application] Rita Dattel Education

### ISSUE THREAD

**Issue by ZszCldesb12** [filecoin-project/filecoin-plus-large-datasets#864]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Ruida Daitai Education Technology Co.
- Website / Social Media:www.ruidaedu.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1qkfppqjrmc6oxwn3zygmmngqvv7l5r2mgqgn64i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ltd. is an educational training institution that integrates training for the National Law Professional Qualification Examination, the National Law Master Examination and the Certified Public Accountant Examination, referred to as "Rada Education". In June 2017, Zhengbao Distance Education and Vistra Education joined forces to promote a new chapter of Vistra Education's online and offline teaching services. Since its establishment, the company has grown rapidly and now has more than 100 franchised campuses across the country, forming a national chain of Rida Education brand and realizing the Rida training model and comprehensive teaching service system of online online classes + offline face-to-face teaching.

```

What is the primary source of funding for this project?
```
Company's revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
No connection to other projects
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly educational course materials video (criminal law, three countries, series of shifts, civil law, administrative, criminal prosecution,, business and economics, theory, civil litigation)
```

Where was the data in this dataset sourced from?
```
http://www.ruidaedu.com/core/selectcourse/courseList.shtm
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
http://www.ruidaedu.com/core/selectcourse/courseList.shtm
http://www.ruidaedu.com/core/library/librarylist.shtm
```

What is the expected retrieval frequency for this data?
```
Anyone who retrieves this data
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Anywhere you can trade
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We transfer via offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select a number of suppliers who can provide services reliably and consistently
```

How will you be distributing deals across storage providers?
```
We will allocate an equal share to high quality storage providers. In addition, each miner will not be allocated more than 25% of our data volume.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough money and resources.
```

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
