### ISSUE TITLE
[DataCap Application] <Beijing Atop Culture Arts Co., Ltd.> 

### ISSUE THREAD

**Issue by panjianyongeiangi** [filecoin-project/filecoin-plus-large-datasets#870]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Atop Culture Arts Co., Ltd.
- Website / Social Media: http://ziyuan.baby611.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation: f17mlrkvho3c44ovlscouwfllchfe7bfiedpcmaki

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2011, Beijing Atop Culture Arts Co., Ltd. offers FREE educational resources for preschool and kindergarten educators and students. We work with many organizations and people to develop collections of standards-aligned content, lesson plans, and more. Our goal is to enhance educator practice and equitable student learning through educational resources that are available to teachers and students at no cost for educational use, and designed to promote and support effective practices in teaching and learning with digital media. We want to create a website with untimed, multisensory interactive games that allow children to see, hear, and touch as they learn.
```

What is the primary source of funding for this project?
```
Company revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Online course source material, original videos and interactive resources such as lesson plans, curriculum units and recordings of live courses custom-built for classroom use.
```

Where was the data in this dataset sourced from?
```
From different teachers and volunteers around China who give lessons and make these videos.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link: https://pan.baidu.com/s/1_XP7fpBwrTgKVBqru-nR7g?pwd=1234
PW: 1234
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is a public dataset that can be publicly retrieved.
```

What is the expected retrieval frequency for this data?
```
Our resources span multiple subject areas plus professional development, grouped by grade bands to give teachers and students free and instant access to high-quality material. So its retrieval frequency will be pretty high.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent archival.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We are planning to use online transfer. But if the data is too big then we will use offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will undertake inspections over prospective storage providers based on the following factors:
- location
- transmission speed
- deal success rate
- previous experience of real data storage
- stability of their nodes
```

How will you be distributing deals across storage providers?
```
Depends on their network bandwidth and storage efficiency, and we plan to evenly distribute deals across 4 storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between Beijing Atop Culture Arts Co., Ltd. and http://ziyuan.baby611.com/?
What's the Chinese name of Beijing Atop Culture Arts Co., Ltd.
http://baby611.com/ is belong to a person, who's name is Liaoguojian.
What's the relationship between you and organization?

**Comment by panjianyongeiangi** [comment]
Hi @Sunnyiscoming The Chinese name of Beijing Atop Culture Arts Co., Ltd. is 北京上尚文化艺术有限公司. 
We outsourced our website and web design services. Liao is from a team of expert outsourced web development specialists we hire to handle our website and implement technical features.

**Comment by Sunnyiscoming** [comment]
> We outsourced our website and web design services. Liao is from a team of expert outsourced web development specialists we hire to handle our website and implement technical features.

Can you provide related materials?
How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #870.

**Comment by panjianyongeiangi** [comment]
@Sunnyiscoming Hello, please refer to below. Thanks!
1．Related material is sent by email as requested. 
2．We will store 3-5 copies currently.
3．I am Jason Pan. I’m a project manager of the company.
4．We’ve been contacting some top-rated SPs from https://filrep.io/ and we’ll decide who to partner with after careful consideration. 
5．Sent by email as requested.
![确认邮件](https://user-images.githubusercontent.com/108716956/193246800-f806ce8d-0014-471b-b8cd-bcf96a67f5ae.png)

> > We outsourced our website and web design services. Liao is from a team of expert outsourced web development specialists we hire to handle our website and implement technical features.
> 
> Can you provide related materials? How many copies will you store? What's the relationship between you and organization? Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #870.

**Comment by Sunnyiscoming** [comment]
Your official domain [baby611.com/](http://ziyuan.baby611.com/) doesn't match the email you sent.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
