### ISSUE TITLE
[DataCap Application]Xiamen Weizhongwang Food Co.

### ISSUE THREAD

**Issue by wzwfood** [filecoin-project/filecoin-plus-large-datasets#873]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xiamen Weizhongwang Food Co.
- Website / Social Media:http://www.wzwfood.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1pg6hmj3iuuwhct6plkbwhyjoqtfmj2ad5txmnxi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xiamen Weizhongwang Food Co., Ltd. is a modern high-tech enterprise specializing in the research and development, production and sales of food flavors, spices and advanced condiments. The company is headquartered in Hong Kong and the factory is located in Xiamen, Fujian, a world-famous garden city. It has conducted positive interactions with many scientific research institutions in Taiwan and Japan all year round, adhering to the traditional Chinese flavor technology, while introducing world-class biological enzymatic hydrolysis technology and Maillard reaction technology. , microwave technology and microencapsulation technology. The company's main products include advanced series of products such as flavors and fragrances, condiments, western food ingredients, etc., which have the characteristics of high temperature resistance, can penetrate the fragrance into the food to the greatest extent, and emit an attractive fragrance. The special effect of removing fishy greasy and making dishes fresh and delicious.
Based on excellent quality and high-tech technology, through continuous technical research and development and market development, we continue to pursue excellent quality and top technology, and have won unanimous recognition at home and abroad. The company always takes integrity, professionalism, innovation and win-win as its business philosophy, adheres to the principle of "excellent quality, meticulous service", and strives to quickly become a well-known enterprise with influence and brand at home and abroad. "People put taste first." With the spirit of unremitting efforts and sincere service, we continue to innovate new products to meet people's continuous demand for food flavor.
```

What is the primary source of funding for this project?
```
The company funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Photos and videos of product production, sales process, photos and videos of marketing activities, photos and videos of franchisee activities, live video, etc..
```

Where was the data in this dataset sourced from?
```
The data comes from, in the past 3 years, photos and videos of product production and sales process, photos and videos of marketing activities, photos and videos of franchisee activities, live video recordings.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1oIimYQXbgQcIPVcwc-dVafvpoW8IpJ4B?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,we confirm.
```

What is the expected retrieval frequency for this data?
```
2-3 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
at least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China first, Asia, Europe can be.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will send CAR files to storage providers offline for deal making.
Welcome storage service providers to contact us.
```

How will you be distributing deals across storage providers?
```
We will allocate DataCap according to miner's preference, such as online transfer and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we have enough funding.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by wzwfood** [comment]
> Can you explain your data composition? How many copies will you store? What's the relationship between you and organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Hello,@Sunnyiscoming
The data stored this time are mainly condiment demonstration videos, a large number of partners and video information publicly released by the media.
6-8 copies are required to ensure data safety.
We have finished contacting with f01310564,f08403,f096976 through filrep.io,
but we have not finalized cooperation.
Of course, we are still in contact with more node.
Thanks.

**Comment by Sunnyiscoming** [comment]
Please provide sufficient data samples related with a large number of partners and video information publicly released by the media.
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #873.

**Comment by wzwfood** [comment]
> Please provide sufficient data samples related with a large number of partners and video information publicly released by the media. Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #873.
Hi,@Sunnyiscoming 
Added storage case, please check.
https://drive.google.com/drive/folders/1w-btuj67pPSdvtq225KNvtxEgC2skn36?usp=sharing
Emails will be sent as soon as possible after work.

**Comment by Sunnyiscoming** [comment]
Waiting for email.

**Comment by wzwfood** [comment]
> [wzwfood](/wzwfood)
Hi,@Sunnyiscoming
Confirmation email has been sent, please check. thank you very much.
![image](https://user-images.githubusercontent.com/111366977/194760030-a1cc2c3c-ed69-4509-8f5d-c6ceaf165449.png)

**Comment by raghavrmadya** [comment]
<img width="316" alt="Screen Shot 2022-10-12 at 9 44 48 PM" src="https://user-images.githubusercontent.com/91579519/195503670-8f86ec45-d71a-4777-9970-9af3d7fba2e1.png">

**Comment by raghavrmadya** [comment]
Who is Jonathan Helmick?

**Comment by wzwfood** [comment]
> Who is Jonathan Helmick?
hi sir,@raghavrmadya
This account is used to contact overseas customers, mainly to establish a Youtube account and promote the company's products overseas. This is the colleague responsible for contacting overseas markets.
At that time, she also applied for the github account.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1pg6hmj3iuuwhct6plkbwhyjoqtfmj2ad5txmnxi

**Comment by Sunnyiscoming** [comment]
Hey @wzwfood  , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by OpenGate01** [comment]
Can you tell us a little bit about your encapsulation program?
What are some of the SPs that you are sure to work with now?

**Comment by wzwfood** [comment]
> Can you tell us a little bit about your encapsulation program? What are some of the SPs that you are sure to work with now?

The original data is cut by singularity, and after cutting, it is transmitted by mailing the hard disk
f02223012
f02051391
f02027952
f0693793
Thank you for your support

**Comment by OpenGate01** [comment]
Ok, as a first round of allocation, I'm willing to support it, I hope you follow the rules strictly for data allocation and encapsulation, I'll keep an eye out for it in the future.

**Comment by OpenGate01** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced43j6dl3yxfg2jnzotxkgpcx3n3erhaq33nahhwgfmhlg42jnl54 
#### Address 
> f1pg6hmj3iuuwhct6plkbwhyjoqtfmj2ad5txmnxi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> ed7513e2-f48d-4f8f-b470-9c6f3d3e86dd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced43j6dl3yxfg2jnzotxkgpcx3n3erhaq33nahhwgfmhlg42jnl54

**Comment by cryptowhizzard** [comment]
> ## Request Proposed
> Your Datacap Allocation Request has been proposed by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzaced43j6dl3yxfg2jnzotxkgpcx3n3erhaq33nahhwgfmhlg42jnl54
> 
> #### Address
> > f1pg6hmj3iuuwhct6plkbwhyjoqtfmj2ad5txmnxi
> 
> #### Datacap Allocated
> > 50.00TiB
> 
> #### Signer Address
> > f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
> 
> #### Id
> > ed7513e2-f48d-4f8f-b470-9c6f3d3e86dd
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced43j6dl3yxfg2jnzotxkgpcx3n3erhaq33nahhwgfmhlg42jnl54

@OpenGate01 

Why are you signing without KYC?

**Comment by cryptowhizzard** [comment]
> Ok, as a first round of allocation, I'm willing to support it, I hope you follow the rules strictly for data allocation and encapsulation, I'll keep an eye out for it in the future.

Why are you signing without KyC @OpenGate01

**Comment by OpenGate01** [comment]
> Can you tell us a little bit about your encapsulation program? What are some of the SPs that you are sure to work with now?

This one's not?

**Comment by OpenGate01** [comment]
@cryptowhizzard I think every notary has a different way of KYC, you have your way and I have mine.
As a first round of distribution, in my perspective, I would do this KYC, and you can do yours if you have a different opinion.

**Comment by cryptowhizzard** [comment]
> > Can you tell us a little bit about your encapsulation program? What are some of the SPs that you are sure to work with now?
> 
> @cryptowhizzard This one's not?

Uhm, no it is not.

@wzwfood 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by wzwfood** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

I am watching. 
There will be data storage in the near future.

**Comment by herrehesse** [comment]
checker:manualTrigger
