### ISSUE TITLE
[DataCap Application] Guangzhou Aichen Chemical Technology Co

### ISSUE THREAD

**Issue by aichenhuagong** [filecoin-project/filecoin-plus-large-datasets#874]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Aichen Chemical Technology Co
- Website / Social Media:http://www.acchem.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1uk43zjovr2vugw4idekyrejte4zplfijfe4vsgy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Guangzhou Acchem Chemical Technology Co., Ltd. (Acchem) specializes in providing solutions for bonding, printing and flocking of films, sheets, paper, non-woven fabrics, metals, etc. We are a supplier specializing in special adhesives, coatings and daily chemicals. The company relies on the products of well-known international chemical companies, combined with our excellent technical support, and has good and close cooperation with many domestic universities and research institutes.
Since its establishment, the company has been committed to providing users with the best quality products and overall solutions, and has always adhered to the concept of "relying on products and serving as the core". Form a winning strategy for customers, and have the ability to integrate, implement and implement comprehensively, and help customers improve their overall competitive advantage to the greatest extent.
Guangzhou Aichen Chemical Technology Co., Ltd. has always served the society with the tenet of "honesty, customer first, service in place, and technology pilot"..
```

What is the primary source of funding for this project?
```
self-funding.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Product video materials, promotional pictures and videos, daily factory video recordings, etc..
```

Where was the data in this dataset sourced from?
```
A large part is stored in the hard disks purchased centrally by the company, and a small part is stored on Alibaba Cloud
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/11DnrWaw2RZ2RQSriHyeZG4drS6TCUrmT?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,that is a public data.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Best in China, but Asian and European countries are also ok.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Storage service providers who want to provide high-quality services contact us, most of the data will be provided to the cooperative storage service providers in the form of hard drives by mail, and a small part will be transmitted online..
```

How will you be distributing deals across storage providers?
```
We will cooperate with no less than 3 storage service providers, and we also hope that more storage service providers will contact us. We hope that the storage share of each storage service provider does not exceed 30% to ensure data security..
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough funds to start.
No help needed now, thanks
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by aichenhuagong** [comment]
> Can you explain your data composition? How many copies will you store? What's the relationship between you and organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Hi,@Sunnyiscoming
I'm the department manager in charge of this storage project.
5-6 backups are required. The data stored this time are mainly product-related publicity data and customer feedback information.
We have contacted some SPs,
f096976,
f01715155,
f0152799,
f01579009,
But it has not been finalized and needs to be further confirmed.
We hope that more excellent storage service providers will contact us, and we comply with the official retrieval specifications to ensure that the stored data is retrievable.
Thanks.

**Comment by Sunnyiscoming** [comment]
How much is the total amount of product-related publicity data and customer feedback information? Can you provide more data samples of customer feedback information?

**Comment by aichenhuagong** [comment]
> How much is the total amount of product-related publicity data and customer feedback information? Can you provide more data samples of customer feedback information? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #874.

Hi,@Sunnyiscoming
More video cases have been uploaded, please check:
https://drive.google.com/drive/folders/1lMGFiN-w68xouEImGi1A98Ha7GDxJhK7?usp=sharing
The total amount of data stored this time is about 300 TiB
Confirmation email has been sent, please check.
![截图20221009211446](https://user-images.githubusercontent.com/111367281/194758884-b62debed-b613-4790-a29a-d0b8af5e6f0e.png)

**Comment by Sunnyiscoming** [comment]
Email received.

**Comment by raghavrmadya** [comment]
<img width="322" alt="Screen Shot 2022-10-12 at 9 43 43 PM" src="https://user-images.githubusercontent.com/91579519/195503531-9b729fb6-119a-46a7-8569-59700e41aa80.png">

**Comment by raghavrmadya** [comment]
"daily factory video recordings" - How is this public data?

**Comment by aichenhuagong** [comment]
> "daily factory video recordings" - How is this public data?

Hello,@raghavrmadya 
The expression "daily factory video recordings" may not be accurate. It should be the daily work of the workshop, which is used to show the workshop, promote products, and provide partners with daily factory photography. We ensure that the data provided are confirmed to be safe and open.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1uk43zjovr2vugw4idekyrejte4zplfijfe4vsgy

**Comment by Sunnyiscoming** [comment]
Hey @aichenhuagong , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 1.5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by OpenGate01** [comment]
How are you going to carry out your first batch of data encapsulation and how are the SP locations distributed?

**Comment by aichenhuagong** [comment]
> How are you going to carry out your first batch of data encapsulation and how are the SP locations distributed?

This is the initial cooperation with several SPs we have contacted temporarily, and more SPs are still in contact. I will distribute the data through offline transmission
f060754 hk
f02130918 hk
f01708981 Shenzhen
f01116671 Fuzhou
