### ISSUE TITLE
[DataCap Application] Jiashan yanfan Textile Technology Co., Ltd.

### ISSUE THREAD

**Issue by jsyanfan** [filecoin-project/filecoin-plus-large-datasets#875]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiashan yanfan Textile Technology Co., Ltd.
- Website / Social Media:http://www.cnyanfang.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ou356dpwynn5pxzyqlqpllo4l35dmljfkcegawq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jiashan yanfan Textile Technology Co., Ltd., located in the trade circle around Shanghai, is a company specializing in all kinds of warp and weft knitted nylon / polyester / spandex elastic fabrics. The corresponding factory has 30 weft knitting machines with an annual output of 2000 tons. At the same time, it is equipped with fully automatic computer configuration, dyeing vat, setting machine, washing machine, drawing machine and other imported equipment. The corresponding dyeing plant has passed the certification of ISO9000, ISO14000, GB / T28001 and environmental protection product system certification of Oeko tex 100. Our main products include: warp knitted / weft knitted polyamide spandex elastic fabric, warp / weft knitted polyester / spandex elastic fabric, elastic fleece cloth, warp and weft knitted polyester fabric, mesh fabric and other special processing products. The dyeing fastness has reached the domestic and international advanced level. All products are subject to antibacterial, flame retardant, antistatic, UV resistant, moisture absorption and perspiration, sprinkling and other multi-functional post-treatment processing according to customer requirements. Since its establishment, the company has won the trust of customers at home and abroad with good reputation, and its trade scale is expanding day by day. Customers all over the world, and has a backbone team with excellent business and strong operation ability. While providing customers with a variety of logistics solutions, we can also explore the Chinese market for overseas customers, find the source of goods, check and accept the goods, declare and determine the warehouse, so as to relieve all worries of import and export. Provide professional, personalized, all-weather, all-round service.
```

What is the primary source of funding for this project?
```
Company's own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Clothes production workshop video, product promotional materials, self-media promotion video materials, etc.
```

Where was the data in this dataset sourced from?
```
The video of the garment production workshop is automatically recorded and archived every day,
Product promotional materials are regularly produced by the Marketing Department,
We-media promotional video materials are produced by partners according to their own characteristics.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1N3qSEgPquGUzg9vZ8eZGSloQQyA0-BYk?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,confirm.
```

What is the expected retrieval frequency for this data?
```
Data call frequency is 3-5 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China,Asia, Africa, Europe we can all accept.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have just contacted this project, and we hope that more high-quality storage service providers will contact us. We will store data in full accordance with the requirements of retrieval services.
```

How will you be distributing deals across storage providers?
```
We plan to distribute our data equally among 5-8 storage service providers. Of course, powerful service providers will obtain more data, but a single storage service provider will not take 20% of the data volume to ensure the security of our data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough funds to start right away.
No,thanks.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/192707373-6ef24bc3-2170-453c-8028-fc709d4d819c.png)
There is something wrong with the website. Can you explain it?

**Comment by jsyanfan** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/192707373-6ef24bc3-2170-453c-8028-fc709d4d819c.png) There is something wrong with the website. Can you explain it?

Encrypted due to device manufacturers' privacy requirements

**Comment by Sunnyiscoming** [comment]
Please provide sufficient data samples related with self-media promotional video materials, which are produced by partners according to their own characteristics. 
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #875.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by jsyanfan** [comment]
> Please provide sufficient data samples related with self-media promotional video materials, which are produced by partners according to their own characteristics. Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #875.
Sorry for not replying in time due to the recent holiday.
Please refer to the link below for a sample case：
https://drive.google.com/drive/folders/1vMyiNVsuK_k83bnBcmPTquyCDuixIK2W?usp=sharing
A confirmation email will be sent out as soon as possible, and I will reply here for confirmation as soon as possible.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no update. You can open another new application if you need.
