### ISSUE TITLE
[DataCap Application] Changsha Changhai Hospital

### ISSUE THREAD

**Issue by cschyy** [filecoin-project/filecoin-plus-large-datasets#877]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Changsha Changhai Hospital
- Website / Social Media:http://www.cschyy.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ss6hra2j7gp6y4ko72rxpvptckssxjkx44dyufq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Changsha Changhai Hospital, founded in 2006, is a modern and new general hospital. The hospital is located in Mingwei Building, No. 1029, Section 1, East Second Ring Road, Furong District, Changsha City. At present, the total construction area of the hospital is over 12,000 square meters, with 53 approved beds and more than 200 employees. Since the establishment of the hospital, the hospital has focused on building a first-class high-quality medical team. There are 1 chief physician and professor, 6 deputy chief physicians and associate professors, 12 intermediate professional titles, and 22 junior professional titles.
The comprehensive medical service function of the hospital is complete, with 28 clinical, medical technology and business departments. Inspection, function, imaging and other medical technology departments are equipped with advanced, sophisticated and cutting-edge diagnostic instruments and equipment at the forefront of modern medicine.
At present, the outpatient department of the hospital has preventive health care department / internal medicine / surgery / obstetrics and gynecology / pediatrics / otolaryngology / dermatology / medical aesthetics / emergency medicine / anesthesiology / medical laboratory / medical imaging / traditional Chinese medicine / traditional Chinese and Western medicine Combined Section.
```

What is the primary source of funding for this project?
```
Hospital's own funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Hospital environment and equipment promotional videos, graphics, and public surveillance video recordings
```

Where was the data in this dataset sourced from?
```
Surveillance videos are all stored in hard disks, stored in warehouses, and promotional materials are stored in cloud disks, such as Tencent Cloud
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1HhWIG9VqXGY_ZZbs5i_uhpvlAlGGU4_Z?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,confirm.
```

What is the expected retrieval frequency for this data?
```
Once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
No specific requirements, but preferably Asia, Europe
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
At present, we are in contact with several domestic storage service providers, but none of them have been confirmed yet. We hope that more high-quality storage service providers will contact us, and the surveillance video data will be delivered by post.
```

How will you be distributing deals across storage providers?
```
We hope that more storage service providers will provide services to ensure data security. The data share of a storage service provider cannot exceed 30%
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have sufficient funds ready to start storing immediately.
```

**Comment by Sunnyiscoming** [comment]
How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #877.

**Comment by cschyy** [comment]
> How many copies will you store? What's the relationship between you and organization? Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #877.

3-5 copies will be made.
I'm the assistant dean, in charge of this project.
For storage providers distribution, we have contacted the following SPs:
f0818235,
f01824405,
f087096,
We contacted these nodes through https://filrep.io/, but we have not finalized cooperation. 
Of course, we are still in contact with more node.
And more Sps will be welcomed to join us! 
The confirmation email will be sent out after the National Day holiday and I will notify you in time.

**Comment by Sunnyiscoming** [comment]
f0818235, f087096 are unreachable, f01824405 can not be found on the website https://filrep.io/. How you contact them?

**Comment by cschyy** [comment]
> f0818235, f087096 are unreachable, f01824405 can not be found on the website https://filrep.io/. How you contact them?
Hi,@Sunnyiscoming
Sorry, we contacted a long time ago, because the application has not been successful, so there is no further confirmation recently.
f08403 is the one we've got in touch with today, and we'll be in touch with more SPs in the near future.

**Comment by Sunnyiscoming** [comment]
Close for no update. You can open another new application if you need.
