### ISSUE TITLE
[DataCap Application] Henan Ring Dixu Trading Co. LTD

### ISSUE THREAD

**Issue by huandixu** [filecoin-project/filecoin-plus-large-datasets#878]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Henan Ring Dixu Trading Co. LTD
- Website / Social Media: https://www.huandixu.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1ckelo457jpoj7ziwrkd6h4m7phovytlkqjvzxiy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Henan Huandixu Trading Co., LTD., R & D, production and sales of all kinds of doors and Windows products, products cover the series of open doors and Windows, sliding doors and Windows, heavy folding doors, insulation broken bridge window series and other kinds, is a modern private enterprise.The company has nearly 30,000 square meters of modern production base, as well as residential, commercial and villa and other types of engineering cases.
```

What is the primary source of funding for this project?
```
The company's funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Publicly available design video. Publicly available design images. Publicly available design data.
```

Where was the data in this dataset sourced from?
```
Since the establishment of the company, all design pictures and videos, as well as the marketing process of pictures and videos, publicity materials, regularly updated, historical data need to be properly preserved.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/15BvUVjsfPy1B0pwbV2gGU5NQdxroJz3H?usp=sharing
https://drive.google.com/drive/folders/1IDBkej46SHhWUK1jYPbLt3SiFywx3m1P?usp=sharing
https://drive.google.com/drive/folders/1RzHJhkwrrmsn1CsNPoSkgn0Q_IZWBRJQ?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
It depends on actual needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
There are at least two regions in Asia and North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online and offline transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
we are actively contacting more storage providers, we welcome storage providers to contact us, we hope that data can be stored securely and decentralized.
```

How will you be distributing deals across storage providers?
```
Less than 25% data for every storage providers. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by raghavrmadya** [comment]
Clicking on website results in error. <img width="695" alt="Screen Shot 2022-08-30 at 1 53 04 PM" src="https://user-images.githubusercontent.com/91579519/187540942-e732cc5c-c706-4f22-afb1-fffed69fa7e1.png">
