### ISSUE TITLE
[DataCap Application] AOLIGEI

### ISSUE THREAD

**Issue by aoligei-1122** [filecoin-project/filecoin-plus-large-datasets#880]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  AOLIGEI
- Website / Social Media: www.aoligei-Fighting.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:  f1txoa2y643i7zguyorpahfzo74d2zmin6kw54bpi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Zhejiang AOLIGEI Culture Media Co., Ltd is a cultural media platform focused on the development of artists. With accurate market positioning, we’ve won a certain market share out of many competitors. Engaged in the filed of the image promotion of internet influencers, short video planning, filming training consulting, etc., not only do we have a large number of cultural media resources, but also create their own flow of IP with the professional operation teams, helping them achieve their own dreams!
```

What is the primary source of funding for this project?
```
We currently have two main sources of funding.
1、Own funds.
2、Business income of the project's business line.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our company currently has more than 100 artists under contract, and our current business has close ties with film and television companies, social media platforms, and e-commerce.
1、Cooperating with some film and TV companies to shoot TV series and advertisement promotion works.
2、Cooperating with some social media platforms to publish videos, pictures and advertisements of our contracted artists.
3、We also do e-commerce by selling a full range of products through live-stream media.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin are our business videos, commercials, image and client’s video materials. 
```

Where was the data in this dataset sourced from?
```
Mainly from customer's storage data and our project's storage data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Douying：
https://www.douyin.com/user/MS4wLjABAAAAqHIH7OBGnA77xHvRJNYaNXRS5MAm-2lDxNIk3dJSHtU?modal_id=7117310005006568740
https://www.douyin.com/user/MS4wLjABAAAAqHIH7OBGnA77xHvRJNYaNXRS5MAm-2lDxNIk3dJSHtU?modal_id=7116789513619361032
https://www.douyin.com/user/MS4wLjABAAAAqHIH7OBGnA77xHvRJNYaNXRS5MAm-2lDxNIk3dJSHtU?modal_id=7118665932796431647
https://www.douyin.com/user/MS4wLjABAAAAAD-lSehi3CNwG1I8bTSfQUZ-Ak2j9Rxdulx6TZNFsAc?modal_id=7026563322648579362
https://www.douyin.com/user/MS4wLjABAAAAAD-lSehi3CNwG1I8bTSfQUZ-Ak2j9Rxdulx6TZNFsAc?modal_id=7062130813122481423
https://www.douyin.com/user/MS4wLjABAAAA5Zr5L2owYCE9QuAWtxzbYfBc2Nhj0b4Pf8FBk-xyUu4?modal_id=6651515890045160711
https://www.douyin.com/user/MS4wLjABAAAA5Zr5L2owYCE9QuAWtxzbYfBc2Nhj0b4Pf8FBk-xyUu4?modal_id=7134982490384616743
https://www.douyin.com/user/MS4wLjABAAAA5Zr5L2owYCE9QuAWtxzbYfBc2Nhj0b4Pf8FBk-xyUu4?modal_id=7135387938128497958
https://www.douyin.com/user/MS4wLjABAAAA5Zr5L2owYCE9QuAWtxzbYfBc2Nhj0b4Pf8FBk-xyUu4?modal_id=7136491982939049227
https://www.douyin.com/user/MS4wLjABAAAA_UAtaMCagWq8N1RPE-KCyW9VIyt6wwhhJ3J4l7pI-tXCiK6I1TQvV1Adv9PkQj2a?modal_id=6837725081230200071
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm that the data we will store is publicly available
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The data we store on filecoin is subject to the demand and business needs. It is expected that 20% of the data will be stored for 540 days and 80% of the data will be stored permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Singapore、America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to transfer the data by Online Deal or by hard disk mail
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose those with real data storage experience and stable operation nodes
```

How will you be distributing deals across storage providers?
```
Allocate each miner 15% of DataCap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are ready to make deals. 
```

**Comment by aoligei-1122** [comment]
We are a media company, we have signed some artists and there will be a lot of video material that needs to be stored for backup. Secondly, we have business cooperation with external KOLs and there will be many business opportunities, so the video data used for online sales also need to be stored.Thank you！

**Comment by raghavrmadya** [comment]
How much data do you have as of today?

**Comment by aoligei-1122** [comment]
Hello, @raghavrmadya 
We’ve got  5P DataCap before, and have prepared 1P data to be stored. Our business has been terminated due to the account limit of our GitHub. This is the new issue we have created. 
In addition, our company is a media company and has a lot of KOLs. Video materials will be created everyday. Secondly, there are online sales videos in cooperation with external parties. All the materials generated every day need to be stored on Filecoin network. 

Thank you so much.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #880.

**Comment by aoligei-1122** [comment]
Hello, @Sunnyiscoming  I have sent a KYC email to the official email, please check. Thanks!
![_20220930194100](https://user-images.githubusercontent.com/111726859/193262120-976d8f1a-98ee-4dd1-bfc1-8ced5fb16255.jpg)

**Comment by aoligei-1122** [comment]
Hello, @Sunnyiscoming  the email to send KYC is the email address on our official website. Thank you！
![图片_20221008144132](https://user-images.githubusercontent.com/111726859/194693797-437e44e9-337e-4b4d-84c8-d9d21e9712a0.jpg)

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/195493632-75ff3a68-e6b7-416f-b1e0-ee2dcd156bc5.png)
But I can't even see your qq email address, could you try to resend it?

**Comment by aoligei-1122** [comment]
@Sunnyiscoming I can see the email address, I have resent, please check the email
![075627D2-3093-4B29-A258-8F955EBA1850](https://user-images.githubusercontent.com/111726859/195758122-0cf80f8f-9219-4270-a866-b7ceee0952e2.jpeg)

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/200160910-38118b46-d768-4fa6-b0f8-4bf6aa184ed4.png)
This email address is not same as the address published on the website.

**Comment by aoligei-1122** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/200160910-38118b46-d768-4fa6-b0f8-4bf6aa184ed4.png)
> This email address is not same as the address published on the website.

This email address is the same as the one posted on the website, please check carefully
! thanks.
![Uploading 2DB9AB76-F3EA-43FE-8603-65874E21786D.jpeg…]()

**Comment by aoligei-1122** [comment]
Hello, @Sunnyiscoming @raghavrmadya our official email has been modified correctly, please check again, thank you!
![FBB72A10-B0DA-43C9-9109-597B910FEE62](https://user-images.githubusercontent.com/111726859/202353110-b934b09f-9d32-4e4f-8f75-c10916d03008.jpeg)
![E832FC86-6058-4079-86EE-852435771619](https://user-images.githubusercontent.com/111726859/202353156-f18d26b7-b2b7-4968-9453-013090f6627b.png)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1txoa2y643i7zguyorpahfzo74d2zmin6kw54bpi

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpkw3ljaaylfwnezaurbdpewoithi76xiq72njj45wy4rjkoibnm 
#### Address 
> f1txoa2y643i7zguyorpahfzo74d2zmin6kw54bpi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 874f3b74-2851-4984-9a6a-f9537d5b52cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpkw3ljaaylfwnezaurbdpewoithi76xiq72njj45wy4rjkoibnm

**Comment by Tom-OriginStorage** [comment]
This is the first time to sign. I will follow up on it later. If there are any problems, I will contact the owner to solve them

**Comment by BDEio** [comment]
@aoligei-1122 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your valuable data with reliable storage providers. If you need any help, we are always here for you！

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi there!

It seems that you have successfully onboarded deals to the network, congratulations!
Unfortunately all the miners you used for onboarding have been involved in heavy CID sharing / non compliance in the FIL+ program.  Can you share us their contact information and the offer they made to you for storing this data?

Unfortunately nothing of this data is retrievable (As expected) with this SP. This is against the rules and guidelines of FIL+ you can read here: https://github.com/filecoin-project/filecoin-plus-large-datasets/

Awaiting your comments @aoligei-1122


>>

Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675098540697899876|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675098540697899877|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 8ms [1675098540697899876|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 8ms [1675098540697899877|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 169ms [1675098540697899876|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 171ms [1675098540697899876|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 182ms [1675098540697899877|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 185ms [1675098540697899877|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 188ms [1675098540697899876|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 189ms [1675098540697899876|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 272ms [1675098540697899877|0]
Jan 30 20:36:25 proposals dealscanner-f01981679-f01890456: Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 273ms [1675098540697899877|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675098540697899878|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675098540697899879|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 8ms [1675098540697899878|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 9ms [1675098540697899879|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 207ms [1675098540697899878|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 208ms [1675098540697899878|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 209ms [1675098540697899879|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 211ms [1675098540697899879|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 215ms [1675098540697899878|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 216ms [1675098540697899878|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 324ms [1675098540697899879|0]
Jan 30 20:36:26 proposals dealscanner-f01981679-f01853104: Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 325ms [1675098540697899879|0]

**Comment by aoligei1122** [comment]
Hi~ @cryptowhizzard 
Thank you for your reply, we have contacted sp for confirmation as the DC credit is currently unused and we expect to complete the storage this week. The data CID will be retrieved and publicly disclosed by this week. We are also in the process of contacting new sp's, the one we are currently in communication with is Greaterheat in China and we expect to have more sp's storing our data in the next round.

**Comment by cryptowhizzard** [comment]
Hi @aoligei-1122 

--
Unfortunately all the miners you used for onboarding have been involved in heavy CID sharing / non compliance in the FIL+ program. Can you share us their contact information and the offer they made to you for storing this data?
--

**Comment by CaptaiNLP** [comment]
@cryptowhizzard Thanks for the reminder, for us, as long as the sp storing our data is compliant and can be retrieved, it is a good partner for us. Because our data is still being stored, we will soon ask the sp to provide us with the CID of the data. At that time, I will make this information public here.
--
In addition, because our colleague who is responsible for submitting the fil+ application is on leave, I will answer your questions during the period, thank you.

**Comment by YuanHeHK** [comment]
checker:manualTrigger

**Comment by CaptaiNLP** [comment]
The following is our stored data cid disclosure, hope to get the notary's support, thanks

[ldn-880.xlsx](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/11144448/ldn-880.xlsx)

**Comment by fireflyHZ** [comment]
Spot check the published data and search appears to be fine. 
![截图 2023-04-07 13-24-19](https://user-images.githubusercontent.com/100905326/230546632-5b5c7a41-a722-4d76-8ece-ab786306dafd.png)
![截图 2023-04-07 13-23-28](https://user-images.githubusercontent.com/100905326/230546636-51eed107-4f2d-4252-ac98-a6c03f24661e.png)

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahyzyksxaro5gvco2cklcutkuydg6gcgifmrbaetyeq62cyofv7y 
#### Address 
> f1txoa2y643i7zguyorpahfzo74d2zmin6kw54bpi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahyzyksxaro5gvco2cklcutkuydg6gcgifmrbaetyeq62cyofv7y

**Comment by Bitrise0111** [comment]
This has been retrieval tested and the check report shows no problem.

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamgabycaq2n6o3jhqzllxevpv6dmf7uqjdsvrsx4nvkpdl2kjmzo 
#### Address 
> f1txoa2y643i7zguyorpahfzo74d2zmin6kw54bpi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamgabycaq2n6o3jhqzllxevpv6dmf7uqjdsvrsx4nvkpdl2kjmzo

**Comment by CaptaiNLP** [comment]
The LDN reported an error and could not continue, I have reapplied for a new LDN

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/68a96d5b-1e37-443c-8791-5f99b4879e65)
There is 94 TB datacap left. Can you specify the problem in applying for datacap?

**Comment by CaptaiNLP** [comment]
hi, @Sunnyiscoming 
Thanks for your reply, as shown in 880's log, this LDN bot has reported errors which prevented us from continuing. So I asked for help in slack but didn't get a reply, so I had to re-initiate a new application #2077.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/121649929/4bedb0c3-5fd0-4c23-872d-a2bc5616220c)
Also, as you can see, our check bot is healthy and we also disclose the stored data cid. hope we can get your support.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/121649929/a7c688c5-7249-4e91-8d8e-c76df8df46d1)

**Comment by Sunnyiscoming** [comment]
So I suggest you close #2077 .

**Comment by CaptaiNLP** [comment]
> So I suggest you close #2077 .

@Sunnyiscoming Hi,Sun.

I apologize, but the #880 application was not submitted through my GitHub account. The colleague responsible for the application has already left, so I can only resubmit a new application at this time. The 880 application is no longer usable due to bot errors, and I kindly request your assistance in closing the #880 application. Your help in this matter would be greatly appreciated.
