### ISSUE TITLE
[DataCap Application] Fujian Strong Flex Electronic Technology Co.,LTD

### ISSUE THREAD

**Issue by strong-flex** [filecoin-project/filecoin-plus-large-datasets#885]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fujian Strong Flex Electronic Technology Co.,LTD
- Website / Social Media:http://www.strong-flex.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1m5doxcxmh7n46vakcniipkf3ap523b6jrobpo3i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Fujian Strong Flex Electronic Technology Co.,LTD. is a professional flexible printed circuit manufacturer.
A team with more than ten years experience and modern workshop & advanced equipments, we have confidence to supply high value solution to our customers. Now our annual ability is 120,000 square meters and can deliver within 7 days.
As an ISO9001 qualified factory, we have driven without compromised to access advance management. Serials of our products have got ROHS and UL approved.
Dedicate to provide our customers with satisfied solution. We create high value with competitive price, fast delivery and comprehensive after-sales service.
We are looking forward to share our reputation of excellence with you in the near future.
```

What is the primary source of funding for this project?
```
The company is self-financed.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Company introduction, instructional videos, product pictures and videos.
```

Where was the data in this dataset sourced from?
```
Stored on the company server, and also purchased Alibaba Cloud.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1u1Zl2gzfQuILjWv5X6Vac-EG8tV_mNK4?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,confirm.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in Asia, Europe, Africa also available.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope that high-quality and stable storage service providers will contact us, and we will carefully screen storage service providers to ensure the safe storage of data.
```

How will you be distributing deals across storage providers?
```
No more than 50% in Asia, and no more than 30% for the same storage service provider to ensure data security.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have sufficient funds to start the project, thank you for your support.
```

**Comment by raghavrmadya** [comment]
No sample of instructional videos. Only .jpg. Please provide more information

**Comment by strong-flex** [comment]
> No sample of instructional videos. Only .jpg. Please provide more information
Hi,@raghavrmadya
This is an omission, thank you for your attention to us
Here is the link to share the video
https://drive.google.com/drive/folders/1o41t_pAhVI2_u8b_BDJpx6YXCvfjdKLI?usp=sharing

**Comment by Sunnyiscoming** [comment]
Is all these data samples, video produced by your organization? How much data are you going to store? How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #885.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by strong-flex** [comment]
> Is all these data samples, video produced by your organization? How much data are you going to store? How many copies will you store? What's the relationship between you and organization? Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #885.
Hello,@Sunnyiscoming
I am the director of the company office.
The data are all produced by our company and our partners.
We will store 5-6 backup copies, and the total amount of data does not exceed 200T.
We have finished contacting with f0152799 and f01681808.
At the same time, we are still actively looking for more high-quality SPs. We promise that we will abide by the rules of FIL+, and the storage of a single SP does not exceed 25%.

**Comment by Sunnyiscoming** [comment]
KYB email has not be sent.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
