### ISSUE TITLE
[DataCap Application] Shenzhen Guose Tianzi Clothing Co., Ltd.

### ISSUE THREAD

**Issue by szguosetianzi** [filecoin-project/filecoin-plus-large-datasets#886]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Guose Tianzi Clothing Co., Ltd.
- Website / Social Media: http://www.feiola.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1szepmm5hyjuv433t4qu7myv74445qvlvu76v5ni

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Guose Tianzi Co., Ltd. is an international trading company with its own brand Feiola. Guose Tianzi was established in 1983. It has its own factory in Dongguan - Dongguan Wangfei Pleated Garment Factory. It has a professional design team, a pattern maker and skilled lathes with many years of experience in pleating. At the same time, we have opened our own stores in large shopping malls in the three major cities of Guangzhou, Shenzhen and Dongguan. We focus on the design and sales of mid-to-high-end clothing.

Feiola's pleated clothing has its own characteristics. When laid flat, it is like a sculpture, showing a three-dimensional geometric pattern, and it conforms to the body curve and the rhythm of movement when worn on the body.

In the more than 30 years since its establishment, we have mainly focused on offline sales, but with the development of the new crown epidemic, the business of stores has gradually begun to slump. Therefore, we established Douyin for online promotion. Our Douyin account is Feiola's flagship store and currently has 63,000 followers.
```

What is the primary source of funding for this project?
```
Our company has a long history, and the unit price of clothes is more than 3000, so it is very profitable.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Stores data related to clothing.

First of all, models or store managers/clerks wear photos or videos of new clothes in order to show them to more customers. Therefore, videos or pictures of models wearing our pleated clothes are stored.

Secondly, in our offline stores, the environment of the offline store, the display of clothes in the store, and even the scene where the store receives users, will also choose to store part of it on the filecoin network.

Finally, we basically participate in the clothing conference held in Shenzhen every year, but due to insufficient computer and mobile phone memory, these materials have been deleted by us, so if you agree to our request to store data on the filecoin network, we will We chose to store the live broadcast of the press conference and the videos of the models walking the runway.

```

Where was the data in this dataset sourced from?
```
Pictures and videos of what our models are wearing, and pictures and videos from events we host.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/u/0/folders/1bnDyDrl9-0GE5svFCV85O0hY6qQXod14
https://drive.google.com/drive/u/0/folders/1HOl4xpHN-qP2eKzYLhHhbvK3VtW5RmUn
https://drive.google.com/drive/u/0/folders/1Yv8Sz9MXMDJfds14CGgH46ElUoZa_6hi

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Maybe once every1 year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For about 3year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We have no restrictions on where we store。Our only wish is for our data to be safely and permanently stored.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We apply for 3P data and do 2-3 backups.
We will mainly transfer data to SP through hard disk. We thank filecoin for giving us the opportunity to store data for free. Therefore, we will prepare the cost of hard disk by ourselves. However, if it's a sp outside of Greater China, we expect them to cover the postage.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We found that Slack and Filgram and Filfox are better tools for finding sps, and we will choose comprehensively.
```

How will you be distributing deals across storage providers?
```
We believe that storing data in multiple nodes is one of the manifestations of distributed data storage, and I will definitely abide by the rules of FIL+ to ensure that the stored data of each node does not exceed 25%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough resources.
```

**Comment by raghavrmadya** [comment]
unable to access data samples
