### ISSUE TITLE
[DataCap Application] DKArt

### ISSUE THREAD

**Issue by Muse214** [filecoin-project/filecoin-plus-large-datasets#888]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: DaYe Art Tuition Class (DKArt) 
- Website / Social Media: https://www.artinize.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
With a strong faculty and perfect management, DaYe has become a dream place for students to realize their art dreams since 2012. Our teaching team (60 teachers) has more than five years of teaching experience. Over the years, DaYe has guided art competitions and taught students unique painting techniques.
```

What is the primary source of funding for this project?
```
Income from the classes.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We store paintings by students and teachers, as well as videos of teachers teaching painting. All data need to be stored as 6 copies.
```

Where was the data in this dataset sourced from?
```
All data is from lessons we provided. Now we are using local storage.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1HJml6bRsr92M6-dE8eifAnDDVklrlfz5/view?usp=sharing
https://drive.google.com/file/d/1Hm_IsE4GTvDDkUCwFaplLP7iKf1Zc4Gi/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. We confirm.
```

What is the expected retrieval frequency for this data?
```
We think that the frequency of future retrieval will be once every two years.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years. Next we will expand the size of the studio and the amount of data will be bigger.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia------China, Singapore and more countries.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. We can transfer data online in China. If we distribute data to other countries in Asia, we may change the way into offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
First, we plan to find storage providers on slack.
Then, we check the qualification of SPs. (History and experience)
After we confirm the sp situation and get the datacap, we will start the cooperation.
```

How will you be distributing deals across storage providers?
```
Our distribution depends on the number of SP we reach out to. We hope to contact at least 5 SPs, so that we can distribute to every SP <20% deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by DKArtstudio** [comment]
I will complete it later!

**Comment by DKArtstudio** [comment]
I will finish it later!

**Comment by raghavrmadya** [comment]
Unable to verify 5 PiB request based on data sample. Share more about your business and operations.

**Comment by Muse214** [comment]
@raghavrmadya We are DK Art Studio, a professional art training institution with a variety of classes.
In our daily teaching, we have accumulated a large number of students' paintings and teaching materials---includes images of sample paintings and videos of live teaching sessions. We need to save students' drawings for teaching and research, so part of our data comes from scanned files of them. The teacher's drawing examples will be used for display, so they need to be stored for backup as well.
The amount of our current data is about 800 TiB, and we intend to store 6 copies. I've updated the data sample. https://drive.google.com/file/d/1Hm_IsE4GTvDDkUCwFaplLP7iKf1Zc4Gi/view?usp=sharing
Hope it can give you a good answer.

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #888.

**Comment by Muse214** [comment]
![1](https://user-images.githubusercontent.com/107523650/193519915-35a3871e-3b29-4f39-a51e-c649ae5a88a8.jpg)
Hi @Sunnyiscoming , I’ve followed your request and sent the email. I‘m an employee of DaYe who is taking charge of our data. For the storage, we have a plan with these Sps: f01141810, f080103, f039800. We’ll mainly make deals in Asia, so we’ll find more Sps from there.

**Comment by raghavrmadya** [comment]
The community is still concerned about the amount of DC requested. Please come to the next Trust and Transparency WG call or share a video recording explaining your business and dataset so that we can share it with the community

**Comment by raghavrmadya** [comment]
Who is the technical person responsible for data transfer? Are you working with an SP already?

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvk3ekjwfe7blm5zhn5qv5basmhak7yg532ql43v75aljudzg5bq 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvk3ekjwfe7blm5zhn5qv5basmhak7yg532ql43v75aljudzg5bq

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdwccmclp6qptauvl4p5jeijmlufdoxzi4c3n6yd6qzzekudrhuu 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdwccmclp6qptauvl4p5jeijmlufdoxzi4c3n6yd6qzzekudrhuu

**Comment by BigD-Exchange** [comment]
@Muse214 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebytc2qixmg4vhzj7rj7jtoj24odeiqnlv5ghtt4yu775ihqcmyia 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 148ed856-75eb-4ee5-b27b-266063bb526d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebytc2qixmg4vhzj7rj7jtoj24odeiqnlv5ghtt4yu775ihqcmyia

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbfyw46ogdhegn6qs7jbuffat74bnzninczmzrybgy76bov27wou 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> dc6c59a5-9499-44de-9cce-c907e70c1d5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbfyw46ogdhegn6qs7jbuffat74bnzninczmzrybgy76bov27wou

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvaf5bldvbbgg2sushbqrla5pbp5a2riguyxow4bw7e654y5qbt6 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> dc6c59a5-9499-44de-9cce-c907e70c1d5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvaf5bldvbbgg2sushbqrla5pbp5a2riguyxow4bw7e654y5qbt6

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzbokewziozqzs5mu5s4tvqe2fpinxocwi7w3sfpseqhu2iv3d44 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> f2d83cdc-563e-45a6-b9ee-3c93f0837eeb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzbokewziozqzs5mu5s4tvqe2fpinxocwi7w3sfpseqhu2iv3d44

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb45krgovlwalpwj4fw4a4qnltmu6czzxqlsas4khllxjddbz2wkg 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> f2d83cdc-563e-45a6-b9ee-3c93f0837eeb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb45krgovlwalpwj4fw4a4qnltmu6czzxqlsas4khllxjddbz2wkg

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkspg525zwmgvvj63545u2vpq7efzaomxm6oqoytljj6yefo24ce 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> a028866e-7ebd-4c65-9f3f-91f1d82abe2c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkspg525zwmgvvj63545u2vpq7efzaomxm6oqoytljj6yefo24ce

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxtfrtsictqdzelvdcmsugrj3ieiqou6sevjrzv3iy7yrgs77roo 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 45b05b9d-a916-4ea7-ae69-55a788a72834
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxtfrtsictqdzelvdcmsugrj3ieiqou6sevjrzv3iy7yrgs77roo

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6pxtflp43q4pt7q736ewdmi3r4vnfuzk5cqgmazez3lj3ichlmg 
#### Address 
> f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 45b05b9d-a916-4ea7-ae69-55a788a72834
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6pxtflp43q4pt7q736ewdmi3r4vnfuzk5cqgmazez3lj3ichlmg

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `DaYe Art Tuition Class (DKArt) `
 - Client: `f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01969789](https://filfox.info/en/address/f01969789) has sealed 41.84% of total datacap.

⚠️ 74.20% of total deal sealed by [f01969789](https://filfox.info/en/address/f01969789) are duplicate data.

⚠️ [f0681068](https://filfox.info/en/address/f0681068) has sealed 26.24% of total datacap.

⚠️ 87.77% of total deal sealed by [f0681068](https://filfox.info/en/address/f0681068) are duplicate data.

⚠️ 86.07% of total deal sealed by [f01344987](https://filfox.info/en/address/f01344987) are duplicate data.

⚠️ 62.23% of total deal sealed by [f01841131](https://filfox.info/en/address/f01841131) are duplicate data.

⚠️ 83.83% of total deal sealed by [f01841133](https://filfox.info/en/address/f01841133) are duplicate data.

⚠️ 89.71% of total deal sealed by [f0229199](https://filfox.info/en/address/f0229199) are duplicate data.

⚠️ 78.96% of total deal sealed by [f01392600](https://filfox.info/en/address/f01392600) are duplicate data.

⚠️ 87.50% of total deal sealed by [f0136399](https://filfox.info/en/address/f0136399) are duplicate data.

⚠️ 89.74% of total deal sealed by [f01384077](https://filfox.info/en/address/f01384077) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01969789](https://filfox.info/en/address/f01969789)       | Hong Kong, Central and Western, HK |         482.34 TiB |     41.84% |  124.47 TiB |          74.20% |
| [f0681068](https://filfox.info/en/address/f0681068)         | Hong Kong, Central and Western, HK |         302.50 TiB |     26.24% |   37.00 TiB |          87.77% |
| [f01344987](https://filfox.info/en/address/f01344987)       | Hong Kong, Central and Western, HK |         142.72 TiB |     12.38% |   19.88 TiB |          86.07% |
| [f01841131](https://filfox.info/en/address/f01841131)       | Hong Kong, Central and Western, HK |          70.75 TiB |      6.14% |   26.72 TiB |          62.23% |
| [f01841133](https://filfox.info/en/address/f01841133)       |           Singapore, Singapore, SG |          55.84 TiB |      4.84% |    9.03 TiB |          83.83% |
| [f0229199](https://filfox.info/en/address/f0229199)         | Hong Kong, Central and Western, HK |          49.81 TiB |      4.32% |    5.13 TiB |          89.71% |
| [f01392600](https://filfox.info/en/address/f01392600)       | Hong Kong, Central and Western, HK |          34.16 TiB |      2.96% |    7.19 TiB |          78.96% |
| [f0136399](https://filfox.info/en/address/f0136399)         | Hong Kong, Central and Western, HK |          13.50 TiB |      1.17% |    1.69 TiB |          87.50% |
| [f01384077](https://filfox.info/en/address/f01384077)`new`  |           Guangzhou, Guangdong, CN |           1.22 TiB |      0.11% |  128.00 GiB |          89.74% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/888/1671097891051.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       202.47 TiB |      1023.97 TiB |                   1 |          88.82% |
|        14.38 TiB |       128.88 TiB |                   2 |          11.18% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/888/1671097891635.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                       | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :---------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                    |           131.03 TiB |         401 | LDN v3 multisig |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui)                                                                                                     | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                             |            81.34 TiB |         241 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy)                                                                                                     | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)       |            66.69 TiB |         197 | LDN v3 multisig |
| [f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa](https://filfox.info/en/address/f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa)                                                                                                     | [NOAA GOES\-\-\-Piero](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112)              |            63.38 TiB |         444 | LDN v3 multisig |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)              |            62.34 TiB |         206 | LDN v3 multisig |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                          |            47.09 TiB |         232 | LDN v3 multisig |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429) |            39.91 TiB |         188 | LDN v3 multisig |
| [f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy](https://filfox.info/en/address/f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy)                                                                                                     | [BotSmart ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/373)                          |            29.84 TiB |         145 | LDN v3 multisig |
| [f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa](https://filfox.info/en/address/f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                           |            27.94 TiB |         211 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                         |            27.81 TiB |          89 | LDN v3 multisig |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui)                                                                                                     | `Weipaitang`                                                                                                      |            17.53 TiB |          88 | LDN v3 multisig |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                           |            15.78 TiB |          98 | LDN v3 multisig |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)             |            13.09 TiB |          87 |        LDN # 51 |
| [f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay](https://filfox.info/en/address/f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay)                                                                                                     | [Public Data\-FlyBrain](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1013)             |             1.03 TiB |           5 | LDN v3 multisig |
| [f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc<br/>3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7<br/>gg2q](https://filfox.info/en/address/f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7gg2q) | [Runtu Information Technology](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1150)   |           448.00 GiB |           4 |       Steven Li |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Another application full of fraud.

All this data is fake data and shared among different LDN requests.

**Comment by BDEio** [comment]
@Muse214 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your valuable data with reliable storage providers. If you need any help, please get in touch.
