### ISSUE TITLE
[DataCap Application] Xiamen Xinfan Industry and Trade Co., Ltd.

### ISSUE THREAD

**Issue by xmxinfan** [filecoin-project/filecoin-plus-large-datasets#889]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xiamen Xinfan Industry and Trade Co., Ltd.
- Website / Social Media:http://www.xmxinfan.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1oc3fuzztq7qs3jqrz2qxdwqz23xxfzilrtcrjki

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xiamen Xinfan Industry and Trade Co., Ltd. was established in 2018 and is located in Xiamen. It is a professional design, printing and production enterprise. The main purpose is to let customers enjoy beautiful visual and spiritual feelings through professional vision and technical means. richer. Grasp the market, pursue unique and outstanding design, enhance product value, and enhance corporate image are the company's design features.
The company has a group of well-trained professionals with excellent artistic quality. After unremitting efforts, the company has established branches in major cities in China with Xiamen as the center, and established strategic cooperative relations with some domestic institutions in the same industry.
Over the years, based on the concept of professionalism and concentration, and the unremitting pursuit and struggle for ideals, the company has served and won the recognition of many domestic and foreign customers!
```

What is the primary source of funding for this project?
```
Company's own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Rendering design of living space, including: renderings of home decoration, renderings of star-rated hotels, lobby, shared space, lobby bar, renderings of Four Seasons Hall, business center, multi-function hall, disco, bar, coffee shop, sauna, KTV , karaoke hall, private room, tea house, swimming, fitness, Internet cafe, beauty salon, SPA, wedding dress, photo studio, restaurant, western restaurant, Chinese restaurant, banquet hall, dance hall design renderings.
Design of public office space renderings, including: office buildings, office buildings, office renderings, halls, foyer, reception desk, general manager room, president, president, director room, conference room, reception room, reference room, conference hall, Renderings of government affairs, banking, finance, telecommunications business halls, hospitals, schools, bookstores, children's palaces, kindergartens, lecture halls, exhibition halls, museums, post offices, concert halls, theaters, gymnasiums, office furniture renderings.
Commercial display space rendering design, including: commercial storefronts, shopping malls, stores, specialty store renderings, clothing, cosmetics, jewelry, electrical appliances, food, creative gifts.
Service products: packaging design, printing design, color box processing, book printing, etc.
```

Where was the data in this dataset sourced from?
```
The company's existing servers, part of hard disk storage, part of network cloud storage, such as Tencent Cloud.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1F-wAo_ZiRoEryM2qqZ2v0wNOSaqritI_?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,we confirm that is a public data.
```

What is the expected retrieval frequency for this data?
```
2-3 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
No specific region requirements, as long as data is securely stored.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly offline transmission, a small part of online transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
At present, we are in contact with several storage service providers, and we hope that more storage service providers will contact us. We hope that the data will be stored safely, and there are not too many requirements for the storage service providers. It is enough to meet our basic conditions.
```

How will you be distributing deals across storage providers?
```
Regarding the allocation of data, it is enough to ensure that the data is not concentrated in one storage service provider, that is, a service provider does not store more than 30% of the data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are fully funded.
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/193439567-89d5a1cd-28f1-422a-9177-b8708af8e46a.png)
![image](https://user-images.githubusercontent.com/105098820/193439599-fcece12f-6d17-4b80-b05e-b9236b4239ff.png)
![image](https://user-images.githubusercontent.com/105098820/193439605-629c429c-8595-4c37-b3fc-39c42300ea51.png)
It seems that this website is not very complete. Can you explain about that?

> Describe the data being stored onto Filecoin
> Rendering design of living space, including: renderings of home decoration, renderings of star-rated hotels, lobby, shared space, lobby bar, renderings of Four Seasons Hall, business center, multi-function hall, disco, bar, coffee shop, sauna, KTV , karaoke hall, private room, tea house, swimming, fitness, Internet cafe, beauty salon, SPA, wedding dress, photo studio, restaurant, western restaurant, Chinese restaurant, banquet hall, dance hall design renderings.
> Design of public office space renderings, including: office buildings, office buildings, office renderings, halls, foyer, reception desk, general manager room, president, president, director room, conference room, reception room, reference room, conference hall, Renderings of government affairs, banking, finance, telecommunications business halls, hospitals, schools, bookstores, children's palaces, kindergartens, lecture halls, exhibition halls, museums, post offices, concert halls, theaters, gymnasiums, office furniture renderings.
> Commercial display space rendering design, including: commercial storefronts, shopping malls, stores, specialty store renderings, clothing, cosmetics, jewelry, electrical appliances, food, creative gifts.
> Service products: packaging design, printing design, color box processing, book printing, etc.

The main business described on the website does not appear to be directly related to the data to be stored. Where these data originate from?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by xmxinfan** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/193439567-89d5a1cd-28f1-422a-9177-b8708af8e46a.png) ![image](https://user-images.githubusercontent.com/105098820/193439599-fcece12f-6d17-4b80-b05e-b9236b4239ff.png) ![image](https://user-images.githubusercontent.com/105098820/193439605-629c429c-8595-4c37-b3fc-39c42300ea51.png) It seems that this website is not very complete. Can you explain about that?
> 
> > Describe the data being stored onto Filecoin
> > Rendering design of living space, including: renderings of home decoration, renderings of star-rated hotels, lobby, shared space, lobby bar, renderings of Four Seasons Hall, business center, multi-function hall, disco, bar, coffee shop, sauna, KTV , karaoke hall, private room, tea house, swimming, fitness, Internet cafe, beauty salon, SPA, wedding dress, photo studio, restaurant, western restaurant, Chinese restaurant, banquet hall, dance hall design renderings.
> > Design of public office space renderings, including: office buildings, office buildings, office renderings, halls, foyer, reception desk, general manager room, president, president, director room, conference room, reception room, reference room, conference hall, Renderings of government affairs, banking, finance, telecommunications business halls, hospitals, schools, bookstores, children's palaces, kindergartens, lecture halls, exhibition halls, museums, post offices, concert halls, theaters, gymnasiums, office furniture renderings.
> > Commercial display space rendering design, including: commercial storefronts, shopping malls, stores, specialty store renderings, clothing, cosmetics, jewelry, electrical appliances, food, creative gifts.
> > Service products: packaging design, printing design, color box processing, book printing, etc.
> 
> The main business described on the website does not appear to be directly related to the data to be stored. Where these data originate from?

Sorry for not replying in time due to recent vacation.
Due to the principle of confidentiality of some design manuscripts, some of our pictures are case illustrations. We will rectify this in time. Thank you for your reminder.
The data stored are public data for allergy desensitization, as well as promotional video data of partners.

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with the data you will store to prove that you have 5 PB data? Videos would be better. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
