### ISSUE TITLE
[DataCap Application] <Guangzhou Yispeed Cloud Computing Co.> - <Eastspeed Cloud 2>

### ISSUE THREAD

**Issue by sahdqh2763** [filecoin-project/filecoin-plus-large-datasets#890]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Eastspeed Cloud
- Website / Social Media:https://www.yisu.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):178TiB
- On-chain address for first allocation:f1cwsjy3tlulgmbqufuswarn3opbuvrfu2oay2efi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yispeed Cloud, full name Guangzhou Yispeed Cloud Computing Co. Founded in 2017, it is an innovative enterprise dedicated to cloud computing, cloud security technology development, product operation and service guarantee. The core team of Yishu Cloud has more than sixteen years of experience in the Internet field, and the company currently has more than one hundred employees, mainly responsible for technical research and development and service guarantee. As an independent and neutral cloud computing enterprise, its self-developed cloud computing, cloud security, cloud storage, SDN customizable network platform, with excellent cloud computing technology, solutions more in line with the actual needs of customers and perfect after-sales service guarantee, has been obtained including greedy game, 4399 games, Seventh Avenue, cloud tour holding group, 9377 games, playmaker entertainment, tiger live currently, running The total number of cloud servers exceeds 50,000, and grows at a rate of more than 10% per month.
```

What is the primary source of funding for this project?
```
The main source of funding for this project is provided by the company's operating income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
The company provides tutorial videos, file data and data generated during the operation of the Yishu cloud platform.
```

Where was the data in this dataset sourced from?
```
The data in this dataset comes from Yishu Cloud, a cloud computing product that currently acquires data from games, finance, live streaming, video, portals, downloads, webmaster platforms, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1l1VeUCSsHG0heMoczAJiGW7QKvhTpP4p?usp=sharing
https://drive.google.com/file/d/18ydEjB1ttlu9AY157akXEc0S16G_TA_k/view?usp=sharing
https://www.yisu.com/zixun/hlwkj/
https://www.yisu.com/help/
https://drive.google.com/drive/folders/1W_qRpJFBXM4m963UwsK8jSSkIXP4h1Ti?usp=sharing
https://www.yisu.com/solution/
https://www.yisu.com/appmarket/
https://www.yisu.com/case/
https://www.yisu.com/zixun/sjk/
https://www.yisu.com/zixun/sjk_msju/
https://www.yisu.com/zixun/sjk_mdb/
https://www.yisu.com/zixun/sjk_gxx/
https://www.yisu.com/zixun/fwq/
https://www.yisu.com/zixun/sjk/
https://www.yisu.com/zixun/kf/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is a public dataset that can be retrieved by anyone on the web.
```

What is the expected retrieval frequency for this data?
```
2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store this dataset on Filecoin for at least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong, China, United States.Europe, Japan, Korea，Singapore and other regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Off-line transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We intend to plan to select a strong, stable and experienced service provider.
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources/money to start trading.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? And to provide more data samples related with data generated during the operation of the Yishu cloud platform. How many copies will you store?
Otherwise, a strong, stable and experienced service provider is not meet the requirement of FIL+ LDN that each sp should not exceed 30%.
What's the relationship between you and organization?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #890.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
