### ISSUE TITLE
[DataCap Application] <Coala> - <Crypto currency>

### ISSUE THREAD

**Issue by gruipeng999** [filecoin-project/filecoin-plus-large-datasets#891]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Coala
- Website / Social Media: https://coala.co.kr/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1hgzuoilpui6hhz5zbncmi5gptcfnscw5r5pymdy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
COALA is an online community integrating Korean blockchain data and information, providing various reliable information for the development of the blockchain ecosystem and creating infrastructure for the development of the blockchain ecosystem.
We provide: Software Development, Cryptocurrency Exchange, Cryptocurrency Consulting / Educational
```

What is the primary source of funding for this project?
```
Own money
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Pictures uploaded by users, transaction data, etc
```

Where was the data in this dataset sourced from?
```
Our software system.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1pyUK6y-7E-gCu8yWAuxcluItJLozgxCx
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
500 days or more.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in  Korea，Hong Kong， Singapore
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online or Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have contacted 3 SPS and plan to use five vendor storage.
```

How will you be distributing deals across storage providers?
```
Every storage provider will have same amount of deals to accept and seal.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. There are operators familiar with the transaction process to help us.
```

**Comment by raghavrmadya** [comment]
What is your relationship with coala?

**Comment by gruipeng999** [comment]
> 

I work at this company.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/193441847-927c8a9f-c3ad-492d-8e25-f77fcd56ab64.png)
Too many similiar pictures in the data samples you provided. Are these pictures uploaded by users?

> Describe the data being stored onto Filecoin
> Pictures uploaded by users, transaction data, etc

Have you obtain users authorization to upload these data onto Filecoin as public data?

Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
