### ISSUE TITLE
[DataCap Application]Xiamen culf Precision Hardware Co., Ltd.

### ISSUE THREAD

**Issue by dixiedrake** [filecoin-project/filecoin-plus-large-datasets#895]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xiamen culf Precision Hardware Co., Ltd.
- Website / Social Media:http://www.culf.top/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1lvscvp6u5iydls5w6ssvewgwupg5hzs6vldgz7a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xiamen culf Precision Hardware Co., Ltd.was established in 2015. Our company specializes in precision hardware design, production and processing, with advanced processing equipment, professional design team and long-term cooperation in surface treatment plant. The main fields include aviation, medical, industrial and communication industries. The production team has more than 5 years of processing experience. We are committed to meet the differentiated needs of customers, and achieve win-win with customers in accordance with the mode of high quality, short delivery time and low cost.
```

What is the primary source of funding for this project?
```
Company's own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mechanical design drawings, product design drawings, parts drawings, processing drawings, product manuals, test reports.
```

Where was the data in this dataset sourced from?
```
Company servers, hard drives, and Alibaba Cloud.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1gf7WMyMnnv-YLYX5IJz-z1j6dCHNhWGV?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,we confirm.
```

What is the expected retrieval frequency for this data?
```
Twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Anywhere, no limit.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have contacted several storage service providers, which are still under investigation. We also hope that more storage service providers will contact us, regardless of region.
```

How will you be distributing deals across storage providers?
```
In order to ensure data security, there are no less than 5 storage service providers, and each storage service provider has a data volume of no more than 30%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have sufficient funds.
```

**Comment by raghavrmadya** [comment]
It's hard to believe that the kind of data described is 1.5 PB. Please provide more information including but not limited to number of copies, SP distribution etc.

**Comment by raghavrmadya** [comment]
No response
