### ISSUE TITLE
[DataCap Application] <Willing> - <Willing>

### ISSUE THREAD

**Issue by willingchem** [filecoin-project/filecoin-plus-large-datasets#897]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Willing
- Website / Social Media: https://www.willingchem.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Willing  New Materials Technology Co., Ltd. (Willing New Materials) started from 1998 with investment of RMB85020000.00, 
located in Chemical Industry-Intensive Area, Puyang, Henan, China, focusing on the production and sales for Rubber Chemicals, 
Thermosetting Resins and Organic Chemical Intermediates. Willing New Materials is key High-tech enterprise of National Torch Plan and
 innovative enterprise in Henan Province and the energy saving technology innovation demonstration enterprise, 
 and also the technological innovation demonstration enterprise, Top 100 enterprises and AAA grade credit quality Henan industrial enterprises.
```

What is the primary source of funding for this project?
```
Own money
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Product manuals, operation manuals, videos and pictures
```

Where was the data in this dataset sourced from?
```
Our own
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1O2RXBkrVFxYxDQmjFxSIng?pwd=gsij
Code：gsij
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
530 days or more.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in China, Hong Kong or Singapore.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to find high-quality service providers in the slack community, including 3 in Hong Kong and 2 in Singapore.
```

How will you be distributing deals across storage providers?
```
Each storage provider keeps one copy.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We don't need any help for the time being. Thank you very much.
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/193440919-d6af91b1-7d23-4937-9f37-15aeb125eee2.png)
The shared file has expired, please check it.

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by willingchem** [comment]
https://pan.baidu.com/s/1yvjz5IeDMZchdHUlD0fGmw 
Code：6o5w

**Comment by willingchem** [comment]
> https://pan.baidu.com/s/1yvjz5IeDMZchdHUlD0fGmw Code：6o5w

New link

**Comment by willingchem** [comment]
> What's the relationship between you and organization? Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?

I'm willing's partner

Now I have contacted 3 SPs (f01852023,f01852664, f01896030), plan to store 5 copies, and look for more SPs

**Comment by Sunnyiscoming** [comment]
The data samples are not totally from your organization, such as https://pan.baidu.com/s/1yvjz5IeDMZchdHUlD0fGmw#list/path=%2F%E5%8C%96%E5%B7%A5%E8%B5%84%E6%96%99%2F%E5%8C%96%E5%B7%A5%E5%8E%9F%E7%90%86%E5%85%A8%E5%A5%97%E8%B5%84%E6%96%99. Have you authorized to store these data on the Filecoin network?

**Comment by willingchem** [comment]
This is the data I uploaded, which can be fully disclosed with authorization

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3xe4nebln6qlcg3c5qd2wyo3zyrnlhrqzpyv4nsro62lpqvvo74 
#### Address 
> f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> ec3da524-1118-4b79-9917-f851656faa05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3xe4nebln6qlcg3c5qd2wyo3zyrnlhrqzpyv4nsro62lpqvvo74

**Comment by Tom-OriginStorage** [comment]
This is the first time to sign. I will follow up on it later. If there are any problems, I will contact the owner to solve them

**Comment by newwebgroup** [comment]
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

**Comment by willingchem** [comment]
![92567f2352df5ce3e751fa4d740d222](https://user-images.githubusercontent.com/112528699/204435761-d9dbca9e-328a-4f3e-b523-b07cf929c63d.jpg)

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecda5us7nsrpauudkwvn44hvey2rqulwbktjgfl2pxfejrb6e2t4y 
#### Address 
> f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> ec3da524-1118-4b79-9917-f851656faa05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecda5us7nsrpauudkwvn44hvey2rqulwbktjgfl2pxfejrb6e2t4y

**Comment by NDLABS-OFFICE** [comment]
Information has checked. will support it and will follow up on it.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedanwguopmn7kvaok3lactr7iqafj6i5tti7gjurunj6fafuft2jw 
#### Address 
> f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> d5284b73-c155-4499-8831-cd883286fb49
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedanwguopmn7kvaok3lactr7iqafj6i5tti7gjurunj6fafuft2jw

**Comment by xingjitansuo** [comment]
Things look good so far. I will approve this tranche

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceay2qj6piscfjtfmgve4bttsdvin2kcn5apdfo7b6uzmylmftyw4e 
#### Address 
> f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> d5284b73-c155-4499-8831-cd883286fb49
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceay2qj6piscfjtfmgve4bttsdvin2kcn5apdfo7b6uzmylmftyw4e

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Willing`
 - Client: `f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |          12.09 TiB |     24.35% |   12.09 TiB |           0.00% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |          10.47 TiB |     21.08% |   10.47 TiB |           0.00% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |           9.81 TiB |     19.76% |    9.81 TiB |           0.00% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |           9.63 TiB |     19.38% |    9.63 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |           7.66 TiB |     15.42% |    7.66 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/897/1671097904830.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        39.38 TiB |        39.38 TiB |                   1 |          79.30% |
|         4.63 TiB |         9.25 TiB |                   2 |          18.63% |
|       352.00 GiB |         1.03 TiB |                   3 |           2.08% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/897/1671097905437.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by stcouldlisa** [comment]
Looks ok, SPs are spread across other different continents, at the same time, the storage ratio is right, also, no CID sharing occurs.

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvpe26ll45pefcniaz245n3anwrzxkdyxgky3c6bl73mndoj4ee2 
#### Address 
> f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> cdf22b8f-9df2-4626-b3e2-b2e9313162ef
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvpe26ll45pefcniaz245n3anwrzxkdyxgky3c6bl73mndoj4ee2

**Comment by Tom-OriginStorage** [comment]
Cid Checker's results look good.
The SP locations are relatively distributed, and there is no Cid sharing

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecb5n32g2kh67zfzojq6y6glzvu5cwa2fwb62ck2ufooq6nigvney 
#### Address 
> f13lqyp2whkncrqx32mi2lxibscwurztn5w4ts37y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> cdf22b8f-9df2-4626-b3e2-b2e9313162ef
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb5n32g2kh67zfzojq6y6glzvu5cwa2fwb62ck2ufooq6nigvney

**Comment by herrehesse** [comment]
@willingchem dear applicant,

Your application seem to be aimed at business content and not suitable for a LDN on the Filecoin+ program.
Your data description "Product manuals, operation manuals, videos and pictures" is suited for FIL-E.

If you need help to move or place a new application there I would love to assist you.

@raghavrmadya @Sunnyiscoming

**Comment by BDEio** [comment]
@willingchem Hi! Congratulations on your DataCap approval！
BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by C00kies77** [comment]
checker:manualTrigger
