### ISSUE TITLE
[DataCap Application]shanghaixinshu

### ISSUE THREAD

**Issue by shanghaixinshu1** [filecoin-project/filecoin-plus-large-datasets#9]
# Large Client Application
### PLEASE NOTE ANY APPLICATION SUBMITTED BEFORE THE FINALIZATION OF THE GOVERNING FIP OR THIS REPO WILL BE DISCARDED

To apply as a large client, please fill out the following form. 

## Core Information
- Organization Name: Shanghai Xinshu Technology Co.Ltd
- Website / Social Media: http://iaphoto.cn/
- DataCap Requested: 5 PiB
- On-chain Address(es) to be Notarized: f1jayzlakave6ktfeu3ssymh7t5xnsancdehrli4i

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details
Describe the data being stored onto Filecoin
```
Cloud storage reserves have reached 200t, mainly photographer pictures, short video photography
There are more than 400 contracted photographers and photo agencies, and each photographer or photo agency needs 10-20t cold data storage space. Now they are communicating one by one
```

Confirm that this is a public data set that can be retrieved by anyone on the Network
```
Yes, everyone has access retrieval
```

What is the expected retrieval frequency for this data?
```
Records of life, travel, activities and other content will be searched by the public, and the storage volume is large for a long time. We think it is very appropriate to choose filecoin network.
```

For how long do you plan to keep this dataset stored on Filecoin? Is this a permanent archival or a temporary storage deal?
```
I think this is permanent files, and continuous.
```

## Use-case details
Describe the data being stored onto Filecoin
```
Cloud storage reserves have reached 200t, mainly photographer pictures, short video photography
There are more than 400 contracted photographers and photo agencies, and each photographer or photo agency needs 10-20t cold data storage space. Now they are communicating one by one
```

Confirm that this is a public data set that can be retrieved by anyone on the Network
```
Yes, everyone has access retrieval
```

What is the expected retrieval frequency for this data?
```
Records of life, travel, activities and other content will be searched by the public, and the storage volume is large for a long time. We think it is very appropriate to choose filecoin network.
```

For how long do you plan to keep this dataset stored on Filecoin? Is this a permanent archival or a temporary storage deal?
```
I think this is permanent files, and continuous.
```

## DataCap allocation plan
In which geographies do you plan on making storage deals?
```
It is mainly concentrated in chia
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We think the amount of data uploaded to the Fielcoin network is around 100 TiB per week
```

How do you plan on choosing the miners with whom you will be making deals?
```
We will select miners through miners reputation systems like filrep.io, or Filecoin blockchain explorers.
The main factors we considered are the following:
1.Location (Greater China is a priority for us)
2.Possess of experience in dealing with verified data.
3.Possess of more than 10 PiB Total Raw Power
```

How will you be ensuring fair distribution of storage and DataCap across miners storing data?
```
We will follow the rules for large-datasets, and we will ensure fair distribution through limiting the amount of deals send to each miner. These records will be made and published regularly on Github.

```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
Regarding this piece, we will talk to different miners and of course compare the prices of services between them, and these factors will also determine the distribution ratio between real data and DataCap.
```

**Comment by kernelogic** [comment]
I believe the current focus is public data only. How is this considered public data?
