### ISSUE TITLE
[DataCap Application] <DUIER> 

### ISSUE THREAD

**Issue by liangdewanjfieang** [filecoin-project/filecoin-plus-large-datasets#901]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: DUIER
- Website / Social Media: https://www.instagram.com/duier/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f16uctiqsjbebjlyor3fyaradd7zl4vvhzjxs72yq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The IT twins of the Orient set the new perspective of fashion entrepreneurship Ada and Anna, the twin founders of DUIER is one of the success stories, their fashion empire started in 2009. They are the hottest duo in the oriental fashion world, leading a team of top-class stylists, DUIERistas. With rising fame, Ada and Anna affected the world with their passion in fashion and their sharp sense of style. They were set to make a name for themselves in fashion.The Unconventional Trendsetter. The passion in styling have always been the motivation. Headquartered in Seoul, South Korea, DUIER expanded its styling studios to more than 10 locations across China with a flagship store in Seoul. The brand communicates with its clients to build trusting relationships, and creates statement styles for each and every one of its clients. Clients of DUIER value style as well as quality. While trends in design may come and go, DUIER believes that a cohesive aesthetic will help one to stand out with sophistication.
Weibo: http://weibo.com/duiersky
WeChat Official Account: Duier_Fashion 
Facebook: http://www.facebook.com/DuierSky
Instagram @duier @duierstyle
Pinterest: DUIER® Styling
YouTube: 对儿 DUIER
```

What is the primary source of funding for this project?
```
Commercial revenue of our own company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
In-store data, user data, shopper data, brand data, consumer review data, product data including inventory, discounts, categories, and other attributes of the products, and other related data categories used in eCommerce analytics and marketing.
```

Where was the data in this dataset sourced from?
```
Data generated during the operation of our business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/liangdewanjfieang/Data-Sample
https://mp.weixin.qq.com/s/hfeJn-QqqxTkDzdmrX9D4g
https://mp.weixin.qq.com/s/Cn2Rrz0YR5m4FtcdR4G_iw
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm this is a public dataset that can be publicly retrieved.
```

What is the expected retrieval frequency for this data?
```
At present, it is only used as a backup until our private cloud data is lost.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent archival.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Preferably Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline are available for us. SPs should have minimum 1Gbps bandwidth to get the online deal from us. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will work with miners through miners reputation systems like filrep.io, or Filecoin blockchain explorers.
The main factors we consider are the following:
- location (preferably Asia)
- transmission speed
- deal success rate
- previous experience of real data storage
- stability of their nodes
```

How will you be distributing deals across storage providers?
```
We'll divide percentage of deals on the basis of their ability before allocating deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by liangdewanjfieang** [comment]
@galen-mcandrew @raghavrmadya Hi could u check if there's any further info we need to provide? Our request needs progress. Thanks!

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with the data you will store to prove that you have 5 PB data? Videos would be better. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and DUIER?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by liangdewanjfieang** [comment]
@Sunnyiscoming 
Our data mainly consists of product photos and promotional videos. Photos are shown on our instagram account https://www.instagram.com/duier/ and we present our videos through WeChat Official Account: Duier_Fashion. 
![微信图片_20221008151252(1)](https://user-images.githubusercontent.com/108717156/194695233-28cf046e-77de-4198-8729-48be88ce9f51.png)

We’ll store 3-5 copies of the data.

I’m Olivia Chen, the marketing manager of the company.

We plan to work with 4-6 SPs and we’re doing some research to decide which SPs to allocate data to. Any advice on this? Thanks!

**Comment by Sunnyiscoming** [comment]
I have sent a confirmation to your instagram account. Please confirm it.

**Comment by liangdewanjfieang** [comment]
@Sunnyiscoming Hi Sunny we just sent the confirmation email with our official domain. Anna is the co-founder of the brand. Please confirm it.
![1](https://user-images.githubusercontent.com/108717156/197684601-d6ea8e48-6319-4ce4-8179-52598229b695.jpg)

**Comment by Sunnyiscoming** [comment]
I cannot confirm whether this domain name is the official domain name of this organization, so please provide the business license.

**Comment by liangdewanjfieang** [comment]
@Sunnyiscoming Hi we sent our business license to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with our official domain. Please check your email. Thanks~
![微信图片_20221108111604](https://user-images.githubusercontent.com/108717156/200469087-c372ae15-ee1c-49ab-978e-aa497820a5d3.jpg)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f16uctiqsjbebjlyor3fyaradd7zl4vvhzjxs72yq

**Comment by Defil2022** [comment]
> https://github.com/liangdewanjfieang/Data-Sample
https://mp.weixin.qq.com/s/hfeJn-QqqxTkDzdmrX9D4g
https://mp.weixin.qq.com/s/Cn2Rrz0YR5m4FtcdR4G_iw

From your description of sample data: https://github.com/liangdewanjfieang/Data-Sample/blob/main/videoplayback.zip
here's only one 30min video that i think is not relevant with your business.  Could you show us more  to present that you really own the video?

**Comment by liangdewanjfieang** [comment]
@Defil2022 Hi our data mainly consists of product photos and promotional videos and we present our videos through WeChat Official Account: Duier_Fashion.
![1](https://user-images.githubusercontent.com/108717156/205025340-a0ad7d84-78a0-4c5a-bc3a-eb6084754555.png)

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Hey @liangdewanjfieang , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by liangdewanjfieang** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

1. It's our first time working with IPFS, but recommended by our business partner which has been involved in IPFS for years, we are impressed by the development of the Filecoin network as the Fil+ program enables acquiring new users and onboarding valuable datasets and Filecoin is different from IPFS because it has an incentive layer on top to incentivize contents to be reliably stored and accessed. We hope we can have this opportunity to work with Filecoin and deliver benefits to the community.

2. https://github.com/liangdewanjfieang/Data-Sample 
https://mp.weixin.qq.com/s/hfeJn-QqqxTkDzdmrX9D4g 
https://mp.weixin.qq.com/s/Cn2Rrz0YR5m4FtcdR4G_iw
We’ll store 3-5 copies of the data. As you can see, these are part of our dataset which includes product dataset, revenue figures, product APIs, retailer lists, ecommerce dataset, E-commerce apparel dataset for AI & Computer Vision model, Consumer Purchase Data and product sales volume data of each SKU. We currently store our dataset on company server which is unsafe and inconvenient so we need to find alternatives such as cloud storage or better solutions like Fil plus.
![1111](https://user-images.githubusercontent.com/108717156/216272453-2390a5ee-fb1e-42e2-8cc3-c483d0f5425a.png)
![222](https://user-images.githubusercontent.com/108717156/216272465-fcdbc9bc-4a6c-4320-94a2-14be606527db.png)
![1111](https://user-images.githubusercontent.com/108717156/216272472-039ba1a1-9c47-492e-b7e7-5436d33b8e87.png)
![4444](https://user-images.githubusercontent.com/108717156/216272483-614a231f-4697-4fd1-aefc-edb14dfc366d.png)

**Comment by liangdewanjfieang** [comment]
> Hey @liangdewanjfieang , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

Thanks, will do.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by liangdewanjfieang** [comment]
@cryptowhizzard Hi I've already answered the questions. Please check above messages. Thanks

**Comment by cryptowhizzard** [comment]
Dear @liangdewanjfieang 

Thanks for completing KYC.

There are 2 fields that you left open on the KYC form. I need that information before i can sign on your application.

You indicated that you are the data preparer and owner of the dataset. Can you confirm you don't have any stake in SP's you are going to send this data to? As stated in the form I am allowing 1 replica of the set to be stored on your own miners. That's the reason i ask.

Second:

As the form states _> RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed.
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.

Can you provide me with the Sp's and their contact information?

Thanks!

**Comment by liangdewanjfieang** [comment]
@cryptowhizzard 
Dear notary, please refer to the following:
1. Can you confirm you don't have any stake in SP's you are going to send this data to?
Confirm.
2. Can you provide me with the SP's and their contact information?
May I ask if this is a mandatory rule in the Fil+ network since I haven't read any docs mentioning this. Please feel free to remind me if there's anything I missed. 

Thanks in advance!
