### ISSUE TITLE
[DataCap Allocation] - Dynamic mathematics software-GeoGebra

### ISSUE THREAD

**Issue by Ggb-6** [filecoin-project/filecoin-plus-large-datasets#906]
---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: GeoGebra
- Website / Social Media:  https://www.geogebra.org/ 
twitter/facebook/youtube/ins: GeoGebra 
Mali：chenchao@geogebra.org 
github：Ggb-6
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 80TiB
- On-chain address for first allocation: f1uv5w23yfteyllcpcomhji7yo7kkurrqydtcknay
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
GeoGebra is a dynamic mathematics software for all levels of education that brings together geometry, algebra, spreadsheets, graphing, statistics and calculus in one engine. In addition, GeoGebra offers an online platform with over 1 million free classroom resources created by our multilingual community. These resources can be easily shared through our collaboration platform GeoGebra Classroom where student progress can be monitored in real time.
GeoGebra is a community of millions of users located in just about every country. It has become the leading provider of dynamic mathematics software, supporting science, technology, engineering and mathematics (STEM) education and innovations in teaching and learning worldwide. GeoGebra’s math engine powers hundreds of educational websites worldwide in different ways from simple demonstrations to full online assessment systems.
In 2021, GeoGebra became part of the BYJU’S family with hundreds of millions of students on their learning platforms. GeoGebra's apps, classroom resources, GeoGebra Classroom & other features will continue to be available to the public for free. GeoGebra continues to operate as an independent unit within the BYJU’S group under the leadership of GeoGebra’s original founders and developers.
Rewards：
-Archimedes 2016: MNU Award in category Mathematics (Hamburg, Germany)
-Microsoft Partner of the Year Award 2015: Finalist, Public Sector: Education (Redmond, WA, USA)
-MERLOT Classics Award 2013: Multimedia Educational Resource for Learning and Online Teaching (Las Vegas, Nevada, USA)
-NTLC Award 2010: National Technology Leadership Award (Washington D.C., USA)
-Tech Award 2009: Laureat in the Education Category (San Jose, California, USA)
-BETT Award 2009: Finalist in London for British Educational Technology Award
-SourceForge.net Community Choice Awards 2008: Finalist, Best Project for Educators
-AECT Distinguished Development Award 2008: Association for Educational Communications and Technology (Orlando, USA)
-Learnie Award 2006: Austrian Educational Software Award (Vienna, Austria)
-eTwinning Award 2006: 1st prize for "Crop Circles Challenge" with GeoGebra (Linz, Austria)
-Les Trophées du Libre 2005: International Free Software Award, category Education (Soisson, France)
-Comenius 2004: German Educational Media Award (Berlin, Germany)
-Learnie Award 2005: Austrian Educational Software Award (Vienna, Austria)
-digita 2004: German Educational Software Award (Cologne, Germany)
-Learnie Award 2003: Austrian Educational Software Award (Vienna, Austria)
-EASA 2002: European Academic Software Award (Ronneby, Sweden)
```

What is the primary source of funding for this project?
```
Our funding comes primarily from therevenue of our own company, online course partnerships, and course innovation and r&d revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Geogebra's online platform has more than 1 million free classroom resources. These resources can be easily shared through the collaboration platform geogebra classroom to provide services for students and education platforms around the world.

From the course data and real-time business data, we select the data that can be disclosed for storage, including the real-time calculation videos of some cutting-edge products (such as 3D calculator), the teaching demonstration of geogebra classroom, and the course pictures used by users. In the later stage, we will decide whether to expand the storage scope and quantity according to the data storage condition and quality of the current period.

```

Where was the data in this dataset sourced from?
```
The data comes from the free course data of geogebra online platform and the real-time data generated in the business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Click here: https://drive.google.com/drive/folders/10YKoVeYABE_XHo091wjoshbTM4y1E8pO?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.This is a public dataset.
```

What is the expected retrieval frequency for this data?
```
Multiple times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store these data in the filecoin network permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to initially store in Singapore, Hong Kong and North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will send the data to the storage providers mainly by offline transmission. It is desirable to save multiple but not more than 10 copies of each file.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Based on the principle of distributed storage, we hope that the final number of storage nodes will not be less than 10. At present, we have selected a Singapore company with rich real data storage experience and stable storage support capability.
In addition, we will look for SPs on slack, and we hope that SPs can recommend themselves. Before determining the selection, we hope that the SPs can provide more information for us and we can konw their abilities better ,including the storage capacity, computing capacity, network access time and other capabilities, which can ensure that we can select the correct partners to work with.
```

How will you be distributing deals across storage providers?
```
We will distribute the deals fairly according to the service capabilities of the storage service providers.

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have had the resources/funding and don't need any more support from the community.
```

**Comment by Ggb-6** [comment]
Hello, @raghavrmadya 
I'm a staff of Geogebra. Our company have developed a dynamic mathematics software for all levels of education.And all of education data on our  platform are all free to share.
Therefore, we have a lot of data form our users,such as mathematics courseware etc,now we wanna store our user's data on Filecion network.
And almost two months ago, we have also submitted the application through issue408, but the resignation of our project Leader has put our application on stage. In this time,we have all our company information and accounts ready and apply to store our user data on Filecoin again. We sincerely hope that you will check out our application,and we will cooperate with your inspection any time.

**Comment by raghavrmadya** [comment]
Hi, please send an email to filplus-app-review@fil.org from office@geogebra.org. Thanks
