### ISSUE TITLE
[DataCap Application] - OpenStreetMap

### ISSUE THREAD

**Issue by cosmic1106** [filecoin-project/filecoin-plus-large-datasets#907]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.
## Core Information
- Organization Name: OpenStreetMap.
- Website / Social Media: https://www.openstreetmap.org/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1o4elwbh2mng3o6ej3tpw7akzj7y7xfu6c2d7vji 
_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._
## Project details
Share a brief history of your project and organization.
```
OpenStreetMap is a community of map-making enthusiasts. These enthusiasts provide and maintain data on roads, byways, cafes, railway stations and more all over the world.
```
What is the primary source of funding for this project?
```
Self-funded. 
```
What other projects/ecosystem stakeholders is this project associated with?
```
No related association.
```
## Use-case details
Describe the data being stored onto Filecoin
```
The project that creates and distributes free geographic data for the world. We started it because most maps you think of as free actually have legal or technical restrictions on their use, holding back people from using them in creative, productive, or unexpected ways.
```
Where was the data in this dataset sourced from?
```
[planet.openstreetmap.org/](https://planet.openstreetmap.org/)
```
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://planet.openstreetmap.org/pbf/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```
What is the expected retrieval frequency for this data?
```
Once a month
```
For how long do you plan to keep this dataset stored on Filecoin?
```
minimum 3 year.
```
## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```
How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Choose Offline transmission as far as possible.
Our enterprise private cloud should support normal users. If it is used for online transmission, it will occupy too many resources.
```
How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are prefer to find suitable miners in the storage provider.
We will ask the service provider that stores the data to provide the function of rapid retrieval, and will review the work after the storage is completed.
```
How will you be distributing deals across storage providers?
```
Max 1 copy's per storage provider if stored on different miners / locations.
```
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by cosmic1106** [comment]
@raghavrmadya

**Comment by Sunnyiscoming** [comment]
> How will you be distributing deals across storage providers?
> Max 1 copy's per storage provider if stored on different miners / locations.

How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #907.

**Comment by Sunnyiscoming** [comment]
Any update here?
