### ISSUE TITLE
[DataCap Application] shiatang - shiatang

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [filecoin-project/filecoin-plus-large-datasets#908]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information

- Organization Name:  ShiaTang
- Website / Social Media: http://shiatang.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1qv4a2uxsldzxq5kebmbxbgdw4idrkqcutilq7xy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

```
ShiaTang Technology (Beijing) Co., Ltd. (abbreviation: ShiaTang Technology) is a leading industrial intelligent service provider in China. Founded in 2011, ShiaTang Technology is a national high-tech enterprise, a Zhongguancun gazelle enterprise, an ISO9001 certified enterprise, and has a number of software copyrights. He has won many awards such as Beijing Innovation Fund and Beijing Cultural and Creative Industry Development Fund.

Since its establishment, ShiaTang Technology has always adhered to the core concept of "data-driven industrial innovation", guided by the self-developed industrial intelligent operation model, and relied on leading software such as cloud computing, artificial intelligence, Internet of Things, and data analysis in the 5G era. Hardware technology, as well as industrial intelligence series products independently developed by industry communication, community communication, and smart data communication, provide various types of enterprises with RPA digital employees, MarTech intelligent marketing, BI visualization, DMP data center, B2B industrial e-commerce, etc. business intelligence transformation plan and industrial digital new infrastructure overall solution.

At present, it has served hundreds of government and enterprise customers in dozens of fields at home and abroad. While insisting on independent research and development, ShiaTang Technology has established a close strategic partnership with top artificial intelligence companies at home and abroad, and is committed to empowering enterprises with the world's leading cloud computing, artificial intelligence, Internet of Things, data management, etc. in the 5G era. hardware and software technology.

ShiaTang Technology has a professional AI technical team, a digital consulting and marketing team, and a cloud service guarantee team. From the perspective of development, deployment, implementation, and technical training, it helps enterprises to achieve comprehensive digital and intelligent transformation.
```

What is the primary source of funding for this project?

```
Company funds
```

What other projects/ecosystem stakeholders is this project associated with?

```
None
```

## Use-case details

Describe the data being stored onto Filecoin

```
Digital Marketing Business Data
```

Where was the data in this dataset sourced from?

```
Company data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

```
http://shiatang.com/Detail/6163d20c7f32fa5cba8dee24
http://shiatang.com/Detail/60e52da09361606a566cc81c
http://shiatang.com/Detail/60d14db6bc45ef1408e017c3
http://shiatang.com/Detail/60cbfe1abc45ef1408e017b9
http://shiatang.com/Detail/60c1c57bbc45ef1408e0164e
https://user-images.githubusercontent.com/109669727/179981826-ac04309d-6999-4d3b-9a12-5fc09c0658d7.png
https://user-images.githubusercontent.com/109669727/179981848-3c58dab4-56a5-4cba-b16d-582e77ad62be.png
https://user-images.githubusercontent.com/109669727/179981899-00fdaaa3-362e-40fb-88ed-c3b385010380.png
https://user-images.githubusercontent.com/109669727/179981965-82366cd5-4979-49de-9080-1e7f2466bcb0.png
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

```
Yes
```

What is the expected retrieval frequency for this data?

```
3-4 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?

```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

```
Mainland China & Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?

```
offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

```
(i) We wish to store our data in a storage service provider located in Mainland China or Hong Kong.
(ii) We require storage providers to provide retrieval functions
```

How will you be distributing deals across storage providers?

```
The same data is stored in different storage service providers, and data security is ensured through redundancy. We will store data evenly across different storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes
```

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with the data you will store to prove that you have 5 PB data? Videos would be better. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by zhaoxiangjunupi** [comment]
Hi , the data we will be storing is our digital marketing business data and data security storage. We will store about 5 copies. We have not identified a provider to store data for us, we will look for it in the community, or wait for the storage provider to contact us when the application is approved.

**Comment by zhaoxiangjunupi** [comment]
What's the relationship between you and the organization?
We sent a verification email, please check our identity:
![image](https://user-images.githubusercontent.com/101166067/196418455-78bb608c-66da-44db-867b-fb9ad9f5fdfe.png)

**Comment by zhaoxiangjunupi** [comment]
> What's the relationship between you and the organization?
We sent a verification email, please check our identity:
![image](https://user-images.githubusercontent.com/101166067/196418865-33a63f0e-d45b-49bb-a749-c39ba5ceb548.png)

**Comment by zhaoxiangjunupi** [comment]
>What's the relationship between you and the organization?
We sent a verification email, please check our identity:
![Uploading image.png…]()

**Comment by qianmonetwork** [comment]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/64911932/196419315-fa9269d5-4892-45c1-ae81-62ecf3b512c3.png">

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with the data you will store, digital marketing business data and data security storage, to prove that you have 5 PB data? Videos would be better.

**Comment by liyunzhi-666** [comment]
- What is your specific data allocation plan?
- Can you share the SP id you found?

**Comment by zhaoxiangjunupi** [comment]
> * What is your specific data allocation plan?
> * Can you share the SP id you found?

@liyunzhi-666 I will be evenly assigned to multiple SPs. I have currently contacted f01851482, f01852325, f01852677 and other SPs. I will continue to look for SPs, thank you

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacean5d5mhcsx7sm55akedb76mkp4vmhb3d2zole3gunyh36tovq3ic 
#### Address 
> f1qv4a2uxsldzxq5kebmbxbgdw4idrkqcutilq7xy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 140c746b-94c5-4d43-b01a-c8f7718c05e6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacean5d5mhcsx7sm55akedb76mkp4vmhb3d2zole3gunyh36tovq3ic

**Comment by kernelogic** [comment]
@zhaoxiangjunupi what regions are these SPs that you listed? And can you specify how you meet the requirements of the community?

**Comment by zhaoxiangjunupi** [comment]
> @zhaoxiangjunupi what regions are these SPs that you listed? And can you specify how you meet the requirements of the community?

@kernelogic Hi, we have communicated with f01851482, f01966534, f01852325, f01852677, f01965334 SP and reached a cooperation. We store our data in SP distributed in Asia, such as Hong Kong, Singapore, South Korea and other places. We will strictly abide by the distribution rules of the community to ensure the compliant use of DataCap. thanks

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkwed3afrbsk42tvgdcxwlkwjk5mt7ycn57wc4htmkdfhcq7dbf2 
#### Address 
> f1qv4a2uxsldzxq5kebmbxbgdw4idrkqcutilq7xy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 140c746b-94c5-4d43-b01a-c8f7718c05e6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkwed3afrbsk42tvgdcxwlkwjk5mt7ycn57wc4htmkdfhcq7dbf2

**Comment by BDE-io** [comment]
@zhaoxiangjunupi  Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?
