### ISSUE TITLE
[DataCap Application] Define NFT Platform

### ISSUE THREAD

**Issue by Alex11801** [filecoin-project/filecoin-plus-large-datasets#91]
# Large Dataset Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  Define Platform
- Website / Social Media: http://www.define.one
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
DeFine is the social NFT platform for all creators including artists, musicians, influencers, gamers, and athletes. The platform facilitates all social interaction, engagement and communication for creators and their fanbase with digital assets like NFTs and social/fan tokens, and real assets on the blockchain. Owners of social/fan tokens will have many benefits including special access to the creators’ NFTs, merchandise, content, etc. while being part of a private community. It is also the social platform for all participants in the digital world where they can identify and interact with each other through their NFT social profiles which are based on their contribution and achievements in the digital world. Ultimately, the DeFine will serve as a social platform for creators and users to define how to engage with each other and build communities in the digital world.
```

What is the primary source of funding for this project?
```
Funding from venture investors and also the income from the platform revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We started with NFT stuff on Ethereum and now extended to multiple chains including Binance Smart Chain, TRON and Polygon. And also have plans to continue expanding to more chains. Besides, we also have various partners across the world like Abyss, 3LAU, Mymusictaste, Huobi ventures, and so on. Check the details here: https://define.one/#partners
```

## Use-case details

Describe the data being stored onto Filecoin
```
The platform is NFT-based and it’s important to transfer the data of the NFT to a decentralized storage network which can reduce the risk of data loss. Also it’s important for users to identify whether the NFT data is valid or not by the means of the Filecoin storage.

```

Where was the data in this dataset sourced from?
```
All the data comes from the users or artists on Define platform who created their assets and minted them to NFT, including artwork, paintings, music, videos.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://api.de-fine.art/api/tokens/mainnet/0x70A76282752b5D2F09f81fe86D49d80ED8B53DC7/20

https://define-art-static-prod.s3-ap-northeast-1.amazonaws.com/token/image/mainnet/ERC721/20.png

https://define-art-static-prod.s3-ap-northeast-1.amazonaws.com/token/video/mainnet/ERC721/28.mp4

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that the data is public and can be retrieved by anyone on the network.
```

What is the expected retrieval frequency for this data?
```
We may need to retrieve the data from the Filecoin network to restore the data when the NFT stored on the servers is lost, or to verify the NFTs when there is some doubt as to whether it’s genuine or fake. The expected retrieval frequency is on average half a year if you ask me.

```

For how long do you plan to keep this dataset stored on Filecoin?
```
Presumably for about 5 years, I think. But it depends case by case according to the general network requirements.

```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to make deals across Asia, North America, and more regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Some small NFT data is to be distributed online to storage providers and for some big data like a large collection of videos, we prefer offline data transfer. The detailed offline transfer process is obliged to be made then.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will refer to some reputation platforms of storage providers in the Filecoin ecosystem or get some suggestions from Filecoin officials and community. We may select several eligible storage providers to try a little bit of DataCap firstly and then have more cooperation on the storage deals.

```

How will you be distributing deals across storage providers?
```
We plan to distribute deals to 3-5 or more miners. We also need to have multiple copies across miners.

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Although we don’t have enough knowledge of the Filecoin network, and the Filecoin Plus program. Our technical teammates have been learning about those for some time and we have sufficient budget to make the storage deals on Filecoin. We may need a few supports from the community and Filecoin official team onboarding onto the first allocation of DataCap. Thanks.

```

**Comment by galen-mcandrew** [comment]
@Alex11801 We will need an active client address in order to move forward with next steps for the large dataset application process. Please provide the active client address for receiving the DataCap; this will be the address that you use to make deals with storage providers, as DataCap cannot be transferred between client addresses.

**Comment by Alex11801** [comment]
> @Alex11801 We will need an active client address in order to move forward with next steps for the large dataset application process. Please provide the active client address for receiving the DataCap; this will be the address that you use to make deals with storage providers, as DataCap cannot be transferred between client addresses.

@galen-mcandrew thanks Galen for your kind reminder. I have updated the application and provided an available active address above, which is f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi. Please check it again. If any problem, let me know.

**Comment by Alex11801** [comment]
Our team has prepared ourselves to onboard our dataset to Filecoin. So, could we move forward with next steps for the large dataset application process?

**Comment by galen-mcandrew** [comment]
@Alex11801 Are you able to use https://verify.glif.io/ to request an automated first allocation of DataCap? This will also help initialize that client address.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by AnthnoySmith** [comment]
It sounds like you want to upload private or NFT data. These data belong to each data owner rather than your platform. We can't verify them at present.

**Comment by Alex11801** [comment]
> @Alex11801 Are you able to use https://verify.glif.io/ to request an automated first allocation of DataCap? This will also help initialize that client address.

Thanks @galen-mcandrew and we have requested the automated allocation of 32 GiB DataCap successfully. Am I right in thinking we need to wait for the multisign by RKH and Notaries?

**Comment by Alex11801** [comment]
> It sounds like you want to upload private or NFT data. These data belong to each data owner rather than your platform. We can't verify them at present.

Hi @AnthnoySmith , I appreciate your attention and understand your concerns. However, please allow me to interpret the fact that NFT data on Define platform are a set of metadata describing the information of artwork, paintings, music, videos, and stuff like that which are all publicly visible data, rather than private data. Moreover, while users upload their stuff on Define platform to mint exclusive NFTs, they give consent to display the NFT data to public and proof of ownership on-chain.

Please be assured that the data we plan to store on Filecoin network is absolutely public and can be retrieved by anyone on the network as we have confirmed in the application above.

**Comment by galen-mcandrew** [comment]
@Alex11801 

> Am I right in thinking we need to wait for the multisign by RKH and Notaries?

Yes, the root key holders will approve the creation of the multisig notary, and then the first allocation request will be made for the notaries. At that time, 2 of the active notaries will need to review and sign the first allocation request.

**Comment by IreneYoung** [comment]
If the data is publicly available, then I'll support the request. If you guys get any problem making the storge deals with miners, you could come back here for help and suggestions from us or @galen-mcandrew.

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczyovdkszbsyzpeo6y7sro7p537vvxjmib4hdmxeykwulluhjqtg 
#### Address 
> f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczyovdkszbsyzpeo6y7sro7p537vvxjmib4hdmxeykwulluhjqtg

**Comment by Alex11801** [comment]
@IreneYoung Hi and thank you a lot for your support! Yes, the data is publicly available, I promise.

**Comment by flyworker** [comment]
hey do you have tools doing migration to the filecoin network? we are interested and want to support

**Comment by Alex11801** [comment]
> hey do you have tools doing migration to the filecoin network? we are interested and want to support

Hi @flyworker, thanks for your support. My team is outsourcing the tools. my contact email, alex@de-fine.art

**Comment by flyworker** [comment]
great to hear you have prepared for the migrating. We are ok to sign

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdaxjmyspvbjocgmubnxmobbkkua2jhyp5uipzn3o45flvon5iny 
#### Address 
> f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdaxjmyspvbjocgmubnxmobbkkua2jhyp5uipzn3o45flvon5iny

**Comment by Alex11801** [comment]
Thanks for supports!

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmbp5xnp3eddzey2jmkjggefj4flti734mbbzarlbe6cuyxnsneo 
#### Address 
> f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmbp5xnp3eddzey2jmkjggefj4flti734mbbzarlbe6cuyxnsneo

**Comment by Alex11801** [comment]
@Reiers @IreneYoung @flyworker @MasaakiNawatani @tinkmk @s0nik42 @aaitor @rayshitou @cryptowhizzard @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @steven004 @neogeweb3 @waynewyang @swatchliu @MRJAVAZHAO @KodaRobotDog @andrewxhill @XnMatrixSV 
Hi notaries, please help us to approve the next round of Datacap allocation. Thank you so much!

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecs2b5z7gk6yu73c4mkn6yd6dr67hf4u3fcdauazd2l24z6mgm7ls 
#### Address 
> f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecs2b5z7gk6yu73c4mkn6yd6dr67hf4u3fcdauazd2l24z6mgm7ls

**Comment by Alex11801** [comment]
@Reiers @IreneYoung @flyworker @MasaakiNawatani @tinkmk @s0nik42 @aaitor @rayshitou @cryptowhizzard @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @steven004 @neogeweb3 @waynewyang @swatchliu @MRJAVAZHAO @KodaRobotDog @andrewxhill @XnMatrixSV

Hi notaries, please help us to approve this allocation. Thank you so much!

**Comment by cryptowhizzard** [comment]
Seems that from the 100TB datacap you sent 80% to one SP. Is there a specific reason for not spreading the data across 4+ clients?

can you give us a list of SP’s where you store(d) data and some example deals to test retrieval?

**Comment by Alex11801** [comment]
@cryptowhizzard thanks for your questions.

We contacted about 10 SPs and started dealing with 6 of them. We thought these SPs would have similar speed. But due to various reasons, one of those SPs is very faster than others. We stopped dealing the fastest SP when we found the distribution issue. At the same time,  we took lots of efforts to improve the speed with other SPs. The distribution issue has been fixed already and the allocation will be normal for the next round dealing.

Here is the SP list: f01380788 , f01602479, f01606849, f01641612, f01666984, f01716466
There are some real deals that should be retrieved successfully, please feel free to check it 
bafykbzacedsj4opdjnrb7q5q6qzy7jihv5tt4juh5uoysviwzcojsvjw7tspm f01602479
bafykbzaced2zvrj5dlo6s5bzjk5obxbze7wes4lyxdjuhjkxb6t6himk3dtji f01641612
bafykbzacedsj4opdjnrb7q5q6qzy7jihv5tt4juh5uoysviwzcojsvjw7tspm
f01606849
bafykbzacedpbq4o6bhs7gyxdnhz2pfatx7m6osw4t5nv6gdiy2qqlayczhseq
f01380788

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjzvprfzqpv6rbidngfpwkuvmawybjieaqtyks53kxsowogb22vo 
#### Address 
> f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjzvprfzqpv6rbidngfpwkuvmawybjieaqtyks53kxsowogb22vo

**Comment by cryptowhizzard** [comment]
Hello @Alex11801 

That is good to hear!

Please take some time and read this page about Fil+ / LDN. -> 
https://github.com/filecoin-project/filecoin-plus-large-datasets 

And please check regularly that the data you are storing will be open for retrieval during the time of the deal like described on this page.

Have a nice day!

**Comment by Alex11801** [comment]
Thank you! @cryptowhizzard and @IreneYoung

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyidvbr2n7nmjhlrps6cywjcb6tpbatxu45lvzor3cghpqudjjo2 
#### Address 
> f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyidvbr2n7nmjhlrps6cywjcb6tpbatxu45lvzor3cghpqudjjo2

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6agtknqvhrpr5oaok7rvks7chvgt77fkewz3jlprkesjjwblts2 
#### Address 
> f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6agtknqvhrpr5oaok7rvks7chvgt77fkewz3jlprkesjjwblts2

**Comment by Akke-1** [comment]
Hi, @Alex11801  Would you like to share your rootCID with us?

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` Define Platform`
 - Client: `f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01380788](https://filfox.info/en/address/f01380788) has sealed 29.30% of total datacap.

⚠️ 50.31% of total deal sealed by [f01602479](https://filfox.info/en/address/f01602479) are duplicate data.

⚠️ 50.25% of total deal sealed by [f01606849](https://filfox.info/en/address/f01606849) are duplicate data.

⚠️ 50.13% of total deal sealed by [f01641612](https://filfox.info/en/address/f01641612) are duplicate data.

⚠️ 50.00% of total deal sealed by [f01716466](https://filfox.info/en/address/f01716466) are duplicate data.

| Provider                                                    |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01380788](https://filfox.info/en/address/f01380788)       |   Shanghai, Shanghai, CN |         110.17 TiB |     29.30% |   97.76 TiB |          11.26% |
| [f01602479](https://filfox.info/en/address/f01602479)       |    Longueuil, Quebec, CA |          74.63 TiB |     19.85% |   37.08 TiB |          50.31% |
| [f01606849](https://filfox.info/en/address/f01606849)       |     Montréal, Quebec, CA |          74.53 TiB |     19.82% |   37.08 TiB |          50.25% |
| [f01641612](https://filfox.info/en/address/f01641612)       |     Montréal, Quebec, CA |          74.34 TiB |     19.77% |   37.08 TiB |          50.13% |
| [f01666984](https://filfox.info/en/address/f01666984)`new`  |       Dorval, Quebec, CA |          42.33 TiB |     11.26% |   37.08 TiB |          12.40% |
| [f01716466](https://filfox.info/en/address/f01716466)       | Singapore, Singapore, SG |           8.00 GiB |      0.00% |    4.00 GiB |          50.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/91/1671092466884.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 29.30% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        97.77 TiB |       110.18 TiB |                   1 |          29.30% |
|        37.08 TiB |       265.83 TiB |                   4 |          70.70% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/91/1671092469490.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                   | Total Deals Affected | Unique CIDs | Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------- | -------------------: | ----------: | -------: |
| [f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6<br/>yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56f<br/>qdsq](https://filfox.info/en/address/f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq) | [Ecology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/36) |             1.72 TiB |           1 | LDN # 36 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hello, @Alex11801 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
