### ISSUE TITLE
[DataCap Application] btclass - BT Education

### ISSUE THREAD

**Issue by pzhx521** [filecoin-project/filecoin-plus-large-datasets#910]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information

- Organization Name:  btclass
- Website / Social Media: https://www.btclass.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

```
Shenzhen btclass Education Technology Co., Ltd. (BT Education for short), BT Education is an Internet live education brand. Focusing on financial research and accompanying learning, it is known for its high-efficiency examinations, high pass rates, and accompanying struggles. At present, BT Education has formed a closed-loop financial education for qualification certification, postgraduate entrance examination, practical training, and financial quotient improvement. It is a financial education platform suitable for everyone. In the past six years, the company has adhered to the original intention of education and the concept of companionship, relying on word-of-mouth communication, covering more than one million users, and accumulatively paying more than 300,000 students, becoming a dark horse in the industry.

At present, there are six major halls covering 19 courses, including
Certification Exam: Certified Public Accountant, CFA, Legal Exam, Intermediate Accounting Title, Junior Accounting Title, Sponsor Representative, Tax Accountant, ACCA, Asset Appraiser
Postgraduate entrance examination promotion: MPAcc/MBA, Master of Law, Master of Finance, postgraduate entrance examination public courses, accounting practice, audit practice
Financial and business education: financial practice courses, insurance compulsory courses, financial reading clubs

In the future, BT Education will continue to devote itself to everyone's financial education practice, increase investment in teaching, research and technology, accompany students to struggle and grow, build an online financial university with all temperatures, and become a benchmark brand in domestic financial education.
```

What is the primary source of funding for this project?

```
Company funds
```

What other projects/ecosystem stakeholders is this project associated with?

```
None
```

## Use-case details

Describe the data being stored onto Filecoin

```
Course Materials Archive Data
```

Where was the data in this dataset sourced from?

```
Company data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

```
https://www.btclass.cn/course/explore?categoryId=3&page=1&orderType=recommendedSeq
https://www.btclass.cn/course/explore?categoryId=30&page=1&orderType=recommendedSeq
https://www.btclass.cn/course/explore?categoryId=19&page=1&orderType=recommendedSeq
https://www.btclass.cn/course/explore?categoryId=206&page=1&orderType=recommendedSeq
https://www.btclass.cn/course/explore?categoryId=189&page=1&orderType=recommendedSeq
https://www.btclass.cn/course/explore?categoryId=306&page=1&orderType=recommendedSeq
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

```
Yes
```

What is the expected retrieval frequency for this data?

```
3-5 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?

```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

```
Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?

```
offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

```
The storage provider must provide retrieval function, considering the cost of data transmission, we want to choose a storage provider in mainland China or Hong Kong.
Storage providers in Singapore are also under consideration.
```

How will you be distributing deals across storage providers?

```
Store multiple copies of the same data. And store to different storage service providers to ensure data security.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes
```

**Comment by Sunnyiscoming** [comment]
Based on the data samples and website you provided, only a few of the course videos are free to view. Are you sure you will store all the paid courses on Filecoin as public data for everyone to download? Or you will just store these free courses. How much data will you store? How many copies?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by pzhx521** [comment]
@Sunnyiscoming The data samples provided are the actual data types that we are proposing to store, and we have a lot of unprocessed instructional videos. Yes, we understand that as long as it is stored in filecoin, it means that everyone can download it, we will only store videos that can be made public, but may contain paid courses, but not absolutely. We have not cooperated with any storage providers yet . We wish to wait for the approval of the application to negotiate with the storage provider. thank you!

**Comment by pzhx521** [comment]
@Sunnyiscoming The data samples provided are the actual data types that we are proposing to store, and we have a lot of unprocessed instructional videos. Yes, we understand that as long as it is stored in filecoin, it means that everyone can download it, we will only store videos that can be made public, but may contain paid courses, but not absolutely. We have not cooperated with any storage providers yet . We wish to wait for the approval of the application to negotiate with the storage provider. thank you!

**Comment by pzhx521** [comment]
@raghavrmadya @Sunnyiscoming I sent a verification email to certify the authenticity of the application. hope to be approved.

**Comment by Sunnyiscoming** [comment]
> we will only store videos that can be made public, but may contain paid courses, but not absolutely. 
Based on the data samples and website you provided, only a few of the course videos are free to view. How much data will you store? How many copies?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky

**Comment by pzhx521** [comment]
> Based on the data samples and website you provided, only a few of the course videos are free to view. How much data will you store? How many copies?

Hello, the videos on the website are just data samples. We don't just store the videos displayed on the website. The data samples provided are the actual data types we propose to store. We have many unprocessed teaching videos, and they are still important. We will store 4-5 backups, we will have about 1P of data to be stored. thank you

**Comment by newwebgroup** [comment]
Hey Client，
About KYC&KYB
1：Could you send an email to filplus-app-review@fil.org ？

The content should include the number of the LDN application.
2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

3.How large is your existing dataset? How much is the data growth per month?

**Comment by pzhx521** [comment]
1. Hi, we have sent the verification email again
2. We have established exchanges and cooperation with the following storage providers. The SPs are: f01852664, f01967473, f01852023, f01851482, f01964002. We will store the data evenly on these 5 SPs.
3. Our existing data set has about 1P of data waiting to be stored, and the monthly data growth is several Tib, which is not necessarily the case.

**Comment by pzhx521** [comment]
![20221223-175748](https://user-images.githubusercontent.com/46491088/209315009-e2140bc1-83f8-445f-b9eb-053726871dcf.png)

**Comment by pzhx521** [comment]
@newwebgroup Thank you for your question, looking forward to approval, thank you very much

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceam7mnubde2g7qdbhrkrfbqihqedv4qkmsfgf5sxsjhqgt365sbwg 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 9edaa079-6169-4025-8306-06ae014c75d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceam7mnubde2g7qdbhrkrfbqihqedv4qkmsfgf5sxsjhqgt365sbwg

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfo2t4xbnmkq5knx7afbaorav2fi36w7iwpvxoggr6l4y534vf64 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 9edaa079-6169-4025-8306-06ae014c75d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfo2t4xbnmkq5knx7afbaorav2fi36w7iwpvxoggr6l4y534vf64

**Comment by BDEio** [comment]
@pzhx521  Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by xiaoyuaiheshui** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/43629914/217452304-7c6d406d-701a-4343-90d8-2ac8fef19b42.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/43629914/217452976-77d2d3c7-8da9-4a16-b6f3-ee8330a01c80.png">
Check that all SP can support retrieval, and the distribution also conforms to the specification. I am willing to support

**Comment by herrehesse** [comment]
Not agreeing with the above. All miners are new and possible VPN use. Will confirm and report back. Suggest not to sign.

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea62l7hzukrcbhammdc4d23jdp2fcystppdnmmcvulvudlv2w6j4g 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> 7431e856-2aa3-4412-b14e-1cd844ff0b01
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea62l7hzukrcbhammdc4d23jdp2fcystppdnmmcvulvudlv2w6j4g

**Comment by xiaoyuaiheshui** [comment]
> Not agreeing with the above. All miners are new and possible VPN use. Will confirm and report back. Suggest not to sign.

@pzhx521  Can you provide some data to prove it? I will cancel the signature first

**Comment by pzhx521** [comment]
> > Not agreeing with the above. All miners are new and possible VPN use. Will confirm and report back. Suggest not to sign.
> 
> @pzhx521 Can you provide some data to prove it? I will cancel the signature first

OK  ，Thank you

**Comment by pzhx521** [comment]
> Not agreeing with the above. All miners are new and possible VPN use. Will confirm and report back. Suggest not to sign.

Hello, I don't know what caused your groundless accusation? This is disrespectful to me, I just talked to the SP and they are not using a VPN.
filecoin is a decentralized community, but everyone should be responsible for what they say, and can’t make groundless accusations that affect the judgment of others. If you judge it as a VPN based on these two points, then many LDNs are like this, don’t you think?

**Comment by herrehesse** [comment]
@pzhx521 Please tone down a bit, give us a few minutes and we will be back with results. I stated "possible VPN use". Not accusing anyone here.

**Comment by cryptowhizzard** [comment]
On request of @herrehesse 

![Schermafbeelding 2023-02-08 om 09 03 28](https://user-images.githubusercontent.com/36404435/217470385-63f74d58-4964-494d-af94-f07f6789b3d9.png)
![Schermafbeelding 2023-02-08 om 09 03 45](https://user-images.githubusercontent.com/36404435/217470386-e25d673e-ac0c-4104-9b83-b5b9557ccecb.png)
![Schermafbeelding 2023-02-08 om 09 04 03](https://user-images.githubusercontent.com/36404435/217470389-f71b7f23-2386-48b5-a7cc-0480fc223e27.png)
![Schermafbeelding 2023-02-08 om 09 04 24](https://user-images.githubusercontent.com/36404435/217470391-a5d26870-d75a-4668-a4dc-37af3ec33b82.png)

**Comment by herrehesse** [comment]
@pzhx521 It seems that two out of the five minerID's are 100% VPN's and one is potentially a VPN. The two other IP's are not yet in the fraud detection system. This could mean they are proper, or just not yet added to the system due to their new nature.

I would suggest, looking at your fierce response on my due diligence request, that you provide physical and contractual evidence of location so we can verify the locations before continuing with this request. Adding to this are the business names of the SP's you are storing the deals at. Take a look as example at: #1554. All miners are stated with business names and region/city. 

Looking forward to the updates! We are here if you have any questions.

**Comment by herrehesse** [comment]
@pzhx521 It seems that two out of the five minerID's are 100% VPN's and one is potentially a VPN. The two other IP's are not yet in the fraud detection system. This could mean they are proper, or just not yet added to the system due to their new nature.

I would suggest, looking at your fierce response on my due diligence request, that you provide physical and contractual evidence of location so we can verify the locations before continuing with this request. Adding to this are the business names of the SP's you are storing the deals at. Take a look as example at: #1554. All miners are stated with business names and region/city. 

Looking forward to the updates! We are here if you have any questions.

**Comment by pzhx521** [comment]
1: I consulted the SP again, and they confirmed that they did not use it. Please tell me what is the basis for checking the VPN?
2: I think SP is willing to prove his own problem, who does it need to prove to?

**Comment by cryptowhizzard** [comment]
Let us start with what is important. I will do retrieval checks now and update when i have downloaded some data to evaluate.

**Comment by pzhx521** [comment]
How is the inspection, thank you all, I hope the rest of the notaries can sign for me.

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/104019147/218672478-597b432d-e142-4bed-b931-12daed3555c2.png">
<img width="999" alt="image" src="https://user-images.githubusercontent.com/104019147/218672493-14fe4fd8-89d2-49ea-88c7-485e1885e33f.png">
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/104019147/218672515-7174ba11-0e95-4fce-93e7-2d286b5ce8ab.png">
Randomly extract data for retrieval success.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6mnxridrr47z5lf3dxjejya252wl6aiq3ocgjwptiieoehafa2k 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 7431e856-2aa3-4412-b14e-1cd844ff0b01
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6mnxridrr47z5lf3dxjejya252wl6aiq3ocgjwptiieoehafa2k

**Comment by herrehesse** [comment]
@NDLABS-OFFICE As stated during multiple governance calls you were asked not to sign any applications, and first do your due diligence on 50 new applications. I am surprised to see you signing this application and would kindly suggest to revert your signature.

Due diligence is not what you performed and your statement "Randomly extract data for retrieval success." is not sufficient.

For transparency tagging: @cryptowhizzard @raghavrmadya @dkkapur @galen-mcandrew @Sunnyiscoming

**Comment by NDLABS-OFFICE** [comment]
@herrehesse Hi, as I said to Hid, we are also in the meeting, we can review and sign as normal. In addition, about collecting sp information during due diligence, today we will ask questions at the notary meeting, and we can communicate with the governance team at the notary meeting.

**Comment by cryptowhizzard** [comment]
Retrieval OK + data inspection ok.

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqo4icpgv7q5wgncwhhkr53pbguvx5yhujixmn4v6m4v7hobq4mu 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 7431e856-2aa3-4412-b14e-1cd844ff0b01
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqo4icpgv7q5wgncwhhkr53pbguvx5yhujixmn4v6m4v7hobq4mu

**Comment by 1ane-1** [comment]
<img width="415" alt="bec7a386dd48b3f2b75ea9b84c5363f" src="https://user-images.githubusercontent.com/91301211/220023652-6af29992-dc6d-4df9-97c7-8780919e6ae3.png">
<img width="415" alt="226f1b37440a1b7b3cc2aa0d1e654f3" src="https://user-images.githubusercontent.com/91301211/220023666-ec3eb56d-e48f-4191-bf91-af4382ed9ce6.png">
It is ok for me.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecteq5myrnvkoejfvjtwq4a7ilwovaofz6vddxzfzovhhph5xsg6w 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 59630eba-e496-45cb-bffd-bf6b88589362
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecteq5myrnvkoejfvjtwq4a7ilwovaofz6vddxzfzovhhph5xsg6w

**Comment by kernelogic** [comment]
<img width="1015" alt="Screen Shot 2023-02-19 at 10 36 15 PM" src="https://user-images.githubusercontent.com/3711825/220031071-93e083cb-d64b-405a-852e-ab22f6b0159f.png">
retrieval OK

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceax4tlomkr3fajj2yj3wr44o3dxewr5ck3fsn4cz7j64anndsjmws 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 59630eba-e496-45cb-bffd-bf6b88589362
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceax4tlomkr3fajj2yj3wr44o3dxewr5ck3fsn4cz7j64anndsjmws

**Comment by kernelogic** [comment]
Continue the above, retrieval all complete
<img width="946" alt="image" src="https://user-images.githubusercontent.com/3711825/220186779-9ff88599-3475-40fe-82bd-09b795edf4f6.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/3711825/220187974-5a099489-9c22-45b8-b096-4e5b383f6434.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/3711825/220188001-8d01a0fb-f2cc-43d4-a128-246565755e56.png">

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacav65emydufkdktd5vbzzgi3fszempchqb5ruayiygtztpcxxte 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> bda30422-8e06-46ee-ab95-bb348617b427
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacav65emydufkdktd5vbzzgi3fszempchqb5ruayiygtztpcxxte

**Comment by cryptowhizzard** [comment]
I have been downloading some content here.

I am no expert in this field, but this content does not look like education content to me. I see some copyrighted video's about bats and some car commercial video.

http://www.datasetcreators.com/downloadedcarfiles/QmVp3FzpfUHZ3tvr1uTfagApH6f6vfrsX6Y1SHwnKVw58A

Please explain.

**Comment by pzhx521** [comment]
@cryptowhizzard 
Thank you for your attention to our project, thank you very much for your verification of our project, we have a lot of video files, and there are many categories, you can download and see more, these data are all data that we can make public, and it is not ruled out. There are some other types of data, because there are too many lists of underlying data files, but it is also the data that our project needs to save.

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
The check bot display is very good, and the data supports retrieval, which fully complies with the ND review standard

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6j2mhwfdrjrtdmliz3zw2e74u6mn4xkqy7ssomgn6elffmsap6m 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 2.07PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> b40b7340-5be3-4e03-a3d5-01bc3ecafafd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6j2mhwfdrjrtdmliz3zw2e74u6mn4xkqy7ssomgn6elffmsap6m

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
Retrieval ok,CID Checker ok
![8758f5983450d64d320a11de22ac6e4](https://user-images.githubusercontent.com/52949274/222054808-11e7c5e4-d12f-4a23-b6fd-f1fbc23910df.png)

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7m5ole6ahiwwlxwpymxn7aqgb5rzxydytm3thrscqufucegri5a 
#### Address 
> f1c7ezgelfakzzhnxywmi5mcd7iuck3yymftau2ky
#### Datacap Allocated
> 2.07PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> b40b7340-5be3-4e03-a3d5-01bc3ecafafd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7m5ole6ahiwwlxwpymxn7aqgb5rzxydytm3thrscqufucegri5a
