### ISSUE TITLE
[DataCap Application] <SemiDrive> - <MetaDriving in Future>

### ISSUE THREAD

**Issue by bensonfen2020** [filecoin-project/filecoin-plus-large-datasets#911]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: SemiDrive Technology
- Website / Social Media:https://www.semidrive.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
SemiDrive Technology has focused on providing high-performance and high-reliability automotive-grade chips and is also the first provider of “full-scenario and platform-based” chip product and technical solutions in the world. The products have served more than 260 clients and covered more than 90% of auto manufacturers in China.And the next step is to grow international. Under the background, SemiDrive has cultivated many international projects to expand in business. One of the projects is called "MetaDriving in Future" which is collaborated with more than 30+ car companies to elevate Metaverse power in China this year. With that said, we need to create and store massive data like videos, 3D modeling senarios and cars, other brand advertising.
```

What is the primary source of funding for this project?
```
company business income and funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
This projects is associated with many car brands.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need to create and store massive data like videos, 3D modeling senarios and cars, other public brand advertising.
```

Where was the data in this dataset sourced from?
```
accumulative data from the project.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1k1-ZRxRiZ-7JhYCOJGkp3A?pwd=tvh5
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
frequently
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3years at least
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
supporting online and offline data distributing depending on the need of data providers(brand).
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select the SPs with strategical partnership who are interested in Meta Power and its commercial value.
```

How will you be distributing deals across storage providers?
```
We will identify at least 10-15 SPs as our long term partners, and Ideally we will distribute deals according to their business needs
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by bensonfen2020** [comment]
Thank you, Team. Could you kindly expedite the process? Appreciate your time and question.

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? And to provide more data samples related with data you will store. How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by bensonfen2020** [comment]
Hi Sunny

Thanks for your questions.
Sorry that I replied you a bit late due to the long national holiday in
china.
Please kindly refer to my response in below contents.
1)Can you explain your data composition?
    We plan to store the things like real videos, 3D modeling videos, other
public brand advertising videos and photos, which will be used together to
build up the mini-metaverse focusing on vehicles industry. Anyway, out of
vehicles,we still need various elements to improve the mini-metaverse like
meta-driving AMA, courses videos working closely with some KOLs, brand
launch event,car industry conferences. Hopefully, we will also store some
NFTs created and produced by car brands as well.

2)And to provide more data samples related with data you will store.
You can take below links for your references. Thanks
https://www.bilibili.com/video/BV1gB4y157MN/?spm_id_from=autoNext
https://www.bilibili.com/video/BV1c24y1R7qb/?spm_id_from=333.337.search-card.all.click#/
https://www.bilibili.com/video/BV1nv4y1A7rC/?spm_id_from=333.337.search-card.all.click#/
https://www.bilibili.com/video/BV11F411v7PX/?spm_id_from=333.337.search-card.all.click#/
https://www.bilibili.com/video/BV1dr4y147rz/?spm_id_from=333.337.search-card.all.click#/



3)How many copies will you store?
Considering the safety, we plan to store at least 2 copies.

4)What's the relationship between you and the organization?
   Project Team member in the company

5)Can you provide more detailed information about other storage providers
participated in this program, such as  you can list SPs you have contacted
with at present?
We work with many car brands, and as I said, We plan to select the SPs with
strategical partnership who are interested in Meta Power and its commercial
value such as SAIC,NIO, XPeng, Chery,. We plan to run this project smoothly
in China first.

Sunnyiscoming ***@***.***> 于2022年10月4日周二 14:31写道：

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #911.

**Comment by bensonfen2020** [comment]
Hi Sunny

Kindly refer to below replies to your question and requirement:

1)Can you provide more detailed information about other storage providers
participated in this program, such as you can list SPs you have contacted
with at present?

We plan to select SPs though Github community, slack or telegram.
The main factors we care are the as followed:
1.Location(China and USA are priorities for us
2.Faster Internet connection would be preferred
2)Could you send an email to ***@***.*** with your official
domain in order to confirm your identity? Email name should includes the
issue id #911.

I have sent the verification email to the above email address with tag #911
in the title.
Kindly check it.

Sunnyiscoming ***@***.***> 于2022年10月13日周四 11:57写道：

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq

**Comment by liyunzhi-666** [comment]
- I have reviewed your application and will approve it.
- I hope you can decentralize storage storage on multiple nodes.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea52l5sy32cnh67tafove7flv7g3e2husu6xnhhrum3g7djbu3qmq 
#### Address 
> f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea52l5sy32cnh67tafove7flv7g3e2husu6xnhhrum3g7djbu3qmq

**Comment by BigD-Exchange** [comment]
@bensonfen2020 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechtd2aaru5fekpatudejc6srxdqe5yd3xdhbz5vgdttefi4paj74 
#### Address 
> f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechtd2aaru5fekpatudejc6srxdqe5yd3xdhbz5vgdttefi4paj74

**Comment by NDLABS-OFFICE** [comment]
Top provider is reasonable,I would like to support.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnfalx3fxhcfy3xxcfxa5cmn4yio2ana4y3a3coruvsbtdr7ynm6 
#### Address 
> f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 7869454f-1e09-4f84-879a-9d756014b327
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnfalx3fxhcfy3xxcfxa5cmn4yio2ana4y3a3coruvsbtdr7ynm6

**Comment by Defil2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3vhitdv3xsbdu4i7xoyxz7gk3swdwbyxuo76rveh7ilufsm6eu6 
#### Address 
> f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 7869454f-1e09-4f84-879a-9d756014b327
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3vhitdv3xsbdu4i7xoyxz7gk3swdwbyxuo76rveh7ilufsm6eu6

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `SemiDrive Technology`
 - Client: `f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01384160](https://filfox.info/en/address/f01384160) has sealed 27.95% of total datacap.

⚠️ 88.89% of total deal sealed by [f01384160](https://filfox.info/en/address/f01384160) are duplicate data.

⚠️ [f01943959](https://filfox.info/en/address/f01943959) has sealed 25.10% of total datacap.

⚠️ 87.79% of total deal sealed by [f01943959](https://filfox.info/en/address/f01943959) are duplicate data.

⚠️ [f01943959](https://filfox.info/en/address/f01943959) has unknown IP location.

⚠️ 82.79% of total deal sealed by [f01853077](https://filfox.info/en/address/f01853077) are duplicate data.

⚠️ 75.72% of total deal sealed by [f01852363](https://filfox.info/en/address/f01852363) are duplicate data.

⚠️ 80.17% of total deal sealed by [f01890456](https://filfox.info/en/address/f01890456) are duplicate data.

⚠️ 71.63% of total deal sealed by [f01854080](https://filfox.info/en/address/f01854080) are duplicate data.

⚠️ 77.48% of total deal sealed by [f01878534](https://filfox.info/en/address/f01878534) are duplicate data.

⚠️ 84.91% of total deal sealed by [f01893023](https://filfox.info/en/address/f01893023) are duplicate data.

| Provider                                              |                    Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | --------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01384160](https://filfox.info/en/address/f01384160) |     Shenzhen, Guangdong, CN |          65.84 TiB |     27.95% |    7.31 TiB |          88.89% |
| [f01943959](https://filfox.info/en/address/f01943959) |                     Unknown |          59.13 TiB |     25.10% |    7.22 TiB |          87.79% |
| [f01853077](https://filfox.info/en/address/f01853077) |    Singapore, Singapore, SG |          23.78 TiB |     10.09% |    4.09 TiB |          82.79% |
| [f01852363](https://filfox.info/en/address/f01852363) |    Singapore, Singapore, SG |          22.91 TiB |      9.72% |    5.56 TiB |          75.72% |
| [f01890456](https://filfox.info/en/address/f01890456) | Los Angeles, California, US |          18.75 TiB |      7.96% |    3.72 TiB |          80.17% |
| [f01854080](https://filfox.info/en/address/f01854080) | Los Angeles, California, US |          17.63 TiB |      7.48% |    5.00 TiB |          71.63% |
| [f01878534](https://filfox.info/en/address/f01878534) | Los Angeles, California, US |          17.63 TiB |      7.48% |    3.97 TiB |          77.48% |
| [f01893023](https://filfox.info/en/address/f01893023) | Los Angeles, California, US |           9.94 TiB |      4.22% |    1.50 TiB |          84.91% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/911/1671097931154.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        27.88 TiB |       190.06 TiB |                   1 |          80.67% |
|         4.41 TiB |        40.00 TiB |                   2 |          16.98% |
|       576.00 GiB |         5.53 TiB |                   3 |           2.35% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/911/1671097931687.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                      | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga](https://filfox.info/en/address/f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga) | [Asia Blockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/872)   |            25.34 TiB |         150 | LDN v3 multisig |
| [f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy](https://filfox.info/en/address/f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy) | [NFTSTAR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960)                           |            25.03 TiB |         183 | LDN v3 multisig |
| [f1hkvuvlwgzsgxnyet3wb4w2s3fyujvtkgeizdaey](https://filfox.info/en/address/f1hkvuvlwgzsgxnyet3wb4w2s3fyujvtkgeizdaey) | [Blue Storm Information Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323) |            13.84 TiB |         139 | LDN v3 multisig |
| [f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa](https://filfox.info/en/address/f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa) | [iPolloverse SG PTE\. LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767)          |             7.50 TiB |          45 | LDN v3 multisig |
| [f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi](https://filfox.info/en/address/f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi) | [We Doctor](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/962)                         |             5.25 TiB |          39 | LDN v3 multisig |
| [f1k7y7jd3ly42cg5ysty2ngc5smxmaery5mglbynq](https://filfox.info/en/address/f1k7y7jd3ly42cg5ysty2ngc5smxmaery5mglbynq) | `MikaeLa `                                                                                                       |             3.06 TiB |          13 | LDN v3 multisig |
| [f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri](https://filfox.info/en/address/f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri) | [Blockchain Media](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1048)                 |             3.06 TiB |          21 | LDN v3 multisig |
| [f1qpkmibcsitxtxwg6ayghxwkssoxs4bfyzwzslza](https://filfox.info/en/address/f1qpkmibcsitxtxwg6ayghxwkssoxs4bfyzwzslza) | [GAMEWAY PTE\. LTD\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/158)               |           640.00 GiB |           2 |       LDN # 158 |
| [f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq](https://filfox.info/en/address/f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq) | `Pow Power`                                                                                                      |           416.00 GiB |           2 | LDN v3 multisig |
| [f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q](https://filfox.info/en/address/f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q) | [TIMAGE](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/302)                            |           256.00 GiB |           1 | LDN v3 multisig |
| [f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq](https://filfox.info/en/address/f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq) | [Ipollo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/168)                            |           256.00 GiB |           1 |       LDN # 168 |
| [f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq](https://filfox.info/en/address/f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq) | [Proya](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/295)                             |            32.00 GiB |           1 | LDN v3 multisig |
| [f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq](https://filfox.info/en/address/f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq) | `rctAI`                                                                                                          |            32.00 GiB |           1 | LDN v3 multisig |
| [f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi](https://filfox.info/en/address/f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi) | ``                                                                                                               |            32.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
