### ISSUE TITLE
[DataCap Application] <Full Truck Alliance> - <Intelligent Supply Chain>

### ISSUE THREAD

**Issue by liushiquan1234** [filecoin-project/filecoin-plus-large-datasets#914]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Full Truck Alliance
- Website / Social Media: https://www.fulltruckalliance.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1gw2bubxkhv4jid3eyshqjjamlelwhcw3lb6xjma

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
As a technology-oriented company, Full Truck Alliance provides its drivers and consignors with wholehearted assistance to improve delivering efficiency and reduce logistics cost. Meanwhile, Full Truck Alliance is dedicated in building the world largest intelligent logistics ecological platform. By deploying and implementing a business ecosystem with core businesses such as platforms, transactions, and some other international businesses, Full Truck Alliance is gradually transforming from a platform enterprise to an intelligent enterprise, then to an ecosystem-based enterprise. In order to meet the market demand and the needs of the company's business development, the company's business scope has expanded from a single road transportation service to a comprehensive logistics services.To focus on intelligence and data-oriented business, we have many projects with massive data to store. One of them is called "Intelligent Supply Chain" , a self-developed project coverying 300+ cities in Greater China to map the best routes for its drivers and consignors with helpful information.
```

What is the primary source of funding for this project?
```
company business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
This projects is associated with some of our enterprises customers from different industries, have a strategic partnership with them.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we store onto Filecoin is routes map, monitor video in real time for safety, campaign videos , business needs from drivers and consignors, advertising videos/pictures and so on.
```

Where was the data in this dataset sourced from?
```
ccumulative data from the project.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
for some advertising videos, you can check our Douyin account:huochebang(1M+ followers), for other contents, you can refer to http://www.ymm56.com/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Daily
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
supporting online and offline data distributing depending on the need of data providers```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select the SPs with strategical partnership or contributing to this project in their way.
```

How will you be distributing deals across storage providers?
```
We will identify at least 5-10 SPs as our long term partners, and we will distribute deals according to their business needs
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by liushiquan1234** [comment]
Hi Team. Is everything going well with my application? Appreciate your time and review. We look forward to further communication.

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with each type of data you will store, routes map, monitor video in real time for safety, campaign videos , business needs from drivers and consignors, advertising videos/pictures? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by liushiquan1234** [comment]
Dear Sunny


Sorry for the late reply since we have just had Chinese national holiday.
Appreciate your further questions, and I would like to share my answers as below:


1)Can you provide more data samples related with each type of data you will store, routes map, monitor video in real time for safety, campaign videos , business needs from drivers and consignors, advertising videos/pictures?&nbsp;
&nbsp; &nbsp;Some historic data for your reference:


Stories of Drivers and consignors:
https://www.douyin.com/user/MS4wLjABAAAAq8O-0c9_Cg7vkh0dwq4zWJFj4ww54P_oU010DEtvyuQ?modal_id=7147312034739260713


https://www.douyin.com/search/%E6%BB%A1%E5%B8%AE%E7%A7%91%E6%8A%80?modal_id=6773494385561619719&amp;publish_time=0&amp;sort_type=0&amp;source=switch_tab&amp;type=video


https://www.douyin.com/user/MS4wLjABAAAAq8O-0c9_Cg7vkh0dwq4zWJFj4ww54P_oU010DEtvyuQ?modal_id=6862987863856893192


https://www.douyin.com/user/MS4wLjABAAAAq8O-0c9_Cg7vkh0dwq4zWJFj4ww54P_oU010DEtvyuQ?modal_id=7128309697223970061


https://www.douyin.com/user/MS4wLjABAAAAq8O-0c9_Cg7vkh0dwq4zWJFj4ww54P_oU010DEtvyuQ
https://haokan.baidu.com/v?pd=wisenatural&amp;vid=7900517179564546967#/


Route Planning Data:
www.GIS9.com




Some knowledge popularization/advertising videos:
https://www.douyin.com/user/MS4wLjABAAAALSCKmGFDcMcjJc5KXXo970OfhJBzouqkzTqkx8rNgmg
https://www.163.com/v/video/VQBQ6PD4L.html#/
http://haokan.hao123.com/v?vid=13716004174811378997&amp;tab=recommend#/


&nbsp;
2)How many copies will you store?
Two


3) What's the relationship between you and the organization?
Company staff


4) Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
&nbsp; SPs are diverse. We have contacted map planning company, MCN (run KOLs), truck operation company.&nbsp;


&nbsp;Thanks, look forward to your reply.



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 4, 2022 14:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [filecoin-project/filecoin-plus-large-datasets] [DataCapApplication] <Full Truck Alliance&gt; - <Intelligent Supply Chain&gt; (Issue #914)




 
Can you provide more data samples related with each type of data you will store, routes map, monitor video in real time for safety, campaign videos , business needs from drivers and consignors, advertising videos/pictures? How many copies will you store?
 What's the relationship between you and the organization?
 Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #914.

**Comment by simonkim0515** [comment]
Closing due to no response
