### ISSUE TITLE
[DataCap Application] kingdata - kingdata

### ISSUE THREAD

**Issue by zhang14725804** [filecoin-project/filecoin-plus-large-datasets#915]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: kingdata
- Website / Social Media: https://kingdata.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
As an industry-leading blockchain data service platform, KingData processes massive projects and information every day, analyzes and statistics on-chain data, and provides powerful tools for insight into industry development trends and potential investment opportunities. The platform integrates investment and wealth management, asset kanban, opportunity analysis, data analysis, indicator monitoring and other functions to provide users with real-time and accurate information services.
KingData platform provides:
(i) DAPP analysis
(ii) NFT analysis aggregation platform
(iv) IDO aggregation platform
(v) Airdrops
(vi) DEFI Farm APY/Borrow APY/ Token APY/HECO Node APY
(vii) Project Analysis/ Whale Addresses/Whale Transaction
```

What is the primary source of funding for this project?
```
Company funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Analytics data from multiple blockchains
```

Where was the data in this dataset sourced from?
```
Platform data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
```
[data1.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9089418/data1.csv)
[data2.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9089419/data2.csv)
[data3.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9089420/data3.csv)
[data4.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9089421/data4.csv)
[data5.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9089423/data5.csv)
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
1-2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Day
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainland China or Hong Kong or Singapore or United States
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to store the data in multiple SPs to improve the reliable storage of the data, and we will periodically check to ensure that the data can always be retrieved.
```

How will you be distributing deals across storage providers?
```
Balanced storage to multiple SPs
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by raghavrmadya** [comment]
<img width="851" alt="Screen Shot 2022-09-07 at 2 44 43 PM" src="https://user-images.githubusercontent.com/91579519/188988514-50a0481d-5ca7-4773-8c23-42b83a193e0d.png">
What does this mean? Please be specific

**Comment by zhang14725804** [comment]
> <img alt="Screen Shot 2022-09-07 at 2 44 43 PM" width="851" src="https://user-images.githubusercontent.com/91579519/188988514-50a0481d-5ca7-4773-8c23-42b83a193e0d.png">
> 
> What does this mean? Please be specific

Mainland China or Hong Kong or Singapore or United States

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? And to provide more data samples related with data you will store to prove that you have 5 PB already. How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by zhang14725804** [comment]
Hi @Sunnyiscoming , As an industry-leading blockchain data service platform, KingData's data composition comprises of the data generated daily from processing large web3 projects, on-chain blockchain data and also data analysis of them . We plan to store 4-5 copies of the data to ensure that it can be safely stored.
We have not contacted any storage providers at this time.

**Comment by zhang14725804** [comment]
I am applying on behalf of an organization and I have sent a verification email：
<img width="821" alt="image" src="https://user-images.githubusercontent.com/15354910/196329795-56377602-74c8-4d3d-99a0-631e40be4879.png">

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with data you will store to prove that you have 5 PB already?

**Comment by zhang14725804** [comment]
@Sunnyiscoming Hello, our platform generates a lot of data every day. These data are valuable and can be further analyzed to generate new value. I have added some sample data: https://drive.google.com/drive/folders /1Lmpb_sZ9dUZta4EUfAqVBdIYopSyxF2C?usp=sharing. Thank you, hope to make progress

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq

**Comment by NDLABS-OFFICE** [comment]
First Signature Support.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbegebbxfnnzfu5rrrkrzeqlbhhvyhh2bomz5ehwmo3qeka2tf7u 
#### Address 
> f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 509358cc-f7e0-47f8-8419-2064ead05b08
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbegebbxfnnzfu5rrrkrzeqlbhhvyhh2bomz5ehwmo3qeka2tf7u

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkuqdkastj5asxjkvmxbvdztu3r4uga6lkvzmobzj47wuuk5lylm 
#### Address 
> f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 509358cc-f7e0-47f8-8419-2064ead05b08
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkuqdkastj5asxjkvmxbvdztu3r4uga6lkvzmobzj47wuuk5lylm

**Comment by Tom-OriginStorage** [comment]
This is the first time to sign. I will follow up on it later. If there are any problems, I will contact the owner to solve them

**Comment by BigD-Exchange** [comment]
@zhang14725804 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedztj6ife6isouo2xus54ufqkp5v4ayf34snqpn7nyapevpoor5hc 
#### Address 
> f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> d4906a87-789b-45b0-8455-1aa191d7fa25
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedztj6ife6isouo2xus54ufqkp5v4ayf34snqpn7nyapevpoor5hc

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced77pyhjkbfxxhqykkiyvd7op563ak224o4noordhdc4ey2ogswiq 
#### Address 
> f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> d4906a87-789b-45b0-8455-1aa191d7fa25
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced77pyhjkbfxxhqykkiyvd7op563ak224o4noordhdc4ey2ogswiq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzdlavsf73bz4yel6eteydyclrmkcq6wyzjxeoqjdyavvgm2edlg 
#### Address 
> f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> cc28af7a-cbb8-4db3-8de2-ef5f07f391e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzdlavsf73bz4yel6eteydyclrmkcq6wyzjxeoqjdyavvgm2edlg

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafzt36bnucwluik7oa7lnx7xnj6urrlaap3qtp7ghukowctcynkc 
#### Address 
> f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> cc28af7a-cbb8-4db3-8de2-ef5f07f391e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafzt36bnucwluik7oa7lnx7xnj6urrlaap3qtp7ghukowctcynkc

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `kingdata`
 - Client: `f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |         192.59 TiB |     20.77% |  192.53 TiB |           0.03% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |         188.31 TiB |     20.31% |  188.25 TiB |           0.03% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |         184.75 TiB |     19.92% |  184.69 TiB |           0.03% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |         184.50 TiB |     19.90% |  184.44 TiB |           0.03% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |         177.19 TiB |     19.11% |  177.13 TiB |           0.04% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/915/1671097944524.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 25.63% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        30.22 TiB |        30.22 TiB |                   1 |           3.26% |
|        47.78 TiB |        95.56 TiB |                   2 |          10.30% |
|        37.31 TiB |       111.94 TiB |                   3 |          12.07% |
|        20.06 TiB |        80.25 TiB |                   4 |           8.65% |
|       121.81 TiB |       609.38 TiB |                   5 |          65.71% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/915/1671097945026.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
Cid Checker's results look good.
The SP locations are relatively distributed, and there is no Cid sharing

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedx3ievfernam43y5yhjtmv4do3pr5jw2d7dks42547qphgfsfn7u 
#### Address 
> f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 194af468-66a6-40e1-b063-ce90bb6e4b2c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedx3ievfernam43y5yhjtmv4do3pr5jw2d7dks42547qphgfsfn7u

**Comment by herrehesse** [comment]
@zhang14725804 Multiple approved applications by the notary are potentially fraudulent, hence increased screening on applications signed by this notary.

In my view, storing "Analytics data from multiple blockchains" adds some value to the network. Useful data.

Also, the CID report looks clean.

**My question to the applicant is:**

You requested 5PiB of datacap for storing analytics data. Just to put this in perspective, the entirety of wikipedia with 55 million pages of information is 22GiB compressed.

Can you explain to me why you need the volume and hereby provide evidence of file size?

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabrmkntvvobrjkwdesvua3zzmt2vqc457jyzzexifnmnghibs6bg 
#### Address 
> f1nmccvqvv6bsxkqoa6s5nizif2t5g34kqxcyeyhq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 194af468-66a6-40e1-b063-ce90bb6e4b2c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabrmkntvvobrjkwdesvua3zzmt2vqc457jyzzexifnmnghibs6bg

**Comment by Tom-OriginStorage** [comment]
Cid Checker's results look good.
The SP locations are relatively distributed, and there is no Cid sharing

**Comment by herrehesse** [comment]
@Tom-OriginStorage I would strongly recommend you not to sign looking at the above questions. First due diligence, then approve of next batch. This is NOT proper notary behavior.

Also, we are checking the distribution, miner ID's are all the same so this is most likely the same entity.

@zhang14725804 can you explain to my why these 5 minerID's are so similar? Are they the same company? Are they controlled by the same business?

**Comment by cryptowhizzard** [comment]
Hello,

I noticed all these providers are not available for retrieval.

Provider | Deals | Ping
-- | -- | --
f01852325 | 8464 | context canceled
f01852664 | 8436 | context canceled
f01851482 | 8420 | context canceled
f01852677 | 8404 | context canceled
f01852023 | 8394 | context canceled

For example Deal ID 21036388 results in:

retrieve: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmTipAaCt3RLQmgpT57XMjvkiiJB2145gVtfvRp2NhgsE2: getting pieces containing block QmTipAaCt3RLQmgpT57XMjvkiiJB2145gVtfvRp2NhgsE2: failed to lookup index for mh 12204ff7e79c4d52a3e818a4049a58161787a1ff1a3e720a570aee9bffcd6369de73, err: datastore: key not found

Deal ID 20973407: 
retrieve: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmaTZnESKn24McxBvUoWBEscihKdJ6QYN2aNhP2zzmoCPp: getting pieces containing block QmaTZnESKn24McxBvUoWBEscihKdJ6QYN2aNhP2zzmoCPp: failed to lookup index for mh 1220b411bc567a97137d1658f6f77cb7661ffaff43027ee1fb670dd9af51265e5907, err: datastore: key not found

DealID 20887352:
retrieve: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid Qma9GkMQP4gKJXP14cnkSFzuVLEjcjFvhqkunzX1JXDxFh: getting pieces containing block Qma9GkMQP4gKJXP14cnkSFzuVLEjcjFvhqkunzX1JXDxFh: failed to lookup index for mh 1220af6205c3fbc9e4d62fdd9691ff381777f69f8284bad33f151f36c826f8dff570, err: datastore: key not found

To be eligible for Fil+ datacap the data needs to be retrievable and the SP's need to be available. 
Please have a talk with your SP's and get this sorted out. You might want to have them switch to boost here to get the deals stored correctly and have retrieval proper.

**Comment by cryptowhizzard** [comment]
@Tom-OriginStorage 

We have a sign here from you without you checking that the data is retrievable. @newwebgroup the same. That is unfortunate. Please have a talk with this client to have the data retrievable before he continues with this LDN and starts on further using the datacap. This needs to be sorted.

**Comment by Tom-OriginStorage** [comment]
> @Tom-OriginStorage I would strongly recommend you not to sign looking at the above questions. First due diligence, then approve of next batch. This is NOT proper notary behavior.
> 
> Also, we are checking the distribution, miner ID's are all the same so this is most likely the same entity.
> 
> @zhang14725804 can you explain to my why these 5 minerID's are so similar? Are they the same company? Are they controlled by the same business?

@herrehesse First, this LDN has completed KYC. Second, its packaging is also in compliance with the rules. The robot inspection results are also correct. I have done what I should do as a notary. I have a question who are you?

**Comment by herrehesse** [comment]
@Tom-OriginStorage I have messaged you with questions in multiple applications. If you keep blindly signing and do not respond I will be forced to address this behaviour with a dispute.

Please answer my and @cryptowhizzard's questions.

**Comment by Tom-OriginStorage** [comment]
@herrehesse
The packaging of this LDN completely conforms to the official rules.
For the retrieval problem, I have been contacting them for inspection,
Recently, I saw you leave a message under a lot of normal LDN asking questions, and some robots did not see you pay attention to those that did not comply with the rules. What is your purpose?
And why can your account apply for so many LDN data? Does it really meet the specifications?
Why are some applications closed?
Why can your LDN be approved in such a short time? Far below the average time of LDN application

I have a few questions？

who are you？
what organization do you belong to？
who do you work for and why should I answer your question?

**Comment by Tom-OriginStorage** [comment]
My information is public and can be found in the notary community. You don't tell me who you are? How can I answer your question?

**Comment by Tom-OriginStorage** [comment]
> @Tom-OriginStorage I have messaged you with questions in multiple applications. If you keep blindly signing and do not respond I will be forced to address this behaviour with a dispute.
> 
> Please answer my and @cryptowhizzard's questions.

Are you threatening me?

**Comment by Tom-OriginStorage** [comment]
Shouldn't I believe the robot's detection results？

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@zhang14725804 

It seems that none of this data is retrievable. This is against Fil+ LDN rules.

Please have this situation corrected before we can grant more datacap.

[f01972309.csv.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10421168/f01972309.csv.log)

**Comment by cryptowhizzard** [comment]
Any news here? Are you ready to support retrieval @zhang14725804

**Comment by Sunnyiscoming** [comment]
Hello @zhang14725804 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
