### ISSUE TITLE
[DataCap Application] IINDA - medicine

### ISSUE THREAD

**Issue by JackRipper1888** [filecoin-project/filecoin-plus-large-datasets#916]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information

- Organization Name:  IINDA
- Website / Social Media: https://www.iinda.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

```
IINDA (Chengdu ) Technology Co., Ltd., established in May 2015, is an innovative technology company dedicated to the field of Internet medical imaging. Industry-leading technology solutions. At the beginning of the business, with the entrepreneurial mission of "bringing high-quality imaging diagnosis to patients in remote third- and fourth-tier areas", it has continued to serve more than 600 medical institutions and customers through high-quality technology research and development and service capabilities.

The company independently develops and provides a series of high-quality medical imaging software products and services such as imaging cloud integrated machine, hospital-level PACS system, electronic film, ipacs imaging cloud platform, and IMDT multidisciplinary consultation platform, and has passed the double certification of Sichuan Software Industry Association. Soft (software product and software enterprise) certification.

With the rapid development of the medical industry, Yingda Technology has expanded from providing medical imaging cloud platform, electronic film, cloud archiving, in-hospital PACS and other products to web-based products.
3.0 in the field of blockchain medical infrastructure research.

The company's main products:
(i) Electronic film solution: Electronic film is also called cloud film, that is, the original image of medical images stored in cloud space or server disk space, non-JPG, JPEG format, high-precision rendering of DICOM original complete full-pixel image, retaining all sequences
(ii) Medical Consortium Internet Image Cloud Comprehensive Solution: A comprehensive medical imaging solution for various forms of medical consortia, based on HTML5 full-pixel rendering technology to ensure diagnostic-level accuracy on any platform, based on B/S architecture, It seamlessly integrates image resources with cloud HIS and Internet systems to maximize sharing.
(iv) Hospital-level PACS comprehensive solution: a new hospital-level comprehensive medical imaging solution with Internet attributes, which allows flexible access to images in hospitals and clinical departments, and integrates hospital resources through the medical imaging Internet mobile office solution.
```

What is the primary source of funding for this project?

```
Company funds
```

What other projects/ecosystem stakeholders is this project associated with?

```
None
```

## Use-case details

Describe the data being stored onto Filecoin

```
Medical imaging data and archived data without private information
```

Where was the data in this dataset sourced from?

```
Company data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

```
https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9149500/iinda.zip
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

```
Yes, the data we store is public data without private information.
```

What is the expected retrieval frequency for this data?

```
1 - 2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?

```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

```
Hongkong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?

```
offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

```
We would like to choose a storage service provider in Hong Kong. We require data to be retrievable, which is a requirement of our choice of storage provider.
```

How will you be distributing deals across storage providers?

```
For data security, we will store multiple copies of data to different storage service providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes
```

**Comment by raghavrmadya** [comment]
@JackRipper1888 , what is your relationship with the client?

**Comment by JackRipper1888** [comment]
> @JackRipper1888 , what is your relationship with the client?

If you need it, I can use the official email address of the company domain name to send the certification information

**Comment by JackRipper1888** [comment]
Thanks for your question. I am applying on behalf of organization and we would like to join filecoin to reduce our costs. If you need, I can use the official mailbox of the company domain name to send the certification information

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? And to provide more data samples related with data you will store to prove that you have 5 PB already. How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #916.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by JackRipper1888** [comment]
Hello, the data consists of: desensitized medical image data and desensitized archival data. We store data to multiple storage providers and store 4-5 backups to ensure reliable data storage. Also, we are preparing new sample data, which will be published later. We sent a verification email:
![5091666009566_ pic](https://user-images.githubusercontent.com/35095410/196177159-9aedaecc-45fe-4d4f-b1c0-deb8d55f1e74.jpg)

**Comment by JackRipper1888** [comment]
@Sunnyiscoming @raghavrmadya  We have added sample data: https://drive.google.com/drive/folders/1P6sPZOPMh3EiKzpEDExqraR04Cv-8Q0W. Hope to make progress, thanks

**Comment by JackRipper1888** [comment]
@Sunnyiscoming @raghavrmadya  We have added sample data: https://drive.google.com/drive/folders/1P6sPZOPMh3EiKzpEDExqraR04Cv-8Q0W. Hope to make progress, thanks

**Comment by JackRipper1888** [comment]
@raghavrmadya @Sunnyiscoming Hi, is there an update? looking forward to being approved, thanks

**Comment by Sunnyiscoming** [comment]
@JackRipper1888 Sorry for delaying. Email received.
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i

**Comment by kernelogic** [comment]
@JackRipper1888 what regions are these SPs that you listed? And can you specify how you meet the requirements of the community?

**Comment by JackRipper1888** [comment]
@kernelogic Hello, we plan to store data in Hong Kong/Singapore/Korea, etc., we have contacted the following SP: f01852023, f01964002, f01852664, f01967473, f01851482, we will cooperate further. For our data security and according to community rules, we evenly distribute our data to multiple SPs. thanks

**Comment by Tom-OriginStorage** [comment]
it looks good i will sign him

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacededesv6uyrgsstptbtomoj6jffcoz35f6a52a4yrga2nt5v7uzli 
#### Address 
> f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> e612bb9f-86df-49a6-98d2-04a4ecef1e87
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacededesv6uyrgsstptbtomoj6jffcoz35f6a52a4yrga2nt5v7uzli

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by JackRipper1888** [comment]
We are preparing data, and communicating with SPs, I think it will start soon, thank you for your attention @Sunnyiscoming

**Comment by 1ane-1** [comment]
CID report looks good,  i will suport it

**Comment by cryptowhizzard** [comment]
> CID report looks good, i will suport it

Retrieval?

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckgys7qumkjiwl4mevze5ysqu6zyeenbok6ogujkn7tj3cikez3o 
#### Address 
> f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> e797fcac-eebd-4507-b203-4650e7641790
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckgys7qumkjiwl4mevze5ysqu6zyeenbok6ogujkn7tj3cikez3o

**Comment by cryptowhizzard** [comment]
@1ane-1 

Did you test retrieval?

**Comment by cryptowhizzard** [comment]
@1ane-1 

I tested retrieval for you. This SP's don't support it.



>>

Feb  7 07:35:04 proposals dealscanner-f01980914-f01970716: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675554614710751788|0]
Feb  7 07:35:04 proposals dealscanner-f01980914-f01970716: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 3ms [1675554614710751788|0]
Feb  7 07:35:04 proposals dealscanner-f01980914-f01128320: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675554614710751789|0]
Feb  7 07:35:04 proposals dealscanner-f01980914-f01128320: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 3ms [1675554614710751789|0]
Feb  7 07:35:05 proposals dealscanner-f01980914-f01970716: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 632ms [1675554614710751788|0]
Feb  7 07:35:05 proposals dealscanner-f01980914-f01970716: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 633ms [1675554614710751788|0]
Feb  7 07:35:07 proposals dealscanner-f01980914-f01970716: Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 3.142s [1675554614710751788|0]
Feb  7 07:35:07 proposals dealscanner-f01980914-f01970716: Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 3.143s [1675554614710751788|0]

**Comment by 1ane-1** [comment]
@cryptowhizzard I cancel the signature forfurther confirmation.

**Comment by JackRipper1888** [comment]
I have no problem using lotus to retrieve data. What tool or CID are you using
![img_v2_1d1dcc01-3c1d-47df-b128-0baeea3707eh_MIDDLE_WEBP](https://user-images.githubusercontent.com/35095410/217184196-4ad61ce6-7d60-44ae-8f77-3c32329e7069.jpg)

**Comment by cryptowhizzard** [comment]
@JackRipper1888 

I managed to download some files , however , all the .tif files i managed to download in the data are broken.
Can you explain why i can't open the TIF files?

**Comment by cryptowhizzard** [comment]
Ahh ... i managed to view one. Please let me know how this relates to medical data.

![Schermafbeelding 2023-02-07 om 08 56 50](https://user-images.githubusercontent.com/36404435/217185425-5532c169-488c-4443-9588-9f9c695f64f1.png)

**Comment by JackRipper1888** [comment]
Your cid data is wrong. It doesn't belong to our project

**Comment by cryptowhizzard** [comment]
I got this from the FIL+ website?

https://filplus.d.interplanetary.one/clients

Will recheck later today.

**Comment by cryptowhizzard** [comment]
Cleaned up my comments. Indeed there was a bug in the retrieval script. Sorry for that. 
I fixed it and am re-testing as we speak.

**Comment by JackRipper1888** [comment]
Thanks for checking, are you a notary? Can you sign it for me?

**Comment by cryptowhizzard** [comment]
> Thanks for checking, are you a notary? Can you sign it for me?

Yes i am a notary. When i finished checking i will make my decision.

**Comment by JackRipper1888** [comment]
I have contacted this SP to make adjustments and can try again

**Comment by cryptowhizzard** [comment]
I did so, however the retrieval is painfully slow. It will take 72 hours to download the carfile. When i have it i will evaluate it.

**Comment by JackRipper1888** [comment]
@cryptowhizzard

**Comment by NDLABS-OFFICE** [comment]
Received dm from this client. 
Has done review, SPs are normal. 
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/104019147/218666018-f432808e-ee9b-4fee-8f6d-c6fec1e36b33.png">
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/104019147/218666049-1eb69c98-1359-4f7a-92e1-e89e22ee852c.png">

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahxm6yh7k3plvox7yquio7urz7tkfehp7eui2esrirrrr6pccody 
#### Address 
> f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> e797fcac-eebd-4507-b203-4650e7641790
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahxm6yh7k3plvox7yquio7urz7tkfehp7eui2esrirrrr6pccody

**Comment by herrehesse** [comment]
@NDLABS-OFFICE As stated during multiple governance calls you were asked not to sign any applications, and first do your due diligence on 50 new applications. I am surprised to see you signing this application and would kindly suggest to revert your signature.

Due diligence is not what you performed and your statement "Has done review, SPs are normal." is not sufficient.

For transparency tagging: @cryptowhizzard @raghavrmadya @dkkapur @galen-mcandrew @Sunnyiscoming

**Comment by NDLABS-OFFICE** [comment]
@herrehesse Hi, as I said to Hid, we are also in the meeting, we can review and sign as normal. In addition, about collecting sp information during due diligence, today we will ask questions at the notary meeting, and we can communicate with the governance team at the notary meeting.

**Comment by herrehesse** [comment]
This is not correct. You were asked not to sign and do due diligence on 50 applications.

This is a huge violation and should not be taken lightly.

**Comment by NDLABS-OFFICE** [comment]
@herrehesse There may be some misunderstanding here, I hope the results will be discussed at the notary meeting today

**Comment by herrehesse** [comment]
@NDLABS-OFFICE No misunderstanding, we had this talk privately and you know that @raghavrmadya asked to hold off with signing any applications and do your due diligence on 50 applications.

I suggest to remove your signature from this application.

**Comment by NDLABS-OFFICE** [comment]
@herrehesse I have repeatedly confirmed that we can review and sign normally. RG proposed in slack that we should review the LDN more, but it did not explicitly say that we cannot sign. In addition, what doubts do you have about the current LDN?

**Comment by herrehesse** [comment]
This application is so clearly abusive I can't even......

They state "Hongkong" as their only storage region, and hence we can see global distribution. 
<img width="1621" alt="Screenshot 2023-02-14 at 10 03 56" src="https://user-images.githubusercontent.com/70132857/218688760-ec56cbbf-0f8a-4d37-9d6b-9e469e37790d.png">
All of which is achieved by VPN.

@cryptowhizzard stated to be evaluating the data, and you quickly sign before he could get back with results.

Do I need to continue?

**Comment by NDLABS-OFFICE** [comment]
@herrehesse As I mentioned just now, each notary will have its own review method. The governance team also said that notaries need to conduct review according to their own original rules. You can have your own review method, and so can we. In addition, this issue can be discussed in depth and concluded tonight. You can also ask this question at the meeting. Thanks.

**Comment by cryptowhizzard** [comment]
Retrieval + data verified.

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechzzvi2lq4xgtplqtyn5jjuc5sygwetrbnxihhk3grhcpepmtpfq 
#### Address 
> f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> e797fcac-eebd-4507-b203-4650e7641790
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechzzvi2lq4xgtplqtyn5jjuc5sygwetrbnxihhk3grhcpepmtpfq

**Comment by xiaoyuaiheshui** [comment]
As stated above, I did some additional checks and it all looked good, I'm happy to sign this round. Looking forward to the next milestone

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5e5zcremmxlgpadtrwtjrtpv52jqrrpynkp5txxn4akhftggzhk 
#### Address 
> f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> b31df3da-1e5a-46c0-901f-3f3a1060d780
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5e5zcremmxlgpadtrwtjrtpv52jqrrpynkp5txxn4akhftggzhk

**Comment by cryptowhizzard** [comment]
I verified and downloaded the data. All looks ok to me.

**Comment by psh0691** [comment]
https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/916/1676649880958.md

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapbgil3hxzp7yfozyu72mymh2drohfmtbagk2xxvuknbwyw77lb4 
#### Address 
> f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 3f1e4b4a-3452-4056-8344-73a301a52de6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapbgil3hxzp7yfozyu72mymh2drohfmtbagk2xxvuknbwyw77lb4

**Comment by flyworker** [comment]
lotus client retrieve --provider f02006841 --pieceCid baga6ea4seaqeptlp75vyekxblsiegjkahrrb76axyoq26q3xyk33kmnb6kbmiei Qmdbj8fHmUGSDJa8tXaAYL2Qq9gkdicdT8rwJSvrSygJTk 20230221-225554.file >> log/23742329.log
Recv 0 B, Paid 0 FIL, Open (New), 0s
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 26ms
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 440ms
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 440ms
Recv 71 B, Paid 0 FIL, BlocksReceived (Ongoing), 480ms
Recv 1015 B, Paid 0 FIL, BlocksReceived (Ongoing), 505ms
Recv 49 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 739ms
Recv 1.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3.323s
Recv 2.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 5.777s
Recv 3.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 8.916s
Recv 4.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 13.397s
Recv 5.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 20.659s
Recv 6.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 28.598s
Recv 7.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 32.771s

**Comment by MatrixStorage** [comment]
The project looks good and I'm willing to provide signatures if needed.

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvedoeri6gq4pbdqkferojgxjgzzeh524k2iomkof3vxrrude7rw 
#### Address 
> f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i
#### Datacap Allocated
> 2.07PiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> dddcd2ad-acec-4c3a-8bce-695a9582529d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvedoeri6gq4pbdqkferojgxjgzzeh524k2iomkof3vxrrude7rw

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebo5roksyesit2hmpelloavq5gndp2pylhajftogbrjj35nzoqk7u 
#### Address 
> f1s72ymkzujzb5hnxfaqkgekn37nbisu4pc26eh3i
#### Datacap Allocated
> 2.07PiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> dddcd2ad-acec-4c3a-8bce-695a9582529d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebo5roksyesit2hmpelloavq5gndp2pylhajftogbrjj35nzoqk7u
