### ISSUE TITLE
[DataCap Application] FiLSwan - Dataset for Computing Over Data

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/filecoin-plus-large-datasets#917]
# Large Dataset Notary Application

## Core Information
- Organization Name: FilSwan
- Website / Social Media: https://console.filswan.com/#/dataset
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq

## Project details

Share a brief history of your project and organization.
```
FilSwan has been participate the slingshot since 2020.   FilSwan has built the swan client - a filecoin deal sending tool, Swan provider - a deal processing tool, and the MCS - a cross chain IPFS storage product.

While working with the computing over data team, we found there is a strong need to create dataset for computing team.
The data should have a cache layer on IPFS and backed up to Filecoin network.

This product is aiming at provide a computing compatible layer for dataset cached on IPFS. A recent work about the computing over data can be found here:  https://www.youtube.com/watch?v=41ou-S337gE

Founded in 2021, FilSwan is a layer-2 cross-chain solution that helps Web3 projects to integrate data, computing, storage, and payment into one suite.
```

What is the primary source of funding for this project?
```
FilSwan team
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
e.g. one dataset we store is waymore dataset
The Waymo Open Dataset is comprised of high resolution sensor data collected by Waymo self-driving cars in a wide variety of conditions. We are releasing this dataset publicly to aid the research community in making advancements in machine perception and self-driving technology. https://waymo.com/open

You can find the link here
https://console.filswan.com/#/dataset

another video about how to use the data for computing:
https://youtu.be/iZCtIso3arI

Another devgrant about the user case can be found here: https://github.com/filecoin-project/devgrants/pull/277/files#diff-456660d1dff0aa1e8b8692c817832fea0f81aefe0e15f6aaf1af0a6b4594b505


```

Where was the data in this dataset sourced from?
```
Open Data set
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://console.filswan.com/#/dataset
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Based on User request, should be weekly
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All continents.

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute to storage providers using offline deals 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We use the Filswans auto-bid system, users need to submit their requests, and the system will match storage providers and users automatically. We also build an api for providers to download the dataset query the dataset name, and retrieve via miner id and cid. 
```

How will you be distributing deals across storage providers?
```
We are using FilSwan client agent for batch sending deals.  https://github.com/filswan/swan-client
We have a reputation module called [Swan reputation system](https://docs.filswan.com/filswan-platform/overview/reputation-system) to give SPs scores for the data storage behavior, it based on Time-based Reachability + Regional Weighted Adjusted Power + General Deals and Verified-Storage Provider Deals

FilSwan Auction System will matching the SPs based on reputation and codictions, for the bidding policy you can find it [here](https://docs.filswan.com/filswan-platform/overview/filswan-auction-system)

The mcs is online for 6 month, we have the following SPs storing data:
 f03624
f010088
f02301
f0187709
f01402814
f01398391
f01072221
f0240185
f0143858
f01390330
f01222595
f03223
f01784458
f01840390
f01859603
f01133080
f01858429
f01871352
f01883179
f01886797
f01870135
f0520660
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. Funding & marketing support from the community.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedoeb5f5u72xs3qe3vru2lvmsx7krxjmie4bh4popae2wvvsgskog 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedoeb5f5u72xs3qe3vru2lvmsx7krxjmie4bh4popae2wvvsgskog

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedec5cyispchzzl7duankgkbk555wsftqke7bscslbygxcitdbpgo 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedec5cyispchzzl7duankgkbk555wsftqke7bscslbygxcitdbpgo

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadn4l63bb6mz72qlg3s3pzwvcpou2lry4ryas36xpsiz6n62gfru 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadn4l63bb6mz72qlg3s3pzwvcpou2lry4ryas36xpsiz6n62gfru

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmdacihhklnc5btd3igsmj2u6q77ghyxd4yn3x3ydxwejp5nskgo 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmdacihhklnc5btd3igsmj2u6q77ghyxd4yn3x3ydxwejp5nskgo

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectz4susnpiza2o6knkmbiwyxy5yqvupmcironiqjp5kh66unnloc 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 73e5ae77-fd3f-4dbe-b13e-8d32cdb277db
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectz4susnpiza2o6knkmbiwyxy5yqvupmcironiqjp5kh66unnloc

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebr2xbo64ahmo5uftnojsujoxuwrkftujj2njbtwatiuxulzaa2di 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 73e5ae77-fd3f-4dbe-b13e-8d32cdb277db
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebr2xbo64ahmo5uftnojsujoxuwrkftujj2njbtwatiuxulzaa2di

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6yok3nl7uicqdgag2wysixgohbqqmtjibprhxmivqzk2bk4br6g 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> ad03f9b0-7ddb-47bc-a329-1d64f72e57aa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6yok3nl7uicqdgag2wysixgohbqqmtjibprhxmivqzk2bk4br6g

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavk25lxpj2egpl3xvlmezg2mrfdhqri7czuwvqgwt43bzxzpajrw 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 7f6ec647-8a09-470c-bea2-d97e8045b991
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavk25lxpj2egpl3xvlmezg2mrfdhqri7czuwvqgwt43bzxzpajrw

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealq5qd6ancgsv3slmiyvifnviejh3jqnurhqlb4podc6e37rqrdk 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 7f6ec647-8a09-470c-bea2-d97e8045b991
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealq5qd6ancgsv3slmiyvifnviejh3jqnurhqlb4podc6e37rqrdk

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhodyianpdleejqig32uncj2izw3hsnrilvrzlzgzgkdvrcak5do 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 9d609b10-8cc3-4cb6-8274-76d35919e663
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhodyianpdleejqig32uncj2izw3hsnrilvrzlzgzgkdvrcak5do

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea64ffsrli5mac3ceqwkxnwi7s4bzbm26eqxef7ijag4cxg2o5asm 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> 9d609b10-8cc3-4cb6-8274-76d35919e663
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea64ffsrli5mac3ceqwkxnwi7s4bzbm26eqxef7ijag4cxg2o5asm

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2af3gfdt6lluugtolnd5xfzxdbp6lnnhhah2gssw7522vpnkfuw 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 89cf4187-9f22-4cd6-a399-477a9a814c58
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2af3gfdt6lluugtolnd5xfzxdbp6lnnhhah2gssw7522vpnkfuw

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtfsdvs4tjeglboowtfcuvow6yusviybbpphnbvycgvwgjzkievw 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 89cf4187-9f22-4cd6-a399-477a9a814c58
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtfsdvs4tjeglboowtfcuvow6yusviybbpphnbvycgvwgjzkievw

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `FilSwan`
 - Client: `f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 26.82% of total deal sealed by [f01955034](https://filfox.info/en/address/f01955034) are duplicate data.

⚠️ 21.68% of total deal sealed by [f01953944](https://filfox.info/en/address/f01953944) are duplicate data.

⚠️ 36.15% of total deal sealed by [f01146045](https://filfox.info/en/address/f01146045) are duplicate data.

⚠️ 21.08% of total deal sealed by [f01713152](https://filfox.info/en/address/f01713152) are duplicate data.

⚠️ [f01981571](https://filfox.info/en/address/f01981571) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01955034](https://filfox.info/en/address/f01955034)       |             Hangzhou, Zhejiang, CN |         370.81 TiB |     19.87% |  271.38 TiB |          26.82% |
| [f01955028](https://filfox.info/en/address/f01955028)       |             Hangzhou, Zhejiang, CN |         311.84 TiB |     16.71% |  281.19 TiB |           9.83% |
| [f01955030](https://filfox.info/en/address/f01955030)       |             Hangzhou, Zhejiang, CN |         255.69 TiB |     13.70% |  230.59 TiB |           9.81% |
| [f01938223](https://filfox.info/en/address/f01938223)       |               Montréal, Quebec, CA |         207.80 TiB |     11.14% |  207.80 TiB |           0.00% |
| [f01947280](https://filfox.info/en/address/f01947280)       |             Hangzhou, Zhejiang, CN |         194.13 TiB |     10.40% |  185.41 TiB |           4.49% |
| [f01786736](https://filfox.info/en/address/f01786736)       |          Saint-Gabriel, Quebec, CA |         126.27 TiB |      6.77% |  126.27 TiB |           0.00% |
| [f01953944](https://filfox.info/en/address/f01953944)`new`  |           Singapore, Singapore, SG |         109.41 TiB |      5.86% |   85.69 TiB |          21.68% |
| [f01970622](https://filfox.info/en/address/f01970622)`new`  | Hong Kong, Central and Western, HK |          55.59 TiB |      2.98% |   55.59 TiB |           0.00% |
| [f0705704](https://filfox.info/en/address/f0705704)`new`    |                 Taipei, Taiwan, TW |          55.06 TiB |      2.95% |   55.06 TiB |           0.00% |
| [f01146045](https://filfox.info/en/address/f01146045)       |           Singapore, Singapore, SG |          54.81 TiB |      2.94% |   35.00 TiB |          36.15% |
| [f01713152](https://filfox.info/en/address/f01713152)       |               Jakarta, Jakarta, ID |          23.72 TiB |      1.27% |   18.72 TiB |          21.08% |
| [f01981571](https://filfox.info/en/address/f01981571)       |                            Unknown |          23.47 TiB |      1.26% |   23.47 TiB |           0.00% |
| [f0240456](https://filfox.info/en/address/f0240456)         |               Chengdu, Sichuan, CN |          23.28 TiB |      1.25% |   23.28 TiB |           0.00% |
| [f079426](https://filfox.info/en/address/f079426)           |           Singapore, Singapore, SG |           9.22 TiB |      0.49% |    9.22 TiB |           0.00% |
| [f01876488](https://filfox.info/en/address/f01876488)       |  Ho Chi Minh City, Ho Chi Minh, VN |           9.13 TiB |      0.49% |    9.13 TiB |           0.00% |
| [f02401](https://filfox.info/en/address/f02401)             |        Raleigh, North Carolina, US |           6.38 TiB |      0.34% |    6.38 TiB |           0.00% |
| [f0717969](https://filfox.info/en/address/f0717969)         |        Los Angeles, California, US |           3.78 TiB |      0.20% |    3.78 TiB |           0.00% |
| [f010088](https://filfox.info/en/address/f010088)           |            Everett, Washington, US |           3.75 TiB |      0.20% |    3.75 TiB |           0.00% |
| [f0187709](https://filfox.info/en/address/f0187709)         |                 Moscow, Moscow, RU |           2.50 TiB |      0.13% |    2.50 TiB |           0.00% |
| [f08399](https://filfox.info/en/address/f08399)             |            Seattle, Washington, US |           2.34 TiB |      0.13% |    2.34 TiB |           0.00% |
| [f01072221](https://filfox.info/en/address/f01072221)       |        Los Angeles, California, US |           2.06 TiB |      0.11% |    2.06 TiB |           0.00% |
| [f01886797](https://filfox.info/en/address/f01886797)       |    Vancouver, British Columbia, CA |           2.06 TiB |      0.11% |    2.06 TiB |           0.00% |
| [f01896422](https://filfox.info/en/address/f01896422)       |            Fremont, California, US |           1.69 TiB |      0.09% |    1.69 TiB |           0.00% |
| [f03624](https://filfox.info/en/address/f03624)             |              Nürnberg, Bavaria, DE |           1.59 TiB |      0.09% |    1.59 TiB |           0.00% |
| [f01871352](https://filfox.info/en/address/f01871352)       |                   Seoul, Seoul, KR |           1.56 TiB |      0.08% |    1.56 TiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272)       |                Perm, Perm Krai, RU |           1.56 TiB |      0.08% |    1.56 TiB |           0.00% |
| [f01222595](https://filfox.info/en/address/f01222595)       |                 Moscow, Moscow, RU |           1.50 TiB |      0.08% |    1.50 TiB |           0.00% |
| [f01931631](https://filfox.info/en/address/f01931631)       |            Shenzhen, Guangdong, CN |         992.00 GiB |      0.05% |  992.00 GiB |           0.00% |
| [f0836160](https://filfox.info/en/address/f0836160)         |                   Seoul, Seoul, KR |         768.00 GiB |      0.04% |  768.00 GiB |           0.00% |
| [f032824](https://filfox.info/en/address/f032824)           |                  Austin, Texas, US |         672.00 GiB |      0.04% |  672.00 GiB |           0.00% |
| [f01443744](https://filfox.info/en/address/f01443744)       |                Leipzig, Saxony, DE |         512.00 GiB |      0.03% |  512.00 GiB |           0.00% |
| [f01402814](https://filfox.info/en/address/f01402814)       |           Singapore, Singapore, SG |         512.00 GiB |      0.03% |  512.00 GiB |           0.00% |
| [f01708981](https://filfox.info/en/address/f01708981)       |            Shenzhen, Guangdong, CN |         480.00 GiB |      0.03% |  480.00 GiB |           0.00% |
| [f0697249](https://filfox.info/en/address/f0697249)         |               Beijing, Beijing, CN |         448.00 GiB |      0.02% |  448.00 GiB |           0.00% |
| [f0214334](https://filfox.info/en/address/f0214334)         |               Gwangju, Gwangju, KR |         288.00 GiB |      0.02% |  288.00 GiB |           0.00% |
| [f047419](https://filfox.info/en/address/f047419)           |       North Prairie, Wisconsin, US |         288.00 GiB |      0.02% |  288.00 GiB |           0.00% |
| [f01862564](https://filfox.info/en/address/f01862564)       |                 Xi’an, Shaanxi, CN |         192.00 GiB |      0.01% |  192.00 GiB |           0.00% |
| [f01390330](https://filfox.info/en/address/f01390330)       |                 Xi’an, Shaanxi, CN |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/917/1671097983905.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 51.93% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       247.59 TiB |       250.81 TiB |                   1 |          13.44% |
|       154.81 TiB |       336.28 TiB |                   2 |          18.02% |
|       108.84 TiB |       381.97 TiB |                   3 |          20.47% |
|       158.81 TiB |       739.84 TiB |                   4 |          39.65% |
|        20.78 TiB |       125.63 TiB |                   5 |           6.73% |
|       576.00 GiB |         3.66 TiB |                   6 |           0.20% |
|       704.00 GiB |         5.34 TiB |                   7 |           0.29% |
|       672.00 GiB |         5.25 TiB |                   8 |           0.28% |
|       416.00 GiB |         3.66 TiB |                   9 |           0.20% |
|       352.00 GiB |         3.44 TiB |                  10 |           0.18% |
|       288.00 GiB |         3.09 TiB |                  11 |           0.17% |
|       352.00 GiB |         4.13 TiB |                  12 |           0.22% |
|        96.00 GiB |         1.22 TiB |                  13 |           0.07% |
|       128.00 GiB |         1.75 TiB |                  14 |           0.09% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/917/1671097984610.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                                          | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :--------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y](https://filfox.info/en/address/f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/278)                                                               |             2.52 PiB |      15,972 | LDN v3 multisig |
| [f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq](https://filfox.info/en/address/f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq)                                                                                                     | [ NEXRAD \- FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/80)                                                     |             1.04 PiB |       5,647 | LDN v3 multisig |
| [f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa](https://filfox.info/en/address/f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa)                                                                                                     | [ FilSwan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157)                                         |           701.88 TiB |       5,601 | LDN v3 multisig |
| [f3wn64jznjqmr3s3qt4tfwynxo6k73wdxkhd6wo2l<br/>4rwpjdyyddirah2ugfaibvlzz2asaj3ehsp7bwc2z<br/>vnia](https://filfox.info/en/address/f3wn64jznjqmr3s3qt4tfwynxo6k73wdxkhd6wo2l4rwpjdyyddirah2ugfaibvlzz2asaj3ehsp7bwc2zvnia) | [Jiaxing Yangtze Delta Region Blockchain Technology Research Institute](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/523) |           444.06 TiB |       2,446 | LDN v3 multisig |
| [f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi](https://filfox.info/en/address/f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi)                                                                                                     | [BigData Exchange](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/391)                                                      |           345.75 TiB |       2,447 | LDN v3 multisig |
| [f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea](https://filfox.info/en/address/f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea)                                                                                                     | [ FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/15)                                                               |           277.59 TiB |       5,993 | LDN v3 multisig |
| [f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hm<br/>hi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjro<br/>z54a](https://filfox.info/en/address/f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a) | [dropcool \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/145)                                         |            78.81 TiB |       2,356 | LDN v3 multisig |
| [f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a](https://filfox.info/en/address/f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a)                                                                                                     | [ FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1139)                                                             |            49.78 TiB |         520 | LDN v3 multisig |
| [f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga](https://filfox.info/en/address/f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga)                                                                                                     | [X\-Order Lab](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/936)                                                          |            48.59 TiB |         298 | LDN v3 multisig |
| [f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y](https://filfox.info/en/address/f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y)                                                                                                     | [ Haoqian Mx](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/308)                                                           |            38.97 TiB |         258 | LDN v3 multisig |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151)                                        |            15.53 TiB |         103 | LDN v3 multisig |
| [f3td7znsz2q6laexewfqogczo74xyiwgbysuf6i75<br/>k2wrdqwzyvln7wvzmxaz3jvqzskwxqerdwaetdvue<br/>jama](https://filfox.info/en/address/f3td7znsz2q6laexewfqogczo74xyiwgbysuf6i75k2wrdqwzyvln7wvzmxaz3jvqzskwxqerdwaetdvuejama) | Unknown                                                                                                                                              |             7.47 TiB |         236 |         Unknown |
| [f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa](https://filfox.info/en/address/f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa)                                                                                                     | [ PiKNiK](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/432)                                                               |             1.38 TiB |          44 | LDN v3 multisig |
| [f3wzua4wihcouehv5datojpgalyapegvdfkhkqamx<br/>dtr4tzcsn7kylkoaapmmxisbp3tzekgijb32lrswf<br/>5t5q](https://filfox.info/en/address/f3wzua4wihcouehv5datojpgalyapegvdfkhkqamxdtr4tzcsn7kylkoaapmmxisbp3tzekgijb32lrswf5t5q) | [Ninth Heaven Guild](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1801)                                                |             1.00 TiB |          32 |          Neo Ge |
| [f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq](https://filfox.info/en/address/f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq)                                                                                                     | [Starboard Networks](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1855)                                                |           224.00 GiB |           7 |       Steven Li |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceackydcn4susjawnydoky4grfgjaso2fv2nlo7r7yfprcy7ai26wi 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f70c61d4-46f9-4b4b-b3fc-6a9085a04431
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceackydcn4susjawnydoky4grfgjaso2fv2nlo7r7yfprcy7ai26wi

**Comment by xingjitansuo** [comment]
checker:manualTrigger

**Comment by xingjitansuo** [comment]
I had offline sync with @flyworker.  He cleared my doubts about the results of the CID report, and below is the summary. 
1. This LDN contains more than the Waymo dataset, but also other scientific datasets including but not limited to previously applied and expired Slingshot Dataset, and that explains the heavy sharing with other LDNs applied by Filswan. 
2. Filswan distributes car fie with their engine that can be publicly accessible, and that cannot prevent others from downloading it.

**Comment by flyworker** [comment]
> I had offline sync with @flyworker. He cleared my doubts about the results of the CID report, and below is the summary.
> 
>     1. This LDN contains more than the Waymo dataset, but also other scientific datasets including but not limited to previously applied and expired Slingshot Dataset, and that explains the heavy sharing with other LDNs applied by Filswan.
> 
>     2. Filswan distributes car fie with their engine that can be publicly accessible, and that cannot prevent others from downloading it.

Thanks for the dialogue, yes, I confirmed this is what I said.

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahkzevhfgdgokcilu7prkifkutk6fqmuqlaohpxz6sv7eqay5lmk 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> f70c61d4-46f9-4b4b-b3fc-6a9085a04431
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahkzevhfgdgokcilu7prkifkutk6fqmuqlaohpxz6sv7eqay5lmk

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxm63hdcpbxwsar6mzexhokr7o6sbl6oylqr2zryflibjpfgxolg 
#### Address 
> f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> c0d70c2f-cfa6-413b-bd69-c51d568aa4c7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxm63hdcpbxwsar6mzexhokr7o6sbl6oylqr2zryflibjpfgxolg
