### ISSUE TITLE
[DataCap Application] <Global Unit-A Corp.>

### ISSUE THREAD

**Issue by penghailinfhoabng** [filecoin-project/filecoin-plus-large-datasets#918]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Global Unit-A Corp.
- Website / Social Media: https://www.globalunit-a.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Global Unit-A established in April 2021 with a capital of $40,000 is the company specializing in providing cryptocurrency financial asset management services. We recently are focusing on IPFS technology R&D and distribution of supercomputers and servers.
Global Unit-A provides customers with financial products such as custody products, and asset management product. Our compnay is rapidly expanding its infrastructure by utilizing the existing business infrastructure. We currently have about infrastructure of 6300 customers.
We are at the forefront of Korea's cryptocurrency financial services sector. We are contributing to the development of the Korean cryptocurrency ecosystem by utilizing Filecoin not only in the front-end service but also in the data sector of the back-end to achieve complete block chain technology.
Recently, our engineer team with long-term development experience in finance, block chain, network and DB conducts IPFS technology R&D and develops the total platform involved asset management product. We are expected to officially launch in early 2022.
Users of the Global Unit-A platform are all users who are publishers of public data, administrators, and a person requesting public data.
All users who use the product through this platform can access, publish and manage their data. All data is stored on Filecoin's network through Filecoin storage providers.
```

What is the primary source of funding for this project?
```
It is from the investment of shareholders and the usage fee of users who use this platform.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There are currently no other project/ecosystem stakeholders involved. But we are discussing cooperation with Korean IPFS related officials.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored in Filecoin is all data related to subscription product of users who use Global Unt-A's products, and the capacity is very large such as photos, word, excel files, etc.
```

Where was the data in this dataset sourced from?
```
All data is provided by the user.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Sample Data.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/7623134/Sample.Data.zip)
Yes.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, anyone who store the data and are interested in it can read the data. 
```

What is the expected retrieval frequency for this data?
```
Anytime when clients wants to search.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
This data will be permanently stored in Filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
In Republic of Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We are considering both online and offline data transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Our criteria of storage provider selection are as follows:
- Location: Seoul and its suburbs.
- Companies with facilities that comply with IDC operating regulations (electricity, network, etc.).
- Companies with real data storage experience.
- Companies operating nodes stable (transmission speed, transaction success rate, etc.).
```

How will you be distributing deals across storage providers?
```
We are planning to distribute evenly to companies that meet the above criteria.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough capital. It comes from our shareholders' funds and our customers.
```

**Comment by penghailinfhoabng** [comment]
Global Unit-A Corp aims to provide users with professional financial products with social attributes.All data generated by the product will be stored in filecoin. In Unit-A, users can purchase financial products, store pictures, and view their wealth management income. In the future, we will release the social subscription function, open the function of uploading public videos and tables, and allow users to store their public pictures, wealth management videos.

**Comment by penghailinfhoabng** [comment]
@galen-mcandrew @raghavrmadya Hi, we lost the previous request [#110](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/110) because the account was flagged by GitHub and our datacap allocation process has been interrupted. Please kindly review our application and sign if you support our project. Thank you!

**Comment by raghavrmadya** [comment]
The address listed above is not a verified client address (https://verify.glif.io/). How much DC did you get before and what is the associated address?

**Comment by penghailinfhoabng** [comment]
@raghavrmadya Hi RG, this is the same address we used in the previous application and you can find the verified deals at https://filplus.d.interplanetary.one/clients/f01676203. wondeing why it shows not verfied.
<img width="765" alt="4" src="https://user-images.githubusercontent.com/108708675/189056062-9e93e9f0-8a07-4c24-ac2b-03c95c2dec67.png">
![image](https://user-images.githubusercontent.com/108708675/189056663-2bb472de-bb7d-4969-ada5-b4890b871be0.png)

**Comment by penghailinfhoabng** [comment]
@raghavrmadya Hi RG, is everything okay with the info I provided? Please let me know if you need anything else. Thanks~

**Comment by Sunnyiscoming** [comment]
The issue you applied for before has disappeared, can you explain it?
Are these data you store user data? Whether to obtain the user's authorization to store these data as public data?
Can you explain your data composition? And to provide more data samples related with data you will store to prove that you have 5 PB already. How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by penghailinfhoabng** [comment]
@Sunnyiscoming Hi
The previous GH account was flagged which proved to be a universal problem for the community and Filecoin said nothing could be done on this. So we had to submit this request again with all the same information but a different GH account.

All data is provided by the user which is public.

The data stored in Filecoin is all data related to subscription product of users who use Global Unt-A's products, and the capacity is very large such as photos, word, excel files, etc. All data is provided by the user. We’ll store 3-5 copies.
Data sample: https://github.com/filecoin-project/filecoin-plus-large-datasets/files/7623134/Sample.Data.zip

Please refer to the following for SP information. Thanks!
![image](https://user-images.githubusercontent.com/108708675/194736394-4b8910dc-6710-433b-ab4d-bf9f6a81badf.png)

**Comment by penghailinfhoabng** [comment]
@Sunnyiscoming @raghavrmadya Any update pls?

**Comment by Sunnyiscoming** [comment]
What platform do you provide to upload data to your customers? Can you provide more data samples to prove that you have 5PB data?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a

**Comment by Sunnyiscoming** [comment]
@penghailinfhoabng Any update here?

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `GLOBAL UNIT-A Corp.`
 - Client: `f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01771508](https://filfox.info/en/address/f01771508) has sealed 51.88% of total datacap.

⚠️ 23.13% of total deal sealed by [f01841131](https://filfox.info/en/address/f01841131) are duplicate data.

⚠️ [f01854755](https://filfox.info/en/address/f01854755) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01771508](https://filfox.info/en/address/f01771508)       |           San Jose, California, US |          24.63 TiB |     51.88% |   24.63 TiB |           0.00% |
| [f01841131](https://filfox.info/en/address/f01841131)       | Hong Kong, Central and Western, HK |          10.00 TiB |     21.07% |    7.69 TiB |          23.13% |
| [f01854755](https://filfox.info/en/address/f01854755)`new`  |                            Unknown |           6.44 TiB |     13.56% |    6.44 TiB |           0.00% |
| [f01841134](https://filfox.info/en/address/f01841134)       |           Singapore, Singapore, SG |           3.28 TiB |      6.91% |    2.78 TiB |          15.24% |
| [f01877862](https://filfox.info/en/address/f01877862)       |                   Seoul, Seoul, KR |           3.13 TiB |      6.58% |    3.09 TiB |           1.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/918/1671097992246.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        44.63 TiB |        47.47 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/918/1671097992815.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                            | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :--------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                         |            11.36 TiB |          69 | LDN v3 multisig |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429)      |             9.27 TiB |          84 | LDN v3 multisig |
| [f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa](https://filfox.info/en/address/f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa)                                                                                                     | ``                                                                                                                     |             5.59 TiB |          48 |       LDN # 121 |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)                  |             3.59 TiB |          85 |        LDN # 51 |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)                   |             3.44 TiB |          46 | LDN v3 multisig |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui)                                                                                                     | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                                  |             1.78 TiB |          27 | LDN v3 multisig |
| [f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxo<br/>zmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmq<br/>cbwq](https://filfox.info/en/address/f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq) | [VillageOne Space LLCVillageOne Space LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/39) |           544.00 GiB |          17 |        LDN # 39 |
| [f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly](https://filfox.info/en/address/f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly)                                                                                                     | ``                                                                                                                     |           288.00 GiB |           3 |     Zhehao Chen |
| [f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i](https://filfox.info/en/address/f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i)                                                                                                     | [Myserver](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/447)                             |           192.00 GiB |           6 |    Tim Williams |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                               |            64.00 GiB |           1 | LDN v3 multisig |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)                                |            32.00 GiB |           1 |        LDN # 54 |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                                |            32.00 GiB |           1 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                       |            32.00 GiB |           1 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                        |            16.00 GiB |           1 |        LDN # 72 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
