### ISSUE TITLE
[DataCap Application] Zhengyu Technology: Life Sciences - Genomic Data

### ISSUE THREAD

**Issue by shiji605** [filecoin-project/filecoin-plus-large-datasets#92]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Zhengyu Network Technology Co., Ltd
- Website / Social Media:https://mp.weixin.qq.com/mp/profile_ ext?action=home&__ biz=Mzg3NzU2MzMyNQ==&scene=124&uin=&key=&devicetype=Windows+10+x64&version=63030532&lang=zh_ CN&a8scene=7&fontgear=2
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):250TiB
- On-chain address for first allocation:f1n5m6umzh2xi3nqqt5tjx757pa6ogjavumouobta

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Zhengyu Technology is a technology company focusing on the research and development of blockchain technologies such as distributed storage, distributed computing, distributed databases, and edge computing. It is also an innovative company focusing on IPFS. Zhengyu Technology is committed to creating high-performance terminal storage devices, stable and secure storage network systems, and efficient storage algorithms.
```

What is the primary source of funding for this project?
```
The company will cover the cost
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects/ecosystem stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
COVID-19 PubSeq is a free and open online bioinformatics public sequence resource with on-the-fly analysis of sequenced SARS-CoV-2 samples that allows for a quick turnaround in identification of new virus strains. PubSeq allows anyone to upload sequence material in the form of FASTA or FASTQ files with accompanying metadata through the web interface or REST API.
```

Where was the data in this dataset sourced from?
```
[Please answer here.](https://registry.opendata.aws/pubseq/)
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Please answer here.](https://covid19.genenetwork.org/about)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Licensed under https://creativecommons.org/licenses/by/4.0/
```

What is the expected retrieval frequency for this data?
```
Anyone interested in retrieving this datacet.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
A year and a half.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global, but mostly in Europe and Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online or offline. There has been an offline transmission process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will see if the storage provider has relevant experience and is sustainable.
```

How will you be distributing deals across storage providers?
```
All storage deals will be verified if they have enough FIL to pledge and their equipment can handle.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have prepared sufficient funds and resources.
```

**Comment by galen-mcandrew** [comment]
@shiji605 can you clarify here: It sounds like you represent Guangzhou Zhengyu Network Technology Co., Ltd, but the website provided fails to load. Also it sounds like the dataset you are uploading is public SARS-CoV-2 Sequence data.

Can you clarify your role? Are you a representative of the client or a storage provider?

**Comment by dkkapur** [comment]
Closing this issue out for now for inactivity. Please re-open if still required.
