### ISSUE TITLE
[DataCap Allocation] - Client Allocation Request for: Dekun cloud data technology

### ISSUE THREAD

**Issue by taskerone** [filecoin-project/filecoin-plus-large-datasets#920]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Client Allocation Request for: Dekun cloud data technology"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dekun cloud data tecnology
- Website / Social Media: https://dekun.decoo.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 450TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1n6lyl2qcxnjn2aoiinmrux6rnumxnzdyoslcpmi
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Dekun Cloud Data Technology Co., Ltd. is a company focusing on web3.0 distributed storage since founded in 2020 on September. We are constantly exploring and expanding distributed and decentralized storage technology's development potential and application boundaries.
Our project, Dekun Cloud, is a cloud storage service that creates professional cloud storage products for large-scale commercial scenarios and provides a new option for meeting the storage needs of enterprises and individuals.
```

What is the primary source of funding for this project?
```
Project operating income and Dekun Foundation
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Instructional videos, surveillance videos, pictures, documents, and other data uploaded by users through our website. Couse, they are tremendous real data, so we need more storage space to meet the needs of users.
```

Where was the data in this dataset sourced from?
```
Our users are divided into individual users and institutional users, they come from schools, online training institutions, IoT platforms, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://ipfs-sh.baitech-ipfs.net/ipfs/QmUcfquVa37WWYPtUPtLgraMKDrYbbzSpu2ozTFRTPZS1i?filename=b210143c17eee19c8c0dcd1544b2fd57.mp4
https://ipfs-sh.baitech-ipfs.net/ipfs/QmSkX42BLBNmYPoBzL5V8bUodidhdKee17nu9AdjXMdA7S?filename=20220903_103100.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Anyone can access it through the sharing link.
```

What is the expected retrieval frequency for this data?
```
The frequency of retrieval is determined by the users.

```

For how long do you plan to keep this dataset stored on Filecoin?
```
If it is convenient to use, we will use it for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly online transactions. We accept offline transactions.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
we will consider not only the reputation of the storage providers but also the other aspects below.
- location
- transmission speed
- deal success rate
- previous experience with real data storage
- stability of their nodes
- quoted price
```

How will you be distributing deals across storage providers?
```
There are two options we are going to consider, one is the degree of reputation for storage providers and their ability of stabilization, which could ensure they will help us to store data securely and stably. Another is that the provided prices offered by the miners are relatively within our acceptable range.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Absolutely. We will make deals as soon as we can.
```

**Comment by AnthnoySmith** [comment]
Seems that you are not the real data owner. At present, the LDN process is not oriented to storage providers. Recommended to invite actual clients to apply for it so as to do KYC and KYB.

**Comment by taskerone** [comment]
As one of our company's businesses, the Dekun Cloud project is oriented to customers, providing customers with secure data storage, and providing services for small and medium-sized enterprises, because they do not have independent data storage resources, but they have storage requirements. To keep customer data more securely, we choose to change our centralized storage method for choosing the FILECOIN project to fulfill decentralized storage needs. May I ask that do you think we are the storage provider or the client? @AnthnoySmith

**Comment by raghavrmadya** [comment]
Your request does not qualify for LDN as it is less than 500 TiBs. Please apply using direct allocation - https://github.com/filecoin-project/filecoin-plus-client-onboarding
