### ISSUE TITLE
[DataCap Application] KNCA (Korea NFT Certificate Authority)

### ISSUE THREAD

**Issue by kornft** [filecoin-project/filecoin-plus-large-datasets#922]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: KNCA (Korea NFT Certificate Authority)
- Website / Social Media: https://kornft.org
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3wsfr5rgaq6ex46oylqms4dok6njj45fem5yhayhjkdythlylb3esweul6ps23hzrdzsawdqz3dwsani5sdwa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
KNCA (Korea NFT Certificate Authority) supports non-fungible items owned by individuals or companies to NFT using blockchain technology. We have established NFT registration and certification centers online and offline so that analog or digital items can be easily accessed and used by anyone, not an expert.

KNCA provides the following one-stop services.
- Digitization: Digitizing various items with specialized technology,
- NFT Verification: Verifies the entity, ownership, copyright, and right relationship of the item.
- NFT Registration: Hash this into a non-fungible NFT token and register it on the blockchain.
- NFT View: Anyone can view the details of the registered NFT like a registered copy,
- NFT Certification: This is a service that the certification agency guarantees through due diligence that it is an actual original.
- Certification mark: This is a service that discloses reliability by using an accredited certification mark at each NFT exchange.

KNCA is an expert group that has successfully led numerous projects of companies based on many years of blockchain and NFT development performance, service mind for customers, and communication ability with customers. We will lead solid trust with our customers by providing the best quality and service that meets the needs of our customers, and more than what they expect.
```

What is the primary source of funding for this project?
```
Company shareholders and technology partners.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We plan to store the data processed by KNCA in Filecoin.
- NFT digital content data
- NFT registration certificate
- NFT accredited certificate registration copy
```

Where was the data in this dataset sourced from?
```
- NFT digital content data registered from users in KNCA
- NFT registration certificate issued directly by KNCA and certified certified register data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Sample of NFT Digital Content Data
- https://kornft.org/data/file/300/metacamp1.gif
- https://kornft.org/data/file/300/6161020600589485449.mp4
- https://kornft.org/data/file/300/3661063259_UNf0DWx5_5d10824a4b9503f5f4987c37ada272d5a1ecd0df.png

Sample of NFT registration certificate and register copy data
- https://kornft.org/theme/knca/img/knca/knca_paper11.png
- https://kornft.org/pages/bon0/certi_new.php
- https://kornft.org/pages/bon1/certi_history.php
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Data retrieval is required in the following cases:
- When a user requests restoration of NFT content stored in Filecoin, registration certificate, and registered copy data
- When it is necessary to restore the entire KNCA data
Therefore, the frequency of data retrieval can occur irregularly.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The data stored in Filecoin will be stored according to the following criteria.
- The NFT content data, registration certificate, and registered copy data generated by KNCA will be permanently stored in Filecoin.
- When storing data in Filecoin to back up all KNCA data, we plan to keep each backup data set for 5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Korea, Japan
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We use online transfer. However, in special cases such as full data backup, data can be sent offline via hard disk or SSD.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
- Due to the importance of data storage, we plan to select a storage provider considering its reputation, reliability, and price.
- We also plan to select a storage provider that provides an offline data transfer process in consideration of the need to store large amounts of data.
```

How will you be distributing deals across storage providers?
```
- We plan to store data distributed across 3 or more storage providers.
- And we plan to distribute our allocated Datacap to each storage provider so that no more than 25% is allocated.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we will find and add better storage providers as soon as we receive DataCap, and we have the resources and funds ready to start trading.
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/194756227-ee38e061-979c-49c5-84a4-cf0564dc7885.png)
https://kornft.org/

Sample of NFT Digital Content Data
- https://kornft.org/data/file/300/metacamp1.gif
- https://kornft.org/data/file/300/6161020600589485449.mp4
- https://kornft.org/data/file/300/3661063259_UNf0DWx5_5d10824a4b9503f5f4987c37ada272d5a1ecd0df.png

Sample of NFT registration certificate and register copy data
- https://kornft.org/theme/knca/img/knca/knca_paper11.png
- https://kornft.org/pages/bon0/certi_new.php
- https://kornft.org/pages/bon1/certi_history.php

All these links are currently unavailable. Please check it.

**Comment by kornft** [comment]
@Sunnyiscoming
Hello.
We had a problem accessing the service website while we were doing server maintenance over the last holiday.
The website now works fine. please check.

**Comment by raghavrmadya** [comment]
Can you help me understand what exactly are you storing? You are a certification authority and I fail to understand how you have 5 PiBs of certifications

**Comment by kornft** [comment]
@raghavrmadya 
Hello.

KNCA is in the business of issuing NFT certificates.
When KNCA issues an NFT certificate, it also stores digital content data such as certified NFT images and NFT videos.

Please refer to the press articles below
(The content of the press article is written in Korean.)
* Signed a technology contract with Korea NFT Certificate Authority and Korea YMCA for $600,000
http://www.segyebiz.com/newsView/20221027508943
* Korea NFT Certificate Authority held a meeting with YMCA Korea and Seoul Foreign Correspondents' Club
https://www.ekn.kr/web/view.php?key=20221027001247382

As mentioned in the above press article,
- KNCA issues and stores certificates for the contents of NFT works such as images and videos created at YMCA's 120 regional headquarters.
- KNCA has signed contracts with various art groups, copyright associations, and sports groups, and composes their contents into NFT contents of images and videos, and issues and stores certificates.
- In addition, KNCA records and stores the on-site due diligence process as a video for all verification registrations.

Considering the above, we applied for a DataCap of sufficient capacity.

**Comment by Sunnyiscoming** [comment]
I would like to confirm with you the type of data you currently have, the size and the number of backups.
Some links of data samples are currently unavailable.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>On-chain address for first allocation: f3wsfr5rgaq6ex46oylqms4dok6njj45fem5yhayhjkdythlylb3esweul6ps23hzrdzsawdqz3dwsani5sdwa

**Comment by psh0691** [comment]
To sign the DC allocation, I would like to ask you a few questions first.
1. It is difficult to check 5PiB with sample data. Please provide the basis for applying for 5PiB. Example) Screenshot of the size of the data you have.
2. Is the NFT certificate and live-action video shared? Is there no privacy violation?
3. Please explain if there is a related SP.

**Comment by Sunnyiscoming** [comment]
> I would like to confirm with you the type of data you currently have, the size and the number of backups.
> Some links of data samples are currently unavailable.
> 

> To sign the DC allocation, I would like to ask you a few questions first.
> 
> It is difficult to check 5PiB with sample data. Please provide the basis for applying for 5PiB. Example) Screenshot of the size of the data you have.
> Is the NFT certificate and live-action video shared? Is there no privacy violation?
> Please explain if there is a related SP.

Any update here?

**Comment by kornft** [comment]
@psh0691 @Sunnyiscoming 

### It is difficult to check 5PiB with sample data. Please provide the basis for applying for 5PiB. Example) Screenshot of the size of the data you have.

**1) High definition image (jpg ,png,svg,gif…)**
In the process of converting analog to digital, we take and store images and videos from various angles with high-definition cameras. After taking dozens of pictures and saving the original state, the raw data in the digitized state is stored.
<img width="452" alt="image1" src="https://user-images.githubusercontent.com/111728739/209290594-7befaecd-4f78-4590-9729-0d4df6c70df7.png">

**2) High definition video (mp4, avi, mov…)**
We record and archive interviews with owners, interviews with copyright holders, and introductions to work stories. We use video recordings to establish authenticity and verification of ownership of documents and copyright holders.
<img width="452" alt="image2" src="https://user-images.githubusercontent.com/111728739/209290626-58267511-7901-4cec-8c5d-88a9fe6f9454.png">

**3) Scanned document image (png…)**
We keep high-definition scans of contracts and confirmations submitted for Nft copyright and ownership verification.
<img width="452" alt="image3" src="https://user-images.githubusercontent.com/111728739/209290659-fed88e0e-7251-44ec-a6a1-b4c853efbb36.png">


### Is the NFT certificate and live-action video shared? Is there no privacy violation?

For the NFT works registered in KORNFT, there are on-site investigation videos such as interviews and interviews with the artist to confirm the reality of the NFT.

1) certificate and live-action video share

- Certificate in the form of documents for issuance: Real-life images are shared in the form of images.
- Certificate of online viewing format: Live action video is shared in the form of a video

2) Is there no privacy violation?

- No infringement of personal information: pre-filtering system, sharing after consent of the copyright holder
- All images and videos are stored separately in their original form → Check whether or not the original has been tampered with with the hash value (keep for evidence).
- For images and videos to be shared, only those that have been agreed upon by the person with the registration right (owner) are selected and shared.


### Please explain if there is a related SP.

- Korea: KT IDC (Mokdong) has its own storage and server
- Global: Amazon S3

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqzedat3urj7rijmczfooco22vn3ks22gkjikcwxpgh7atkv3v32 
#### Address 
> f3wsfr5rgaq6ex46oylqms4dok6njj45fem5yhayhjkdythlylb3esweul6ps23hzrdzsawdqz3dwsani5sdwa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 57f2beac-7b7c-47ab-bbe2-f8367c93c65b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqzedat3urj7rijmczfooco22vn3ks22gkjikcwxpgh7atkv3v32

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
