### ISSUE TITLE
[DataCap Application] <Aiyao (Shanghai) Food Technology Co., Ltd> 

### ISSUE THREAD

**Issue by iyelliyell** [filecoin-project/filecoin-plus-large-datasets#929]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Aiyao (Shanghai) Food Technology Co., Ltd
- Website / Social Media:www.iyell.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200T 
- On-chain address for first allocation:f1teogheqo4o2rkhlqecbp53mm6dz7t2nj5nj6qbi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Aiyao is a user driven Internet + Chocolate Company, positioned to provide users with natural and functional chocolate health food. We look forward to working with one heart and one mind to create more and richer product use scenarios and high-quality experiences for users in the process of cooperation.
```

What is the primary source of funding for this project?
```
The main source of funding for this project is provided by the company's operating income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
The experimental data and production process related to microbial science are used to study the chemical reaction of microbial fermentation in the process of chocolate production, with the purpose of improving the production process and producing healthier chocolate that is more in line with oriental tastes.
```

Where was the data in this dataset sourced from?
```
Experimental data and production process of chemical reaction in microbial fermentation of chocolate
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1P33yPcVg5bfwrxQagLlLZvjEjrOlCsGd/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store it on filecoin for at least 3 years and hope to keep it for a long time
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China,Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We hope it is offline transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a well-funded storage provider that understands project dat
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Our own company has sufficient project funds
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/194801825-94fae258-7567-48fc-85c9-ed2871a300ae.png)
I can't check data samples you provided.
What's the relationship between you and the organization?
Can you explain your data composition? And to provide more data samples related with data you will store to prove that you have 5 PB already. How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by simonkim0515** [comment]
Closing due to no response.

**Comment by iyelliyell** [comment]
https://drive.google.com/drive/folders/1BLkwtgfXaALjkSPj4Bh0PcORPuEHTjms?usp=share_link

**Comment by iyelliyell** [comment]
@simonkim0515 @Sunnyiscoming 
The dataset has been uploaded again and can be downloaded for viewing
This is only a part of the data, please check
https://drive.google.com/drive/folders/1BLkwtgfXaALjkSPj4Bh0PcORPuEHTjms?usp=share_link

**Comment by iyelliyell** [comment]
Hi, 
I am an Operation & Maintenance Engineer of Aiyao, a user-driven Internet + chocolate company, positioned to provide users with purely natural, functional and health chocolate food. We are looking forward to creating more and richer product usage scenarios and high-quality experiences for users in the process of cooperation with unity. The sample data is experimental data related to microbiology science. It is used in the study of chemical reactions in the microbial fermentation process in the chocolate making process, in order to improve the production process and produce healthier chocolate that are more in line with the taste of the Orientals.

The total size of data set is about 600T, and we are planning to make 8 backups.
There is no requirement for storage location, because biological experimental data are not as readable as pictures and videos.
We have analyzed the data samples provided with professional tools, which you can view here:
codebook：Dealing with GenBank files in Biopython 
https://ftp.ncbi.nlm.nih.gov/refseq/release/viral/

.fna (FASTA file), mainly used to store sequence files of organisms, such as genomes, nucleic acid sequences of genes, and amino acids, etc., is the most common biological sequence format

SPs currently in contact are:
f0417848
f01915287
f01922865
f01940076
f0119976
f01264518
