### ISSUE TITLE
[DataCap Allocation] - FIL+

### ISSUE THREAD

**Issue by FILDCKabat** [filecoin-project/filecoin-plus-large-datasets#930]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "FIL+"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: FILDC KABAT
- Website / Social Media: wwww.kabacinski.com.pl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500
- Weekly allocation of DataCap requested (usually between 1-100TiB): 70
- On-chain address for first allocation: f1cuoouxsmyeigcqbbviebgvdd4xdkapy42jgo4vy
- Region: Europe

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We are working as an SP for over 1 year. Now after getting agreement with Darma Capital, we search for bigger deals.
```

What is the primary source of funding for this project?
```
Own source and Darma Capital
```

What other projects/ecosystem stakeholders is this project associated with?
```
none 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
```

Where was the data in this dataset sourced from?
```
Please answer here.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please answer here.
```

What is the expected retrieval frequency for this data?
```
Please answer here.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Please answer here.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Please answer here.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Please answer here.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
```

How will you be distributing deals across storage providers?
```
Please answer here.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Please answer here.
```

**Comment by raghavrmadya** [comment]
incomplete application

**Comment by FILDCKabat** [comment]
finally completed, or do You need anything from our side?

**Comment by FILDCKabat** [comment]
ok, clear, I just found out that some information were missing, so in those position add comments

**Comment by raghavrmadya** [comment]
Please open a new application as this is closed. Additionally, please provide more evidence as data samples. A youtube link is no enough

**Comment by FILDCKabat** [comment]
https://www.icloud.com/iclouddrive/0e9W2hcPJ8JYDpFyg3n5br4nA#Kabat_RP_2021

**Comment by lyjmry** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2008#issuecomment-1643645187

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
