### ISSUE TITLE
[DataCap Application] zhixiaotongxin - zhixiaotongxin

### ISSUE THREAD

**Issue by chenfan76673** [filecoin-project/filecoin-plus-large-datasets#931]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: zhixiaotongxin
- Website / Social Media: https://www.zhixiaotongxin.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
GOVGO (Beijing) Communication Technology Co., Ltd, which is located on the sixth floor of Yingu Building, Zhongguancun, Beijing, China. It belongs to national high-tech enterprises, national double-soft enterprises, Zhongguancun high-tech enterprises, ISP operators of Ministry of Industry and Information Technology, representatives of global VR alliance, etc. The company has a large platform of Internet of Things and data developed independently, and serves various industries. Nearly 30 Internet of Things soft and hard products; Alibaba IOT core partners in the Internet of Things, HIKVISION industry suppliers; the company holds more than 30 independent intellectual property rights patents and copyrights, through the IS9001/14001/18001 certification system.

GOVGO is positioned in the information service of modern enterprises, and taking big data, Internet of Things and cloud computing as the core to build system application service platform, we have developed many software and hardware products of independent intellectual property rights and Internet of Things data service platform, and provided relevant information solutions to help enterprises realize real-time data. Modern enterprise production mode with controllable production and efficient management.
```

What is the primary source of funding for this project?
```
Company
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Platform data
```

Where was the data in this dataset sourced from?
```
Company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/chenfan76673/data
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
1 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainland China or Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We can provide download links for SPs to download. If distance allows, we can also mail disks where the data is stored
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose SPs based on geographic location and the quality of service the SPs provide
```

How will you be distributing deals across storage providers?
```
Store to multiple SPs to ensure data security
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?
Can you explain your data composition? And to provide more data samples related with data you will store to prove that you have 5 PB already. How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by chenfan76673** [comment]
I am a technical engineer in the company, and the data I need to store includes
1) The information intermediate data stored in our database is about 500T
2) The log data is about 800T
3) Product, user promotional video, about 100T
4) The back-end can publicly store about 800T of data
We need to store 5 copies. The SP of the storage supplier we have contacted has them
f01909429
f01923787
f01851482
f01852664
f01852023
f01885088
f01901351

**Comment by chenfan76673** [comment]
The data will be updated later ,Thank you!

**Comment by chenfan76673** [comment]
Hello,Mr/Ms Sunny.
Updated data address: https://drive.google.com/drive/folders/1zF6JoZaDCHyh7_FfXX_ku5lDWSZJLvOo

**Comment by chenfan76673** [comment]
If you have any questions, please contact us @Sunnyiscoming

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7nqyaipfpteix23wn7c3oxahln2ykp6dzjiylrsh74mq7zji2kk 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> b48bc837-41bb-4bae-8b37-a49f75af25e6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7nqyaipfpteix23wn7c3oxahln2ykp6dzjiylrsh74mq7zji2kk

**Comment by Tom-OriginStorage** [comment]
This is the first time to sign. I will follow up on it later. If there are any problems, I will contact the owner to solve them

**Comment by newwebgroup** [comment]
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

**Comment by chenfan76673** [comment]
![图片](https://user-images.githubusercontent.com/48347945/203932724-0502bdeb-0349-4191-8c64-f60d5dbf916a.png)

**Comment by chenfan76673** [comment]
thanks for checking!

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbxpxfo2unel33uqq3qucdkpo4zg5icccrlensmhzw54leo436xc 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> b48bc837-41bb-4bae-8b37-a49f75af25e6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbxpxfo2unel33uqq3qucdkpo4zg5icccrlensmhzw54leo436xc

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqiilf7dzmhymgxd4hquuzz4bnk7an52f3fc5ejb2j6r32bwjb5y 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> ba4475d8-57c4-43ad-a0c9-37337405df3e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqiilf7dzmhymgxd4hquuzz4bnk7an52f3fc5ejb2j6r32bwjb5y

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebed3hpuvr43a52pd7hrveoc7ecsflqmn2elg5getqwdzvossncmo 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> ba4475d8-57c4-43ad-a0c9-37337405df3e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebed3hpuvr43a52pd7hrveoc7ecsflqmn2elg5getqwdzvossncmo

**Comment by BDE-io** [comment]
@chenfan76673 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpus4wddqiktpsk56mkulrbyvueu7t4tfsd42vwfr47v5hdbv6wy 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 1520ce79-7a0f-4741-a891-a58dcfc90c82
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpus4wddqiktpsk56mkulrbyvueu7t4tfsd42vwfr47v5hdbv6wy

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazfg2xuhetdmxzqugcpursi6vr62kte7qc3ef7ulsziymykprpey 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 1520ce79-7a0f-4741-a891-a58dcfc90c82
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazfg2xuhetdmxzqugcpursi6vr62kte7qc3ef7ulsziymykprpey

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebn3ukz6occ75kdsqztxsdabk4wfflksmdsbc45m6psct3mz3b3v6 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> b206a19b-fd32-47b9-913e-db945fd6acce
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebn3ukz6occ75kdsqztxsdabk4wfflksmdsbc45m6psct3mz3b3v6

**Comment by newwebgroup** [comment]
Bot doesn't seem to work properly. @raghavrmadya 

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/100118145/204960225-81ab0e41-88e1-47bc-9149-48db7b1f4dbc.png">
<img width="844" alt="image" src="https://user-images.githubusercontent.com/100118145/204960280-b375b0a1-8e8d-465a-8f8a-87bf503e5277.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4nq47h3x6jvpxfmorfxjqcokqaei5gl7pjlzjvi2pv3dv52tbjw 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> b206a19b-fd32-47b9-913e-db945fd6acce
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4nq47h3x6jvpxfmorfxjqcokqaei5gl7pjlzjvi2pv3dv52tbjw

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyrsmdje3ykpan75bcpkp5al5t4oqjo5hwjsk4lliie5f6gw6csu 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 79735362-4bb1-4ba8-9909-69d975f6b1ae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyrsmdje3ykpan75bcpkp5al5t4oqjo5hwjsk4lliie5f6gw6csu

**Comment by xingjitansuo** [comment]
The distribution looks good so far. I will approve this tranche

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3rgefhp2au3yedciw6jpbyeibu62ctatowifth7veeuyzdlwzse 
#### Address 
> f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 79735362-4bb1-4ba8-9909-69d975f6b1ae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3rgefhp2au3yedciw6jpbyeibu62ctatowifth7veeuyzdlwzse

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `zhixiaotongxin`
 - Client: `f1qf3h3pqz7lu7yuxqed6g4qbeydaof2d63gm4z6q`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |         108.59 TiB |     22.99% |  108.59 TiB |           0.00% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |         100.03 TiB |     21.18% |  100.00 TiB |           0.03% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |          94.31 TiB |     19.97% |   94.28 TiB |           0.03% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |          92.19 TiB |     19.52% |   92.19 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |          77.25 TiB |     16.35% |   77.25 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/931/1671098029993.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 61.22% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        44.25 TiB |        44.25 TiB |                   1 |           9.37% |
|        49.44 TiB |        98.88 TiB |                   2 |          20.93% |
|        48.69 TiB |       146.06 TiB |                   3 |          30.92% |
|        32.81 TiB |       131.31 TiB |                   4 |          27.80% |
|        10.38 TiB |        51.88 TiB |                   5 |          10.98% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/931/1671098030673.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by BDEio** [comment]
@chenfan76673 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your valuable data with reliable storage providers. If you need any help, please get in touch.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
proposals dealscanner-f01973609-f01965334: Error: Failed to retrieve content with candidate miner f01965334: data transfer failed: deal errored: getting pieces for cid QmPdK9qd185uwSTyFoSNboAE8Y1apwWUjYWzmGA2BghKT6: getting pieces containing block QmPdK9qd185uwSTyFoSNboAE8Y1apwWUjYWzmGA2BghKT6: failed to lookup index for mh 1220132072c12c5e460d85b60c66b21733ac07e92fff499e4e76207b02e9f3868621, err: datastore: key not found

Sorry but the data is not retrievable.

**Comment by C00kies77** [comment]
checker:manualTrigger
