### ISSUE TITLE
[DataCap Application]-<Blockcasting> 

### ISSUE THREAD

**Issue by mingyang313** [filecoin-project/filecoin-plus-large-datasets#932]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: blockcasting
- Website / Social Media: http://blockcasting.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Blockcasting (Hangzhou) Technology Co., Ltd. is headquartered in Hangzhou, China. Facing the future development trend of the Internet, the optical carrier interconnection focuses on the field of video processing and has accumulated a lot of experience in the field of video/image processing. Among them, artificial intelligence-based video and image recognition/analysis/processing technology and 8K/VR and other ultra-high-definition video encoding/decoding/compression/encryption/transmission technologies are the company's core technologies.

(i) AI-based video and image recognition/analysis/processing: By training AI algorithms on a large amount of data, a mathematical model is automatically constructed, and video/image content is analyzed without special programming, and by extracting key information, Mark, and form corresponding processing or alarm. Especially when processing a large amount of video data, the traditional manual processing method is inefficient, and it is easy to miss information. AI-based video processing technology analyzes the video stream by using comprehensive and complex algorithms, viewing the image of the video pixel by pixel, with hardly any important information missing.

(ii) Encoding/decoding/compression/encryption/transmission of ultra-high-definition videos such as 8K/VR: Internet video development has gone through two stages. The second stage, from 2013 to 2019, will focus on live broadcasting and short videos; in the third stage, we believe that video will enter the era of real-time interaction and VR/AR. The immersive experience of VR/AR/360-degree viewing angle requires higher and higher video transmission capabilities. In this scenario, video encoding/compression/transmission technology plays an important role in VR/AR.
```

What is the primary source of funding for this project?
```
Company
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
AI training data & HD video
```

Where was the data in this dataset sourced from?
```
Company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/mingyang313/sample_data
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
1-2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Use offline transfer or mail hard drive for data transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We would like to choose a storage provider in Hong Kong. Storage providers need to ensure that data can always be retrieved.
```

How will you be distributing deals across storage providers?
```
Store to multiple SPs
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by Sunnyiscoming** [comment]
What's the Chinese name of your company? Can you provide the search link of your company in Qichacha?
The sample data you provide seems to be replicated on other social platforms.
For example,
https://github.com/mingyang313/sample_data/blob/main/YF1fn7uriQPvDQ.mp4
https://m.weibo.cn/status/KcZqNlRSf
Please provide that the data is your data or the data you are authorized to use.

**Comment by mingyang313** [comment]
> What's the Chinese name of your company? Can you provide the search link of your company in Qichacha? The sample data you provide seems to be replicated on other social platforms. For example, https://github.com/mingyang313/sample_data/blob/main/YF1fn7uriQPvDQ.mp4 https://m.weibo.cn/status/KcZqNlRSf Please provide that the data is your data or the data you are authorized to use.

Our company's name is 光载互联（杭州）科技有限公司.
The search link of our company in Qichacha  is https://www.qcc.com/firm/e3c358d70d481fe6556a5efc6e1d8f6c.html.

**Comment by mingyang313** [comment]
@Sunnyiscoming Do you have any questions about what we have provided? If you have any questions, please feel free to contact me.

**Comment by mingyang313** [comment]
@Sunnyiscoming any updates?

**Comment by mingyang313** [comment]
@Sunnyiscoming  Any update about this application?

**Comment by Sunnyiscoming** [comment]
> The sample data you provide seems to be replicated on other social platforms.
> For example,
> https://github.com/mingyang313/sample_data/blob/main/YF1fn7uriQPvDQ.mp4
> https://m.weibo.cn/status/KcZqNlRSf
> 

The data samples you initially provided seems not to be your own.

What is the source of the data sample you provided?
Can you describe the type, size of the data you currently have and provide the evidence?

**Comment by mingyang313** [comment]
> > The sample data you provide seems to be replicated on other social platforms.
> > For example,
> > https://github.com/mingyang313/sample_data/blob/main/YF1fn7uriQPvDQ.mp4
> > https://m.weibo.cn/status/KcZqNlRSf
> 
> The data samples you initially provided seems not to be your own.
> 
> What is the source of the data sample you provided? Can you describe the type, size of the data you currently have and provide the evidence?

@Sunnyiscoming 
First of all, thanks for your reply. Just like the video samples provided above, our high-definition videos are collected from the Internet, internally generated by the company, and provided by users.
Various Ultra HD Videos: 900T
AI training video：100T

<img width="840" alt="image" src="https://user-images.githubusercontent.com/37865375/201942692-b054a142-6d1f-43a3-9acb-5d4eb1d3a153.png">

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji

**Comment by mingyang313** [comment]
![image](https://user-images.githubusercontent.com/37865375/204208108-55cacdee-6c06-4641-b2e1-0918b7a6baf1.png)
I have sent a confirmation email with my corporate mailbox, please check.

**Comment by Tom-OriginStorage** [comment]
I saw the screenshot of your email, please provide the SP area you want to store, if you already have a negotiated SP, you can also provide the next node number

**Comment by mingyang313** [comment]
> I saw the screenshot of your email, please provide the SP area you want to store, if you already have a negotiated SP, you can also provide the next node number

@Tom-OriginStorage 
These are the sp I contacted  f01851482,f01852325,f01852664

**Comment by Tom-OriginStorage** [comment]
Okay, I will sign for you and I will continue to pay attention to it later

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzkebbtaluo3vm7qlyfefev2njhjkmtkm5qhlr4knrhoskirbuc4 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 3082c094-dd3c-4933-9ae6-f2cdd414d459
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzkebbtaluo3vm7qlyfefev2njhjkmtkm5qhlr4knrhoskirbuc4

**Comment by newwebgroup** [comment]
The first approval is not bad from the data samples provided.
Will continue to pay attention

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedywk7xzsqiawpe7bzkjpz6x4zn7agcfphx2ipvvkwrnlslcjq73y 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 3082c094-dd3c-4933-9ae6-f2cdd414d459
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedywk7xzsqiawpe7bzkjpz6x4zn7agcfphx2ipvvkwrnlslcjq73y

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
no,we always are on the road.

**Comment by mingyang313** [comment]
keep on

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
Inaccurate robot retrieval, new node blocked, support provided in this round

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsntt5sinjaodnjdbegvfjnumk7lkmbrbloq2wa2nafexnkvkfaa 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> f6ab7330-942b-484c-8369-673607098976
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsntt5sinjaodnjdbegvfjnumk7lkmbrbloq2wa2nafexnkvkfaa

**Comment by mingyang313** [comment]
The robot encountered a bug and only showed a credit of less than 5t and an incomplete report.

**Comment by mingyang313** [comment]
![0003a131-67a1-435e-a9fc-8468e2621804](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/8d3cccf5-4c56-4580-b11d-c35642275794)

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
The data retrieval rate is acceptable, but the data distribution is extremely uneven. The proportion of individual service providers (SP) is too high, exceeding the limit of 25% set by Fil+. Adjustments are needed accordingly.
Retrieval Statistics
Overall Graphsync retrieval success rate: 22.22%

Furthermore, improvements are required for data replication. However, considering that this is the first round, the client has promised to make changes and I am willing to support them in this round.

There is no CID sharing and no disputes have arisen. I am willing to provide support in this round and will monitor the situation closely. If any violations occur, I will raise a flag to T&T.

[f02236965](https://filfox.info/en/address/f02236965) has sealed 83.90% of total datacap.

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><g-emoji class="g-emoji" alias="warning" style="box-sizing: border-box; display: inline-block; min-width: 1ch; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: var(--base-text-weight-normal, 400); line-height: 1; vertical-align: -0.075em; font-style: normal !important;">⚠️</g-emoji><span> </span>100.00% of deals are for data replicated across less than 3 storage providers.</p>

Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage
-- | -- | -- | --
193.56 TiB | 193.56 TiB | 1 | 100.00%

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3hbqqqeahk5jesbptrdwyzqsuevmfxtkhj4c6khjjbbfrif23eo 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> f6ab7330-942b-484c-8369-673607098976
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3hbqqqeahk5jesbptrdwyzqsuevmfxtkhj4c6khjjbbfrif23eo

**Comment by mingyang313** [comment]
it's in use.

**Comment by mingyang313** [comment]
in use.

**Comment by mingyang313** [comment]
in use.

**Comment by mingyang313** [comment]
works.

**Comment by mingyang313** [comment]
works.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
Application has been self-dealing. Requesting closure @kevzak

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
> Application has been self-dealing. Requesting closure @kevzak

The data displayed by the robot is incomplete. It has already used 600 TiB of the quota, but only shows the usage details for 300 TiB.

**Comment by mingyang313** [comment]
We have recently onboarded 4 new SPs and have already utilized 250t of the quota, but it is not displaying accurately.

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwiduxzeh2dxet3acbtgu65aarevkpf6ojqt2h3qg7zgw3uen4by 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> a4bf4acf-c161-456b-ad1a-e44179e7429e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwiduxzeh2dxet3acbtgu65aarevkpf6ojqt2h3qg7zgw3uen4by

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebed5muzlh6rinwezd6gxz6xk4dqp6x6tvrymtrobvrpshiune754 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> a4bf4acf-c161-456b-ad1a-e44179e7429e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebed5muzlh6rinwezd6gxz6xk4dqp6x6tvrymtrobvrpshiune754

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
The data displayed by the robot is incomplete. It has already used 1000 TiB of the quota, but only shows the usage details for 350 TiB.

We have recently onboarded 5 new SPs and have already utilized 600t of the quota, but it is not displaying accurately.

**Comment by kernelogic** [comment]
I cross referenced on another site and it shows healthy distribution. I think the bot is buggy and stopped tracking this LDN.

https://ehume.com/#/clientDetail?clientAddress=f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsb5a2a7flyjhslpxbbf2q2pukiifz7bpbcgijsxhdl5xbvminby 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> a4bf4acf-c161-456b-ad1a-e44179e7429e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsb5a2a7flyjhslpxbbf2q2pukiifz7bpbcgijsxhdl5xbvminby

**Comment by nj-steve** [comment]
> I cross referenced on another site and it shows healthy distribution. I think the bot is buggy and stopped tracking this LDN.
> 
> https://ehume.com/#/clientDetail?clientAddress=f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji

also think so.Robot data has been a lot buggy lately.

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapkdlis3hztfcfbbjmrefdh32xn3s4extjjtojiwyureoqjuutma 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> a4bf4acf-c161-456b-ad1a-e44179e7429e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapkdlis3hztfcfbbjmrefdh32xn3s4extjjtojiwyureoqjuutma

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Checked historical comments, reports are not normal due to bot bugs, LDN distribution is shown to be healthy through other sources, so willing to support this round
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/14f9c48a-84ab-4d5c-a61f-cc3fff31d7ce)

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwkxnzzoczf2gvxovee4feuvvyyzsoirrixd7lzfl732sisuhsv4 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> f67db356-8f4f-40a1-9feb-b49abf6364b8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwkxnzzoczf2gvxovee4feuvvyyzsoirrixd7lzfl732sisuhsv4

**Comment by METAVERSEDATAMINING** [comment]
Hope to improve the distribution of copies.

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7logygpcj3yjd2tsb6cnvzp76zduebfvpzwo5t2syd3nnrussy2 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> f67db356-8f4f-40a1-9feb-b49abf6364b8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7logygpcj3yjd2tsb6cnvzp76zduebfvpzwo5t2syd3nnrussy2

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
LGME

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb47hglk5lkzhok6wdkeghlrygm6wz6szpbzufna2a3kjcxugrmc4 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 236f0488-b539-4135-b64b-0e458da8f85e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb47hglk5lkzhok6wdkeghlrygm6wz6szpbzufna2a3kjcxugrmc4

**Comment by ipollo00** [comment]
seems the retrieval bot has not synced with the CID checker in time. LGTM is willing to support.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedii4o633555khmik6lr5q2lmsaelcqgoqf622xlfdz5ne4zpzeym 
#### Address 
> f14kpqkcnwakfwwy3m2olconcttwv4nh7vec6clji
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 236f0488-b539-4135-b64b-0e458da8f85e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedii4o633555khmik6lr5q2lmsaelcqgoqf622xlfdz5ne4zpzeym

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 09 48 27](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/c16ab2e1-65c4-402e-b946-c1d8d1599941)

This entity uses multiple VPN providers for fake distribution against the rules.

@NiwanDao not happy seeing you sign this Cabrina.

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 09 49 31](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/88004e7c-8239-4f76-a605-22e5c635c485)

Close this LDN @kevzak

**Comment by herrehesse** [comment]
Entity is self-dealing, sadly.

**Comment by mingyang313** [comment]
Can you publicly disclose your testing website and testing tools?

**Comment by Filplus-govteam** [comment]
Hello, @mingyang313 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review. Closing until clear list of SP entities and locations is provided

**Comment by mingyang313** [comment]
This is ridiculous. Reminding me to fill in SP information and close at the same time.
