### ISSUE TITLE
[DataCap Application] Ruineng Medical Technology Co.LTD

### ISSUE THREAD

**Issue by tpkkijsss** [filecoin-project/filecoin-plus-large-datasets#934]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ruineng Medical Technology Co.LTD
- Website / Social Media: http://zlkj.ruiup.net/ ,  http://rnyxkj.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation:  f1jup56xqrdzekualy3mkfol3mcrpq5sjb5umhgvq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Guangzhou Ruineng Medical Technology Co.LTD was established in 2017. The company focuses on the research and development, production and sales of pre-treatment instruments for medical tests, with strong technical experience and development strength. The company provides high-quality medical device products and professional services for hospitals, third-party testing institutions and scientific research units.
```

What is the primary source of funding for this project?
```
Profit from company
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have no other stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Some of the research & development data including patent, lab test result data, UI design, product pictures, etc that can be public retrieval.
```

Where was the data in this dataset sourced from?
```
From our company 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://pan.baidu.com/s/1hEsMmilGUqJ9a5H5aFY4iw?pwd=h9sv 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
1 time per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
About 2 to 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Via online transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Stability and reliability is the first concern.   
```

How will you be distributing deals across storage providers?
```
Storage will be fairly distribute to multiple SPs.                               
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we would like to do it as soon as possible.. 
```

**Comment by Sunnyiscoming** [comment]
This seems to be the organization's website, http://rnyxkj.com/. Why would you use another company's secondary domain name?
![image](https://user-images.githubusercontent.com/105098820/195475508-b235f2c2-c44a-4d54-8596-2cd9c7d5a070.png)
The data samples you shared has also been deleted.
You should contact more SP's before applying to develop a storage plan.

**Comment by tpkkijsss** [comment]
> This seems to be the organization's website, http://rnyxkj.com/. Why would you use another company's secondary domain name? ![image](https://user-images.githubusercontent.com/105098820/195475508-b235f2c2-c44a-4d54-8596-2cd9c7d5a070.png) The data samples you shared has also been deleted. You should contact more SP's before applying to develop a storage plan.

Hi @Sunnyiscoming 
1. Both domain belongs to our company, zlkj.ruiup.net was previously used, you can see that both are point to same ip, thanks for pointing that out, we have added rnyxkj.com in the application.
![ede0e6a0f5bffb6d76493a31e74182e](https://user-images.githubusercontent.com/109796976/196129296-73ba9ee6-bd1f-4d85-b733-140b7e97a7c0.jpg)
![556b737c1cebe95fbcd271ecf64a7a6](https://user-images.githubusercontent.com/109796976/196129336-f0104765-6bb3-4a56-8ab8-490cabf3b598.jpg)
2. It's been too long and the shared link expired, we shared it again ,kindly refer to the link: https://pan.baidu.com/s/1BXBkat53OXAljoVtDUvvuQ?pwd=ynd4
3. we have contacted serval SPs including f0145162, f0218407, f01096124, f01506844, f017665, we can try to contact more if required.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1jup56xqrdzekualy3mkfol3mcrpq5sjb5umhgvq

**Comment by Sunnyiscoming** [comment]
Hey @tpkkijsss , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3.5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
