### ISSUE TITLE
[DataCap Application] <Shenzhen wannuowei Technology Co., Ltd> 

### ISSUE THREAD

**Issue by Vanergy** [filecoin-project/filecoin-plus-large-datasets#938]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen wannuowei Technology Co., Ltd
- Website / Social Media:www.vanergytech.com/https://wannuowei.en.alibaba.com/minisiteentrance.html?spm=a2700.details.cordpanyb.2.195d4ef9erxjVG&from=detail&productId=1600435917468
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:f1kvbhxv42tcafj6tbiuggr3oelmwuywg7jmxvfua
_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Vanover is an innovative technology company that independently develops and produces various ear band products. Its core components include earphone components. In order to test and fully run in each module of the earphone, it needs to use various audio files to run in the earphone for a long time, so as to achieve the most perfect performance index.
The company mainly uses the live broadcast function of the store to promote and sell to users, so the store link is attached
```

What is the primary source of funding for this project?
```
The main source of funds is our company
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Data information of each project
```

Where was the data in this dataset sourced from?
```
Test sound source file for headphone running in
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1lecjD_9GpCelYy5TOCMApjlWBQTX-AWo?usp=sharing

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I think we will keep it for 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, I choose offline data transfer primarily.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
1. Companies with actual data storage experience
2. Stable node operation (fast transmission speed, etc.)
3. Support retrieval and have sp operation experience
```

How will you be distributing deals across storage providers?
```
Hosting files online where storage providers can download them.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Of course, we have enough funds
```

**Comment by Sunnyiscoming** [comment]
https://drive.google.com/drive/folders/1lecjD_9GpCelYy5TOCMApjlWBQTX-AWo?usp=sharing
Error 404. Please check it.

**Comment by Sunnyiscoming** [comment]
Close for no reply.
