### ISSUE TITLE
Large Dataset Notary Application for project DMDB.

### ISSUE THREAD

**Issue by 15012700225** [filecoin-project/filecoin-plus-large-datasets#941]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:   ShenSuanYun Co.,ltd
- Website / Social Media: http://www.sspool.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f3xdiulg4aznbjwjcptafl7iy5aqwybdvyuyuowwyq5zldbwynsgw7ryudtroa5k425t3na7ciqzyoxsybeqta

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

    ShenSuanYun  Co.,ltd founded in September 2020, is a professional supply block chain service provider. 
The decentralized Materials Database (DMDB) cooperated with Harbin Institute of Technology will carry out cooperation in the field of blockchain, IPFS distributed storage and other fields to empower ShenZhen Nanshan blockchain industry development.
    With the growth of massive data and the development of emerging technologies, how to challenge the scientific research data analysis platform, how to establish a set of scientific research big data platforms that can meet massive data collection, storage, analysis, and sharing have become important issues facing the development of scientific research computing. 
    Essence DMDB decentralized material science large database is based on blockchain and IPFS storage technology to build scientific research big data platforms to achieve data encryption, non -tampering, traceability and other functions. The platform covers data fusion, data processing, data storage, and data interaction. system. Realize the full -process services such as data extraction, data standardization, data processing, data storage, data archiving, and data interaction.
   You can access this project with http://dmdb_dev.sspool.cn/ and  review or experience the first release.

What is the primary source of funding for this project?

ShenSuanYun  Co.,ltd and The Harbin University of Technology (Shenzhen) Lin Yan's research group. 

What other projects/ecosystem stakeholders is this project associated with?

Harbin Institute of Technology (Shenzhen) Lin Yan research group.

## Use-case details

Describe the data being stored onto Filecoin

Mainly preserve the data used in scientific experiments.
1.Scientific experiment original dataset
2.Scientific experimental process data
3.Model analysis results data

File types include text, pictures, audio, video and other types.

Where was the data in this dataset sourced from?

The data from Members of the Science Experimental Project Team.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

https://ipfs.io/ipfs/QmXZXavXRmgu9EryFzcBEp47DJZkGAySDQhZBAcJz8y3aV?filename=Laravel5.1_learn_test_1.zip
https://ipfs.io/ipfs/QmZQ6m2vLmzRTXFfmkrYsMQyXDCXBHQDxFiKreAkEKf58Q?filename=yele_lesson_test_01.zip 
https://ipfs.io/ipfs/QmTWABFUzdQ3LhPGg3PhKD8SosTFtM2qtCGnUU9R8j8tK5?filename=test.data
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

We confirm that this is a publicly retrievable public dataset.

What is the expected retrieval frequency for this data?

The frequency of retrieval depends on the user's needs.

For how long do you plan to keep this dataset stored on Filecoin?

We plan to store it permanently.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

Asia.

How will you be distributing your data to storage providers? Is there an offline data transfer process?

Online deal only in first phase .

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

We have selected more than 10 miners around us with good reputation, trustworthiness, and experience in verifying data to conduct transactions, we will cooperate for a long time with reputable miners.

How will you be distributing deals across storage providers?

Each file will be stored 2 copies on the Filecoin network, and seal them with the fast retrieval option. When a sector error is detected, the system will reseal to a new miner to ensure the safety and availability of the file.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

Yes, we have resources and funds to start making deals as soon as we receive Datacap.
Efficient and stable retrieval will make the filecoin network more perfect, looking forward to solutions from the community, thank you for the hard work of the community.
Please let us know if other information needed, .Thank you.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/195479861-706c10c3-e875-4143-96b0-5dea363588c0.png)
The data samples you provided is not available, please check them.
![image](https://user-images.githubusercontent.com/105098820/195480105-1e42f2fa-fbce-435f-a926-7a25f41341f9.png)
Can you provide more data samples related with the data you will store to prove that you have 5 PB data? Videos would be better. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by 15012700225** [comment]
Greetings, we apologize for not checking the status of this issue in time.

these 2 links below are not used anymore for their instability.

https://ipfs.io/ipfs/QmXZXavXRmgu9EryFzcBEp47DJZkGAySDQhZBAcJz8y3aV?filename=Laravel5.1_learn_test_1.zip
https://ipfs.io/ipfs/QmZQ6m2vLmzRTXFfmkrYsMQyXDCXBHQDxFiKreAkEKf58Q?filename=yele_lesson_test_01.zip

However, we managed to provide new links that work.

data samples:
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/zzzVvCU5rinhQaONUqP79qwaL6qh/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/zvccYQBJaljS_PtOe2im3XIPX42n/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/-0fUQ5_9BSst36IqtA96w24XrHSo/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/10UPmyMrpGFJrbTnEzLadK_ItcmS/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/zyzXDc4fSD0k_hlvKTHF50SJ1cUf/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/JmDa3b2z-f9sBe1UTnB5YQcXPrDR/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/q9Bfa-s_keFRe_a_zlJs79Z8cLXt/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/-AWAzrgkkwtLQNbI2FY-gBhRP-MF/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/zzyAoJTSH5G-d6kqDqqU9Ix-Ira4/raw
http://dmdb-data.sspool.cn:7081/prod/v1/api/v1/entries/xbvGVIbMZ486o5lwdnOZxCDejYLU/raw

------------------------------------------------------------------------------------
Here are some answers to your concerns/questions.

Q: Can you provide more data samples related with the data you will store to prove that you have 5 PB data? Videos would be better. 

The attached video indicates that there are 12,365,578 public model files in our possession, the size of which is larger than 5PB (the requirement).

Q: Can you explain your data composition and provide sufficient data samples separately? 

The DMDB stands for open or private access of scientific materials data. It enables the confirmatory analysis of materials data, their reuse, and repurposing. All data is available in their raw format as produced by the underlying code (Repository) and in a common, machine-processable, and well-defined data format (Archive). 

Q: How many copies will you store?

2 copies.

Q: What's the relationship between you and the organization?

My job title is the Director of the R&D department, and I'm also a shareholder of the company.

Q: Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

The SPs listed below are ready for participation for the DMDB project.
f0427989, f01042409, f0465477,f01039576, f01123232 and f01302086 


[20221017_144717.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9797684/20221017_144717.zip)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

>f3xdiulg4aznbjwjcptafl7iy5aqwybdvyuyuowwyq5zldbwynsgw7ryudtroa5k425t3na7ciqzyoxsybeqta

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

>f3xdiulg4aznbjwjcptafl7iy5aqwybdvyuyuowwyq5zldbwynsgw7ryudtroa5k425t3na7ciqzyoxsybeqta

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4eyyzkrilbrbya7xbrdlgsim54vkt3qu6t7cjckxvoeb3lduodm 
#### Address 
> f3xdiulg4aznbjwjcptafl7iy5aqwybdvyuyuowwyq5zldbwynsgw7ryudtroa5k425t3na7ciqzyoxsybeqta
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 82a7da64-bade-462e-a3d8-b74b22666d87
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4eyyzkrilbrbya7xbrdlgsim54vkt3qu6t7cjckxvoeb3lduodm

**Comment by Defil2022** [comment]
Will keep an eye on this ticket with further data allocation to SPs.

**Comment by Defil2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwjpwsvsgfngcjckxhssoon5msfv6prd75cryn3q7skl2qm4uy6q 
#### Address 
> f3xdiulg4aznbjwjcptafl7iy5aqwybdvyuyuowwyq5zldbwynsgw7ryudtroa5k425t3na7ciqzyoxsybeqta
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 82a7da64-bade-462e-a3d8-b74b22666d87
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwjpwsvsgfngcjckxhssoon5msfv6prd75cryn3q7skl2qm4uy6q

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `  ShenSuanYun Co.,ltd`
 - Client: `f3xdiulg4aznbjwjcptafl7iy5aqwybdvyuyuowwyq5zldbwynsgw7ryudtroa5k425t3na7ciqzyoxsybeqta`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01123232](https://filfox.info/en/address/f01123232) has sealed 100.00% of total datacap.

⚠️ [f01123232](https://filfox.info/en/address/f01123232) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                                    | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f01123232](https://filfox.info/en/address/f01123232)`new`  |  Unknown |          33.00 GiB |    100.00% |   33.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/941/1671098059432.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        33.00 GiB |        33.00 GiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/941/1671098060164.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by changelo** [comment]
checker:manualTrigger

**Comment by 15012700225** [comment]
Hello Friend, the quota of the first week applied for DMDB has been used up, and the quota of the second week has not been allocated.
At present, the sector sealing has been affected. In this case, how can we operate to trigger the quota of the second week?
Please give your guide, thank you.

**Comment by herrehesse** [comment]
@15012700225 unable to continue with notary support here. The above CID report shows that you almost completely ignored the guidelines of the Filecoin+ program.

I am asking notaries not to sign this request until clear answer of the applicant to the questions below.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by 15012700225** [comment]
Greetings, we apologize for not checking the status of this issue in time.


Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

Customer data

Q:Could you demonstrate exactly how and to what extent customer contact occurred?
We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

As a Filecoin third-party solution provider, we are deeply involved in the filecoin project. Our company cooperates with the Lin Yan research group of Harbin Institute of Technology (Shenzhen) to develop the DMDB project. We believe that the public scientific experiment data is valuable and worthy of long-term preservation. It needs a complete, safe and economical backup plan. Based on our company has enough SP storage resources and problem-solving capabilities, so we jointly decided to save this data set to filecoin and participate in Filecoin+ activities.
According to the plan, after the single-node verification is completed in the first week, more SP will be introduced to achieve, and the goal of having two copies of a file in filecoin. 
It is currently in the first week of encapsulation and preparation for the second week. This is also The reason why CID reports only one SP.


Q:Did the customer specify the amount of data involved in this relevant correspondence?

All public data needs to be saved to Filecoin according to the plan, and the amount of data far exceeds 5P. Private private data in the project is not included in this scope to avoid information leakage and disputes.

Q:Why does the customer in question want to use the Filecoin+ program?

We think that the problematic customers who participate in filecoin+ may think that they can quickly increase computing power and obtain governance rewards through filecoin+, and even directly obtain income through quota transactions. This is against the value of filecoin+'s.

Should this only be soley for acquiring datacap this is of course out of the question. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network.

Q:Why is the customer data considered Filecoin+ eligible?
(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)

The users of the project are scientists and scientific researchers. The experimental data and research models they disclose are part of human knowledge and have great reference significance for scientific research. Its value is beyond doubt and it is worth preserving for a long time. This is in line with the value of filecoin+, which permanently preserves valuable and public data.


Files and Processing

Q:Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?

As an alternative technical solution for existing backups system, We have developed a backup management system, include the server and the client.
1.For a large amount of existing backup data, we copy them to the disk in batches and send them to the SP computer offline and avoid huge Internet traffic.
2.For incremental data, it is pushed to the SP through online tasks, and the SP downloads the backup data through the client and starts sector encapsulation. In order to avoid the impact on the space-time proof, the download service implements the current limiting function.
3.In order to optimize the efficiency and performance of the transaction, the go-filemarket project code was optimized to minimize the network traffic generated during the transaction.

Q:Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
Through the above solutions, a large number of network transmissions are avoided. Based on a one-week test, the bandwidth of 200M can meet the needs, which is currently what the SP can afford.

Q:Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

The task distribution management module will manage the distribution tasks of backup files in a unified manner. The sp can only start the assigned sealing task when it is assigned to the task and obtains the certification authorization, so it can control the abuse of data quotas for repeated sealing
We agree with and support the community's rigorous attitude and management of data quotas. Appreciate to the efforts of the community and look forward to the bright future of filecoin.

Please let's us know if other needed. thanks a lots. Together.

**Comment by herrehesse** [comment]
@15012700225 Thank you so much for taking the time to answer my above questions in detail.

The website is not reachable and the provided samples are completely empty or the links are not working. Please assist me further in understanding what you are trying to store here and provide decent examples and working links.

**Comment by 15012700225** [comment]
@herrehesse, apologize for interrupt your work. 
The website http://www.sspool.cn/ and http://dmdb_dev.sspool.cn/ are reachable now and the provided samples are accessable.
Please let's us know if others needed, we will  keep an eye on here . thanks a lots.

**Comment by cryptowhizzard** [comment]
@15012700225 

>>
⚠️ [f01123232](https://filfox.info/en/address/f01123232) has sealed 100.00% of total datacap.
⚠️ [f01123232](https://filfox.info/en/address/f01123232) has unknown IP location.
>>

Is there something not clear to you about the rules of FIL+ ??????????

![Scherm­afbeelding 2023-01-10 om 09 11 40](https://user-images.githubusercontent.com/36404435/211496431-4dce81f4-5a94-4f0a-b7a6-fb55049328e9.png)

There has been zero communication about this, why should any notary thrust you for a second round of datacap?

**Comment by 15012700225** [comment]
@cryptowhizzard，Thank you very much for your guidance and sorry for not solving the issue of CID report in time.

issue: f01123232 has unknown IP location.
the p2p address for f01123232 is /ip4/154.91.39.111/tcp/16889/p2p/12D3KooWFRUWggCK7oBc7Pv1E45SPLEEhmnXjCNqURaochGZfgDk, you can reach it with this commond: 
lotus net connect /ip4/154.91.39.111/tcp/16889/p2p/12D3KooWFRUWggCK7oBc7Pv1E45SPLEEhmnXjCNqURaochGZfgDk.

issue: f01123232 has sealed 100.00% of total datacap.
According to the plan, after the single-node verification is completed in the first week, more SP will be introduced to achieve, and the goal of having two copies of a file in filecoin.
It is currently in the first week of encapsulation and preparation for the second week. This is also The reason why CID reports only one SP.
The next node is f01302086, the p2p address for f01123232 is /ip4/103.44.247.134/tcp/15789/p2p/12D3KooWG73GuA57HvxdqZnnci2f9WrfLnt8GDVD3iXbkwfy9WL6.
The all data sealing on node f01123232  will be send to f01302086 to make sure two copies at filecoin network. 

thanks again.

**Comment by lvschouwen** [comment]
@15012700225 
Thanks for sharing the IPs but ... 
Why is it the IP address of those miners is not announced on chain and therefor cannot be retrieved?

**Comment by cryptowhizzard** [comment]
Hi @15012700225 

Please read the rules of Fil+ carefully.

It states that one has to have his miner available for retrieval. You should announce it. The same for f01302086.

Can you provide us with a list of CID's so we can evaluate the data that has been packed in car files for distribution?
Given that this application has not been according the guidelines we can verify what you intend to store.

**Comment by 15012700225** [comment]
We will announced the address for f01302086 and f01123232 now.

**Comment by 15012700225** [comment]
@lvschouwen，@cryptowhizzard the announced the address for f01302086 and f01123232 has done.  

Due to the modified go-filemarket project, some problems were encountered during the validation and retrieval, and we are repairing them. In fact, when the online system needs to restore data from the filecoin network, instead of using the community retrieval interface, the online system sends the restore task to the corresponding SP, and the SP receives the restore task, which will be directly sent to the online system after unsealed successfully.

![b593db153e38bc054a7d145257b6e71](https://user-images.githubusercontent.com/57610562/211584303-41c6ed21-13c8-4fef-b49e-385cfa2d3eb7.png)

**Comment by 15012700225** [comment]
What should we do next? thanks.

**Comment by cryptowhizzard** [comment]
<img width="1608" alt="Scherm­afbeelding 2023-01-15 om 22 58 56" src="https://user-images.githubusercontent.com/36404435/212569430-ad7dd9ab-4d86-4417-9e67-252111e80104.png">

Hi @15012700225

Please read the rules of Fil+ carefully.

It states that one has to have his miner available for retrieval. You should announce it. The same for f01302086.
*Can you provide us with a list of CID's so we can evaluate the data that has been packed in car files for distribution?
Given that this application has not been according the guidelines we can verify what you intend to store.*

You have stored 100% on one miner instead of 4, you did not follow the rules. What are your suggestions here? When can i receive a list of CID's to check what you are storing?

**Comment by cryptowhizzard** [comment]
checker:manualTrigger
