### ISSUE TITLE
[DataCap Application] <Beijing kebike Education Consulting Co., Ltd​>

### ISSUE THREAD

**Issue by kobiko1** [filecoin-project/filecoin-plus-large-datasets#942]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing kebike Education Consulting Co., Ltd​
- Website / Social Media:www.kobiko.cn​
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation:f1qjxoexyp6o34c6t5fxyebecs7ees4ymacbmgufy​

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing kebike Education Consulting Co., Ltd. is a professional provider of overall solutions for educational institutions. It was initiated and founded by elites from domestic well-known education and training industry, Internet companies and financial industry. It has received high attention and full support from many investment funds, and has formed strategic alliances with many listed companies and well-known education brands. In view of the marketing, teaching and management problems commonly faced by educational institutions, Beijing kebike Education Consulting Co., Ltd. innovatively proposed three solutions. The group has established five service systems for education and training institutions, including marketing service, network service, management service, teaching service and Investment Service​
```

What is the primary source of funding for this project?
```
From ourselves​
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Open academic lectures, open library classes, open university classes and other video files
```

Where was the data in this dataset sourced from?
```
The sample data are video files of open academic lectures, library open classes, and university open classes. They are important learning materials provided by the company to the vast number of students. Video courses facilitate students to learn remotely online at any time.​
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1pPKn6BqTpjQgn1v6OiTqN1c3_yrUQM4j/view?usp=sharing​
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,confirm.​
```

What is the expected retrieval frequency for this data?
```
Once a year​
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 5 years​
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia,China​
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
1. We will choose reliable and highly reputable storage suppliers​
2. Select a storage provider that can provide offline data transmission​
```

How will you be distributing deals across storage providers?
```
We plan to store data distributed among 3 or more storage providers​
We plan to allocate the upper limit of allocated data to each storage provider​
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources and funds to start trading.​
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/196070165-80bbbe40-21b5-4770-bb69-352992dc14a9.png)
![image](https://user-images.githubusercontent.com/105098820/196070181-76396c02-da6c-43d3-b131-aa6fadc91264.png)
The website do not work.
The link of data samples access is limited.
Please check them.

**Comment by kobiko1** [comment]
> ![图片](https://user-images.githubusercontent.com/105098820/196070165-80bbbe40-21b5-4770-bb69-352992dc14a9.png) ![图片](https://user-images.githubusercontent.com/105098820/196070181-76396c02-da6c-43d3-b131-aa6fadc91264.png) 该网站不工作。 数据样本访问的链接是有限的。 请检查它们。

Link to data sample access: 
https://drive.google.com/drive/folders/:-n-FoxK4CN8qJvD-SaKx8-WFM?usp=sharing

**Comment by Sunnyiscoming** [comment]
www.kobiko.cn​
The website do not work, please check it.

**Comment by Sunnyiscoming** [comment]
Close for no reply.
