### ISSUE TITLE
[DataCap Application] <Cyberpop Labs Ltd. Games, Inc.>

### ISSUE THREAD

**Issue by lufakejfoiwang** [filecoin-project/filecoin-plus-large-datasets#943]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Cyberpop Labs Ltd. Games, Inc.
- Website / Social Media: https://cyberpop.online/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1uft2bo66a4xthvozkr4cn6zcvybmenmm5mlzpzy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Cyberpop is focusing on games and web3.0 technology. Cyberpop Metaverse is created by a top technical team whose members are from Ubisoft and is officially authorized by "Prince of Persia". It leads the GameFi industry to the age of AAA games.
As the world's first open world MMO-RPG metaverse game with cyber style, Cyberpop is a 3A level UGC game based on technological development and exploration, which imbues with game playable, combinable and growable. Players can accrue their roles’ experience points by staging or defeating aliens in different maps and earn game currencies. Cyberpop combines the entertainment attribute and financial antagonism of the game, players can make GAME weapons, unphysical establishments, clothing, and other NFT, which can be sold openly in the game exchange market. Moreover, players can even design their own game maps, and the data will be recorded through cochaining. So that Cyberpop is a true UGC content game, which is completely combined with the concept of our team of DAO creation fads.
Cyberpop is compatible with PC, VR, Mobile, and different app provides, in which mobile provides’ rendering level reaches the PS4 level, 3A level game image quality, and experience. The core team includes the members from well-known game companies such as Ubisoft, Huawei, Tencent, and other companies, which leads this game to a peak standard, especially in the game’s UI, stories plots, Gameplay mechanics, economic models.
Equipped with an advanced collapse algorithm and UGC, Cyberpop New World supports the generation of NFTs. The security of the chain-end protocol effectively guarantees the development of multiplayer competition and cyber cities. Cyber cities can currently generate player assets, and new assets are being produced continuously.
Medium: https://medium.com/@Cyberpopmetaverse
Telegram: https://t.me/cyberpopnw 
Discord: https://discord.gg/4826SJsdsA
Reddit: https://www.reddit.com/user/Cyberpop123
Gitbook: https://app.gitbook.com/s/wgJkhsnBpN3LXkR31whG/
Facebook: @Cyberpop 3A NFTgame
Twitter: https://twitter.com/cyberpopnw
YouTube: @Cyberpop Metaverse
Instagram: https://www.instagram.com/cyberpop_metaverse/
LinkedIn: https://www.linkedin.com/company/cyberpop/?originalSubdomain=sg
```

What is the primary source of funding for this project?
```
Shareholders' investment and business revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Basic gameplay and art design, game scenes, game character models, three-dimensional digital images, motion cartoons, animation works, manga works, game CGs, animation promos, etc.
```

Where was the data in this dataset sourced from?
```
From users or artists related to Cyberpop Metaverse who created their assets and minted them to NFT, including transaction data, artwork, paintings, music, audio and videos.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pdf.cyberpop.online/
https://wiki.cyberpop.online/ 
https://cyberppp.s3-accelerate.amazonaws.com/CyberpopMetaverseDeck.pdf 
CyberPOP New world deck(cn).pdf 
CyberPOP New world deck(en).pdf   
https://github.com/lufakejfoiwang/Game 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is a public dataset that can be publicly retrieved.
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency for this data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Preferably 3-5 years according to the roadmap of our game.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer. 
The expected data onboarding rate is 200TiB per week. However, it will be influenced by factors, such as the transmission speed(especially inter-regional transmission), daily power growth of SPs, base fee, equipment performance, etc. For these reasons, the actual data onboarding rate may differ from our expectations.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Major characteristics about choosing the storage providers:
- location
- transmission speed
- deal success rate
- previous experience of real data storage
- stability of their nodes
```

How will you be distributing deals across storage providers?
```
We plan to select 4-6 SPs according to their network bandwidth and storage efficiency with each less than 30% of the quota.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by lufakejfoiwang** [comment]
Forgot to put the links in these two files in the sample data section:
[CyberPOP New world deck(cn).pdf](https://esxieej3ow.feishu.cn/file/boxcnCsEZuHEt9MLX4AGKDWuevh)
[CyberPOP New world deck(en).pdf](https://esxieej3ow.feishu.cn/file/boxcneMSW1NcjKlRqvnzy41sStd)

**Comment by lufakejfoiwang** [comment]
@raghavrmadya @dkkapur Hi are there any updates on this request? Is there any way to speed up the process please? Thanks~

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? And to provide more data samples related with data you will store to prove that you have 5 PB already. How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by simonkim0515** [comment]
Closing due to no response.
