### ISSUE TITLE
[DataCap Application] Pinnacle Cloud Network Technology Co., LTD

### ISSUE THREAD

**Issue by dos2un1x** [filecoin-project/filecoin-plus-large-datasets#944]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Pinnacle Cloud Network Technology Co., LTD
- Website / Social Media: http://www.jfyjy.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
After years of development, we have become a member of the pre-exam counseling and vocational training in China. The total number of employees is about 300, and the business covers many cities across the country, serving the national students. Since January 2021, it has successfully transformed from traditional face-to-face training to Internet training, and established an online live broadcasting platform for vocational training. At present, its standardized curriculum system has become a template in the field of vocational training. The main business involves three major areas - vocational certificate training, academic training and IT skills training. The vocational certificate training includes manpower, accounting, CPA, fund, securities, finance, teacher qualification certificate, tourist guide certificate, etc. Educational training includes self-examination, final examination, MBA; IT training includes PS/UI/UID design, 3D modeling, animation performance, etc.
```

What is the primary source of funding for this project?
```
Company 
```

What other projects/ecosystem stakeholders is this project associated with?
```
None 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Education video
```

Where was the data in this dataset sourced from?
```
Company 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1kuEHAh6E5yFMadhI0o660HmeO7ZdXC_C/view?usp=sharing
https://drive.google.com/drive/folders/1UpuZED5PLMwSMUtJQkyka-pGcRyVPul9?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes 
```

What is the expected retrieval frequency for this data?
```
3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose SPs based on geographic location and the quality of service the SPs provide
```

How will you be distributing deals across storage providers?
```
Store to multiple SPs to ensure data security
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes 
```

**Comment by dos2un1x** [comment]
Hello, may I ask how is our project going?

**Comment by raghavrmadya** [comment]
How long have you been in operation? Please provide a breakdown of the 5 PiBS, SPs you have been in touch with as well as a detailed allocation plan

**Comment by dos2un1x** [comment]
Thank you for your reply.
About a year and a half ago.
We need to store 5 copies.
The SP of the storage supplier we have contacted has them f01852677/f01852023/f01885088/f01901351/f01851482.
The data are all open learning videos of education and teaching.And that's just part of our data.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/34907247/197388211-d9ce9811-4c27-4d48-ba41-c57ea0752869.png">

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 1PB data already?
The data samples you provided also can be seen on the socail media. https://www.bilibili.com/video/BV1Nh411n7r8/
Can you explain about data source of your data?

**Comment by dos2un1x** [comment]
https://drive.google.com/drive/folders/136x2D3KkII4wz737jnQEq65VNjNSMUJe?usp=sharing
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/34907247/201528245-99cecf7c-a3a1-40c6-99dc-877545d55951.png">
We have uploaded some data samples, part of the package teaching course, we have a large number of package teaching courses, self-examination videos and open classes for students to learn, including what you have seen before.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 300TiB

**Client address**

>f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnzus7hk4pnb7najcrua3b7jo4erdowa2to5rbfcpu7qr7tskws2 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 7e88b9a0-b18e-4c80-87a0-ab326e5df1ea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnzus7hk4pnb7najcrua3b7jo4erdowa2to5rbfcpu7qr7tskws2

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaacyfzjssxjt7qmgyh3f6lu3fbbqjpyzxkpouqyap2mzrwblbhpe 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 7e88b9a0-b18e-4c80-87a0-ab326e5df1ea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaacyfzjssxjt7qmgyh3f6lu3fbbqjpyzxkpouqyap2mzrwblbhpe

**Comment by BigD-Exchange** [comment]
@dos2un1x Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by YuanHeHK** [comment]
I supported this app before, now it looks fine together and we will continue to support it

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by dos2un1x** [comment]
@Sunnyiscoming No problem for now. Thank you for your concern. We have just celebrated the New Year. Our project has been started and is progressing smoothly, and will be processed soon.

**Comment by kernelogic** [comment]
The checker bot seems inaccurate about the deals sealed. Another website shows better distribution.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/3711825/218643108-84d7db8a-0583-4282-bcb1-c29f4608e4d2.png">

**Comment by kernelogic** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/3711825/218644527-2ae197f2-ea29-49b9-b89f-2627db1cbee5.png">

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebd5wsfewscox673bzuo3d3hjhsiawyt3f6ytco4fz2uavjt5z5fk 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 6adde2ff-1f98-41df-944a-a6783213782a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebd5wsfewscox673bzuo3d3hjhsiawyt3f6ytco4fz2uavjt5z5fk

**Comment by Tom-OriginStorage** [comment]
lotus client retrieve --provider f01170282 QmTxWK5917PAJ3TD9ebrYT1CiUYhT38DCg3puigt97rYgZ aa
Recv 0 B, Paid 0 FIL, Open (New), 0s
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 2ms
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 28.072s
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 28.072s
Recv 79 B, Paid 0 FIL, BlocksReceived (Ongoing), 42.301s
Recv 1.966 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 42.302s
Recv 49.98 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 42.735s
Recv 1.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 44.352s
Recv 2.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 45.449s
Recv 3.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 46.352s
Recv 4.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 47.249s
Recv 5.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 48.299s
Recv 6.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 49.415s
Recv 7.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 50.537s
Recv 8.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 51.432s
Recv 9.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 52.512s
Recv 10.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 53.403s

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
Encapsulation at first looked all compliant I did a retrieval test and I'm willing to support it

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhkvu5oe5low6zkq5ou5hbwvr5ro4gb6liunawoaww5q6tdkpfm4 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 6adde2ff-1f98-41df-944a-a6783213782a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhkvu5oe5low6zkq5ou5hbwvr5ro4gb6liunawoaww5q6tdkpfm4

**Comment by flyworker** [comment]
[24690740.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10731241/24690740.log)
lotus client retrieve --provider f02029895 --pieceCid baga6ea4seaqd7q7sysovt6h3lnkmq4a7ddieekrefilahfls2qdsldclbjpagii QmU3LmCBWFtyrVyh13A7Re86xeHhepTuXUbTWdDyhF3oQv 20230214-050621.file >> log/24690740.log
Recv 0 B, Paid 0 FIL, Open (New), 0s
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 26ms
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 392ms
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 392ms
Recv 79 B, Paid 0 FIL, BlocksReceived (Ongoing), 555ms
Recv 2.019 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 555ms
Recv 50.03 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 827ms
Recv 1.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3.066s
Recv 2.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 7.262s
Recv 3.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 8.488s
Recv 4.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 9.761s
Recv 5.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 11.002s
Recv 6.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 13.037s
Recv 7.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 14.563s
Recv 8.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 16.114s
Recv 9.049 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 17.63s
Recv 10.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 19.119s
Recv 11.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 20.659s

Retrieval working,

**Comment by flyworker** [comment]
after , 13h1m7.568s we  Recv 37.31 GiB, Paid 0 FIL, BlockstoreFinalized (Completed)
open the data folder and unzip get the following data

![image](https://user-images.githubusercontent.com/8363795/218908747-1c45f216-dc5e-40d3-8adc-f133e29280a4.png)
![image](https://user-images.githubusercontent.com/8363795/218908841-07ee54ef-bafe-440c-a7ac-25576fb176c0.png)

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxqnpijp6unsehxe2g6oomdsnepwhopehxlevlxfzgg7xyfdykd2 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 4041e9fa-6d60-4abb-92bc-b484b25b53d8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxqnpijp6unsehxe2g6oomdsnepwhopehxlevlxfzgg7xyfdykd2

**Comment by GaryGJG** [comment]
Deal Data Replication
⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.
What about your plan to distribute the data to more SP ?

**Comment by dos2un1x** [comment]
Yes, we'll end up storing at least 5sp.

**Comment by GaryGJG** [comment]
> 

Could you share the SP id and location please ?

**Comment by dos2un1x** [comment]
Not yet.
I'm looking for a suitable SP.

**Comment by claydrone** [comment]
Nebula Block can provide an SP in 2 months if needed.

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
According to the audit standard of ND, the main data sample is complete, and the check bot displays it well, but the data backup is currently not complete, and the data backup is a continuous process, so it is understandable. In addition, we tested the retrieval of nodes, and the retrieval was successful.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceds4uguxkmdcwrwd5twyh4mrszls6wci2bqxfqjabvjdeb63vbfea 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 4041e9fa-6d60-4abb-92bc-b484b25b53d8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceds4uguxkmdcwrwd5twyh4mrszls6wci2bqxfqjabvjdeb63vbfea

**Comment by dos2un1x** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
![image](https://user-images.githubusercontent.com/43629914/221503487-29c79d0b-b825-4b17-a1e3-37e3e5e62b95.png)
![image](https://user-images.githubusercontent.com/43629914/221503518-217f98d7-4070-43a2-b2e8-7d2858390e1d.png)
I checked the data samples and checked the bot's results. Except for the problem of data backup, the rest are fine. If you can solve this problem in the next round, I will be happy to assist you.

**Comment by dos2un1x** [comment]
Hi, dear notary, after the initial use will add other nodes to balance the data.

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnnadt2uq5xwr77r3iqsmofbql5bqqjsk7zyry6cqcnpthsgtsia 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> e1c82121-fd17-4c3e-8487-252103dbd1fb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnnadt2uq5xwr77r3iqsmofbql5bqqjsk7zyry6cqcnpthsgtsia

**Comment by dos2un1x** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaayhxd5ztdkzeatbwgwedsbrwmwsgu6sqximy32llhrgyy4cwqvs 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 639a8bf8-003b-4857-8a74-c2d7d8e1bcd2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaayhxd5ztdkzeatbwgwedsbrwmwsgu6sqximy32llhrgyy4cwqvs

**Comment by newwebgroup** [comment]
Check the CID Checker report, it looks normal.
Reviewing and checking the history of Github, KYB verification is complete and has been verified and supported by multiple notaries.

I'm trying to do a retrieval test on some SPs

lotus client retrieve --provider f02029895 QmeWZbVhjRMqV9QQPdCtTvMANkkVMhDCXDXKRtbmJjufqM LDN-944-1
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/100118145/222622761-751fe7ba-2455-49c6-9df5-411bd60917ea.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqoclkkzz25ovsehu76rrsnmpclauvxhjpctq22x3hk4rkevhkd6 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 639a8bf8-003b-4857-8a74-c2d7d8e1bcd2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqoclkkzz25ovsehu76rrsnmpclauvxhjpctq22x3hk4rkevhkd6

**Comment by 1ane-1** [comment]
<img width="783" alt="c36e851781088cde5786459ff9a1950" src="https://user-images.githubusercontent.com/91301211/222642791-ca9f103e-0510-4867-8bc3-1e62dafae4e5.png">
I will support it!

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5tjietqkjulzzgfqya2r6vqhbmxmtzpouyjxrk62cyg2qir5ksc 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 475.76TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> db5a930c-c360-42a3-90da-2d1cec906260
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5tjietqkjulzzgfqya2r6vqhbmxmtzpouyjxrk62cyg2qir5ksc

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbfi5qzn7w26wbfrggfw5hgqblny2mdrvqqgypmkbazp2ztxeuzo 
#### Address 
> f12jqp3z3kh47xmbzre4vauxq532t6n5oceexac4a
#### Datacap Allocated
> 475.76TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> db5a930c-c360-42a3-90da-2d1cec906260
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbfi5qzn7w26wbfrggfw5hgqblny2mdrvqqgypmkbazp2ztxeuzo
