### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by Davekorn** [filecoin-project/filecoin-plus-large-datasets#950]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: McKorn
- Website / Social Media: www.mckorn.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500 TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50 TiB
- On-chain address for first allocation: f1an2kap2rdjfifryjlfznw75z6gy45nbprzknp2i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We have been servicing and developing in the system integration and system management areas for the last 20 years.
Our most clients are the governments and bank companies.
The governments and the companies have to back up their records, not only online records but also the offline documents, such as papers.
Every document, paper, is to be converted into an image, then stored.
So it is called "record management".
We will use this storage service for backup.
```

What is the primary source of funding for this project?
```
Our clients will be the funding source, the governments, and the bank companies.
```

What other projects/ecosystem stakeholders is this project associated with?
```
As mentioned above, our clients, governments, and bank companies are associated with this project.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The majority of data being stored will be images and other media data.
```

Where was the data in this dataset sourced from?
```
The data centers of the governments and the bank companies that we manage.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
No, the data from the governments and bank companies is located in their internal system. So it seems to be difficult to be shared.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
It is aming to back up, therefore retrieval might not be often and on a regular basis.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1100 days(about 3 years)
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Seoul of South Korea in Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Hard drivers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
For convenience, the nearest storage providers.
```

How will you be distributing deals across storage providers?
```
Each deal is to one provider, based on my clients' location.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by raghavrmadya** [comment]
No samples were provided but the client claims the data set to be public. Unable to proceed at this point
