### ISSUE TITLE
[DataCap Application] <Duo Mu Media (Shenzhen) LTD> 

### ISSUE THREAD

**Issue by Screengrabbingmedia** [filecoin-project/filecoin-plus-large-datasets#951]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Duo Mu Media (Shenzhen) LTD
- Website / Social Media:http://www.slidesign.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):300TiB
- On-chain address for first allocation:f1o3c4uaoioq6xwzqrvdw2juzps3eyujbtys2mvpq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded at the end of 2016, the company has become a well-known PPT customization team in China. As you can see, we specialize in presentation level slides, corporate promotions and corporate presentation slides.
```

What is the primary source of funding for this project?
```
The business income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly advertising videos, pictures, music, documents and other materials.These materials are the materials for making advertising PPT and brand picture album for our clients.
```

Where was the data in this dataset sourced from?
```
Our company produces PPT and brand brochures for our clients.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1E7DVLWcd4kicuDb5LhQq__dJxW9Y_Kne?usp=sharing
```
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Five or more times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I'd like to store it permanently, because it's very important information for our company.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
I hope it's in Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have online and offline data transfer processes, depending on the choice of storage provider.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select storage provider with good reputation, trustworthiness, and experience in verifying data to conduct transactions.
```

How will you be distributing deals across storage providers?
```
Average distribution.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Sunnyiscoming** [comment]
https://drive.google.com/drive/folders/1E7DVLWcd4kicuDb5LhQq__dJxW9Y_Kne?usp=sharing
Data samples you provided can not be found. Please check it.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 300TiB

**Client address**

>f1o3c4uaoioq6xwzqrvdw2juzps3eyujbtys2mvpq

**Comment by newwebgroup** [comment]
Data set samples are too few, please provide more data samples

**Comment by Screengrabbingmedia** [comment]
Sorry for the late reply @newwebgroup 

链接: https://pan.baidu.com/s/1UOmBXu_uhhlP23WdwPf1LA?pwd=urdz 提取码: urdz 
--来自百度网盘超级会员v7的分享

**Comment by newwebgroup** [comment]
Hey Client，
About KYC&KYB
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

The content should include the number of the LDN application.
2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

3.How large is your existing dataset? How much is the data growth per month?

**Comment by Screengrabbingmedia** [comment]
Hi , @newwebgroup 

<img width="486" alt="image" src="https://user-images.githubusercontent.com/112838227/209963612-44307c20-a374-4c24-8596-f1bd87215c32.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/112838227/209965131-fbaa8be0-8e00-4b02-bb94-30beeb0a7cff.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebu6pxyabcnzxf4gbj35kqvtt2yuvgar6hcmfhrzpoamdkg3oxg3e 
#### Address 
> f1o3c4uaoioq6xwzqrvdw2juzps3eyujbtys2mvpq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> cfe3eff5-654f-4ec9-a22c-b9dafa671873
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebu6pxyabcnzxf4gbj35kqvtt2yuvgar6hcmfhrzpoamdkg3oxg3e

**Comment by NDLABS-OFFICE** [comment]
Checked the record, willing to support. will continue to pay attention.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgaq3oijvdvgymsn5f4cqarwawzyredvlji2ncbuycnpa2hcv5ee 
#### Address 
> f1o3c4uaoioq6xwzqrvdw2juzps3eyujbtys2mvpq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> cfe3eff5-654f-4ec9-a22c-b9dafa671873
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgaq3oijvdvgymsn5f4cqarwawzyredvlji2ncbuycnpa2hcv5ee

**Comment by BDEio** [comment]
@Screengrabbingmedia  Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by cryptowhizzard** [comment]
Hello,

This application has CID sharing with https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/807

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

**Notary's -> We can't continue signing on this application and any subsequent ones.**

In [LINK](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/807) this application has 100% selfdealing. The same goes for this application , the same miners. Also there is CID sharing taking please.
