### ISSUE TITLE
[DataCap Application] Brazil Data Cube

### ISSUE THREAD

**Issue by Pierofree** [filecoin-project/filecoin-plus-large-datasets#952]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Brazil Data Cube---Piero
- Website / Social Media: https://registry.opendata.aws/brazil-data-cubes/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated in hackathon projects and got a very good ranking.
```

What is the primary source of funding for this project?
```
By myself.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Earth observation (EO) data cubes produced from analysis-ready data (ARD) of CBERS-4, Sentinel-2 A/B and Landsat-8 satellite images for Brazil. The datacubes are regular in time and use a hierarchical tiling system. Further details are described in https://www.mdpi.com/2072-4292/12/24/4033.

I'd like to store 10 copies.
```

Where was the data in this dataset sourced from?
```
The EO data cubes are produced from free and open images of CBERS-4, Landsat-8 and Sentinel-2 satellites.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/brazil-data-cubes/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Minimally, at least every three months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline data transfer. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will send deals to those storage providers who have ability to support retrieval and stable seal.
```

How will you be distributing deals across storage providers?
```
I will distribute under 25% deals to every storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by raghavrmadya** [comment]
<img width="500" alt="Screen Shot 2022-10-23 at 6 43 25 AM" src="https://user-images.githubusercontent.com/91579519/197375918-4eb56303-103e-4c33-9b9c-4a451dedd9df.png">
 Please share an email screenshot of your communication with the data manager clarifying you can store a copy of this dataset

**Comment by Pierofree** [comment]
@raghavrmadya Hey, this is a public dataset on AWS, so I can use it and store it.
![6](https://user-images.githubusercontent.com/107857921/197510840-aefaa61a-ece2-4e10-a85d-2cdbedcdea06.png)

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Pierofree** [comment]
@Sunnyiscoming OK! Now the sps I selected to work with are: f01040469, f0838873, f064218, f0142637, f01149094. I will be looking for more sps to work with in the future to ensure distributed storage.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy

**Comment by Sunnyiscoming** [comment]
Hey @Pierofree , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by swatchliu** [comment]
willing to support at the 1st round.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlumglqad7byswu4v5bf6kzbu7sjg63gsbsi5l5fclsalp374nms 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 16c17039-3d12-4861-954c-9ba14c19fcd2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlumglqad7byswu4v5bf6kzbu7sjg63gsbsi5l5fclsalp374nms

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceas7uor7f3ybqomq3k2vcvy2346rcxv2v2eaxskzf5hsiyuqhvch4 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 16c17039-3d12-4861-954c-9ba14c19fcd2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceas7uor7f3ybqomq3k2vcvy2346rcxv2v2eaxskzf5hsiyuqhvch4

**Comment by BobbyChoii** [comment]
willing to give my sign and help to onboard this application.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceba5pp46fkzlp7ghdqiwm7yzx6nawjhlp6jrlotu5l2vudvm7ymse 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceba5pp46fkzlp7ghdqiwm7yzx6nawjhlp6jrlotu5l2vudvm7ymse

**Comment by TakiChain** [comment]
The client contacted me by slack and shared the storage plan. I'd like to see more public data joining the network!

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealt5gwahqe5wzjy26cdmcoff2nm3g7c2lm4n2typurkojusmmvri 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 4a2e3764-2bcc-4eea-a3d4-8086011d3ff8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealt5gwahqe5wzjy26cdmcoff2nm3g7c2lm4n2typurkojusmmvri

**Comment by Aifabot-Cloud** [comment]
The client followed the allocation plan as planned, good report is all dimensions. Keep it up!

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb36l6ncwiihb75y5br3oe6o7qji7lpxigilhhfxtyc5mejlipdxi 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 4a2e3764-2bcc-4eea-a3d4-8086011d3ff8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb36l6ncwiihb75y5br3oe6o7qji7lpxigilhhfxtyc5mejlipdxi

**Comment by Casey-PG** [comment]
The client followed the allocation plan. Willing to help onboard this application again.

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatgiyojb6y7jqo675o5cjy7mmqwzh4ghql64ac7ecjop7d7ycwac 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 4a7693f2-1b3b-4fd3-8312-93d813b7dbf2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatgiyojb6y7jqo675o5cjy7mmqwzh4ghql64ac7ecjop7d7ycwac

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaox2m5vjmnj4ii37b4nj3dbekjex6tlm6uh6wscq4bgxdlb2kpqa 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 4a7693f2-1b3b-4fd3-8312-93d813b7dbf2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaox2m5vjmnj4ii37b4nj3dbekjex6tlm6uh6wscq4bgxdlb2kpqa

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
The report LGTM,  will to support this round.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczccl77ljxk2u6hub2pyucxezuapx52yro6aziyze75hdvpo6sm2 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 964c4cea-0e0e-414e-961e-c869bcdf9a96
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczccl77ljxk2u6hub2pyucxezuapx52yro6aziyze75hdvpo6sm2

**Comment by Wengeding** [comment]
Good summary report and ongoing communication from the applicant. There're lots of inputs from many notaries and reasonable responses from the applicant. 

DD has done with the applicant this afternoon.  willing to give my sign and help to onboard this application.

**Comment by Wengeding** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3uf5ao4uuudkn4rw66kaleeu6lq3ftvvmzc62v6rieuhxsihbte 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 964c4cea-0e0e-414e-961e-c869bcdf9a96
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3uf5ao4uuudkn4rw66kaleeu6lq3ftvvmzc62v6rieuhxsihbte

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceca5dfrudhsexuzwuc4alzehtwplei2gsw37kkgv3q5jnznr2bhj6 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 86.55TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 58130a06-28c4-4873-8e91-00973940c9c1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceca5dfrudhsexuzwuc4alzehtwplei2gsw37kkgv3q5jnznr2bhj6

**Comment by Bennyyangpu** [comment]
f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy

**Comment by Bennyyangpu** [comment]
checker:manualTrigger

**Comment by Bennyyangpu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaa6tmgrbxlwmksdzytyinxzi2x57omswil3huydafldqizlklzwa 
#### Address 
> f13dxmfvac3yciokh7eqy77u4wogtdga5mn7ccpsy
#### Datacap Allocated
> 86.55TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 58130a06-28c4-4873-8e91-00973940c9c1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaa6tmgrbxlwmksdzytyinxzi2x57omswil3huydafldqizlklzwa

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
It seems that your data is too centralized.Are there plans to distribute to more storage providers?

**Comment by Pierofree** [comment]
@zcfil Yes! We are checking with more SPs. We will improve it. Thank you for your reminder!

**Comment by zcfil** [comment]
If found, please list it out

**Comment by Pierofree** [comment]
Yes

**Comment by Pierofree** [comment]
Yes

**Comment by Pierofree** [comment]
Yes please!

**Comment by Pierofree** [comment]
Yes please!

**Comment by Sunnyiscoming** [comment]
Close for total datacap reached.
