### ISSUE TITLE
[DataCap Application] <gientech> - <AI call>

### ISSUE THREAD

**Issue by gien1hu2** [filecoin-project/filecoin-plus-large-datasets#956]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: gientech
- Website / Social Media: https://www.gientech.com/product/651.html
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Intelligent customer service field: pre sales shopping guide, after-sales customer service, marketing assistant, member service, agent assistant, intelligent training, intelligent quality inspection, etc
Smart office: HR Assistant for digital employees, intelligent conference assistant, etc
Aiot field: smart home appliances, smart service robots, etc
Industry scenario
Bank: Business Assistant Customer Service Assistant Robot
Insurance: insurance product knowledge consultation claim settlement consultation insurance fund inquiry
Medical care: medical care knowledge consultation hospital satisfaction return visit
Government affairs: Policy clause consultation business pre handling
FMCG retail: pre sales shopping guide, marketing assistant, member service agent, after-sales customer service, intelligent research officer
```

What is the primary source of funding for this project?
```
We charge a customer service fee
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Business data, artificial intelligence voice training model, artificial intelligence training library, recording persistent data, video training materials, voice training materials, etc
```

Where was the data in this dataset sourced from?
```
Our own
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/15QRN_soWDPDd1Agts4U59w
Code: kaf8
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
530 days or more.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China、Hong Kong or Singapore .
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline or Online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will be looking for a service provider in Asia to save 5 copies of backup data for security, And we have found 4 SPS
```

How will you be distributing deals across storage providers?
```
Each storage provider keeps one copy.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. Hope it can be passed as soon as possible. Thank you very much.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?
Can you explain your data composition? And to provide more data samples related with data you will store to prove that you have 5 PB already. How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by gien1hu2** [comment]
I am the initiator of this project

Now we have 5TiB's real AI call record data. More AI training videos are about 780TiB (including 190T for customer service calls, 310T for after-sales treatment, and 280T for return visits). We will obtain about 30TiB's data from the Internet every month.
Because our storage space is limited, only 820TiB.
Now we want to store the data to the IPFS network, so that we can sample and download the training results of the data detection robot every 3-5 months.
In this way, our storage server can also delete historical data to process updated training materials
We will store 5 copies of data according to the rules

Now we have contacted some SPs who are willing to help us store
f01852023,f01901379,f01412203,f01922865,f01859603,f01917009,f01896030

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebejoepotqnxi47xv2zvkj724k333ontzjvjgbjxo4grtqdzfqixg 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 354c2c0b-37ac-4463-8bd9-c2382749d9a0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebejoepotqnxi47xv2zvkj724k333ontzjvjgbjxo4grtqdzfqixg

**Comment by newwebgroup** [comment]
Could you send an email to filplus-app-review@fil.org

**Comment by gien1hu2** [comment]
![image](https://user-images.githubusercontent.com/113242122/203898605-5f58765c-b0cd-47f2-a6d0-711f221f4533.png)

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecv5zai5npopo7ceems64tyoopxkrwuc3kzxsjbahvguvw2ldo6g4 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 354c2c0b-37ac-4463-8bd9-c2382749d9a0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecv5zai5npopo7ceems64tyoopxkrwuc3kzxsjbahvguvw2ldo6g4

**Comment by BigD-Exchange** [comment]
@gien1hu2 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealqd2y3e6ag2smc37dpyomwenwcidksvi7labhzbxbuvqcs4uaw2 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 354c2c0b-37ac-4463-8bd9-c2382749d9a0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealqd2y3e6ag2smc37dpyomwenwcidksvi7labhzbxbuvqcs4uaw2

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzqva6tjlbldd6uhbhlnz4bizocz2vvgk3dsblksdmn26s6e3xou 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 354c2c0b-37ac-4463-8bd9-c2382749d9a0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzqva6tjlbldd6uhbhlnz4bizocz2vvgk3dsblksdmn26s6e3xou

**Comment by YuanHeHK** [comment]
I supported this app before, now it looks fine together and we will continue to support it

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacean2xmjrdyrffeorvpzqfz2nqacagznrnoymxgaih3rklonpjt4ws 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 3651075e-c32c-4239-978b-56428cc2badb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacean2xmjrdyrffeorvpzqfz2nqacagznrnoymxgaih3rklonpjt4ws

**Comment by Joss-Hua** [comment]
Based on the current review, I can sign for the first time.

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqi2cpxke5grhasgwcyip3q3vsaljraoydefpetu4idg2yxz4xqu 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 3651075e-c32c-4239-978b-56428cc2badb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqi2cpxke5grhasgwcyip3q3vsaljraoydefpetu4idg2yxz4xqu

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzrt2sxygcivexu3h6tfpu2qh7a76rzkj5mipobbvbw452otskga 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> bfae2bd0-1835-4138-9393-73a438414e41
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzrt2sxygcivexu3h6tfpu2qh7a76rzkj5mipobbvbw452otskga

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecukllsdoeljqpwgvtqeqdnvz2qqp4giddpj3oa552mfybwawtd6m 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> bfae2bd0-1835-4138-9393-73a438414e41
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecukllsdoeljqpwgvtqeqdnvz2qqp4giddpj3oa552mfybwawtd6m

**Comment by Zhangcffff** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtrnfywcxilfmwigvcfq4xzn2vnssqrokihz3hbqt6dvx3vlcylg 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> 3f69dea1-b3ce-4923-bd16-915c53576d06
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtrnfywcxilfmwigvcfq4xzn2vnssqrokihz3hbqt6dvx3vlcylg

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxm6vjymnfttp6etcxnsyjifjjalhikho7d56kxmtmtqti2vxlg6 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 3f69dea1-b3ce-4923-bd16-915c53576d06
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxm6vjymnfttp6etcxnsyjifjjalhikho7d56kxmtmtqti2vxlg6

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7rmiz42uqptbnw2sawvcwybxeiapaokxpwkia7g4gbagn5j2ady 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 035d580c-a1d1-450b-be76-ce63f5048d8e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7rmiz42uqptbnw2sawvcwybxeiapaokxpwkia7g4gbagn5j2ady

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7k3q3vei7cdfe5tb2m5vahjon5fpwellmaokh2zekf7apucck2k 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 035d580c-a1d1-450b-be76-ce63f5048d8e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7k3q3vei7cdfe5tb2m5vahjon5fpwellmaokh2zekf7apucck2k

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `gientech`
 - Client: `f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |          87.94 TiB |     22.12% |   87.88 TiB |           0.07% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |          82.38 TiB |     20.72% |   82.31 TiB |           0.08% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |          80.31 TiB |     20.21% |   80.25 TiB |           0.08% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |          78.19 TiB |     19.67% |   78.16 TiB |           0.04% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |          68.66 TiB |     17.27% |   68.59 TiB |           0.09% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/956/1671098127451.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         1.56 TiB |         1.56 TiB |                   1 |           0.39% |
|         5.31 TiB |        10.63 TiB |                   2 |           2.67% |
|        19.19 TiB |        57.56 TiB |                   3 |          14.48% |
|        40.53 TiB |       162.13 TiB |                   4 |          40.79% |
|        33.06 TiB |       165.59 TiB |                   5 |          41.66% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/956/1671098128029.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5pkbkwcxzp4emm72q52rzq4lormcsnm5j7s4gjhocmfzmo6vdka 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 73fe01ec-e20a-4cfa-9331-82f6c4feac51
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5pkbkwcxzp4emm72q52rzq4lormcsnm5j7s4gjhocmfzmo6vdka

**Comment by kernelogic** [comment]
CID report looks great, willing to support

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebltbyec2selfof2vkyorncs6ekbcasbsmtwrm5taubgwu3swsxow 
#### Address 
> f1iqzddxjrbekqta5tcxlozse243iovr4f43aobxa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 73fe01ec-e20a-4cfa-9331-82f6c4feac51
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebltbyec2selfof2vkyorncs6ekbcasbsmtwrm5taubgwu3swsxow

**Comment by cryptowhizzard** [comment]
Hello,

Retrieval works on some of the nodes.

I have been looking @ f01973010.csv-f0694396-baga6ea4seaqkloqjjw5nkhz5azw4g4bz5ylcshoh5ewbx6ex4tconddpmyttcda.car

<img width="569" alt="Scherm­afbeelding 2023-01-15 om 20 28 55" src="https://user-images.githubusercontent.com/36404435/212562807-015ecc3a-94f9-41cf-8cce-5221049b6803.png">

Can you tell me what is in this files and what i am looking at?
