### ISSUE TITLE
[DataCap Application] <waysas.inc> - <Antique Rescue Project>

### ISSUE THREAD

**Issue by asdfec** [filecoin-project/filecoin-plus-large-datasets#957]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: waysas.inc
- Website / Social Media:waysas.co.jp
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ofzjga3jywceqelxjj2wpvhg6ux6r7czqlftu7a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2009, WAYSAS is a company dedicated to providing office equipment and related services to its partners.
This includes, but is not limited to, professional printing equipment rental and HD printing services.
```

What is the primary source of funding for this project?
```
Company Revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects/ecosystems
```

## Use-case details

Describe the data being stored onto Filecoin
```
We are prepared to use high-resolution photographs of ancient Chinese documents or related materials for this project. We believe that this historical preservation activity will make this project more valuable.
```

Where was the data in this dataset sourced from?
```
Part of it is from internal sources.
There is also a part from open source data.
like:https://new.shuge.org/
http://www.guoxuedashi.net/
https://www.loc.gov/collections/world-digital-library/about-this-collection/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://new.shuge.org/view/kongzi_sheng_ji_tu/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
At least once a day
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China，Japan
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Only through online transmission。
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a storage provider with excellent technical capabilities and an understanding of the value of the project.
```

How will you be distributing deals across storage providers?
```
The shares are distributed evenly and then adjusted according to actual performance.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have enough funds.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ofzjga3jywceqelxjj2wpvhg6ux6r7czqlftu7a

**Comment by psh0691** [comment]
Can I ask you a question?

Why does waysas, a Japanese professional printing equipment rental and HD printing service company, provide samples of online public library data in China?

**Comment by asdfec** [comment]
> 

Our company provides printing and related services, which naturally includes copying. The cultural exchange between Japan and China dates back as far as 202 B.C. and reached its peak in 618 A.D. and continues to this day. As a result, a large number of ancient Chinese books have been transmitted to Japan and have been preserved to this day. Due to war and political reasons, the ancient books in China have not been well preserved. Therefore, many historical researchers came to Japan to copy or take photos of these ancient books and bring them back to China. Our company has a good relationship with these historical researchers.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafeiwd4t2wgno3i5g6t474i45rhrkikyga2r3wvdmvzwtquhbwte 
#### Address 
> f1ofzjga3jywceqelxjj2wpvhg6ux6r7czqlftu7a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafeiwd4t2wgno3i5g6t474i45rhrkikyga2r3wvdmvzwtquhbwte

**Comment by asdfec** [comment]
![微信图片_20221027231056](https://user-images.githubusercontent.com/15544607/198309873-7a387e2a-14c7-4e8b-8301-479f609959c7.jpg)
Excuse me.
We got an error when I want to use this address.
What should I do next?

**Comment by psh0691** [comment]
You must be signed by another notary to receive a complete data cap.
One is "Request Proposed" and the other is "Request Approved."

To check the DataCap:
1. lotus CMD
lotus filplus check-client-datacap <address>
2. glif check
https://verify.glif.io/

**Comment by Alex11801** [comment]
> > 
> 
> Our company provides printing and related services, which naturally includes copying. The cultural exchange between Japan and China dates back as far as 202 B.C. and reached its peak in 618 A.D. and continues to this day. As a result, a large number of ancient Chinese books have been transmitted to Japan and have been preserved to this day. Due to war and political reasons, the ancient books in China have not been well preserved. Therefore, many historical researchers came to Japan to copy or take photos of these ancient books and bring them back to China. Our company has a good relationship with these historical researchers.

So what is your relationship with the data sample provider(new.shuge.org)? Just to ensure that there's no copyright problem.

**Comment by asdfec** [comment]
The copyright of all the ancient books we have included in this collection meet the requirements of the Berne Convention for public dissemination. Meanwhile, Shuge.org welcomes blockchain storage, and they have already entered into a partnership with Resilio Sync. If the project is approved, we will officially start the cooperation.

**Comment by asdfec** [comment]
hello @Alex11801 
May I get some feedbacks so that I could know what’s missing in my applications? Thanks.

**Comment by Alex11801** [comment]
> The copyright of all the ancient books we have included in this collection meet the requirements of the Berne Convention for public dissemination. Meanwhile, Shuge.org welcomes blockchain storage, and they have already entered into a partnership with Resilio Sync. If the project is approved, we will officially start the cooperation.

Sure. That makes sense.

**Comment by Alex11801** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecx6wsrcxrbo7duzx6ou6xihwwntfdpbigjmlp3zrvlk23l3txxyu 
#### Address 
> f1ofzjga3jywceqelxjj2wpvhg6ux6r7czqlftu7a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecx6wsrcxrbo7duzx6ou6xihwwntfdpbigjmlp3zrvlk23l3txxyu

**Comment by BigD-Exchange** [comment]
@asdfec Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `waysas.inc`
 - Client: `f1ofzjga3jywceqelxjj2wpvhg6ux6r7czqlftu7a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f0166896](https://filfox.info/en/address/f0166896) has sealed 74.55% of total datacap.

⚠️ 47.39% of total deal sealed by [f0166896](https://filfox.info/en/address/f0166896) are duplicate data.

⚠️ 20.30% of total deal sealed by [f01975299](https://filfox.info/en/address/f01975299) are duplicate data.

⚠️ [f01975299](https://filfox.info/en/address/f01975299) has unknown IP location.

⚠️ [f060693](https://filfox.info/en/address/f060693) has unknown IP location.

| Provider                                                    |                Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0166896](https://filfox.info/en/address/f0166896)         | Jinrongjie, Beijing, CN |          36.67 TiB |     74.55% |   19.29 TiB |          47.39% |
| [f01975299](https://filfox.info/en/address/f01975299)`new`  |                 Unknown |          11.39 TiB |     23.16% |    9.08 TiB |          20.30% |
| [f060693](https://filfox.info/en/address/f060693)`new`      |                 Unknown |           1.13 TiB |      2.29% |    1.09 TiB |           2.78% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/957/1671098133050.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        27.31 TiB |        46.96 TiB |                   1 |          95.48% |
|         1.08 TiB |         2.22 TiB |                   2 |           4.52% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/957/1671098133680.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by asdfec** [comment]
@Alex11801 @psh0691 
First of all, thank you all for your support, our project is going very well. But we also encountered a trouble. It is that we are running out of space.
We still need 1P to store the next data, how should I do?

**Comment by raghavrmadya** [comment]
Hi, this is RG and I lead Trust and Transparency for Filecoin Plus is the CID checker bot has flagged your application due to the irregular deal-making for the first tranche. Now there might be a good explanation that you might have for this. As the next steps, I'd recommend that you respond to what the CID checker bot has identified in this thread and then post an update in the fil-app-review channel
