### ISSUE TITLE
[DataCap Application] Sinso

### ISSUE THREAD

**Issue by Sinsoteam** [filecoin-project/filecoin-plus-large-datasets#961]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Sinso
- Website / Social Media: http://www.sinso.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
**Organization**
The Sinso team was established in October 2020. As the leading medical imaging SaaS cloud service provider, the core members have served more than 500 medical institutions and more than 80,000 medical imaging doctors.
Sinso builds the Sinso DAC ecology based on WEB3 technology, and jointly promotes the human society to enter the era of decentralized medical care.
**Our project**
Our program also participated in the Filecoin Frontier Accelerator.
Sinso, as a medical image data aggregator for telemedicine and AI diagnosis, provides a basis for remote diagnosis services to solve the problem of authenticity of patient data. Through a customized NFT release template for medical data, users actively participate in data confirmation and help users strengthen data collection And the conversion process of data assets to strengthen the flow of medical data. Therefore, Sinso also provides the issuance of NFT-like virtual assets to further promote the full range of doctors towards free practice.
Users collect data through Sinso Getway, cast health/medical-related data into NFTs in Sinso DAPP, and trade on Sinso Doctors Network to realize the value transfer of medical data. Sinso is based on WEB3 technology and Sinso DAC ecology to jointly create and promote human society into the era of decentralized medical care.
We also achieved a good ranking in the acceleration camp.
The following links are about our projects:
https://www.bilibili.com/video/BV1PV411J7ma/
```

What is the primary source of funding for this project?
```
A: At present, the project investment mainly comes from filecoin's ecological investment, for example: whylab investment fund.
```

What other projects/ecosystem stakeholders is this project associated with?
```
A: IPFS/filecoin、Polkadot 、Ethereum
```

## Use-case details

Describe the data being stored onto Filecoin
```
A: Mainly medical record data, XML and medical image DICOM3.0 files
```

Where was the data in this dataset sourced from?
```
A: Uploaded from patients, doctors and hospitals
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
A: Please refer attachment for detail.
https://drive.google.com/file/d/1JTFp0BYAMygmRHHckv3cBFaS9UonRMIF/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, confirm. (Our data SDM-static data masking & DDM-dynamic data masking)
```

What is the expected retrieval frequency for this data?
```
A: At present, the retrieval frequency in one month is relatively high. Over three months, the retrieval probability will be reduced by 80%
```

For how long do you plan to keep this dataset stored on Filecoin?
```
A: Permanent storage as a patient's long-term personal health asset
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly China or other countries in Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will transmit the data to the miners both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The main factors we considered are the following:
1.Location (Near China)
2.Possess of experience in dealing with verified data.
3.Possess of more than 10 PiB Total Raw Power
```

How will you be distributing deals across storage providers?
```
We will follow the rules for large-datasets, and we will ensure fair distribution through limiting the amount of deals send to
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by UnionLabs2020** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?

**Comment by Sinsoteam** [comment]
![mmexpor](https://user-images.githubusercontent.com/108266562/197753156-8578c161-aa8c-4bc1-92c7-971c5d203eb3.png)
Yes, here's email.
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity?

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sinsoteam** [comment]
@Sunnyiscoming I am the employee in charge of requesting storage capacity in our company, and we have finished KYC. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/961#issuecomment-1290346955
We are ready for f0108979, f01210794, f0524489, then we'll contact more sp for the deal after we get first round datacap. Thank you for your questions.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwwnccnz2xuqj6fahfeltlbpbkmfnwed3py24vhii25yp6b6irpi 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 2a7f3bf1-8385-4b7e-912c-727feb7e0715
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwwnccnz2xuqj6fahfeltlbpbkmfnwed3py24vhii25yp6b6irpi

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccfxqlojionbhsal3b2d3vdonohnmyjciwa73fztlkvseua7amug 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 2a7f3bf1-8385-4b7e-912c-727feb7e0715
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccfxqlojionbhsal3b2d3vdonohnmyjciwa73fztlkvseua7amug

**Comment by BDE-io** [comment]
@Sinsoteam Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Sinso`
 - Client: `f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01735897](https://filfox.info/en/address/f01735897) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01735897](https://filfox.info/en/address/f01735897)`new`  | Hong Kong, Central and Western, HK |          34.47 TiB |    100.00% |   34.47 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/961/1671098155057.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        34.47 TiB |        34.47 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/961/1671098155808.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2mjckew2pdfc3b7h7q2yw6naonkkkpomxnpt6wwzyklwhfknlcu 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 8b4a7ecf-a30a-451d-901b-553939f20f3e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2mjckew2pdfc3b7h7q2yw6naonkkkpomxnpt6wwzyklwhfknlcu

**Comment by Sinsoteam** [comment]
@herrehesse We just got 50 TiB datacap at first round. Since this is at the early stage of allocation and each SP has different onboarding speed, this use case should consider as normal and reasonable. We plan to send 300T data to this SP.

**Comment by cryptowhizzard** [comment]
Can you provide us with a plan what you are going to store and where?

A list of CID's to check what you have build on carfiles would be very helpfull.

**Comment by 1475Notary** [comment]
> @herrehesse We just got 50 TiB datacap at first round. Since this is at the early stage of allocation and each SP has different onboarding speed, this use case should consider as normal and reasonable. We plan to send 300T data to this SP.
> 
> @PluskitOfficial Thanks for your approval!

That's OK, will support!

**Comment by lvschouwen** [comment]
@Sinsoteam
Good to see that you are planning on upholding the rules of the FIL+ program and good to see that 2 notaries already signed your next datacap request.

Can you share with the community which SP(s) are you planning to seal next (Miner ID would be highly appreciated)?
Any insights in your plans moving forward would be highly appreciated!

**Comment by lvschouwen** [comment]
> @Sunnyiscoming I am the employee in charge of requesting storage capacity in our company, and we have finished KYC. [#961 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/961#issuecomment-1290346955) We are ready for f0108979, f01210794, f0524489, then we'll contact more sp for the deal after we get first round datacap. Thank you for your questions.

Follow up questions;
Non of the 3 miners mentioned here has sealed the data. It has been sealed by [f01735897](https://filfox.info/en/address/f01735897)

1 of the 3 miners mentioned in your application is not reachable.
`f01210794 -> {12D3KooWKoB8QKVmAv8f2PP2H3LkoxrBaAjRGaUF2SmkBTj3RJAv: []}`

The other 2 (f0108979 & f0524489) are both behind Korea Telekom, and the WHOIS points them both Korea.

Please elaborate on your plans moving forward with this request.

**Comment by Sinsoteam** [comment]
We used to communicate with these sps and planned to cooperate with them. For some reasons, we didn't reach cooperation with these 3 sps before sealing. And we changed sps in the end.

**Comment by cryptowhizzard** [comment]
HI @Sinsoteam 

It seems that the data you are storing is not retrievable.

>>
./f01919550.sh 
root@proposals:~/Dropbox/download.sh.finished# Error: retrieval query for miner f02025503 failed: failed to dial 12D3KooWPjFeqSQEe8yXoko9vCwoxjz769iJoaauc6bkDp7ype9y:
  * [/ip4/129.226.200.76/tcp/38001] failed to negotiate security protocol: read tcp4 212.6.53.183:39447->129.226.200.76:38001: read: connection reset by peer
  *

Can you contact your SP's and have this fixed please? It is against FIL+ rules and guidelines.

**Comment by Aifabot-Cloud** [comment]
checker:manualTrigger

**Comment by Aifabot-Cloud** [comment]
Based on the datacap and cid checks, the application meets the expected community requirements. @Sinsoteam  I hope you can reach the decentralization goal as soon as possible. If you have trouble finding sp, try slack channel such as fil-deal-market or filmine platform.

**Comment by Sinsoteam** [comment]
We will find new sps to work with who match the demand as soon. Thanks for your attention!

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazw42xgrd5zo3zlpzjehu44d3o2sqy4oh3ik6mddgzi35a74csoe 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 8f54c09e-df18-403c-bbbd-773ae5d2b926
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazw42xgrd5zo3zlpzjehu44d3o2sqy4oh3ik6mddgzi35a74csoe

**Comment by Suyanj** [comment]
The client explained through slack with us that the different onboarding speed caused not enough sp dispersed situation. They promised to improve progressively in the next few rounds.

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamww3jrhibwgpqybnzxaopghhlp5f6bbmf6fohwiubqu2pa2zlew 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 8f54c09e-df18-403c-bbbd-773ae5d2b926
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamww3jrhibwgpqybnzxaopghhlp5f6bbmf6fohwiubqu2pa2zlew

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaprhcylazo7fqjulksd3nwtgdqd5hmf6lx3fvzz42mkx3ypo4fn2 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> f7003394-a9e0-453c-8ce2-a12b7f2a5e25
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaprhcylazo7fqjulksd3nwtgdqd5hmf6lx3fvzz42mkx3ypo4fn2

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3hc4rpr2qcnqlvxon4rxalnkmqorxlsmtsi242etnylkbhyqoz6 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> f7003394-a9e0-453c-8ce2-a12b7f2a5e25
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3hc4rpr2qcnqlvxon4rxalnkmqorxlsmtsi242etnylkbhyqoz6

**Comment by BobbyChoii** [comment]
The client followed the allocation he disclosed before and the datacap usageis in compliance with regulations.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecu4nmirigyc7b4rtre36pzb6hugze6easogdmliqed2kenjv7xmw 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 3dee588e-8f86-4a8b-9905-0dde2c5eeccb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecu4nmirigyc7b4rtre36pzb6hugze6easogdmliqed2kenjv7xmw

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasc4xmkqargodt6grjp2f44h2zcg5mspatwjb4arckayiubikzjo 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 3dee588e-8f86-4a8b-9905-0dde2c5eeccb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasc4xmkqargodt6grjp2f44h2zcg5mspatwjb4arckayiubikzjo

**Comment by AthSmith** [comment]
Necessary to pay attention to the success rate of the retrieval, although the data reported so far is not very accurate. Expect to see changes soon.

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearjyn4fmks6zr2uryagquo6smxj3ue2mx3c3qtl6pdtg7smurpmo 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 335c49a9-d730-4ad0-b9b3-a5a8cb0e9759
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearjyn4fmks6zr2uryagquo6smxj3ue2mx3c3qtl6pdtg7smurpmo

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectornbg436p4nmc42h7m6imh56u433xhey2thkh3cbodnql2fnsc 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 335c49a9-d730-4ad0-b9b3-a5a8cb0e9759
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectornbg436p4nmc42h7m6imh56u433xhey2thkh3cbodnql2fnsc

**Comment by MarshLin88** [comment]
checker:manualTrigger

**Comment by MarshLin88** [comment]
The report shows the retrieval rate is very low.

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by Wengeding** [comment]
Report is OK, please try to improve the Deal Data Replication in the next round.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6laqtgrsdazk6jsy52lm4b2xrv6xi3xmc2jkzjbbklblh4u6dya 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 818faae9-8fc2-4c9f-a626-a7096df46c9f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6laqtgrsdazk6jsy52lm4b2xrv6xi3xmc2jkzjbbklblh4u6dya

**Comment by cryptowhizzard** [comment]
@Wengeding

Exactly after i posted in Slack a message that HTTP retrievals are not reliable and that the retrieval bot is tricked.

This client is not supporting HTTP retrieval and your signature should be revoked until proper retrieval is fixed.

**Comment by cryptowhizzard** [comment]
@Sinsoteam 

Please enable retrieval on your data according to the rules of FIL+.

**Comment by cryptowhizzard** [comment]
As can be seen SP's f0126478, f02025503, f02114868, f02114994 and f02128256 all were heavily involved in CID sharing
The others have Retrieval off.

This LDN should have never received a signature.

<img width="1659" alt="Scherm­afbeelding 2023-07-27 om 21 21 42" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/22090da0-6887-469e-8d6e-940401ebc770">

Legenda:

Client = The LDN data preparer
SP = SP
TotalDeals = Total volume of data in bytes
Ipadress = Ipadress
Port = Port Sp is listening on
Name = Name as known by DCENT
Online = The miner is online
Subnet = The class C subnet derived from IP adres
Matches in Subnet = The number of machines present in this subnet.
Location = Location on the globe
VpnResult = VPN score for IP adres given according to ipqualityscore.com
% = The percentage of deals this SP received in this LDN.
AT = Abuse Type. 1 means CID sharing abuse / 3 means Not retrievable.
Asouce = Abouse Source client address.
MasterAddress = The address this SP is funded from.

**Comment by cryptowhizzard** [comment]
Signed without retrieval. Dispute made.

<img width="700" alt="Scherm­afbeelding 2023-07-31 om 18 14 04" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c51601d1-8e46-4fde-b094-482a4fabaeba">

**Comment by Wengeding** [comment]
There is no CID sharing found in this application, if the collaborating SPs have some CID sharing with other applications, you should flag them, not this one.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/117442528/569f0d4a-790e-468f-bebc-172634d9fe0b)

**Comment by cryptowhizzard** [comment]
I have the logs here with download attempts. They all fail, no matter where i download on this globe.

Also notified governance about your last signature.

**Comment by Wengeding** [comment]
It's not my dataset. You might be mistaken.

**Comment by cryptowhizzard** [comment]
See the screenshot.

Everything with AT 1 = Abuse / CID sharing. The LDN is in the AuditTrail column.
Everything with AT 3 does not have retrieval enabled / tricked for only a few MB.

<img width="1493" alt="Scherm­afbeelding 2023-08-03 om 18 24 17" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/71fc878c-f74c-45e3-ba3a-caee2933069f">

**Comment by Sinsoteam** [comment]
checker:manualTrigger

**Comment by Sinsoteam** [comment]
> See the screenshot.
> 
> Everything with AT 1 = Abuse / CID sharing. The LDN is in the AuditTrail column. Everything with AT 3 does not have retrieval enabled / tricked for only a few MB.
> 
> <img alt="Scherm­afbeelding 2023-08-03 om 18 24 17" width="1493" src="https://user-images.githubusercontent.com/36404435/258175356-71fc878c-f74c-45e3-ba3a-caee2933069f.png">

You need to check your answer.

**Comment by cryptowhizzard** [comment]
This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.

It works as follows:

One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again. 

Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/961.log

**Comment by Filplus-govteam** [comment]
Hello @Sinsoteam  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by Sinsoteam** [comment]
No. We have communicated with SPs and have made sure they are not using NGINX. I am not sure if some of your behavior triggered the network's security defenses.

**Comment by Sinsoteam** [comment]
> This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.
> 
> It works as follows:
> 
> One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again.
> 
> Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/961.log

No. We have communicated with SPs and have made sure they are not using NGINX. I am not sure if some of your behavior triggered the network's security defenses.

**Comment by cryptowhizzard** [comment]
> > This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.
> > It works as follows:
> > One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again.
> > Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/961.log
> 
> No. We have communicated with SPs and have made sure they are not using NGINX. I am not sure if some of your behavior triggered the network's security defenses.

Again:

Boost supports range retrievals. Simple explanation , if a download breaks due timeout , it should pick up again where it left. This function is disabled on your side making retrieval impossible.

Fix it.

**Comment by TakiChain** [comment]
checker:manualTrigger

**Comment by TakiChain** [comment]
Retrieval report seems normal.  Please keep your request in accordance with the principles of the program and in line with their allocation strategy. @Sinsoteam

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecclvi2iekxqbcnnhiy6utc4ulrjrvqjeva22c2ahrt2s4n6a6wsk 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 818faae9-8fc2-4c9f-a626-a7096df46c9f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecclvi2iekxqbcnnhiy6utc4ulrjrvqjeva22c2ahrt2s4n6a6wsk

**Comment by raghavrmadya** [comment]
@TakiChain , I see that another notary is actively conducting due diligence on this application. Can you share evidence of what kind of due diligence you performed? Looking at the bot report is not enough. Did you attempt retrieval sampling?

This application has been under dispute - https://www.notion.so/filecoin/LDN-signed-without-retrieval-aebb6f0a736549ae85e03d7b2d411f0a?pvs=4

Client must show evidence of retrievability to continue

**Comment by TakiChain** [comment]
@raghavrmadya  Isn't the retrieval report valid evidence?   Why not consider upgrading your report?

**Comment by cryptowhizzard** [comment]
Dear Sinsoteam,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqjhbh6emggbx2zlxaaiqjcrci5ujmjnq6n6lh6kk3vwmn5de56gjq ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by Sinsoteam** [comment]
@raghavrmadya This can show that we support retrieval.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/108266562/836264fd-d66e-4e3f-b1ec-89cbd863a7a7)

**Comment by raghavrmadya** [comment]
Thanks @Sinsoteam

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
Report LGTM, willing to support.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6bz5mhmsdrc7dktos2k24wlacgfmq24swskhm33kjlh46gq6ksc 
#### Address 
> f1lozjhyay3heeav3wm4ttycoaumjgtgrp452woki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 818faae9-8fc2-4c9f-a626-a7096df46c9f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6bz5mhmsdrc7dktos2k24wlacgfmq24swskhm33kjlh46gq6ksc

**Comment by kevzak** [comment]
closing until @Sinsoteam provides a clear list of SP miner IDs, entities and locations storing replicas
