### ISSUE TITLE
[DataCap Application]Maierheng (Xiamen) Wine Co., Ltd

### ISSUE THREAD

**Issue by jiucangmatou** [filecoin-project/filecoin-plus-large-datasets#963]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Maierheng (Xiamen) Wine Co., Ltd
- Website / Social Media:https://www.jiucangmatou.com/, https://jc.jiucangmatou.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Maierheng (Xiamen) Liquor Co., Ltd. is located in the beautiful city of Xiamen. It is mainly engaged in all kinds of imported red wine, foreign wine and medium and high-end Baijiu. Through its convenient port advantages, it is committed to building a liquor supply chain brand.

The wine warehouse wharf is the brand and online sales channel of maierheng (Xiamen) Wine Co., Ltd.

The wine warehouse terminal makes use of the company's aggregated supply chain resources to open up channels and channels for suppliers, stores and customers. It gives full play to the price advantages of the supply chain through small programs, official account and app, and gives profits to suppliers, stores and customer terminals.

At present, the platform has more than 10 online and offline stores and nearly 20000 members.
```

What is the primary source of funding for this project?
```
Self-financing.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Promotional brochures, event pictures and videos, brand promotion videos, opening ceremony pictures and videos, reception pictures and videos, production workshop pictures and videos.
```

Where was the data in this dataset sourced from?
```
Promotional marketing video and factory production video.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1St9heF61mIVcTAm2p8i78GzfzOOTtT_q?usp=sharing
https://drive.google.com/drive/folders/1gQfT6ZhC0H_e28BKVC45HRO3ynqEU4g5?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, Europe can be, no specific requirements.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
we are actively contacting more storage providers, we welcome storage providers to contact us, we hope that data can be stored securely and decentralized.
```

How will you be distributing deals across storage providers?
```
Less than 15% data for every storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are fully funded.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?
Can you provide more data samples to prove that you have 1.5 PB data already?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by jiucangmatou** [comment]
Hi,@sunnyiscoming
I am the boss's secretary, responsible for the docking of this storage project.
This is part of the video material that has been sorted out：
https://drive.google.com/drive/folders/1NVWzRpN02kqhtukyzKwAunvl4w-93hER?usp=sharing
We have finished contacting with f08403,f01579009. At the same time, we are still actively looking for more high-quality SPs. We promise that every SP does not exceed 25%.And more Sps will be welcomed to join us! 
Thanks.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia

**Comment by stcouldlisa** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity?
Email name should contain Issue ID #963.

**Comment by jiucangmatou** [comment]
> Can you email [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using your official domain name to confirm your identity? Email name should contain Issue ID #963.

Hi,@stcouldlisa
Please check your mailbox, our sending address is: zhenglanyan@jiucangmatou.com.
<img width="1214" alt="57df4d963bd32ace5b2ff7391aab922" src="https://user-images.githubusercontent.com/111368647/208025074-8603a7e1-9d00-4cb3-a10f-e829346390be.png">
Thanks.

**Comment by ipfscn** [comment]
look nice

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtsq2um6plzjtvjbpzazkz2brtf45ptjch52lrdv35bmtvhhaxny 
#### Address 
> f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 71d98ef1-247b-4321-849f-d9653f927261
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtsq2um6plzjtvjbpzazkz2brtf45ptjch52lrdv35bmtvhhaxny

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxxxqaza637ksoitphvw3i6kx5y3a5hllnxzbhquzoezgia4yq6k 
#### Address 
> f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 71d98ef1-247b-4321-849f-d9653f927261
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxxxqaza637ksoitphvw3i6kx5y3a5hllnxzbhquzoezgia4yq6k

**Comment by newwebgroup** [comment]
According to the CID Checker results, it is OK

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedt7cvnfv3tjubu5fk7kzgzh6nl7pontpu4tqp3pjn7lvtrpcfz2s 
#### Address 
> f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> f6b2cc56-c08d-4d35-b676-a40d9da18ff2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedt7cvnfv3tjubu5fk7kzgzh6nl7pontpu4tqp3pjn7lvtrpcfz2s

**Comment by stcouldlisa** [comment]
looks like there is a bug
I sign it to see  if the DC arrives？

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayxl7joktc25fc734str36oiy7dn2modgeckcpx3la5hdvqkves6 
#### Address 
> f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> f6b2cc56-c08d-4d35-b676-a40d9da18ff2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayxl7joktc25fc734str36oiy7dn2modgeckcpx3la5hdvqkves6

**Comment by stcouldlisa** [comment]
DC arrives
It looks like there is a bug

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Willing to support. Hope future allocations can be more diversed.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyl2trc4qvjdfzqo5vcsew5kbghpo7tnhduujkfjr2tgpp5ruty4 
#### Address 
> f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 96828ce2-8dd5-49bf-8f42-9cd497288a4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyl2trc4qvjdfzqo5vcsew5kbghpo7tnhduujkfjr2tgpp5ruty4

**Comment by YuanHeHK** [comment]
The overall packaging process looks very good, it is recommended to add one or two more SPs to make the data distribution more even.

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6umot5p7iecobo7fmdimdqa2rloidytf266injne4xcmtabgigm 
#### Address 
> f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 96828ce2-8dd5-49bf-8f42-9cd497288a4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6umot5p7iecobo7fmdimdqa2rloidytf266injne4xcmtabgigm

**Comment by zizi-defil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedul7ovtk6gohbqqpnxpmu7pkv533lemtd7fwa6fmcwtbnfsapj5s 
#### Address 
> f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 85887db2-de09-43b8-854a-afce57331474
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedul7ovtk6gohbqqpnxpmu7pkv533lemtd7fwa6fmcwtbnfsapj5s

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamlr5w2kdznjddupyj2fbvyo4vmee2vkz5vnrwj3i5d2jli6tmm4 
#### Address 
> f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 85887db2-de09-43b8-854a-afce57331474
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamlr5w2kdznjddupyj2fbvyo4vmee2vkz5vnrwj3i5d2jli6tmm4

**Comment by herrehesse** [comment]
@jiucangmatou dear applicant,

The data you described is "Promotional brochures, event pictures and videos, brand promotion videos, opening ceremony pictures and videos, reception pictures and videos, production workshop pictures and videos"

This type of data are not suitable for the Filecoin+ program. I should recommend you to use regular storage deals or move your application to FIL-E.

@zizi-defil @stcouldlisa why as notaries are you signing this application looking at the CID report and business data description?

**Comment by BDEio** [comment]
@jiucangmatou Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by cryptowhizzard** [comment]
Hi,

I would love to move forward with this LDN, however retrieval (without costs) is not provided by your SPs. This is against the FIL+ rules. Please fix asap.

Feb 15 16:50:04 proposals dealscanner-f01995046-f0109606: Error: Failed to retrieve content with candidate miner f0109606: payment channel required, boost doesn't support these retrievals
