### ISSUE TITLE
[DataCap Application] China Auto Parts Network

### ISSUE THREAD

**Issue by didiche88** [filecoin-project/filecoin-plus-large-datasets#964]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: China Auto Parts Network
- Website / Social Media:http://www.didiche.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.8 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1wbwggh7id4lm3loajxf5lcnk7o2vacvpk64wvna

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
China Auto Parts Network is a portal website for the auto parts industry that integrates professional modules such as supply, purchase, quotation, and corporate bidding and procurement. .
The website is characterized by the timeliness, extensiveness and no geographical restrictions of industry information. It takes building the most professional and authoritative business platform in the auto parts industry as its own responsibility, and gives full play to the resource integration advantages of network media to continuously develop for users and enterprises. The market provides the best business opportunities, promotes the efficient development of the auto parts industry, and provides authoritative industry information and professional system business services. At present, this website has more than 16,000 suppliers and more than 60,000 kinds of auto parts products.
With the continuous expansion of demand for auto parts in domestic and foreign markets and the rapid development of e-commerce platforms, the website has built a trading platform for enterprise communication and negotiation to adapt to the situation. In view of the situation that my country's independent design is not strong and the industrial chain is at the low end, it pays attention to the information on technological breakthroughs in the industry, and launches the industry dynamic section and equipment industry information to provide auto parts dealers, manufacturers and suppliers with a one-stop shop that is close to their needs. Serve.
China Auto Parts Network will focus on changes in the industry in terms of scale, sales output value, export delivery value, etc., guide the secondary industry to seek new breakthroughs in auto parts technology, and regulate the mining machinery market to continue the healthy and efficient development of the industry.
```

What is the primary source of funding for this project?
```
Corporate shareholder funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Auto parts product information pictures and videos, manufacturer information pictures and promotional videos, maintenance videos, self-media promotional videos, etc.
```

Where was the data in this dataset sourced from?
```
Maintenance videos of cooperative manufacturers in the past 5 years, marketing videos in the past 3 years.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1yUNhgaxWh9byqf8WclTE6K5YDw4mxuKl?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,we confirm that this is a pubilc data.
```

What is the expected retrieval frequency for this data?
```
About 3 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
No restrictions, Asia, Europe, Africa, America are available
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have connected with some storage service providers in Asia, and hope that more high-quality storage service providers in other regions will contact us. Data security is our top concern at present, so long-term and stable cooperation with storage service providers is very important.
```

How will you be distributing deals across storage providers?
```
Asia as the main region will not exceed 50% of the data volume, the number of storage service providers will not be less than 5, and each partner will not exceed 30% of the data volume.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have enough funds to start.
No help needed at the moment, thanks.
```

**Comment by Sunnyiscoming** [comment]
What is the name of the organization? Please provide the corresponding Tianyancha, Qichacha or other proof links. What's the relationship between you and the organization?
![image](https://user-images.githubusercontent.com/105098820/202989864-3b347847-573e-4469-bf23-b58cf6c24f04.png)
The website cannot be opened.
It seems that there are many sources of data samples. Could you explain the sources of your data? Do you have permission to store it on the Filecoin network as public data and provide proof of that?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by didiche88** [comment]
Hi,@Sunnyiscoming
China Auto Parts Network belongs to Quanzhou Meirui Network Technology Co., Ltd.
I'm the director of the office and I'm in charge of this storage project
The website upgrade has been completed, please check
![image](https://user-images.githubusercontent.com/111369007/204068565-07a361d4-3d24-4f07-b5a4-cec77b309186.png)
When applying, the case preparation is not very sufficient, please check the supplementary materials through the following URL.
https://drive.google.com/drive/folders/1jrQMU0ve4Y6EJTQV-i0VlYNey1Ds2HkN?usp=sharing
We are very clear that all the data stored this time are public data, and we strictly abide by your retrieval requirements.
We have contacted the following SPs:
f01681808,f01546926,f01606675
But we have not finalized cooperation. Of course, we are still in contact with more node.
Thanks.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 1.8PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Hey @didiche88 , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by didiche88** [comment]
> You seem to have applied for a long time, do you have any plans?

We need to start, we have been waiting for the support of the notary, we have contacted many people, but no one supports us.

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyxwvisxj5yd7opmd3p6wsihyvmgmw7qkq7uhoafifqlh4qeklca 
#### Address 
> f1wbwggh7id4lm3loajxf5lcnk7o2vacvpk64wvna
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> b30eb6cd-4928-47b9-9fd4-8124b195246b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyxwvisxj5yd7opmd3p6wsihyvmgmw7qkq7uhoafifqlh4qeklca

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2c7i4ivg3zveej6mlqi4yqdmzfr3wiwzcv43rkrbanjn66ucjxo 
#### Address 
> f1wbwggh7id4lm3loajxf5lcnk7o2vacvpk64wvna
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> b30eb6cd-4928-47b9-9fd4-8124b195246b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2c7i4ivg3zveej6mlqi4yqdmzfr3wiwzcv43rkrbanjn66ucjxo

**Comment by SuperChaiChai** [comment]
Willing to support the addition of new projects, and the sealing process needs to comply with fil+ community rules

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
Please make sure to increase the retrieve

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@SuperChaiChai @stcouldlisa 

What due diligence have you guys performed with the start of this application?
Where is the distribution plan and why is there no retrieval supported against rules and guidlines?

**Comment by stcouldlisa** [comment]
When the customer contacted me, he promised to support retrieval. I will urge customers to increase the retrieval rate, and I will check their retrieval rate again tomorrow, thank you for your kind reminder

**Comment by stcouldlisa** [comment]
The first round of 50T for 964 is too small, the robot may only send one retrieval request a day, so the update is very slow

**Comment by cryptowhizzard** [comment]
@stcouldlisa 

Please do not answer selectively.

What due diligence have you guys performed with the start of this application?
Where is the distribution plan and why is there no retrieval supported against rules and guidlines?

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
Looks like retrieval is fixing

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
Please continue to improve your accessibility, and you also want to deploy the http download tool.

**Comment by didiche88** [comment]
> @SuperChaiChai @stcouldlisa
> 
> 你们在开始此申请时进行了哪些尽职调查？ 分配计划在哪里？为什么不支持根据规则和指南进行检索？

Thank you for your attention. 
We have been advancing according to the requirements of the community. 
We have contacted many storage service providers, but although the responses are limited, we will still support retrieval in accordance with the requirements of the community and obey the rules of the community unconditionally. 
Please pay attention at all times our progress thank you
