### ISSUE TITLE
[DataCap Application] <Shenzhen Xiwei Intelligent Technology Co., LTD> 

### ISSUE THREAD

**Issue by SZXiweizhihui** [filecoin-project/filecoin-plus-large-datasets#966]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Xiwei Intelligent Technology Co., LTD
- Website / Social Media:https://www.civicint.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1i72wll4ekssmoa2g5kojqi3hgylxrcxstokepui

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Xiwei Intelligent Technology Co., Ltd. is an edge AI technology, product and solution provider, focusing on "industry +AI" empowerment. The company is committed to the integration of artificial intelligence and edge computing innovation, get through the last mile of artificial intelligence landing; We are good at the deep integration of AI algorithm and hardware, and the full line of algorithms supports all the mainstream chips and operating systems at home and abroad. We like to actively layout the algorithm hardware for wisdom, hoping to build the edge AI platform of Pratt & Whitney and enable more industry scenarios.

As a member unit of the Intelligent Vision Industry Alliance and a partner of Huawei Machine Vision Solutions, we like to provide edge AI platform, cloud mall, algorithm model, 0 code model training and other products and services for integrator customers based on ecological cooperation. To provide end-users with the construction, deployment and operation support of end-edge-cloud-application full scenario and full life cycle AI solutions. The core team of the company has more than 10 years of experience in edge AI technology research and development and productization, and the product technology has achieved good results in many segments..
```

What is the primary source of funding for this project?
```
The revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
They are all videos and pictures of our company's product demonstrations and introductions, including our intelligent algorithms, intelligent applications, intelligent hardware and other products.
```

Where was the data in this dataset sourced from?
```
Mainly from the product department of our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1b-GefyBk_8H6h1a_R2MwF8u9Ho8GniQP?usp=sharing
```
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
About five times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least two years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute offline to storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will check their overall capacity and working hours, we need a storage provider that we can work with for a long time.
```

How will you be distributing deals across storage providers?
```
Try to distribute equally.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,We have prepared a special fund.
```

**Comment by SZXiweizhihui** [comment]
The post applied for earlier has been marked by github. The number of the previous post is # 646. Please check it as soon as possible

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?
Can you explain your data composition? Can you provide more data samples to prove that you have 5 PB data already? How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by SZXiweizhihui** [comment]
I'm an employee of xiwei
Xiwei is a provider of edge AI technologies, products and solutions, focusing on "industry+AI" enabling.
The data type we plan to load into Filecoin this time is: public data set - intelligent agriculture+AI analysis video
Xiwei has been established and operated for 3 years. We help many farms to manage more efficiently and conveniently.
The public data set is about 2P,
We plan to store the contents of 1P in Filecoin for 5-6 backups
Our data storage has no regional restrictions. If it can be in China, it will be more convenient for us.
The SPs we are currently in contact with are:
f0513878   Guiyang City
f0686816   Guangdong City
f01920091 Hongkong
f01901773 Hongkong
f01782338  Yichang City      


The data set of xiwei is divided into two parts:
Public:
From the data samples we provided, we can see that the AI program of xiwei can greatly help the farms to manage animals more efficiently.
This kind of public video is roughly the same in form, and all of them analyze the monitoring content through AI algorithm software to replace manual work.
For example:
Count the number of farmed animals
Whether the farmed animals escape across the border
Which animal didn't eat
Whether the garbage dump is cleaned up in time
Private:
There are also some privacy related videos that we will not upload to Filecoin for the time being.
For example, smoking detection in public places, whether motor vehicles stop illegally, and whether personnel fall down. wait

**Comment by Sunnyiscoming** [comment]
These videos are generally surveillance videos, which are expected to provide adequate explanations for openness.
 Can you provide more data samples to prove that you have 5 PB data already?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
