### ISSUE TITLE
[DataCap Application] <Doge Adventure> 

### ISSUE THREAD

**Issue by bianpengwen** [filecoin-project/filecoin-plus-large-datasets#967]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Doge Adventure
- Website / Social Media: https://dogeavt.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1uhkybnaygmyzt4ie5jzpklurhiuy6bhmnr6d2iy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
About Doge Adventure

Doge Adventure is an original independent chain game incubated by X Protocol and supported by the community. The game combines Doge meme elements and the concept of NFT random fusion. Users earn profits and collect precious NFT collectibles by casting fusion, researching strategies, exploring, and fighting.

Doge Adventure plans to upgrade in 8-12 months to become a game platform that is compatible with third-party NFT access and provides 3D visualization effects.

Doge Adventure which combined NFT+Play to Earn+GameFi elements has reached a strategic partnership with PlanckX, the next-generation game asset trading platform where you own and trade in-game crypto assets. This partnership will bring community members from both sides together and benefits from a more complete ecosystem.

Doge Adventure is backed by strong partners; most are venture capitalists and popular investment companies: Infinity Labs, Spark Digital Capital, Kernel Ventures, Oracles Investment Group, YBB Foundation LTD. , LC Capital, Dealean Capital, Lancer.

https://medium.com/@official_25435
https://t.me/DogeAdventure
https://twitter.com/DogeAdventure_
https://discord.com/invite/ztnHsFfyXe

About X Protocol

X Protocol is a Polkadot-based cross chain protocol that provides decentralized, safe and fast bridging solution. X Protocol aims to build a Decentralized Metaverse based on Web3.0. Multichains Management and Data Aggregation Predictive Analytics will be realized through X Bridge, to build up a valuable network in metaverse.

X Protocol is the first metaverse+ application portal programmed using RUST language with source-generated gameplay and land economy model. It also provides low-cost access to the Metaverse for DAPPs on heterogeneous chains, sharing X Protocol’s users while making the X Protocol ecosystem more prosperous. X Protocol will strive to become the “Ready Player one” ‘s World + STEAM platform in the blockchain space.

Twitter: https://twitter.com/X_Protocol_
Medium: https://medium.com/x-predict-market
Telegram group chat: https://t.me/XPredictMarket
Discord group chat: https://discord.com/invite/sFM8eRa2m2
Website: https://x-protocol.com/
```

What is the primary source of funding for this project?
```
As a project incubated by X Protocol and established a cooperative relationship with X protocol. Doge Adventure’s treasury assets will be supervised by X Protocol as a third party, providing support at the code level and ecology to ensure the healthy and positive development of Doge Adventure.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Metaverse game scenes, 3D models and actions for NFTs, three-dimensional digital images, etc.
```

Where was the data in this dataset sourced from?
```
Doge DAO development team designed P2E paradigm and 3D models and actions for NFTs.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Data sample](https://github.com/bianpengwen/filecoin-plus-large-datasets/blob/main/Doge%20Adventure.zip).
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed.
```

What is the expected retrieval frequency for this data?
```
Probably twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We intend to store this content permanently on Filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We’ll be doing primarily online data transfers with miners who have good reputation in the Filecoin community and we’ll try to realize geographic diversity per deal (redundant storage across locations.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will refer to the Filecoin miner reputation system and select eligible storage providers to work with.
Major characteristics about choosing the storage providers:
- location
- transmission speed
- deal success rate
- previous experience of real data storage
-nodes stability.
```

How will you be distributing deals across storage providers?
```
We plan to cooperate with more than 5 SPs according to their network bandwidth and storage efficiency with each less than 20% of the DataCap allocated.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with the data you will store to prove that you have 5 PB data? Videos would be better. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
