### ISSUE TITLE
[DataCap Application] Xi'an Nuowan Electronic Technology Co., Ltd. 

### ISSUE THREAD

**Issue by Shirly-DU** [filecoin-project/filecoin-plus-large-datasets#968]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xi'an Nuowan Electronic Technology Co., Ltd. 
- Website / Social Media: http://novaet.cn/sy
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1qttvggw2cpaqidpg5luhqvkxu6qmm6x6rvy6zlq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xi'an Nova Electronic Technology Co., Ltd. (abbreviated as Nova Electronics) was established in 2016 and is located in Xi'an High-tech Zone. It is a national-level high-tech enterprise specializing in the research and development of battery management systems.

Nova Electronics has wholly-owned subsidiaries such as Beijing Nuovan Electronic Technology Co., Ltd., Suzhou New Nuovan Electronic Technology Co., Ltd., Anhui Yunuo New Energy Technology Co., Ltd., etc.

The company's core team is formed by a group of doctors and masters who have been deeply involved in the BMS field for more than ten years. They adopt international advanced technical concepts and have won a number of software copyrights and patent certificates in the BMS field,And these advanced technologies are applied to the fields of new energy vehicles, energy storage and small power. The products are sold at home and abroad, and have been widely recognized by the market, and the market share is far ahead.

The company has successfully passed ISO9001, IATF16949 quality system certification, product design is strictly implemented in accordance with QC/T897-2011 standards, and many products have passed CE, UL and other related certifications.

Nova Electronics adheres to the principle of "pragmatic innovation, quality first" and the enterprise spirit of "technology, ingenuity, value, and service", and continues to develop in the field of battery management systems through excellent product innovation concepts and strict quality assurance. Create greater value for users.

Intellectual property certificates: 1 invention patent, 2 utility model patents, 9 software copyrights, and 2 trademark registrations.
```
What is the primary source of funding for this project?
```
Investment and product income.
```
What other projects/ecosystem stakeholders is this project associated with?
```
None
```
## Use-case details

Describe the data being stored onto Filecoin
```
Nova’s R&D data, sales data.
```
Where was the data in this dataset sourced from?
```
The data comes from the data provided by the company's R&D department.
```
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
 https://drive.google.com/drive/folders/1vQ84zLSknwj9EW2hehsRALeHMz2hw_SE?usp=sharing      
```
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```
What is the expected retrieval frequency for this data?
```
About a year or so
```
For how long do you plan to keep this dataset stored on Filecoin?
```
At least 24 months
```
## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia and Greater China.
```
How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```
How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope to select a reputable storage provider, screen the overall technical strength of miners, and ensure distributed storage and data security.
```
How will you be distributing deals across storage providers?
```
We will first choose a more stable and secure storage provider, and then allocate according to the allocation rules on this basis. And hope that more storage providers can contact us to provide us with storage services. 
```
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by simonkim0515** [comment]
Closing due to no response
