### ISSUE TITLE
[DataCap Application] <株式会社BC College> - <MUSIC NFT>

### ISSUE THREAD

**Issue by asdfec** [filecoin-project/filecoin-plus-large-datasets#969]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 株式会社BC College
- Website / Social Media:https://www.bccollege.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1cmxykjxvps3anagl6aldfzj4yp3ixygpuywlr3y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We were founded in 2018 and are dedicated to promoting blockchain technology in Japan and helping companies use it better. For example, blockchain technology training, blockchain app development, blockchain talent recruitment.
This project is to store music NFT related materials for our clients.
```

What is the primary source of funding for this project?
```
The company funds 
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Including but not limited to song demos, 2D MTV, 3D MTV, posters and NFT data.
```

Where was the data in this dataset sourced from?
```
Our partners and our company staff
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.missevan.com/sound/player?id=6218723
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed.
```

What is the expected retrieval frequency for this data?
```
Accompanied by music creation at least 1 time per week. should be more after NFT circulation.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3-5years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Japan, Singapore, China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Only online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
A team with full fil related experience. Also willing to communicate with us frequently.
```

How will you be distributing deals across storage providers?
```
2 SPs are expected to be used to secure the data.
One in China.
One in Japan or Singapore,under dicusstion.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1cmxykjxvps3anagl6aldfzj4yp3ixygpuywlr3y

**Comment by liyunzhi-666** [comment]
hey, @asdfec 
can you share more examples? There's so little data [here ](https://www.missevan.com/sound/player?id=6218723)that it's hard to believe you have a 5PiB storage requirement behind it.

**Comment by asdfec** [comment]
> 

https://drive.google.com/file/d/1gTrJRsHFhjtJGnU_H2kxBK2FWplpjEwH/view?usp=sharing
https://drive.google.com/file/d/1eMwkKYkh5j_PT503mrMpULJd10yo0VRB/view?usp=sharing
There are some MV for our music.Please have a check.

**Comment by asdfec** [comment]
Hello,@liyunzhi-666 
May I get some feedbacks so that I could know what’s missing in my applications? Thanks.

**Comment by liyunzhi-666** [comment]
hi @asdfec 
The data samples all look fine to me. Please continue to be reviewed by other notaries.

**Comment by Sunnyiscoming** [comment]
Hey @asdfec , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499
