### ISSUE TITLE
[DataCap Application]Shanghai QingSong Yu-Geospatil Data

### ISSUE THREAD

**Issue by shiji605** [filecoin-project/filecoin-plus-large-datasets#97]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai QingSong Yu Enterprise Management Co., Ltd
- Website / Social Media:www.qingsongyu.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):300TiB
- On-chain address for first allocation:f1dhtdqj7v36w2twbsumi25o6hszdzmi7a6xin2oq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shanghai relaxed apartment Enterprise Management Co., Ltd., founded in 2017, is a brand of Chengjing group focusing on enterprise apartment operation and management. There are two series subsidiaries of "relaxed apartment" and "relaxed apartment · future". It is committed to building a multi-functional and high-quality urban rental ecosystem integrating residence, entertainment, training, social networking and office. It provides high-quality rental services for users of many well-known brand enterprises such as the world's top 500, listed companies, central enterprises and state-owned enterprises.
```

What is the primary source of funding for this project?
```
The company has reserved sufficient project funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
GOES satellites (GOES-16 & GOES-17) provide continuous weather imagery and monitoring of meteorological and space environment data across North America. GOES satellites provide the kind of continuous monitoring necessary for intensive data analysis. They hover continuously over one position on the surface. The satellites orbit high enough to allow for a full-disc view of the Earth. Because they stay above a fixed spot on the surface, they provide a constant vigil for the atmospheric "triggers" for severe weather conditions such as tornadoes, flash floods, hailstorms, and hurricanes. When these conditions develop, the GOES satellites are able to monitor storm development and track their movements.
```

Where was the data in this dataset sourced from?
```
[Please answer here.](https://registry.opendata.aws/noaa-goes/)
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Please answer here.](https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-goes16)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
There are no restrictions on the use of this data.
```

What is the expected retrieval frequency for this data?
```
Anyone who needs or is interested in retrieving this data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
two years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
I plan to conduct storage transactions around the world.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online distribution can also be done if offline data transmission is required.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Select a storage provider that has sufficient funds, understands the project and is responsible for the data.
```

How will you be distributing deals across storage providers?
```
The more economic strength and relevant experience the storage provider will distribute to enough computing power transactions.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have prepared enough funds and resources.
```

**Comment by galen-mcandrew** [comment]
@shiji605 Can you please clarify your role? Are you a representative of the client (Shanghai relaxed apartment Enterprise Management Co., Ltd.) or a storage provider? Additionally, it sounds like the client is an apartment management company, but the dataset you are referring to is satellite data. I'm not sure I understand how satellite data is related to the apartment management company.

**Comment by pandola0908** [comment]
> @shiji605 Can you please clarify your role? Are you a representative of the client (Shanghai relaxed apartment Enterprise Management Co., Ltd.) or a storage provider? Additionally, it sounds like the client is an apartment management company, but the dataset you are referring to is satellite data. I'm not sure I understand how satellite data is related to the apartment management company.

 I am the representative of the company in charge of application affairs. Our company's business scope includes real estate development business. In the course of this business, it is necessary to store satellite terrain data, which is used for exploration and development and provided to our geological construction team.

**Comment by shiji605** [comment]
> @shiji605 Can you please clarify your role? Are you a representative of the client (Shanghai relaxed apartment Enterprise Management Co., Ltd.) or a storage provider? Additionally, it sounds like the client is an apartment management company, but the dataset you are referring to is satellite data. I'm not sure I understand how satellite data is related to the apartment management company.

 I am the representative of the company in charge of application affairs. Our company's business scope includes real estate development business. In the course of this business, it is necessary to store satellite terrain data, which is used for exploration and development and provided to our geological construction team.

**Comment by shiji605** [comment]
> @shiji605 Can you please clarify your role? Are you a representative of the client (Shanghai relaxed apartment Enterprise Management Co., Ltd.) or a storage provider? Additionally, it sounds like the client is an apartment management company, but the dataset you are referring to is satellite data. I'm not sure I understand how satellite data is related to the apartment management company.

 I am the representative of the company in charge of application affairs. Our company's business scope includes real estate development business. In the course of this business, it is necessary to store satellite terrain data, which is used for exploration and development and provided to our geological construction team. @galen-mcandrew

**Comment by shiji605** [comment]
@galen-mcandrew   I'm sorry to bother you. Can we continue it?

**Comment by dkkapur** [comment]
@shiji605 can you confirm you are a representative of the company though an email or something else? I see you have also opened up another LDN application for a different company here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/92. Can you explain and prove your relationship with each of these organizations?

**Comment by dkkapur** [comment]
@shiji605 - closing this one out for now since we have not heard back on the above issue. Please re-open if still relevant.

**Comment by shiji605** [comment]
@dkkapur  Hi， sorry to keep you waiting, this is my company email：shiji@qingsongyu.cn, you can send a message to verify. Another LDN was entrusted by the cooperative company to help him apply.
