### ISSUE TITLE
[DataCap Application] Guilin GLsun Science and Tech Group Co.,LTD.

### ISSUE THREAD

**Issue by glsun2002** [filecoin-project/filecoin-plus-large-datasets#970]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guilin GLsun Science and Tech Group Co.,LTD.
- Website / Social Media:http://glsun.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1kvxmsu4cu4fziwmgijfsqkzzfp7apytmujfvk5i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2001, Guilin GLSUN Science and Tech Group Co., Ltd as a key member of high-tech enterprises of China National Torch Plan, specializes in high level semiconductor laser diode chips development, production and packaging, focus on both Cloud Data Center and Telecom Networking Inter-connectivity.
With widely production portfolio, our products including DFB LD chips,TO-CAN Laser Diodes, Photo Diodes, high data rate passive optical devices and modules, function modules, monitoring and system protection equipment,etc. 
GLSUN is a optical solution company, offer its customers low-cost, reliable optical products with superior performance in volume, GLSUN strives to develop innovative solutions leveraging III-V semiconductor laser chip technology to interconnect the world for the future. 
```

What is the primary source of funding for this project?
```
Company's own funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Product information, company team building video, company display, etc.
```

Where was the data in this dataset sourced from?
```
Product information includes production videos recorded in the daily workshop, and operation videos are regularly produced by the sales team.
The company's team building activities are carried out every week and are recorded and organized by the office.
The company's exhibition will be organized once a month for external publicity.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1CPdj75QV4txDCy4wPbRA-_xYpbzH76Ko?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,This is a public data.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in China or Asia, Europe, Africa is also possible.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Data security is the first priority, so the cooperative storage service providers are required to be able to provide services continuously and stably, and smaller scales are not considered for the time being. We welcome more high-quality storage service providers to contact us..
```

How will you be distributing deals across storage providers?
```
No less than 40% in Asia, no limit in other regions, no less than 5 storage service providers to cooperate.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have enough ourselves to start the project.
```

**Comment by simonkim0515** [comment]
Closing due to no response
