### ISSUE TITLE
[DataCap Application] disconnect.digital

### ISSUE THREAD

**Issue by richardliangning** [filecoin-project/filecoin-plus-large-datasets#971]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: disconnect.digital
- Website / Social Media: https://disconnect.digital/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f137dth2f4pcaqr4lhmad2qlszwvnfoy35cxqzq6q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
disconnect.digital is a project operation company in the field of WEB3.0 and a full-scale operation company. Our team members are from well-known WEB3.0 companies and have rich and many years of project operation experience. Our team is Human Horizons, CypherCore, ZKSpace , Tbitex, Wemiks, Primas, Sprout and other well-known projects provide long-term services, including but not limited to white paper writing, Twitter operation, article writing, speech writing, PPT writing, media delivery, official website design, planning of event plans, promotion of project market value, etc
```

What is the primary source of funding for this project?
```
Company's own funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
None stakeholders
```

## Use-case details

Describe the data being stored onto Filecoin
```
The stored data comes from our company and data generated by our business.
1. Company promotional articles, website design, event organization, office space design, online meeting video recording, etc.
2. Data for article writing and speech writing
3. Data generated by PPT production, promotional album design, and official website design
```

Where was the data in this dataset sourced from?
```
The data comes from the customers of the business and services that our company conducts.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1mMvAVm7e2J4gjl0Pdta6N07iyOmou8hw
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I’m confirm
```

What is the expected retrieval frequency for this data?
```
About once every 6 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Storage for about 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not limit the storage area. In theory, the more dispersed the storage location, the more our data can avoid the occurrence of force majeure factors to the greatest extent, and the data can be better stored safely.

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We apply for 3P and make four backups. Therefore, we need to provide data for 750T.
750T of data, maybe 50T will be transmitted online, and 700T will be transmitted offline.
We will be responsible for the cost of online transmission, and we hope that SP will be responsible for the cost of postage and hard disk offline.
Therefore, we choose SPs that are willing to provide hard drives and postage.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will look for suitable nodes on https://filrep.io/. , we will communicate with them on slack and other channels. If it is in China, we may meet offline. If it is abroad, we also hope to be able to communicate via video to determine the real existence of the mine and whether its technical strength is strong.
We will set up a FIL+ team to follow up on this matter.
```

How will you be distributing deals across storage providers?
```
We will distribute it evenly. If we use offline hard disk transmission, we will send the hard disk to the SP we cooperate with. At the same time, if we choose online transmission, we will also send the content of online transmission to each SP.

In this way, we can determine that the storage of each SP is fair, about 25%
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we do.
```

**Comment by simonkim0515** [comment]
Closing due to no response
