### ISSUE TITLE
[DataCap Application] myfirstskool

### ISSUE THREAD

**Issue by mkky2022** [filecoin-project/filecoin-plus-large-datasets#973]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: myfirstskool pre-school
- Website / Social Media: https://www.myfirstskool.com/ https://www.youtube.com/user/MyFirstSkool https://www.instagram.com/learningzones/ https://www.facebook.com/ntucfirstcampus/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1zdmxkmub2s6sio64styi52zpkraegzs7t3bbyki

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
For more than 40 years, My first skool has been a leader in early childhood care and education. As the pre-school arm of NTUC (National Trades Union Congress) First Campus Co-operative, we have grown into one of singapore’s most respected early childhood organisations since we opened our doors in 1977.
As one of the pioneer pre-school anchor operators, we are funded by the Early Childhood Development Agency (ECDA) and are committed to providing good quality and affordable early childhood care and education.
```

What is the primary source of funding for this project?
```
income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
none.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Public Lecture recording & activities that uploaded on our social media account.
```

Where was the data in this dataset sourced from?
```
Sourced from our school.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Once per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For 3 to 5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Better southeast Asia region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline transfer for Singapore SPs, online transfer for other locations. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select those providers who can provide services reliability and consistency.
```

How will you be distributing deals across storage providers?
```
We would like allocate an equal share to high quality providers, and each provider shall not allocated more than 25% of the data. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we kept the data for years and we would like to store it immediately.
```

**Comment by raghavrmadya** [comment]
No data sample. Please provide and open new application
