### ISSUE TITLE
[DataCap Application] SUFY - HuiDi-Data

### ISSUE THREAD

**Issue by shibowe** [filecoin-project/filecoin-plus-large-datasets#974]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: HuiDi-Data
- Website / Social Media: http://datahub.huidi-data.com/en-us/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1lklgbk2ote3g7vp4rcexjvpmssdqshvweemrr5q

## Project details

Share a brief history of your project and organization.
```
HuiDi Technology (ShangHai), It is a technology company focusing on providing customers with innovative application development and complete technical solutions.   Relying on years of core technology precipitation and rich project development experience, it is committed to providing customers with the best software products and services, with the help of "multi-speed IT" strategy Enterprises realize the "same frequency resonance" of IT and business.  

Project “Data Hub” 
It is a data service project of Huidi Technology for commercial companies and individuals.
- Long-term data storage and transmission 
- Artificial Intelligence and machine learning training
- Historical data rollback
- Video Content Analysis

```

What is the primary source of funding for this project?
```
Service Fees for D2C Brand Customers and Commercial Chain (B2C) Customers and company shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our business development will involve the use of a large number of AI training datasets to facilitate the improvement of machine learning, computer vision and other application scenarios, data including: video, images, etc.
```

Where was the data in this dataset sourced from?
```
The datasets mainly come from Online webcams or life material + artistic.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
For AI/ML training samples data(videos):  
 http://datahub.huidi-data.com/video/video1.mp4
 http://datahub.huidi-data.com/video/video2.mp4
 http://datahub.huidi-data.com/video/video3.mp4
 http://datahub.huidi-data.com/video/video4.mp4
 http://datahub.huidi-data.com/video/video5.mp4
 http://datahub.huidi-data.com/video/video6.mp4
 http://datahub.huidi-data.com/pics/AIOD-01.png
 http://datahub.huidi-data.com/pics/AIOD-02.png

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm this is a public dataset that can be retrieved by anyone on the network with no specific permissions or access rights required.
```

What is the expected retrieval frequency for this data?
```
No special retrieval frequency and maybe it’s probably twice a year or more.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Expectedly 4 years and it’s likely to be extended afterwards.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plans to make the deals in Asia, like: Sigapore,HongKong or North America (Canada,etc.)
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Prefer online, if needed offline can also be considered.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Well, we want to choose a miner with good size and credit in filecon's ecosystem.
```

How will you be distributing deals across storage providers?
```
We would divide the data up and send it to different miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have got some advices and resources from the community to make deals. We don’t need funding,and we need to get more weekly allocation of DC requested,perhaps 100T/week too small.
```

**Comment by raghavrmadya** [comment]
Presented at gov call and no dissent or concern. The client has provided holistic data samples.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1lklgbk2ote3g7vp4rcexjvpmssdqshvweemrr5q

**Comment by UnionLabs2020** [comment]
Could you share your official name of your company?

**Comment by sufyio** [comment]
> Could you share your official name of your company?

sure things, "HuiDi Information technology (Shanghai), Ltd." 
Thanks.

**Comment by UnionLabs2020** [comment]
You can share the name in Chinese, thank you.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnntwreifi3cvnoxzdkhv7puz2b3lzihkhedujnntfbsh3b4od7m 
#### Address 
> f1lklgbk2ote3g7vp4rcexjvpmssdqshvweemrr5q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnntwreifi3cvnoxzdkhv7puz2b3lzihkhedujnntfbsh3b4od7m

**Comment by sufyio** [comment]
> 

惠谛信息科技（上海）有限公司. 
Thanks.

**Comment by sufyio** [comment]
惠谛信息科技（上海）有限公司.
Thanks

**Comment by Carohere** [comment]
> Presented at gov call and no dissent or concern. The client has provided holistic data samples.

sorry i have one question here. in the data sample you have shared, there're hundreds of people walking in the mall etc., I can even see some people's faces very clearly from the western street one (video5). did you get their consent...? i don't think most of them are even aware of the camera...

**Comment by kernelogic** [comment]
I'm not a lawyer by any means but googling such issue gets me to a Quora page:
https://www.quora.com/Can-a-person-sue-you-for-taking-his-or-her-picture-without-his-consent

"In the U.S., if you are in public, you have no expectation of privacy. Anybody could take a photo of you, a video of you, or even audio recording without your consent. There are some minor exceptions to that, such as if you’re having a private telephone conversation (even in public), it would be a violation of your privacy rights to record you having that conversation if the person recording that conversation is not a part of that conversation.

Aside from that, if you’re in public, your expectation of privacy is not protected."

Also according to Canadian police:
https://globalnews.ca/news/1927766/exploring-your-rights-when-strangers-take-your-picture-in-public/
“You can kindly ask them to please not take the photograph and to delete it from their phone,” said Const. Jenifferjit Sidhu. “However, it’s not a criminal offence.”

**Comment by Carohere** [comment]
Fair points. I'm not a lawyer either just did some googling myself. And it leads me to this blog written by a lawyer to share legal knowledge. https://qusghtk.tistory.com/12 In the "원칙" (rule) part, according to Korean law and previous Supreme Court rulings, it is illegal to take pictures and videos without prior consent. 

I think the definition and protection of portrait rights differ from country to country. If @sufyio you can share which country most of your data is from it might be helpful for notaries to conduct due diligence. Thanks!

**Comment by sufyio** [comment]
Hi, So sorry for the late reply; I've been busy with internal activities recently, and as you known, the National day holiday will be coming in China ^_^,  and Thank you for your questions

Huidi is a provider of AI technology products and services; the video data we store comes from some of our partner merchants. We will provide free storage capacity for a certain period and allow our merchants to download or view this video data when they need it. We also offer free access to the data for AI algorithm training while ensuring data security.
The videos come from two main situations: 
 - the common area where the merchant is responsible.
 - the common area where the merchant can sell/service.

Most of the video data we store come from China, The questionable video (video5), it's only a test example and from a public video on the Web. Also, we think Kernelogic does a good job illustrating that _"In the U.S. if you are in public, you do not expect privacy. Anybody could take a photo of you, a video of you, or even an audio recording without your consent......Aside from that, if you’re in public, your expectation of privacy is not protected."_
We can also remove the ambiguous sample data if someone feels it is inappropriate.

And then all of the formal storage data will be processed if its have object recognition (face or human, etc.), like: 
http://datahub.huidi-data.com/video/video2.mp4；
http://datahub.huidi-data.com/video/video3.mp4。

Of course, We are also happy to provide more sample video data from our data sets; please check it out at the following link:
http://datahub.huidi-data.com/video/video11.mp4；
http://datahub.huidi-data.com/video/video12.mp4
http://datahub.huidi-data.com/video/video13.mp4；

Well, if you also have any questions, please let me know. 
Thanks so much again.

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasbxu6rryntvbgwzvpbyalhftt6reb3iilw2hnwrdebat4rswjro 
#### Address 
> f1lklgbk2ote3g7vp4rcexjvpmssdqshvweemrr5q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasbxu6rryntvbgwzvpbyalhftt6reb3iilw2hnwrdebat4rswjro

**Comment by Carohere** [comment]
Hi @shibowe, appreciate your time and happy holiday!
>The videos come from two main situations:
the common area where the merchant is responsible.
the common area where the merchant can sell/service.

May i know what kind of in-depth training are the surveillance videos 12 and 13 that no one appears to be used for...? Second, I don't see the common features of the selected area regarding AIOD-01 in the application. Could you share more about the identifying criterion?

**Comment by Carohere** [comment]
>Most of the video data we store come from China, The questionable video (video5), it's only a test example and from a public video on the Web. Also, we think Kernelogic does a good job illustrating that "In the U.S. if you are in public, you do not expect privacy. Anybody could take a photo of you, a video of you, or even an audio recording without your consent......Aside from that, if you’re in public, your expectation of privacy is not protected."
We can also remove the ambiguous sample data if someone feels it is inappropriate.

Last, maybe it's better not to put any test videos in the formal application? I agree with Fei, but what he was referring to was US and Canadian law. I doubt that anyone in the video clips would know Filecoin and come across to point it out. That said, removing the data as you offered does not really work. If your data sources are all from China (which I know the privacy protections are not widely recognized yet), there are already acts regarding the ownership of surveillance videos in commercial premises such like http://www.gd.gov.cn/zwgk/wjk/zcfgk/content/post_2531606.html

Personally, I don't think this application should be supported and I would like to get more community input here. Thanks.

**Comment by shibowe** [comment]
> 

Wow, Thanks for your concern about this LDN request. please let me in-depth introduction again: 
Object recognition, face recognition, all count as AI cognitive service categories. the purpose of AI human shoulder training is to recognize how many individuals are in a video, not specific facial features, which is why we blurred the faces in the portrait recognition process.

The data samples in 12,13 are used as a test of the efficiency of the AI algorithm in the case of no recognized subject, similar to the "null or zero" value judgment in programming, and are here only to illustrate the diversity of the data set samples,for AIOD-O1 which that used  for hoping to identify the arms of the people in the picture with the computer vision technology, BTW, the file is CC0 and just only used for testing result. 

The video shows a computer vision task: target segmentation, also called target instance segmentation, most of the image recognition problems are related to ILSVRC, the demo video is target detection: the algorithm generates a list of target categories present in the image and axis-aligned bounding boxes indicating the location of each instance of each target category, only our products and services are still being improved and what we can do now is only what you can see.
And hopeful to answer your questions.

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by shibowe** [comment]
Hello, we noticed a lot of controversy at the time, so we continued to improve the plan.
