### ISSUE TITLE
[DataCap Application] Jobstart

### ISSUE THREAD

**Issue by Emma967** [filecoin-project/filecoin-plus-large-datasets#979]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jobstart
- Website / Social Media:http://www.jobstart.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1wxhgkfcrt3e77iefa7kjmolnslqwqmjxbbsm2aq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jobstart is a consulting human resource service organization specializing in comprehensive, full-service human resources. The company was established in January 2008, headquartered in Ningbo, Zhejiang Province, after more than ten years of development, Jobstart has opened more than 40 branches and subsidiaries in East China, South China, Southwest China and Central China, with nearly 500 internal managers and nearly 500,000 dispatches/outsourcing each year, and has provided human resource services for more than 1,000 large and medium-sized enterprises in the past ten years.
```

What is the primary source of funding for this project?
```
From our income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Skill training videos.
```

Where was the data in this dataset sourced from?
```
From the HR skills training we provide.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Ok, please look at this link. Coming soon.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm.
```

What is the expected retrieval frequency for this data?
```
One to two times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan on choosing China, Singapore, Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We give preference to offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We ask for cooperation to support retrieval of SPs.
f0100116, f029401, f0533124 these Sps meet our requirements.
```

How will you be distributing deals across storage providers?
```
We can give less than 20% deals to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes! We'd like community can make our request of storing safely and conveniently.
```

**Comment by raghavrmadya** [comment]
No data sample.
