### ISSUE TITLE
[DataCap Application] FogMeta Lab - store Filecoin snapshots

### ISSUE THREAD

**Issue by hengdingy** [filecoin-project/filecoin-plus-large-datasets#984]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: FogMeta Lab
- Website / Social Media: https://fogmeta.com/Laboratory, http://rebuilder.fogmeta.com/ 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 80 TiB
- On-chain address for first allocation: f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
FogMeta Lab's research spans multiple levels from system technology, infrastructure, and middleware to services and solutions, and involves future systems, network technology and business, distributed systems and management, information management, and interactive and innovative services. Based on the views on and practices in the industry, FogMeta also solves the problem of business complexity through operations optimization and other technologies.
'filecoin-ipfs-data-rebuilder' is a project of FogMeta, a data build-and-rebuild tool between the IPFS network and the Filecoin network. Rebuilder ensures permanent storage of at least a cold & hot backup and makes data retrievable at any time.
```

What is the primary source of funding for this project?
```
FogMeta Lab.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Full node snapshots of Filecoin mainnet and calibration network maintained by Protocol Labs, including minimal/complete snapshots.
```

Where was the data in this dataset sourced from?
```
Filecoin mainnet snapshots are maintained by Protocol Labs;
Calibration snapshots are maintained by Filecoin community voluntarily;
Moreover, we're also running mainnet and calibration nodes and will export a snapshot every month. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Mainnet
- https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car
- https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/complete_chain_with_finality_stateroots_latest.car
- https://snapshots.mainnet.filops.net/minimal/latest

Calibration
- https://snapshots.calibrationnet.filops.net/minimal/latest
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it's a public dataset.
```

What is the expected retrieval frequency for this data?
```
3 to 5 times a month.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 500 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Preferably in all continents.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be sent to storage providers, and be uploaded to the web server or IPFS for storage providers to download.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will use the FilSwan platform to distribute these data. The Market Matcher, a module of the platform, will choose the most suitable storage providers for us automatically and make sure that the data can be retrieved in the future.
```

How will you be distributing deals across storage providers?
```
We are using FilSwan client agent for batch-sending deals.  https://github.com/filswan/swan-client
FilSwan has a reputation module called Swan reputation system (https://docs.filswan.com/filswan-platform/overview/reputation-system) to give storage providers scores for the data storage behavior, it based on Time-based Reachability + Regional Weighted Adjusted Power + General Deals and Verified-Storage Provider Deals

FilSwan Auction System will match the storage providers based on reputation and conditions. For the bidding policy, you can find it here: https://docs.filswan.com/filswan-platform/overview/filswan-auction-system.

Some of the storage providers are as follows:
f0143858
f03624
f010088
f02301
f0187709
f01402814
f01859603
f01133080
f01858429
f01398391
f01072221
f0240185
f01390330
f01784458
f01840390
f01870135
f0520660
f01871352
f01883179
f01886797
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. FogMeta Lab will fund the project.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 80TiB

**Client address**

>f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaji7f3l2pwyedsob4xlryyuurbx4m72eqs4gjnclv5zkimnr7efe 
#### Address 
> f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaji7f3l2pwyedsob4xlryyuurbx4m72eqs4gjnclv5zkimnr7efe

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqls5bbvbnsgofwpcd62rba2v7eyw72xwdhyt2a2moirkusbcuqa 
#### Address 
> f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqls5bbvbnsgofwpcd62rba2v7eyw72xwdhyt2a2moirkusbcuqa

**Comment by BigD-Exchange** [comment]
@hengdingy Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `FogMeta Lab`
 - Client: `f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                        Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0717969](https://filfox.info/en/address/f0717969)   |     Los Angeles, California, US |           3.51 TiB |      9.37% |    3.07 TiB |          12.46% |
| [f01222595](https://filfox.info/en/address/f01222595) |              Moscow, Moscow, RU |           3.45 TiB |      9.21% |    2.89 TiB |          16.29% |
| [f03624](https://filfox.info/en/address/f03624)       |           Nürnberg, Bavaria, DE |           3.23 TiB |      8.63% |    2.80 TiB |          13.53% |
| [f0187709](https://filfox.info/en/address/f0187709)   |              Moscow, Moscow, RU |           3.01 TiB |      8.02% |    2.50 TiB |          16.75% |
| [f01886797](https://filfox.info/en/address/f01886797) | Vancouver, British Columbia, CA |           2.98 TiB |      7.94% |    2.54 TiB |          14.70% |
| [f01163272](https://filfox.info/en/address/f01163272) |             Perm, Perm Krai, RU |           2.91 TiB |      7.75% |    2.38 TiB |          18.28% |
| [f01072221](https://filfox.info/en/address/f01072221) |     Los Angeles, California, US |           2.72 TiB |      7.25% |    2.25 TiB |          17.24% |
| [f01896422](https://filfox.info/en/address/f01896422) |         Fremont, California, US |           2.69 TiB |      7.17% |    2.25 TiB |          16.28% |
| [f01871352](https://filfox.info/en/address/f01871352) |                Seoul, Seoul, KR |           2.54 TiB |      6.77% |    2.23 TiB |          12.31% |
| [f010088](https://filfox.info/en/address/f010088)     |         Everett, Washington, US |           2.19 TiB |      5.84% |    2.00 TiB |           8.57% |
| [f0240456](https://filfox.info/en/address/f0240456)   |            Chengdu, Sichuan, CN |           1.85 TiB |      4.93% |    1.82 TiB |           1.69% |
| [f01402814](https://filfox.info/en/address/f01402814) |        Singapore, Singapore, SG |           1.79 TiB |      4.77% |    1.51 TiB |          15.72% |
| [f08399](https://filfox.info/en/address/f08399)       |         Seattle, Washington, US |           1.56 TiB |      4.17% |    1.34 TiB |          14.00% |
| [f01390330](https://filfox.info/en/address/f01390330) |              Xi’an, Shaanxi, CN |           1.31 TiB |      3.50% |    1.19 TiB |           9.52% |
| [f047419](https://filfox.info/en/address/f047419)     |    North Prairie, Wisconsin, US |         896.00 GiB |      2.33% |  896.00 GiB |           0.00% |
| [f0836160](https://filfox.info/en/address/f0836160)   |                Seoul, Seoul, KR |         896.00 GiB |      2.33% |  800.00 GiB |          10.71% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/984/1671098240019.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        32.00 GiB |        64.00 GiB |                   1 |           0.17% |
|       208.00 GiB |       448.00 GiB |                   2 |           1.17% |
|       612.00 GiB |         2.02 TiB |                   3 |           5.38% |
|         1.45 TiB |         6.34 TiB |                   4 |          16.92% |
|         1.59 TiB |         8.41 TiB |                   5 |          22.43% |
|       896.00 GiB |         5.63 TiB |                   6 |          15.01% |
|       224.00 GiB |         1.75 TiB |                   7 |           4.67% |
|        64.00 GiB |       512.00 GiB |                   8 |           1.33% |
|        32.00 GiB |       288.00 GiB |                   9 |           0.75% |
|        96.00 GiB |         1.56 TiB |                  12 |           4.17% |
|       224.00 GiB |         3.81 TiB |                  13 |          10.17% |
|       256.00 GiB |         4.88 TiB |                  14 |          13.01% |
|        96.00 GiB |         1.81 TiB |                  15 |           4.84% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/984/1671098240611.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by lvschouwen** [comment]
@hengdingy 
Can you please check with the storing SPs that retrieval of the dataset works?

MinerID f01390330 unable to connect.
```
# lotus net connect f01390330  
f01390330 -> {12D3KooWA1CdDzVVVerBLQP41x76JMPACAue1LxfVah3oTkDrXUg: [/ip4/1.85.217.226/tcp/25212]}
# telnet 1.85.217.226 25212
Trying 1.85.217.226...
```

MinerID f01981571 no IP announced to chain, not even going to try to retrieve data.

And the following MinerIDs reject retrievals;
f01970622
f0240456
f047419
f03624
f01871352

```
# lotus client retrieve --provider f01970622 QmaoMp1EaaTwvpUpSLFCL4JW9V7HzeWtreAY4h3cHTsJvr baga6ea4seaqo4pbne5dq6r4ykxho4zzkbz4jfuemdyfanaudtrdnhpdzlal4gji.car
Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078720|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 1ms [1674922066658078720|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 297ms [1674922066658078720|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 297ms [1674922066658078720|0]
Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 7.258s [1674922066658078720|0]
Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 7.259s [1674922066658078720|0]
ERROR: Retrieval Proposal Cancelled: Provider cancelled retrieval

# lotus client retrieve --provider f0240456 Qmcvp882Vty4W9kNziqFs1fXBFT93r6LcsSuQReDDTkMe7 baga6ea4seaqklxoeag7adr3vpmxrrxrr442kbxetgr3whclav6ozsyxpmmy4yiq.car
Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078719|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 2ms [1674922066658078719|0]
Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 282ms [1674922066658078719|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 283ms [1674922066658078719|0]
Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 571ms [1674922066658078719|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 571ms [1674922066658078719|0]
ERROR: Retrieval Proposal Rejected: deal rejected: miner is not accepting online retrieval deals

# lotus client retrieve --provider f047419 QmQjqHBbZcvZBRp2Etkc62FZhHQoscdCfWFyUVtmCEDCTe baga6ea4seaqozrperwnyxtcfbzaacczuh27nt7cwcfyuvc4guk6nq4hb3au3wmi.car
Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078721|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 1ms [1674922066658078721|0]
Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 152ms [1674922066658078721|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 153ms [1674922066658078721|0]
Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 277ms [1674922066658078721|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 277ms [1674922066658078721|0]
ERROR: Retrieval Proposal Rejected: deal rejected: miner is not accepting online retrieval deals

# lotus client retrieve --provider f03624 QmYZNxNKZtucDcU9EtL2yvSN5mKXNy48pvJdLVTeF6DusJ baga6ea4seaqmgkacstpxho6ebmaj6wglarpoqspok5iakud2c5oorzvcth4rcpi.car
Recv 0 B, Paid 0 FIL, Open (New), 1ms [1674922066658078717|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 4ms [1674922066658078717|0]
Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 78ms [1674922066658078717|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 79ms [1674922066658078717|0]
Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 145ms [1674922066658078717|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 145ms [1674922066658078717|0]
ERROR: Retrieval Proposal Rejected: deal rejected: miner is not accepting online retrieval deals

# lotus client retrieve --provider f01871352 Qma2JSSDXG6TwUtc3N4GHii6MJD5irj7Zhz8sDVjGYNR8p baga6ea4seaqg5tmoqj5apaawdaioumd5dbevdxfir7lvj5njacfqae5efke3wpy.car
Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078725|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 2ms [1674922066658078725|0]
Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 274ms [1674922066658078725|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 274ms [1674922066658078725|0]
Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 543ms [1674922066658078725|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 543ms [1674922066658078725|0]
ERROR: Retrieval Proposal Rejected: deal rejected: miner is not accepting online retrieval deals
```

MinerID f0836160 wants to get payed for retrieval;
```
# lotus client retrieve --provider f0836160 QmUK83Fh7Btc5iji61nDupwym3yvy1aaRQEQ4tn1G4zDsQ baga6ea4seaqhjeql2o7b62xxzr2zsc467m54vnrgqrmqopc3ylmawj7nz7fkoiy.car
ERROR: failed to find offer satisfying maxPrice: 0 FIL. Try increasing maxPrice
```

MinerID f010088 is broken;
```
# lotus client retrieve --provider f010088 Qmd9sugSVk4KH9nnLs7TvE4A5LE12wG2gLeumqSF3JFZLx baga6ea4seaqoyjec7vw2w52ele7abttvmarlazwuxdwh4sj6vk2rfbkipuh6yfa.car
2023-02-10T13:04:46.196+0100	WARN	rpc	go-jsonrpc@v0.1.8/client.go:548	unmarshaling failed	{"message": "{\"Err\":\"stream reset\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f010088\",\"MinerPeer\":{\"Address\":\"f010088\",\"ID\":\"12D3KooWRDb9V7e5WsHHSZHUtVcR9XgY3BBJSDDYr9YBncXfCjgY\",\"PieceCID\":null}}"}
2023-02-10T13:04:46.196+0100	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"
```

So 9 out of 19 miners are broken, that almost 50%.

**Comment by lvschouwen** [comment]
For the nodes that did allow me to retrieve data, it seems the correct data is stored.

**Comment by hengdingy** [comment]
> @hengdingy Can you please check with the storing SPs that retrieval of the dataset works?
> 
> MinerID f01390330 unable to connect.
> 
> ```
> # lotus net connect f01390330  
> f01390330 -> {12D3KooWA1CdDzVVVerBLQP41x76JMPACAue1LxfVah3oTkDrXUg: [/ip4/1.85.217.226/tcp/25212]}
> # telnet 1.85.217.226 25212
> Trying 1.85.217.226...
> ```
> 
> MinerID f01981571 no IP announced to chain, not even going to try to retrieve data.
> 
> And the following MinerIDs reject retrievals; f01970622 f0240456 f047419 f03624 f01871352
> 
> ```
> # lotus client retrieve --provider f01970622 QmaoMp1EaaTwvpUpSLFCL4JW9V7HzeWtreAY4h3cHTsJvr baga6ea4seaqo4pbne5dq6r4ykxho4zzkbz4jfuemdyfanaudtrdnhpdzlal4gji.car
> Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078720|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 1ms [1674922066658078720|0]
> Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 297ms [1674922066658078720|0]
> Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 297ms [1674922066658078720|0]
> Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 7.258s [1674922066658078720|0]
> Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 7.259s [1674922066658078720|0]
> ERROR: Retrieval Proposal Cancelled: Provider cancelled retrieval
> 
> # lotus client retrieve --provider f0240456 Qmcvp882Vty4W9kNziqFs1fXBFT93r6LcsSuQReDDTkMe7 baga6ea4seaqklxoeag7adr3vpmxrrxrr442kbxetgr3whclav6ozsyxpmmy4yiq.car
> Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078719|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 2ms [1674922066658078719|0]
> Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 282ms [1674922066658078719|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 283ms [1674922066658078719|0]
> Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 571ms [1674922066658078719|0]
> Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 571ms [1674922066658078719|0]
> ERROR: Retrieval Proposal Rejected: deal rejected: miner is not accepting online retrieval deals
> 
> # lotus client retrieve --provider f047419 QmQjqHBbZcvZBRp2Etkc62FZhHQoscdCfWFyUVtmCEDCTe baga6ea4seaqozrperwnyxtcfbzaacczuh27nt7cwcfyuvc4guk6nq4hb3au3wmi.car
> Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078721|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 1ms [1674922066658078721|0]
> Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 152ms [1674922066658078721|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 153ms [1674922066658078721|0]
> Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 277ms [1674922066658078721|0]
> Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 277ms [1674922066658078721|0]
> ERROR: Retrieval Proposal Rejected: deal rejected: miner is not accepting online retrieval deals
> 
> # lotus client retrieve --provider f03624 QmYZNxNKZtucDcU9EtL2yvSN5mKXNy48pvJdLVTeF6DusJ baga6ea4seaqmgkacstpxho6ebmaj6wglarpoqspok5iakud2c5oorzvcth4rcpi.car
> Recv 0 B, Paid 0 FIL, Open (New), 1ms [1674922066658078717|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 4ms [1674922066658078717|0]
> Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 78ms [1674922066658078717|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 79ms [1674922066658078717|0]
> Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 145ms [1674922066658078717|0]
> Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 145ms [1674922066658078717|0]
> ERROR: Retrieval Proposal Rejected: deal rejected: miner is not accepting online retrieval deals
> 
> # lotus client retrieve --provider f01871352 Qma2JSSDXG6TwUtc3N4GHii6MJD5irj7Zhz8sDVjGYNR8p baga6ea4seaqg5tmoqj5apaawdaioumd5dbevdxfir7lvj5njacfqae5efke3wpy.car
> Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078725|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 2ms [1674922066658078725|0]
> Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 274ms [1674922066658078725|0]
> Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 274ms [1674922066658078725|0]
> Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 543ms [1674922066658078725|0]
> Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 543ms [1674922066658078725|0]
> ERROR: Retrieval Proposal Rejected: deal rejected: miner is not accepting online retrieval deals
> ```
> 
> MinerID f0836160 wants to get payed for retrieval;
> 
> ```
> # lotus client retrieve --provider f0836160 QmUK83Fh7Btc5iji61nDupwym3yvy1aaRQEQ4tn1G4zDsQ baga6ea4seaqhjeql2o7b62xxzr2zsc467m54vnrgqrmqopc3ylmawj7nz7fkoiy.car
> ERROR: failed to find offer satisfying maxPrice: 0 FIL. Try increasing maxPrice
> ```
> 
> MinerID f010088 is broken;
> 
> ```
> # lotus client retrieve --provider f010088 Qmd9sugSVk4KH9nnLs7TvE4A5LE12wG2gLeumqSF3JFZLx baga6ea4seaqoyjec7vw2w52ele7abttvmarlazwuxdwh4sj6vk2rfbkipuh6yfa.car
> 2023-02-10T13:04:46.196+0100	WARN	rpc	go-jsonrpc@v0.1.8/client.go:548	unmarshaling failed	{"message": "{\"Err\":\"stream reset\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f010088\",\"MinerPeer\":{\"Address\":\"f010088\",\"ID\":\"12D3KooWRDb9V7e5WsHHSZHUtVcR9XgY3BBJSDDYr9YBncXfCjgY\",\"PieceCID\":null}}"}
> 2023-02-10T13:04:46.196+0100	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"
> ```
> 
> So 9 out of 19 miners are broken, that almost 50%.

@lvschouwen Thanks for letting us know! We've already reached out the FilSwan team and they said an investigation report will be done next Tuesday.

<img width="929" alt="image" src="https://user-images.githubusercontent.com/107467232/218236561-7cde9aef-596a-4808-9637-0377ae98bb1c.png">

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecl3lnv3szhp6ccv3gfoy3jb7xwkphuzjc7h36ze5mtlzwh77qbus 
#### Address 
> f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecl3lnv3szhp6ccv3gfoy3jb7xwkphuzjc7h36ze5mtlzwh77qbus

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebabubishbsjczwd6qzmw2ivxer3nmavqcfivbnofijv2y6qe7vak 
#### Address 
> f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> d6d00a55-5fc0-49a0-a93b-22bc3a5c183e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebabubishbsjczwd6qzmw2ivxer3nmavqcfivbnofijv2y6qe7vak

**Comment by igoovo** [comment]
Early packaging, and robot inspection without violations, provide support.
