### ISSUE TITLE
[DataCap Application] zhenye international group

### ISSUE THREAD

**Issue by MasterX2046** [filecoin-project/filecoin-plus-large-datasets#985]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  zhenye international group World Headlines of All media platform
- Website / Social Media: https://worldhds.net/ ,http://en.zhenye500.com/news/9/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f16gfcwnvwlilq66ipqx223dr5suww7fiz7dm4xlq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Zhenye International Group is a comprehensive industrial multinational group 
focusing on industry and combining emerging industries. It is an integrator,
 investor, operator and service provider of the industrial system. The group ranks
 261th among the top 500 Chinese enterprises in 2021, 103rd among the top 500
 Chinese service enterprises, 103rd among the top 500 Chinese private enterprises,
 40th among the top 500 Guangdong enterprises, 24th among the top 100
 Guangdong private enterprises and 21st among the top 100 Guangdong service
 enterprises. World Headlines of All is a worldwide Internet media platform created
 by Zhenye International Group and more than 30 overseas Chinese media. With
 the full support of the Overseas Chinese Media Association (328 Chinese media
 organizations around the world), it has created a multi-language and multi-format
 platform. A full information sharing platform (video, audio, graphic, etc.), featuring
 objective, fair and timely information and an innovative technology platform,
 serving global customers. 
```

What is the primary source of funding for this project?
```
Company income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Videos, audios, graphics on our media platform.
```

Where was the data in this dataset sourced from?
```
Sourced from our news media platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://1drv.ms/u/s!AvVki_MO3j89a6e2U6PSUvDiVYk?e=MTIXzX
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Once per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, EU, America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It will be combination of online and offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
 Storage providers with good reputation, trustworthiness, stable.
```

How will you be distributing deals across storage providers?
```
At least 4 storage providers, and according to their network bandwidth and storage efficiency to occupy with each less than 30% of the quota. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by raghavrmadya** [comment]
What exactly does the company do? -"comprehensive industrial multinational group focusing on industry and combining emerging industries". This is unclear

**Comment by raghavrmadya** [comment]
<img width="274" alt="Screen Shot 2022-10-23 at 6 51 30 AM" src="https://user-images.githubusercontent.com/91579519/197376212-03425d6e-ff1b-4d56-924f-1f8d9ac6359f.png">
 You are located in India. What is your relationship with this organization?

**Comment by MasterX2046** [comment]
ok, let me elabrate on this. we are a industrial group focusing mainly on below:
- New Material. The group has built a new generation of electronic information and new materials industrial park, creating copper rods, precision wires, superconducting copper wires, electronic copper foil, nano copper wires, special cables and other products that are at the international top level.
- New Energy. Group focus on construction of new energy industrial park with photovoltaic modules, energy storage batteries, hydrogen energy application, air energy application as the main body.
- Big Health. Plans to settle in stem cell storage and R&D business, stem cell precision medical application, high-end medical care, medical examination and testing and health management center, characteristic medical beauty hospital and medical beauty product production base, etc.
- Culture Media - Group created worldwide Internet media platform and more than 30 overseas Chinese media. It's a full information sharing platform (video, audio, graphics, etc.), featuring objective, fair and timely information and an innovative technology platform, serving global customers.

As for me, India is not my real location, it's the virtual vpn address when i signed up for github. I am the zhenye employee under culture media platform based in shenzhen.

**Comment by Sunnyiscoming** [comment]
It seems that there are many sources of data samples. Could you explain the sources of your data? Do you have permission to store it on the Filecoin network as public data and provide proof of that?
Can you provide more data samples related with the data you will store to prove that you have 5 PB data? Videos would be better. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by MasterX2046** [comment]
> It seems that there are many sources of data samples. Could you explain the sources of your data? Do you have permission to store it on the Filecoin network as public data and provide proof of that? Can you provide more data samples related with the data you will store to prove that you have 5 PB data? Videos would be better. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

@Sunnyiscoming 
 We are a full information sharing platform (video, audio, graphics, etc.) with more than 30 overseas Chinese media, all the data are sourced from our platform. For now we only have mobile app platform, in our app we have:
- homepage (with subcategory like headlines, international, commercial, arts, etc)
- videos category  
- Chinese media category (with news from 30+ overseas chinese media)

below is the link for the screenshot for all the contents on our platform: https://1drv.ms/u/s!AvVki_MO3j89bBDKv0mAleUviNU?e=hWzIe5, 

we also uploaded our videos in china video platform bilibili, you can refer to the link: https://space.bilibili.com/1678002121

I am from culture media depertment, we are trying to find SPs since we applied this application, and the SPs we engaged are f0398865, f073552, f01215348, f01275559, f0752635.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #985.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.

**Comment by MasterX2046** [comment]
> Close for no reply.

Hi @Sunnyiscoming @simonkim0515 ,we have send the confirmation email, kindly verify. Do need to re-open this application or we submit a new one?

**Comment by MasterX2046** [comment]
![image](https://user-images.githubusercontent.com/111690442/215987681-b7f5b8de-2e39-40a4-a25e-ca8cb3df0fbc.png)

**Comment by Sunnyiscoming** [comment]
Please open another one if you have the needs to apply for datacap.
