### ISSUE TITLE
[DataCap Application] Wopin---Datacap application

### ISSUE THREAD

**Issue by Nora-Wopin** [filecoin-project/filecoin-plus-large-datasets#989]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Wopin365
- Website / Social Media:http://www.wopin365.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f15cdt5fjnqjq4bakar7bdxe234zebicjnnph7phy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Wopin is committed to developing new ways of labor and employment and human resource management, and developing into an expert organization in human resource service outsourcing, providing comprehensive and multi-level human resource outsourcing services for enterprises in China. We play a role in promoting the extension of the human resources industry and related industries, and uses advanced information technology tools and a powerful network platform to build a bridge between enterprises and talents. We are committed to building long-term, trusted strategic partnerships with companies across the country.
```

What is the primary source of funding for this project?
```
Income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we want to store are resume ppt templates for various professions, and recording videos of training sessions on HR knowledge sharing (for employee onboarding and daily training) 
```

Where was the data in this dataset sourced from?
```
The data comes from our business accumulation.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1r3Z9s1DN6NDhySAH_GvJ-0URmD8UTCh6/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm.
```

What is the expected retrieval frequency for this data?
```
Our expected retrieval is once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
4 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan making deals mainly in Singapore, Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Right, we have prepared hard disks for offline transfer. We choose this way.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have some standards on it ------- SP should support data retrieval, and have high speed network.
```

How will you be distributing deals across storage providers?
```
Every SP with less than 25% of the deals. We plan cooperating with 5 SPs at first.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We want more SPs for deals.
```

**Comment by raghavrmadya** [comment]
Samples are private

**Comment by Nora-Wopin** [comment]
> Samples are private

This is because there is a problem with my email. Now it's back to normal.

**Comment by UnionLabs2020** [comment]
Could you send an email from your official business account to filplus-app-review@fil.org?

**Comment by Nora-Wopin** [comment]
@unionlabs2020 Hello, I tried to send the email, but I got feedback that the email failed to be sent. 
![wopin](https://user-images.githubusercontent.com/107846151/198006546-e2389b8a-7db4-4ad0-a430-62dc295cf252.png)

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f15cdt5fjnqjq4bakar7bdxe234zebicjnnph7phy

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceah6uv6n6vp7cfupq3xn35wldqeuq4p7vcixamhl4xwvbth2xr77i 
#### Address 
> f15cdt5fjnqjq4bakar7bdxe234zebicjnnph7phy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 94703368-1135-4eb7-ae4b-3551de5f5efc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceah6uv6n6vp7cfupq3xn35wldqeuq4p7vcixamhl4xwvbth2xr77i

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3rkc5qag4khfemy7ew23lswpcfey6jhjyoj2j4iapo4l2uo7ef2 
#### Address 
> f15cdt5fjnqjq4bakar7bdxe234zebicjnnph7phy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 94703368-1135-4eb7-ae4b-3551de5f5efc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3rkc5qag4khfemy7ew23lswpcfey6jhjyoj2j4iapo4l2uo7ef2

**Comment by BDEio** [comment]
@Nora-Wopin Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by Nora-Wopin** [comment]
ok I know

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by Nora-Wopin** [comment]
@clriesco thank you very much

**Comment by Nora-Wopin** [comment]
ok I know

**Comment by Nora-Wopin** [comment]
Yes

**Comment by Nora-Wopin** [comment]
Yes please.

**Comment by Nora-Wopin** [comment]
Keep open.

**Comment by Nora-Wopin** [comment]
Yes, keep open.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @Nora-Wopin per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.
