### ISSUE TITLE
[DataCap Application] <Korea artists council> - <KAC>

### ISSUE THREAD

**Issue by hidklo88** [filecoin-project/filecoin-plus-large-datasets#990]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Korea artists council
- Website / Social Media: http://koreaart21.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f3qja4qzdlkckris43sls6cpoa2czczxnklrblh4kgvqxsdfi6bkn4geuzhzrc7zd7wij4qzohnmaabiidflwq

Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details
Share a brief history of your project and organization.
```
The Korea Artists Council was formed in July 2021 and is an organization that provides information on companies and policies and displays artists' community activities and works without shrinking artists' artistic activities. 
Artists' artistic activities freely present communication and sharing, but they are alienated and shunned. In addition, the artists' fields and genres were different, so they could not know and communicate with each other, while their exclusive and ignorant attitudes toward other genres deepened their alienation.
Now we need the communication of artists in different genres and the proper channels to represent artists. Accordingly, we would like to establish the Korean Artists Council to continuously communicate with artists about companies and policies and expand our activities overseas.
```

What is the primary source of funding for this project?
```
From our income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```
## Use-case details
Describe the data being stored onto Filecoin
```
Artistic works such as paintings and videos of artists and photographs, exhibitions, news, policies, forums, and projects.
```

Where was the data in this dataset sourced from?
```
Korea artists council
```
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.koreaart21.com/news/articleView.html?idxno=1296
https://www.youtube.com/watch?v=U9r1tRF_ewQ&t=12s
https://www.youtube.com/watch?v=bZ5wtWqK7GU
https://www.youtube.com/watch?v=xmvOmOuUgUI
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?

```
More than 1times a day.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Two years, for as long as possible.
```

## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It is possible online and offline if you are a Korean storage provider.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll search for storage providers online. The storage provider where the data is stored will be disclosed.
```

How will you be distributing deals across storage providers?
```
We can give less than 30% deals to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are not familiar with data storage and technology in Filecoin, so we would like to get help from a storage provider that is geographically close.
```

**Comment by hidklo88** [comment]
request to change the DataCap address : 
f3w32kvmbqief75gulbgcn3f7nshfq22wnu3lughbvm4yqawjvkqumbqelyc2z264dbeb5i736bh5bvey6rb3q

**Comment by raghavrmadya** [comment]
Please justify request for 5 PiBs

**Comment by hidklo88** [comment]
Hi @raghavrmadya 

The annual Korea Art Fair is preparing for a transition from the 2.0 platform era to the 3.0 capacity era. We will develop the data capacity of Metabus and NFT and heat up the hearts of artists around the world.
https://www.thefirstmedia.net/news/articleView.html?idxno=95796

This year, more than 2,000 people from 30 countries around the world participated in the Korean Art Fair, and the number of domestic art fair members reached about 20,000.
http://www.koreaart21.com/news/articleList.html?sc_section_code=S1N9&view_type=sm

http://gangnamcj.kr/news/30159

The association is currently storing about 500TB, and plans to store them in duplicate in 5 to 10.
Data continues to grow with artwork such as paintings, videos, sculptures, photographs, event-related videos, and photographs.

In addition, it plans to collect and store the individual data of more than 20,000 members that the association has failed to keep.

In particular, as the quality of the stored work improves, it is stored in 3D, and one 3D work corresponds to one movie.
https://www.thefirstmedia.net/news/articleView.html?idxno=101240

We will continue to store these works in Filecoin in the future.

**Comment by raghavrmadya** [comment]
Hi, 5 to 10 copies of 500 TiBs do not add up to 5 PiBs. Please apply for the exact amount needed. You can update this application the correct amount

**Comment by simonkim0515** [comment]
@hidklo88 are there any updates?

**Comment by hidklo88** [comment]
Hi @simonkim0515 
The application has been updated and we are waiting for DC approval.

**Comment by Sunnyiscoming** [comment]
You mentioned several websites in your application. 
What is your relationship with these websites? 
Do you have their permission to store this data as public data on the Filecoin network?
http://gangnamcj.kr/
https://www.thefirstmedia.net/
http://www.koreaart21.com/
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by hidklo88** [comment]
> You mentioned several websites in your application. What is your relationship with these websites? Do you have their permission to store this data as public data on the Filecoin network? http://gangnamcj.kr/ https://www.thefirstmedia.net/ http://www.koreaart21.com/ What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

1. Two of the above mentioned websites (http://gangnamcj.kr/
https://www.thefirstmedia.net/) is a news media channel that introduces KAC's events that have applied for DC, and the last one (http://koreaart21.com) is the main site of the agency that has applied for DC.

2. All data to be stored in Filecoin is open data, and a program has been developed to collect and store data from association members.

3. The applicant himself is a KAC employee.

4. Currently, the SPs that will participate in this program are as follows.
    f0521569, f01624021, f0399083, f01819003, f01921523, f01115949, f01770778, 01900525, f01927163

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #990.

**Comment by hidklo88** [comment]
Hi, @Sunnyiscoming 
I sent you an email. Are you sure?
![1669872868616](https://user-images.githubusercontent.com/84013119/204974130-5827de6f-cd73-4591-a5ea-3119438292a2.jpg)

**Comment by Sunnyiscoming** [comment]
Received that.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f3qja4qzdlkckris43sls6cpoa2czczxnklrblh4kgvqxsdfi6bkn4geuzhzrc7zd7wij4qzohnmaabiidflwq

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced37nnjdfitavwq56z5i4eqnnuukqpcfwtqv4otdg5oewq2cmjjya 
#### Address 
> f3qja4qzdlkckris43sls6cpoa2czczxnklrblh4kgvqxsdfi6bkn4geuzhzrc7zd7wij4qzohnmaabiidflwq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 7cd82220-553b-44d0-ac4e-8b7556570a8b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced37nnjdfitavwq56z5i4eqnnuukqpcfwtqv4otdg5oewq2cmjjya

**Comment by NDLABS-OFFICE** [comment]
The customer has confirmed kyb's email, and the information is complete, and will continue to pay attention to it after the first support.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceae2vh6p2hmsouotezkbostscqcfnh365bajfomftebnq3p2tx2fq 
#### Address 
> f3qja4qzdlkckris43sls6cpoa2czczxnklrblh4kgvqxsdfi6bkn4geuzhzrc7zd7wij4qzohnmaabiidflwq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 7cd82220-553b-44d0-ac4e-8b7556570a8b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceae2vh6p2hmsouotezkbostscqcfnh365bajfomftebnq3p2tx2fq

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?
