### ISSUE TITLE
[DataCap Application] Gongxueyun

### ISSUE THREAD

**Issue by Fraser54** [filecoin-project/filecoin-plus-large-datasets#991]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Gongxueyun
- Website / Social Media:www.gongxueyun.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1lryhylimps3agxtu3oocaglzjvzhivzjsdrfqfq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our company is an internship management and comprehensive service platform for students of all types of schools, dedicated to helping skilled people move from school to business and to obtain job opportunities and vocational training on an ongoing basis. 
Our product---Gongxueyun is an internship management and comprehensive service platform for senior high school students, providing efficient and convenient internship management services.
```

What is the primary source of funding for this project?
```
Our funding is from the income about cooperation with these school.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No others.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Promotional video of schools we are cooperating with.
```

Where was the data in this dataset sourced from?
```
All data is provided by 600+ schools we are working with. Total data size is over 540TiB now, and we aim to store 10 copies.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
We put it into google drive.
https://drive.google.com/file/d/1XuiVM259VicVSzX43FRNSqwRrzaKa-3g/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirmed.
```

What is the expected retrieval frequency for this data?
```
At most 3 times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
During our cooperation with these schools, we make copies at filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Now we've already decided to select China-HongKong, Korea-Seoul.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Of course, our first choice is offline data transfer---close distance with SPs.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We've prepared these SPs for deals, and we ensure that they support retrieval---an important element.
We may looking for more SPs who located at other regions.
```

How will you be distributing deals across storage providers?
```
We'll try to keep the data decentralized to be stored. Different SP will have less than 30% of deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by UnionLabs2020** [comment]
Could you verify your identity by sending an email to filplus-app-review@fil.org from your official mailbox?

**Comment by Fraser54** [comment]
Thank you for your question! @UnionLabs2020 ![GXY](https://user-images.githubusercontent.com/108066144/199202556-c809f698-7604-4e09-890c-a2de275dbdd9.jpg)

**Comment by Fraser54** [comment]
@simonkim0515 Ok! Later I will update the link.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1lryhylimps3agxtu3oocaglzjvzhivzjsdrfqfq

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabw6mw5g7mg5sznpv5gm3zq633kxkwne57capj4xc4o5fxrotywa 
#### Address 
> f1lryhylimps3agxtu3oocaglzjvzhivzjsdrfqfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 1487cda0-5a70-4423-9ede-9d351ce3cca2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabw6mw5g7mg5sznpv5gm3zq633kxkwne57capj4xc4o5fxrotywa

**Comment by Sunnyiscoming** [comment]
Hey @Fraser54 , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrcrpwbktfy42q2cq5gkvkfarttlwbubrbro3ykcfss5qac7pmji 
#### Address 
> f1lryhylimps3agxtu3oocaglzjvzhivzjsdrfqfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrcrpwbktfy42q2cq5gkvkfarttlwbubrbro3ykcfss5qac7pmji

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello @Fraser54 

Any update here?

**Comment by Fraser54** [comment]
Yes. Keep open!

**Comment by Fraser54** [comment]
Hello notaries and Gov team, can you help open my application? It can help my previous plan go on.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by zcfil** [comment]
May I ask why the DataCap you applied for last year has not been executed as planned yet?

**Comment by Fraser54** [comment]
@zcfil Because of Covid 19, there's some delay about our plan. We need to look for new SPs to help complete it. We'll make it right as soon as we can.

**Comment by Fraser54** [comment]
Yes, keep open.

**Comment by Fraser54** [comment]
yes please!

**Comment by Fraser54** [comment]
yes please open!

**Comment by Fraser54** [comment]
yes please open!

**Comment by Fraser54** [comment]
yes please open!

**Comment by Sunnyiscoming** [comment]
Hello, @Fraser54 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Fraser54** [comment]
Hello @Sunnyiscoming  i submitted the form. Thank you.

**Comment by Filplus-govteam** [comment]
SPs provided
SP 1	f01927410	individual	Dallas, Texas, US	no	panda
SP 2	f01844999	individual	Ashburn, US	no	tony
SP 3	f01844232	individual	Dallas, Texas, US	no	Lukas
SP 4	f02363999	individual	Singapore, Singapore, SG	no	Leon
SP 5	f02232088	Sunshine	        Chengdu, Sichuan, CN	no	Freda


please provide proof of entity and location for these SPs. Closing until updated
