### ISSUE TITLE
[DataCap Application] Fusionride  - technology-driven

### ISSUE THREAD

**Issue by supor** [filecoin-project/filecoin-plus-large-datasets#992]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fusionride 
- Website / Social Media: https://www.fusionride.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1exenla7t6n3hqwquzfidkcdyfjfgwt7dx4ry4di

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Fusionride, a technology-driven company under Fosun, is a smart mobility solution and service provider. Based on the synergistic development of software and hardware as well as services, including core systems for autonomous driving and vehicle-infrastructure collaboration, key perception sensors, infrastructure-based platforms and smart mobility operations, Fusionride is committed to improving experience for autonomous driving,optimizing smart mobility systems, and leading the smart mobility ecosystem with a caring heart.
```

What is the primary source of funding for this project?
```
parent company investment.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Fosun.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Autonomous driving machine learning sample data, video,images,etc.
```

Where was the data in this dataset sourced from?
```
All data is the project needs to be recorded and collected as a sample for machine learning.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1DbulPVgtFpe_V7Fv_U5dKhacguZBjC0n
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. All data is public.
```

What is the expected retrieval frequency for this data?
```
About a few times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, Hong Kong, Singapore.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Most videos are sent offline to hard drives, some images are transmitted online via a web server.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will look for SPs through slack and filecoin community. We believe that policies (the country where the SP is located), technology, etc. all affect our choice of SP. We tend to choose SPs in Singapore and HK. We plan to search a few times a year, and we ask about their search capabilities when selecting SPs.
```

How will you be distributing deals across storage providers?
```
We will abide by the rules of Fil+, and we will achieve distribution as decentralized as possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I'm ready.
```

**Comment by raghavrmadya** [comment]
What is your relationship with the organization and what geography was this data collected from?

**Comment by simonkim0515** [comment]
Closing due to no response

**Comment by Sunnyiscoming** [comment]
Please open another one if you have the needs to apply for datacap.
