### ISSUE TITLE
[DataCap Application] Fujian ZhanXun Geographic Information Co., Ltd

### ISSUE THREAD

**Issue by mutablepunk** [filecoin-project/filecoin-plus-large-datasets#993]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fujian ZhanXun Geographic Information Co., Ltd
- Website / Social Media: www.zhanxun.site
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 Tib
- On-chain address for first allocation: f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Fujian ZhanXun Geographic Information Co., Ltd , founded in May 2014. The company provides services such as thematic map production and H5 application system development, and is committed to the investment development and application promotion of geographic information applications. The company has successively provided services such as information collection, application development and platform release for provincial-level units such as the Provincial Investigation Bureau、Provincial Safety Administration、Provincial Publicity Department and Provincial Tourism Bureau. At the same time, it also provides information development services for mass merchants and various enterprises. So far, it has served nearly 50 scenic spots and more than 200 enterprises in the province, and accumulated a large number of application data such as tourist attractions, special food, cultural exhibition halls, etc.
```

What is the primary source of funding for this project?
```
From ourselves​.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We has served nearly 50 scenic spots and more than 200 enterprises in the province, and accumulated a large number of application data such as tourist attractions, special food, cultural exhibition halls, etc.
```

Where was the data in this dataset sourced from?
```
From the geographic data in our project
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1RjLa99z8qSFRvLxHMEdIgpiKINbyYhjg?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three years or more 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China，Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will refer to their storage efficiency and overall capacity, then choose a reliable and experienced storage provider
```

How will you be distributing deals across storage providers?
```
We will allocate according to the fil-plus community rule
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by loomeeworld** [comment]
您的邮件我已收到~

**Comment by raghavrmadya** [comment]
Data samples are insufficient. Please share samples and please do not put them in .zip files

**Comment by mutablepunk** [comment]
Hi, we have updated the Data sample, here is the new link：https://drive.google.com/drive/folders/1RjLa99z8qSFRvLxHMEdIgpiKINbyYhjg?usp=sharing

**Comment by simonkim0515** [comment]
Please provide more information.
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with?
Can you explain your data composition? And to provide more data samples related with data you will store to prove that you have 2 PB already. 
How many copies will you store?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by mutablepunk** [comment]
Sorry for late reply.
I am a product developer of the company and hope to use more open technical means to store our relevant data. We have contacted other SP's such as waterdrop lab, here are some information below:
f01907578 FuJian China
f0216849   HongKong
f01949260  FuJian China
f01949267  FuJian China
We are now surveying and mapping the geographical data of many tourist attractions in China (all with the permission of the local administrative department). This is a long-term and arduous work. The data samples we upload are only a small part of the aerial photography model, and Other large-capacity data, including geographic image data and panoramic pictures, have accumulated more than 1P, and are still growing at a capacity of more than 100T per month. You mentioned more data samples above, do you need us to provide more files like the one I mentioned above? Can you provide more specific advice. Because the files are numerous and large, I cannot fully present all the data.

**Comment by mutablepunk** [comment]
@Sunnyiscoming @simonkim0515 
Sorry for late reply.
I am a product developer of the company and hope to use more open technical means to store our relevant data. We have contacted other SP's such as waterdrop lab, here are some information below:
f01907578 FuJian China
f0216849 HongKong
f01949260 FuJian China
f01949267 FuJian China
We are now surveying and mapping the geographical data of many tourist attractions in China (all with the permission of the local administrative department). This is a long-term and arduous work. The data samples we upload are only a small part of the aerial photography model, and Other large-capacity data, including geographic image data and panoramic pictures, have accumulated more than 1P, and are still growing at a capacity of more than 100T per month. You mentioned more data samples above, do you need us to provide more files like the one I mentioned above? Can you provide more specific advice. Because the files are numerous and large, I cannot fully present all the data.However，We plan to store six copies in three different cities.

**Comment by Sunnyiscoming** [comment]
Please open another one if you have the needs to apply for datacap.
