### ISSUE TITLE
[DataCap Allocation] - DataCap for Landsat 9

### ISSUE THREAD

**Issue by TaylorOshan** [filecoin-project/filecoin-plus-large-datasets#995]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "DataCap for Landsat 9"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: The EASIER Data Initiative (FFDW partner project)
- Website / Social Media: -
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
- Region: North America

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The EASIER Data initiative kicked off late this summer and is a two year project in collaboration with the Filecoin Foundation for the Decentralized Web to build pipelines for storing and extracting geospatial data on Filecoin and IPFS. These pipelines will be prototyped and demonstrated using one year of Landsat 9 satellite data, which is estimated at about 500TB.
```

What is the primary source of funding for this project?
```
Filecoin Foundation for the Decentralized Web
```

What other projects/ecosystem stakeholders is this project associated with?
```
University of Maryland, Filecoin Foundation for the Decentralized Web, Atlas, Filecoin Green
```

## Use-case details

Describe the data being stored onto Filecoin
```
One year of landsat 9 satellite images.
```

Where was the data in this dataset sourced from?
```
Landsat 9 is a joint mission between NASA and USGS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.usgs.gov/landsat-missions/landsat-9
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
The data are supported by open missions and are meant to be public
```

What is the expected retrieval frequency for this data?
```
Initially, the data will likely only be retrieved in frequently by the project team, but the hope is that with the development of the pipelines during the duration of the project, the platform will increase the number of users and the retrieval frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3-5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
n/a
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
In small increments to accommodate the batch processing of data.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
TBD - we are collaborating with Atlas to develop a strategy for the most robust storage plan
```

How will you be distributing deals across storage providers?
```
TBD - we are collaborating with Atlas to develop a strategy for the most robust storage plan
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We anticipate being ready to start making storage deals in the next 4 to 6 weeks.
```

**Comment by Datadaos** [comment]
I  think it has been storged by lots of projects already.

**Comment by TaylorOshan** [comment]
I am aware of several projects that have stored some of the Landsat data, but landsat 9 is a new satellite that recently came online and there's not yet one year of data available. I am also aware of other projects that have the goal of storing landsat 9 data (Atlas) and we have been communicating with Eshan Chordia at PL to do this collaboratively. The goal of our FFDW partner project with Brynn O'Donnell is to strategically process and store it so that it is more accessible for retrieval for downstream users.

**Comment by dannyob** [comment]
@Datadaos I think you're thinking of [Landsat 8](https://datasets.filecoin.io/landsat-8), which was part of Slingshot. This is a new slab of data. 


@TaylorOshan Do you have any idea yet of how many SPs you were thinking of storing the data with?

**Comment by TaylorOshan** [comment]
@dannyob we would probably first look to identify one or two larger storage providers and we are currently working on making those connections, but then we were thinking to try to work with several smaller providers for additional replications.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 500PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

>f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq

**Comment by TaylorOshan** [comment]
@raghavrmadya @dannyob just saw these latest comments and I have been meaning to provide some updates to the issue based on project conversations. I believe I originally misunderstood the amount I should be requesting. Originally provided the anticipated size of the data set, but have since realized that we would be planning to store several applications using two different file formats. We also plan to explore different strategies to pack CAR files, but following conversations with @dannyob and others, we have thought of some strategies to first explore this on a smaller scale. Since we are using one year of data that we expect to be about 500 TB and we are planning to store two version (tiff and cog) each with 3 replications, the total request should actually be closer 3 PB. Does this matter up front or can we continue working and expand the request as we go?

**Comment by raghavrmadya** [comment]
Hi, thanks for the update. please feel free to open a new application with the remaining request

**Comment by TaylorOshan** [comment]
Ok , Will do. Thanks for the clarification. One additional question. What was the total amount approved for this request? Trying to understand if I did incorrect and we received enough for replications were just a single copy.

**Comment by TaylorOshan** [comment]
Hi @raghavrmadya, just checking in. When I check to see if we have received the first tranche using https://verify.glif.io/ I don't yet see the 25 TiB.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqgdeeodugy3sja5qbqkv5ahlfx6tyf7aq2a6xarw3ndrr5fguh6 
#### Address 
> f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqgdeeodugy3sja5qbqkv5ahlfx6tyf7aq2a6xarw3ndrr5fguh6

**Comment by xinaxu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnoe2n54wkigypskm2loayzkalojahwtyy4qxy5mm3q3p3nylot2 
#### Address 
> f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnoe2n54wkigypskm2loayzkalojahwtyy4qxy5mm3q3p3nylot2

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by TaylorOshan** [comment]
We are working with Piknik storage provider to finish packing the data for
storage. I will check in with them to understand the timeline and when we
will begin making storage deals.

**Comment by TaylorOshan** [comment]
Just wanted to loop in @dannyob for situational awareness as this moves forward. Would the next status updates/tranche of datacap be granted once we continue dealmaking or do we need to wait for that to happen before we can start dealmaking again with additional SPs and finish the first copy with Piknik?

**Comment by xingjitansuo** [comment]
Hope to see more diverse distribution in the next tranche.

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrebpkiral2pf5bwjd45acokgbah7wus2h6scykswxwvusqr353u 
#### Address 
> f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 7389867f-91cc-4953-aceb-85d9562e66c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrebpkiral2pf5bwjd45acokgbah7wus2h6scykswxwvusqr353u

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5p6kx4rhab4up3d6j7hb3gmkaucr4qxzkaaum2kjwjocwirkwcy 
#### Address 
> f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5p6kx4rhab4up3d6j7hb3gmkaucr4qxzkaaum2kjwjocwirkwcy

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
James has requested my attention to review this LDN. This collaborative project with FFDW is currently in its initial phase of distribution. We will ask @TaylorOshan for distribution plans regarding the upcoming phase. I am willing to provide support, but I will closely monitor the progress during this next round.

**Comment by jamerduhgamer** [comment]
Thank you @cryptowhizzard. Messaged @raghavrmadya on why the next datacap tranche is not firing off like previously. I believe this issue has already been flagged by Raghav though.

**Comment by jamerduhgamer** [comment]
Hi @TaylorOshan, that is correct and there is currently an issue with getting more datacap approved because the bot is not triggering. Confirming with @simonkim0515 or @panges2 if we need to open another application to resolve this issue.
