### ISSUE TITLE
[DataCap Application] LIANLI Electronic Technology Co., Ltd.

### ISSUE THREAD

**Issue by lianliwork** [filecoin-project/filecoin-plus-large-datasets#997]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: LIANLI Electronic Technology Co., Ltd.
- Website / Social Media: https://www.lianliwork.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1njj2h4sexjyvhbpxz42cg535ol3tnmxoe7lzjga

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Dongguan LIANLI Electronic Technology Co., Ltd., founded in 2017, 
is located in Qingxi Town, Dongguan, the most beautiful town in China.

The company is mainly engaged in the production and sales of oil cooling service cabinets,
server equipment, chassis, power supplies (various customized power supplies, industrial control power supplies),
and the development of blockchain host electronic equipment and edge computing software, 
distributed storage software algorithms (software development, optimization and training guidance, 
server hosting, cluster construction, NFT distribution, smart contract development and other full set of project solutions)
```

What is the primary source of funding for this project?
```
From the company
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
- promotion material (videos, pictures, documents, etc.)
- artifacts in software development
- other public business data
```

Where was the data in this dataset sourced from?
```
From our business
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

```
https://drive.google.com/drive/folders/1FcUPW5KS9FdPgVc_yoj_8MwW8luQOGxv?usp=sharing
https://drive.google.com/drive/folders/1iAcS7esIahXIId_9QLes-PihdbQbvDnA?usp=sharing
https://drive.google.com/drive/folders/1GueXCFIO6fU0FVb2XlYMXmtEy33ij4JL?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm.
```

What is the expected retrieval frequency for this data?
```
About once half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least two years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in Mainland China, the countries/regions around are also in consider .
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to choose storage providers based on their regions, scale, stability.
```

How will you be distributing deals across storage providers?
```
We will send deals to different storage providers according to their reliability, and make sure a single storage provider won't get too many deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, the resources is adequate.
```

**Comment by raghavrmadya** [comment]
What is your relationship with the client? The promotional video samples aren't enough for the requested amount. Provide more samples please

**Comment by lianliwork** [comment]
> What is your relationship with the client? The promotional video samples aren't enough for the requested amount. Provide more samples please

I'm on behalf of our company. I have sent an email using company domain to filplus-app-review@fil.org for verifying.

I have update the links for more samples, and here is the new link: https://drive.google.com/drive/folders/1iAcS7esIahXIId_9QLes-PihdbQbvDnA?usp=sharing

**Comment by raghavrmadya** [comment]
How are the samples provided related to the production and sales of oil cooling service cabinets? There is no hardware in the videos...

**Comment by lianliwork** [comment]
> How are the samples provided related to the production and sales of oil cooling service cabinets? There is no hardware in the videos...

Oh Sorry, I just picked the recent videos at random. They are part of the company's promotional video.

Here are more samples about our hardware: https://drive.google.com/drive/folders/1GueXCFIO6fU0FVb2XlYMXmtEy33ij4JL?usp=sharing

**Comment by simonkim0515** [comment]
@lianliwork have you been in contact with any SPs?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2.5PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

> f1njj2h4sexjyvhbpxz42cg535ol3tnmxoe7lzjga

**Comment by Sunnyiscoming** [comment]
Hey @lianliwork , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by lianliwork** [comment]
Hello @cryptowhizzard

> As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

This account is registered with my company email address because I don't want to use my personal account for my company's application. And our application is 2.5PiB not 5PiB.
We are not new to Filecoin, we have join Filecoin community since 2021 and have enough knowloedge of Filecoin. However, this is indeed the first time we apply for Datacapand we don't have real experience in packing or distributing data. So our distribution speed may be a bit slow at first.

Here is a storage system we use:
![图片](https://user-images.githubusercontent.com/114055944/216487569-2ab01141-f331-45f5-9440-b94f9ed9c2fd.png)

I have submitted KYC form. BTW our phone number have a +86 prefix, I hide it to pass the form check.

**Comment by cryptowhizzard** [comment]
Hello @lianliwork 

Thanks for submitting your application and KYC. It is well received.

You indicated that you are the data preparer and owner of the dataset. Can you confirm you don't have any stake in SP's you are going to send this data to? As stated in the form I am allowing 1 replica of the set to be stored on your own miners. That's the reason i ask.

Second, the miners you provided do not qualify. They are not connected to the internet and not open for retrieval.
Chinese Sichuan f01225783, f01946991 and Chinese Hongkong f0114118

Please re-read the rules and confirm that you understand those. If you don't understand please ask explanation on slack to avoid trouble.

>>>>>>>>

RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed.
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.

**Comment by lianliwork** [comment]
Hello @cryptowhizzard,

Sorry for the late reply.
We are contacting to SPs and and setting up our own miner recently.

Here are the new SPs:
- f01167426 Chinese Hongkong
- f02048749 Chinese Guangdong（our miner)
- f01174629 Chinese Sichuan

**Comment by lianliwork** [comment]
Is there any update here?

**Comment by cryptowhizzard** [comment]
Hi @lianliwork 

How about this? -> "Data must be distributed across multiple regions."

**Comment by lianliwork** [comment]
@cryptowhizzard Thanks for your reply.
Does the region here mean regions accross different countries?
So that means we still need find another SP in another country/region?

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard Thanks for your reply. Does the region here mean regions accross different countries? So that means we still need find another SP in another country/region?

Yes ;-)

**Comment by lianliwork** [comment]
@cryptowhizzard We have contacted f02301 and f03223 in North American.
After the datacap request is approved, we will try to contact more SPs.

**Comment by cryptowhizzard** [comment]
Hi @lianliwork 

On first allocation it is my strategy to only sign on applicants who performed KYC and where we have a data onboarding plan. I really need the 4 SP's.

**Comment by lianliwork** [comment]
Hi @cryptowhizzard, 

Thanks for your reply.
Sorry for the misleading. f02301 and f03223 are just additional SPs, not the only SPs.

Currently, we have contacted 5 SPs across two continents and three country/region.

- f02301 North American
- f03223 North American
- f01167426 Hong Kong
- f02048749 Chinese Guangdong
- f01174629 Chinese Sichuan

**Comment by lianliwork** [comment]
Hello, is there any update here?
