### ISSUE TITLE
[DataCap Allocation] - Data storage  of construction industry

### ISSUE THREAD

**Issue by yvetteoor** [filecoin-project/filecoin-plus-large-datasets#999]
---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Yunnan Yuke Architectural Engineering Design Co., Ltd.,
- Website / Social Media: http://www.ynykjg.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 80TiB
- On-chain address for first allocation: f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yunnan Yuke Architectural Engineering Design Co., Ltd., formerly known as Kunming LANGTU Architectural Design Consulting Co., Ltd., has been engaged in the architectural design consulting industry since 2013. The business scope includes various architectural engineering design, outdoor garden landscape design, urban and rural planning design and indoor and outdoor decoration engineering design. Also，the company can undertake engineering construction feasibility study, engineering technology planning consulting and services.

After 9 years of development and precipitation, the company has grown steadily, with complete professional support and strong technical force. It has a professional and enthusiastic designer team, rich design experience and the ability to implement large-scale comprehensive projects. 

Except conventional construction projects, our company also has rich experience in earthquake reconstruction, and participated in the reconstruction project of Zhaotong earthquake in Yunnan (the sample submitted this time includes the desgin data of Zhaotong). In September 2022, a magnitude 6.8 earthquake occurred in Luding, Sichuan, our company is arranging with the participation of the reconstruction project of Luding Earthquake,too.

The design projects are widely distributed in Western China, Myanmar, Laos and other places.with the accumulation and increase of business volume, many projects of the company have retained a large number of materials, drafts, historical modified versions, finished product drawings and other data that need to be backed up and stored for a long time. These increasing cold storage requirements, whether online or offline storage, face high storage costs and data damage risks. Our colleagues are facing the same problems as us. 

With the introduction of friends, we learned that the filecoin distributed storage project can solve these problems. Therefore, we hope to have the opportunity to join the filecoin distributed storage network to reduce storage costs and ensure the stability of long-term data storage.

```

What is the primary source of funding for this project?
```
The data storage fund of the project is provided by our company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data content includes design materials, drafts and finished product drawings; project effect drawing; consulting scheme; planning scheme, video, etc. The total amount of data exceeds 1PiB. To ensure data security to the maximum extent,
these data will be copied as the 4 or 5 same duplicate and distributed to different SPs 
```

Where was the data in this dataset sourced from?
```
The data mainly comes from Yunnan Yuke Architectural Engineering Design Co., Ltd.,and some of them come from the data entrusted by six companies with the same storage needs.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Zhaotong Earthquake Reconstruction Project
https://drive.google.com/drive/folders/1n8Q5n0Mfkj9IkfPNruPI4PV0uEPqikQP?usp=sharing
reconnaissance
https://drive.google.com/drive/folders/1dR5eaB2-ITLOE91uvBtQLkG56ALCgp3T?usp=sharing
Planning scheme and video
https://drive.google.com/drive/folders/1iGT_pQ3bpHZGIFnCMfA_uL8gu-gIVv6T?usp=sharing
Effect Diagram
https://drive.google.com/drive/folders/1zQAstcH0cTUWlHi9uPA_Z8ZguS4yE3Uy?usp=sharing
Design draft
https://drive.google.com/drive/folders/1hb6stqULtJlQK-wc-9tKzH-tM6HA9SGe?usp=sharing
Consulting scheme
https://drive.google.com/drive/folders/1OIcSGRlh8EzUnF0sVo0mKzKVg6VdIAZp?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Of course. 
```

What is the expected retrieval frequency for this data?
```
Because it is cold stored data, the frequency of retrieval is about once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Considering the safe and fast data transmission, it is preferred to store it in Asia and Greater China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Use offline transmission (including hard disk copy) to transmit data.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
In order to reduce storage costs, we prefer to cooperate with low-cost sp for storage. On this basis, we will examine whether SP has real data storage experience, long-term storage operation and maintenance ability and data retrieval.

According to our predetermined amount of stored data, the number of SPs to be selected is about 8-10.

At present, we have started to connect with some SPs, and also pay attention to some data trading platforms, such as BDE.
```

How will you be distributing deals across storage providers?
```
All data is about 1p. Considering security, all data wiil becopied as the 4 or 5 same duplicate and will be reasonably allocated according to the number of SPS finally selected.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, the funds for storage are ready.
```

**Comment by yvetteoor** [comment]
Is there any update here?  I've been waiting for over two weeks.

**Comment by yvetteoor** [comment]
What else can we do to advance the application? Anyone  who can assist? @raghavrmadya @galen-mcandrew @Kevin-FF-USA @Sunnyiscoming

**Comment by raghavrmadya** [comment]
Data samples are .jpg files and we cannot determine the need for 3.5 PiBs. Please provide as much justification as possible to support your case as well as SP IDs

**Comment by yvetteoor** [comment]
Hi, Raghav, I have submitted the sample. If there is anything else to add, please let me know.  @raghavrmadya

**Comment by yvetteoor** [comment]
What else we  can do to speed up the review process?

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #999.

**Comment by yvetteoor** [comment]
> What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/999.

@Sunnyiscoming  Thank you for your reply,The email has been sent, please check.

<img width="353" alt="yuke" src="https://user-images.githubusercontent.com/110969971/204486415-ea835365-6c36-49f0-8c40-75b8657e6912.png">

Here is SPs  that we have contacted with at present  ，and some more are under negotiation. We'll update  here in time.
Japan:
f01451690
China:
f0443184
f0442671
f01832877 
f01880558

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 80TiB

**Client address**

> f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii

**Comment by Sunnyiscoming** [comment]
Hey @yvetteoor  , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by yvetteoor** [comment]
@Sunnyiscoming Thank you for the tip. I'll ask.

**Comment by cryptowhizzard** [comment]
Hi @yvetteoor 

It seems you are not fully aware of the rules of fil+. I screened the miners above and none qualify.

lotus net connect f01451690
f01451690 -> {12D3KooWQKo3kw7dqNuAw8brSWiheGvcQ6LpUxGcbbo4w52e7okg: []}
ERROR: failed to parse multiaddr "f01451690": must begin with /

root@proposals:~# lotus net connect f0443184
f0443184 -> {12D3KooWHSazuftYZhZcy7rBGGSbvtGA7gv1pf3TUsB4waW6iQPo: []}
ERROR: failed to parse multiaddr "f0443184": must begin with /

root@proposals:~# lotus net connect f0442671
f0442671 -> {12D3KooWRLta9x6sKXHrLri54SzENYKhyEZRzSttNAwBn7uAt8rS: []}
ERROR: failed to parse multiaddr "f0442671": must begin with /

root@proposals:~# lotus net connect f01832877
f01832877 -> {12D3KooWN91RquGvfHF7X16KW9svmSwp6DdP3fPQPDbJQULheqRL: []}
ERROR: failed to parse multiaddr "f01832877": must begin with /

root@proposals:~# lotus net connect f01880558
f01880558 -> {12D3KooWG1nJRPMsqsLHSTZmxZiJtTuWJd4iX4vp5USiyzj4i2VB: []}
ERROR: failed to parse multiaddr "f01880558": must begin with /

**Comment by cryptowhizzard** [comment]
Can you please fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

**Comment by mjroddy** [comment]
I don't see how this dataset is aligned to filecoin

"The dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone in the network, without requiring any special permissions or access requirement.

**Comment by yvetteoor** [comment]
> Can you please fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Hello, @cryptowhizzard 
About  SPs . During the application submission, some of the SPs we contacted have withdrawn from Filecoin project, we are still looking for partners, we will comply with fil+ requirements to select SPs.
Regarding the organization information, we have sent a kyc email (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/999#issuecomment-1330309325) to fil+ team via our corporate domain email. You can check it. Here I post the kyc result  of qcc for your confirmation.

<img width="774" alt="yk" src="https://user-images.githubusercontent.com/110969971/220289129-27a1c7fb-5751-4e98-bbe7-2f8a0ad8f57d.png">

**Comment by NewHuoPool** [comment]
Are there any confirmed storage providers that you have contacted now?

**Comment by yvetteoor** [comment]
Hello @NewHuoPool ,Thanks  for asking.
We have reached out to some SPs and currently, we can confirm the following:
f0443184   HK
f02031264  SGP
f01943910  US
f01945296  JP

**Comment by NewHuoPool** [comment]
OK, I'm willing to support you temporarily this time, and I will pay attention to the next cid report.

**Comment by NewHuoPool** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebl53dspefhbhed62tgsnqzqccvbudxjhyekqaqges6csfoyrwaqs 
#### Address 
> f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f16karfxq7lxdy7izqrzrk75jf3not34k6sg6zvcy
#### Id
> 684cc63a-4ef1-4d83-aae0-4dcf7d54b03c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebl53dspefhbhed62tgsnqzqccvbudxjhyekqaqges6csfoyrwaqs

**Comment by newwebgroup** [comment]
Except for the first f0443184 which did not respond (and did not report any error), all the other nodes were reachable after Ask.
Willing to support Client going forward in the first round and would like to see more compliance
<img width="570" alt="image" src="https://user-images.githubusercontent.com/100118145/226324249-14b60d0d-6d3a-4797-acf2-fa357abdd0e0.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecag7axymt5fk5njlqwerbd5cmptvbejamzkmh7kouz6xcu5liuis 
#### Address 
> f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 684cc63a-4ef1-4d83-aae0-4dcf7d54b03c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecag7axymt5fk5njlqwerbd5cmptvbejamzkmh7kouz6xcu5liuis

**Comment by METAVERSEDATAMINING** [comment]
Please explain the abnormal information.
>f0442671 has sealed 100.00% of total datacap.
>All storage providers are located in the same region.
>100.00% of deals are for data replicated across less than 3 storage providers.

**Comment by yvetteoor** [comment]
@METAVERSEDATAMINING thanks  for asking.
The initial allocation was small, according to the distribution plan disclosed in the application, the allocation of a single sp exceeded 500T, and the current allocation is within the reasonable range,Then other SPs began to be encapsulated and got the right allocation, next cid reports will gradually prove this.

**Comment by METAVERSEDATAMINING** [comment]
Well, I'll keep an eye on the distribution and encapsulation of this application.

**Comment by METAVERSEDATAMINING** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfwnh53i5nt7rbwfvmspqxbkvirhjyzecjul66cfwqyebnkrtjgk 
#### Address 
> f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfwnh53i5nt7rbwfvmspqxbkvirhjyzecjul66cfwqyebnkrtjgk

**Comment by OpenGate01** [comment]
Node retrieval is normal. 
![d8d9e62f192fd7cbfc93c9461c1775a_720](https://user-images.githubusercontent.com/117976412/226820951-c728e0d3-d3cb-4c3c-99fb-44058b8d9deb.png)
The first round allocation is small, and it's in a node is acceptable. This round I'll support, but I hope you strictly follow the rules in the future.

**Comment by OpenGate01** [comment]
@yvetteoor I cannot sign this application as the backend search cannot find it.
 I need confirmation if it's a problem with my system or for other reasons.Please help check @galen-mcandrew @fabriziogianni7 
 
![20230322210114](https://user-images.githubusercontent.com/117976412/226912597-8558d4f3-5bf1-4a9e-995e-a6187c921d9b.png)

**Comment by panges2** [comment]
@yvetteoor @OpenGate01 it should be there now

**Comment by OpenGate01** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaoubu7ofa5ycwqq3uvnv3qrmxljdkb5fptsaikdjryocxnamv2pw 
#### Address 
> f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> b4e1656f-9958-498c-b589-e730b81a4250
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaoubu7ofa5ycwqq3uvnv3qrmxljdkb5fptsaikdjryocxnamv2pw

**Comment by yvetteoor** [comment]
Hi @simonkim0515 @panges2 
Datacap allocation is used up. request trigger.mang thanks.

**Comment by yvetteoor** [comment]
Comparing to the previous CID report, there is a noticeable improvement.
At the same time, we are constantly monitoring the storage progress of SPs, adjusting allocation strategies as needed. In the new round of storage, there will be new SPs joining.

**Comment by Tom-OriginStorage** [comment]
A total of 120T is packaged, but the number of nodes is only 3, which does not comply with the rules and there is no CID sharing. Please explain the plan for the next round of packaging

**Comment by yvetteoor** [comment]
@Tom-OriginStorage  thanks for your audit.
The SPs we have been in contact with are gradually joining and this has been reflected in the storage reports so far. We anticipate adding 1-2 new SPs in the next step. Please stay tuned to our application as the next report will show significant improvement.
f02052244   US
f02052252   US

**Comment by Tom-OriginStorage** [comment]
Okay, I will continue to pay attention to this round of support. I hope to see new nodes added in the next round, otherwise there will be no further support from notaries

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6oxsd2e35kfk7dc7r7qvvfrogptpz74oivw3n5glyq5g6nxe6zi 
#### Address 
> f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii
#### Datacap Allocated
> 160.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6oxsd2e35kfk7dc7r7qvvfrogptpz74oivw3n5glyq5g6nxe6zi

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpudkmnfxhp3nwj7herhan762seo76sijjw6mng3sfch43dkkefc 
#### Address 
> f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii
#### Datacap Allocated
> 160.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpudkmnfxhp3nwj7herhan762seo76sijjw6mng3sfch43dkkefc

**Comment by stcouldlisa** [comment]
<img width="734" alt="WechatIMG354" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/112812896/d89e9bca-b87f-4651-97f2-1ae1dad401f2">
<img width="822" alt="WechatIMG353" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/112812896/7b1ec83f-93ef-4bc8-8c87-bb2a6d5dd29d">

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3f4pwuqh7une2oz4qvng5k4lrnez3326mrsxg77v2udnhsk7nzi 
#### Address 
> f1it5bu33xdc2wjt3xhygckvcy3v6iz5f4ojgodii
#### Datacap Allocated
> 320.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 6f322bf3-22f1-4876-9b47-71b4943b0c63
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3f4pwuqh7une2oz4qvng5k4lrnez3326mrsxg77v2udnhsk7nzi

**Comment by yvetteoor** [comment]
We're currently getting the data ready.

**Comment by yvetteoor** [comment]
The next batch of encapsulation is about to start.

**Comment by yvetteoor** [comment]
We are looking for new  SPs as the previously confirmed SPs have withdrawn from the project due to certain reasons.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by yvetteoor** [comment]
Normal packaging...

**Comment by yvetteoor** [comment]
checker:manualTrigger

**Comment by yvetteoor** [comment]
Data preparation

**Comment by yvetteoor** [comment]
Data preparation

**Comment by yvetteoor** [comment]
In Progress

**Comment by yvetteoor** [comment]
In Progress

**Comment by yvetteoor** [comment]
Some of the cooperating SPs are undergoing data center migration, which has affected the progress. We are making efforts to coordinate and ensure that work can continue smoothly

**Comment by METAVERSEDATAMINING** [comment]
checker:manualTrigger

**Comment by yvetteoor** [comment]
Please keep it open.

**Comment by yvetteoor** [comment]
Please keep it open.

**Comment by yvetteoor** [comment]
In Progress

**Comment by yvetteoor** [comment]
In Progress

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
FAKE DISTRIBUTION with Amazon.com, Inc. VPN. Requesting immediate closure of this self-dealing act. @kevzak

**Comment by yvetteoor** [comment]
Please keep it open.

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 09 58 35](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/092ffea5-49b5-4db8-a6d6-2aa0704473bf)

Fully selfdealing. Close this LDN @Kevin-FF-USA

**Comment by Sunnyiscoming** [comment]
Hello, @yvetteoor per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment]
closing until proof of SP entity and distribution provided
